export interface Sprite {
  /** Maps a pixel character to a CSS color. '.' is always transparent and is not listed. */
  palette: Record<string, string>
  /** 16 rows of exactly 16 characters each. */
  pixels: string[]
}

export type SpriteId =
  | 'spearman' | 'crossbowman' | 'gryphon' | 'swordsman' | 'priest' | 'knight'
  | 'skeleton' | 'ghoul' | 'wraith' | 'vampire' | 'lich' | 'deathKnight'
  | 'rock' | 'tree' | 'deadTree' | 'crystal'

/**
 * Pixel art for every unit and obstacle. The characters 'T' (team color) and
 * 't' (darker team shade) are never listed in a palette: the renderer
 * substitutes the owning player's colors for them. All creatures face right.
 */

const OUTLINE = '#1a1410'
const SKIN = '#e0b088'
const STEEL = '#b8c0c8'
const DARK_STEEL = '#6a7480'
const WOOD = '#8a5a2b'
const BOOTS = '#4a3424'
const BONE = '#e8e0c8'
const BONE_SHADOW = '#a89c80'

export const SPRITES: Record<SpriteId, Sprite> = {
  spearman: {
    palette: { o: OUTLINE, s: SKIN, m: STEEL, M: DARK_STEEL, w: WOOD, b: BOOTS },
    pixels: [
      '............o...',
      '...........omo..',
      '...........omo..',
      '....oooo...owo..',
      '...ommmmo..owo..',
      '..ommmmmmo.owo..',
      '..oMMMMMMMoowo..',
      '..oMssssosoowo..',
      '...ossssssoowo..',
      '..oTTTTTTToowo..',
      '.omTTTTTTossso..',
      '.omTTTTTTo.owo..',
      '..otTTTTto.owo..',
      '..ottttto..owo..',
      '..obo..obo.owo..',
      '..obbo.obbooooo.',
    ],
  },
  crossbowman: {
    palette: { o: OUTLINE, s: SKIN, h: '#6b4a2a', l: '#5a3a1e', w: WOOD, b: BOOTS },
    pixels: [
      '................',
      '.....oooo.......',
      '....ohhhho......',
      '...ohhhhhho.....',
      '...ohhsssso.....',
      '...ohhssoso.....',
      '...ohhsssso...o.',
      '....ohhsso...owo',
      '...oTTTTTToooowo',
      '..oTTTTTssllllwo',
      '..oTTTTTTooooowo',
      '..otTTTTto...owo',
      '..ottttto.....o.',
      '...obo.obo......',
      '...obo.obo......',
      '...obbo.obbo....',
    ],
  },
  gryphon: {
    palette: {
      o: OUTLINE,
      f: '#f0ead8',
      g: '#c8902e',
      G: '#8a5a1e',
      y: '#f0b020',
      w: '#6a3e1c',
      W: '#a8743c',
    },
    pixels: [
      '................',
      '.oo........ooo..',
      '.oWo......offfo.',
      '.oWWwo...offofo.',
      '..oWWwo.offffyyo',
      '..oWWWwoofffoyo.',
      'o..oWWWwofffo...',
      '.o.oWWWWwffo....',
      '.o.oTTTTTwffo...',
      '.ooggTTTTTggggo.',
      '..ogggggggggggo.',
      '..oGgggggggggGo.',
      '..oGGoGo..oyoyo.',
      '..oGGoGo..oyoyo.',
      '..oGGoGo..oyoyo.',
      '..oooooo..ooooo.',
    ],
  },
  swordsman: {
    palette: { o: OUTLINE, s: SKIN, m: STEEL, M: DARK_STEEL, y: '#e0b030', b: BOOTS },
    pixels: [
      '..o.............',
      '.omo............',
      '.omo..oooo......',
      '.omo.ommmmo.....',
      '.omo.ommMMo.....',
      '.omo.ommmmo.....',
      'oyyyo.ommmoooooo',
      '.oso.oMmmmoTyTto',
      '.ossooMmmmoyyyto',
      '..o..oMmmmoTyTto',
      '.....oMmmmoTyTto',
      '.....oMMMMoTTTto',
      '.....oMo.oMotto.',
      '.....oMo.oMoo...',
      '.....obo.obo....',
      '.....obbo.obbo..',
    ],
  },
  priest: {
    palette: {
      o: OUTLINE,
      s: SKIN,
      r: '#ece8dc',
      R: '#b8b0a0',
      w: WOOD,
      y: '#fff6b0',
      Y: '#f0c040',
    },
    pixels: [
      '............ooo.',
      '...........oyyyo',
      '.....ooo...oyyyo',
      '....orrro...oYo.',
      '...orrrsso..owo.',
      '...orrsoso..owo.',
      '...orrssso..owo.',
      '..orrrrTro..owo.',
      '..orRrrTrrossso.',
      '..orRrrTrro.owo.',
      '..oRRrrtrro.owo.',
      '.oRRrrrtrro.owo.',
      '.oRRrrrtrrroowo.',
      'oRRRrrrtrrrrowo.',
      'oRRRRrrtrrrrowo.',
      '.ooooooooooo.o..',
    ],
  },
  knight: {
    palette: {
      o: OUTLINE,
      h: '#d8d0c4',
      m: STEEL,
      M: DARK_STEEL,
      w: '#c8a060',
      b: BOOTS,
      s: SKIN,
    },
    pixels: [
      '....oo.........m',
      '...oTTo.......w.',
      '...ommmo.....w..',
      '...omMMo....w...',
      '...ommmo...woo..',
      '..oTTTTTo.wohho.',
      '..oTTTTTsw.ohoho',
      '..otTTTto.ohhhho',
      '.ooooooooohhooo.',
      'oTTTTMTTTThho...',
      'oTTTTMTTTTTo....',
      'otTTTTTTTTto....',
      'otttttttttto....',
      '.ohoho....ohoho.',
      '.ohoho....ohoho.',
      '.obobo....obobo.',
    ],
  },
  skeleton: {
    palette: { o: OUTLINE, w: BONE, W: BONE_SHADOW, m: '#a0a8b0', y: '#8a6a3a' },
    pixels: [
      '..o.............',
      '.omo.oooo.......',
      '.omoowwwwo......',
      '.omoowwowo......',
      '.omoowwwwo......',
      'oyyyo.oWwo......',
      '.owo..owo.oooo..',
      '.owwowWwWoTTTto.',
      '..o.owWwWoTyTto.',
      '....owWwWoTTTto.',
      '.....owWwotttto.',
      '.....owowo.oo...',
      '.....owowo......',
      '.....owowo......',
      '.....owowo......',
      '.....owwowwo....',
    ],
  },
  ghoul: {
    palette: {
      o: OUTLINE,
      g: '#8a9a6a',
      G: '#5a6a44',
      r: '#e03020',
      w: '#d8d0b0',
    },
    pixels: [
      '................',
      '................',
      '....oooo........',
      '...oggggo.oooo..',
      '..oTTggggoggggo.',
      '..oTtGgggogggro.',
      '..oGGtGgggggggo.',
      '..oGGGtGgggowwo.',
      '..oGGGtGGgggooo.',
      '..oGGGGtGoggggo.',
      '...oGGGtGo.ogogo',
      '...otTtTto......',
      '...oGo.oGo......',
      '..oGo..oGo......',
      '..oGo...oGo.....',
      '.oGGo...oGGo....',
    ],
  },
  wraith: {
    palette: {
      o: '#0a0810',
      P: '#3a3650',
      k: '#000000',
      e: '#7af0ff',
      c: '#a8b0c0',
    },
    pixels: [
      '................',
      '.....oooo.......',
      '....oPPPPo......',
      '...oPPPPPPo.....',
      '...oPPkekeko....',
      '...oPPkkkkko....',
      '..oPPPPkkkPo....',
      '..oPTPPPPPPPcco.',
      '.oPPPTPPPPPPoco.',
      '.oPPPPTPPPPPo...',
      '.oPPPPPtPPPo....',
      '..oPPPPPtPo.....',
      '...oPPPTo.......',
      '..oPPo.otTo.....',
      '.oPPo....oo.....',
      'oPo.............',
    ],
  },
  vampire: {
    palette: {
      o: OUTLINE,
      s: '#dcd8e4',
      h: '#141018',
      r: '#e02020',
      k: '#241a26',
      K: '#3e2c40',
      w: '#f0f0f0',
    },
    pixels: [
      '................',
      '......oooo......',
      '.....ohhhho.....',
      'o...ohhssso...o.',
      'oo.oTohssro..oo.',
      'oTooTtosswo.oTo.',
      'oTTtoKkkwkKotTTo',
      'oTTTtKkkkkKtTTTo',
      'oTTTtKkkkkKtTTTo',
      'otTTtKkkkkKtTTto',
      'oo.otKkkkkKto.oo',
      '.....oKkkKo.....',
      '......oKKo......',
      '......okko......',
      '.......oo.......',
      '................',
    ],
  },
  lich: {
    palette: {
      o: OUTLINE,
      w: BONE,
      W: BONE_SHADOW,
      p: '#4a3462',
      P: '#2e1f40',
      g: '#70ff90',
      G: '#20a040',
      y: '#d0a030',
      n: '#5a4030',
    },
    pixels: [
      '.....y.y.y..ooo.',
      '....oyyyyyoogggo',
      '....owwwwwooggGo',
      '....owwwgwo.oGo.',
      '....owwwWwo.ono.',
      '.....owowo..ono.',
      '..oTTTTTTTToono.',
      '..opppppppTowwo.',
      '..oPppppppToono.',
      '..oPPpppppToono.',
      '..oPPpppppToono.',
      '.oPPPpppppToono.',
      '.oPPPpppppToono.',
      'oPPPPpppppToono.',
      'oPoPPoppoTToono.',
      'o.o..o..o.o..o..',
    ],
  },
  deathKnight: {
    palette: {
      o: OUTLINE,
      a: '#3a3a44',
      A: '#22222a',
      n: '#5a4030',
      w: '#c8c0a8',
      r: '#ff3020',
    },
    pixels: [
      'oooon...........',
      'oTTTn.o..o......',
      'oTtTn.oaao......',
      'oTTTnoaarro.....',
      'otTon.oaaao.oo..',
      '.o.on.oAaaAowwo.',
      '....noAaaaaowrwo',
      '....noAaaaAowwwo',
      '.ooooooooowwooo.',
      'oTTTTATTTTwwo...',
      'otTTTATTTTto....',
      'otTTTTTTTTto....',
      'otttttttttto....',
      '.owowo....owowo.',
      '.owowo....owowo.',
      '.oAoAo....oAoAo.',
    ],
  },
  rock: {
    palette: { o: OUTLINE, l: '#b4b4b8', g: '#8a8a8e', G: '#5e5e62', d: '#3e3e44' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oollllgoo...',
      '...ollllggggo...',
      '..ollgllgggggo..',
      '..olggggggggGo..',
      '.oolgggggggGGo..',
      '.olgggggggGGGGo.',
      '.oggggggGGGGdGo.',
      '.oGgggGGGGGdddo.',
      '.oGGGGGGGGddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  tree: {
    palette: {
      o: OUTLINE,
      l: '#5aa040',
      g: '#3a7a2a',
      G: '#245018',
      b: '#7a4e2a',
      B: '#4a2e18',
    },
    pixels: [
      '.....oooooo.....',
      '...oollllggo....',
      '..olllllggggo...',
      '.ollllgllgggGo..',
      '.olllggggggGGo..',
      'ollgggggggggGGo.',
      'olggglgggggGGGo.',
      'oggggggggGGGGGo.',
      '.oGgggggGGGGGo..',
      '..oGGGGoGGGGo...',
      '...oooobBoooo...',
      '......obBo......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '.....oooooo.....',
    ],
  },
  deadTree: {
    palette: { o: OUTLINE, b: '#6a5240', B: '#3a2c22' },
    pixels: [
      '.oo........oo...',
      '.obo......obo...',
      '..obo....obo..o.',
      '...obo..obo..obo',
      '....oboobo..obo.',
      'oo...obbo..obo..',
      'obo..obBo.obo...',
      '.obo.obBoobo....',
      '..obbobBbbo.....',
      '...oobBbo.......',
      '.....obBo.......',
      '.....obBo.......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '....oobbBBoo....',
    ],
  },
  crystal: {
    palette: {
      o: '#1a1030',
      w: '#ffffff',
      c: '#7af0ff',
      C: '#30b0d0',
      p: '#c080ff',
      P: '#6a28b0',
    },
    pixels: [
      '.......oo.......',
      '......owco......',
      '......owcCo.....',
      '.....owccCo.....',
      '.....owccCo.o...',
      '.....owccCoopo..',
      '..o..owccCoppPo.',
      '.opo.owccCoppPo.',
      '.oppoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowcCCoppPo.',
      'oPPPooCCCCoPPPo.',
      '.oooooooooooooo.',
      '................',
    ],
  },
}
