import { UPGRADES, type BaseCreature, type CreatureType, type Faction, type HeroId, type ObstacleKind, type UpgradedCreature } from '../game'

export interface Sprite {
  /** Maps a pixel character to a CSS color. '.' is always transparent and is not listed. */
  palette: Record<string, string>
  /** 16 rows of exactly 16 characters each. */
  pixels: string[]
}

/** Every creature, hero, obstacle and town has a sprite of the same name. */
export type SpriteId = CreatureType | HeroId | ObstacleKind | Faction

/**
 * Pixel art for every unit, obstacle and town. The characters 'T' (team color) and
 * 't' (darker team shade) are never listed in a palette: the renderer
 * substitutes the owning player's colors for them. All creatures face right.
 */

const OUTLINE = '#1a1410'
const SKIN = '#e0b088'
const STEEL = '#b8c0c8'
const DARK_STEEL = '#6a7480'
const WOOD = '#8a5a2b'
const BOOTS = '#4a3424'
const BONE = '#e8e0c8'
const BONE_SHADOW = '#a89c80'
const GOLD = '#f0c040'

const BASE_SPRITES: Record<Exclude<SpriteId, UpgradedCreature>, Sprite> = {
  ballista: {
    palette: { o: OUTLINE, w: WOOD, W: '#5a3a1a', m: STEEL, M: DARK_STEEL },
    pixels: [
      '................',
      '..........oo....',
      '..........omo...',
      '.......oo.oMo...',
      '.....oo...oMo...',
      '...oo.....oMo...',
      '.oo.......oMo...',
      'owwwwwwwwwwwwwmo',
      'oWWWWWWWWWWWWWoo',
      '.oo...oTo.oMo...',
      '...oo.oTo.oMo...',
      '.....ooTo.oMo...',
      '......oTooomo...',
      '.....oTtTo.oo...',
      '....owwwwwo.....',
      '....oWWWWWo.....',
    ],
  },
  firstAidTent: {
    palette: { o: OUTLINE, c: '#f0ead8', C: '#b8ae98', r: '#d02828', W: '#5a3a1a' },
    pixels: [
      '.......o........',
      '.......oTTo.....',
      '.......oTo......',
      '.......o........',
      '......ooo.......',
      '.....occCo......',
      '....occcCCo.....',
      '...occcccCCo....',
      '..occcrcccCCo...',
      '.occcrrrcccCCo..',
      'occcccrcccccCCo.',
      'occcccccccccCCo.',
      'occcoooooccCCCo.',
      'occcoWWWoccCCCo.',
      'occcoWWWoccCCCo.',
      'ooooooooooooooo.',
    ],
  },
  ammoCart: {
    palette: { o: OUTLINE, w: WOOD, W: '#5a3a1a', m: STEEL, M: DARK_STEEL },
    pixels: [
      '................',
      '................',
      '....o.o.o.o.....',
      '...omomomomo....',
      '....owowowo.....',
      '....owowowo.....',
      '..ooowowowooo...',
      '..owwwwwwwwwo...',
      '..owTTTTTTTwo...',
      '..owtttttttwo...',
      '..oWWWWWWWWWoooo',
      '...ooo....ooo..o',
      '..oMMMo..oMMMo..',
      '..oMoMo..oMoMo..',
      '..oMMMo..oMMMo..',
      '...ooo....ooo...',
    ],
  },
  pikeman: {
    palette: { o: OUTLINE, s: SKIN, m: STEEL, M: DARK_STEEL, w: WOOD, b: BOOTS },
    pixels: [
      '............o...',
      '...........omo..',
      '...........omo..',
      '....oooo...owo..',
      '...ommmmo..owo..',
      '..ommmmmmo.owo..',
      '..oMMMMMMMoowo..',
      '..oMssssosoowo..',
      '...ossssssoowo..',
      '..oTTTTTTToowo..',
      '.omTTTTTTossso..',
      '.omTTTTTTo.owo..',
      '..otTTTTto.owo..',
      '..ottttto..owo..',
      '..obo..obo.owo..',
      '..obbo.obbooooo.',
    ],
  },
  archer: {
    palette: { o: OUTLINE, s: SKIN, h: '#6b4a2a', l: '#5a3a1e', w: WOOD, b: BOOTS },
    pixels: [
      '................',
      '.....oooo.......',
      '....ohhhho......',
      '...ohhhhhho.....',
      '...ohhsssso.....',
      '...ohhssoso.....',
      '...ohhsssso...o.',
      '....ohhsso...owo',
      '...oTTTTTToooowo',
      '..oTTTTTssllllwo',
      '..oTTTTTTooooowo',
      '..otTTTTto...owo',
      '..ottttto.....o.',
      '...obo.obo......',
      '...obo.obo......',
      '...obbo.obbo....',
    ],
  },
  griffin: {
    palette: {
      o: OUTLINE,
      f: '#f0ead8',
      g: '#c8902e',
      G: '#8a5a1e',
      y: '#f0b020',
      w: '#6a3e1c',
      W: '#a8743c',
    },
    pixels: [
      '................',
      '.oo........ooo..',
      '.oWo......offfo.',
      '.oWWwo...offofo.',
      '..oWWwo.offffyyo',
      '..oWWWwoofffoyo.',
      'o..oWWWwofffo...',
      '.o.oWWWWwffo....',
      '.o.oTTTTTwffo...',
      '.ooggTTTTTggggo.',
      '..ogggggggggggo.',
      '..oGgggggggggGo.',
      '..oGGoGo..oyoyo.',
      '..oGGoGo..oyoyo.',
      '..oGGoGo..oyoyo.',
      '..oooooo..ooooo.',
    ],
  },
  swordsman: {
    palette: { o: OUTLINE, s: SKIN, m: STEEL, M: DARK_STEEL, y: '#e0b030', b: BOOTS },
    pixels: [
      '..o.............',
      '.omo............',
      '.omo..oooo......',
      '.omo.ommmmo.....',
      '.omo.ommMMo.....',
      '.omo.ommmmo.....',
      'oyyyo.ommmoooooo',
      '.oso.oMmmmoTyTto',
      '.ossooMmmmoyyyto',
      '..o..oMmmmoTyTto',
      '.....oMmmmoTyTto',
      '.....oMMMMoTTTto',
      '.....oMo.oMotto.',
      '.....oMo.oMoo...',
      '.....obo.obo....',
      '.....obbo.obbo..',
    ],
  },
  monk: {
    palette: {
      o: OUTLINE,
      s: SKIN,
      r: '#ece8dc',
      R: '#b8b0a0',
      w: WOOD,
      y: '#fff6b0',
      Y: '#f0c040',
    },
    pixels: [
      '............ooo.',
      '...........oyyyo',
      '.....ooo...oyyyo',
      '....orrro...oYo.',
      '...orrrsso..owo.',
      '...orrsoso..owo.',
      '...orrssso..owo.',
      '..orrrrTro..owo.',
      '..orRrrTrrossso.',
      '..orRrrTrro.owo.',
      '..oRRrrtrro.owo.',
      '.oRRrrrtrro.owo.',
      '.oRRrrrtrrroowo.',
      'oRRRrrrtrrrrowo.',
      'oRRRRrrtrrrrowo.',
      '.ooooooooooo.o..',
    ],
  },
  cavalier: {
    palette: {
      o: OUTLINE,
      h: '#d8d0c4',
      m: STEEL,
      M: DARK_STEEL,
      w: '#c8a060',
      b: BOOTS,
      s: SKIN,
    },
    pixels: [
      '....oo.........m',
      '...oTTo.......w.',
      '...ommmo.....w..',
      '...omMMo....w...',
      '...ommmo...woo..',
      '..oTTTTTo.wohho.',
      '..oTTTTTsw.ohoho',
      '..otTTTto.ohhhho',
      '.ooooooooohhooo.',
      'oTTTTMTTTThho...',
      'oTTTTMTTTTTo....',
      'otTTTTTTTTto....',
      'otttttttttto....',
      '.ohoho....ohoho.',
      '.ohoho....ohoho.',
      '.obobo....obobo.',
    ],
  },
  skeleton: {
    palette: { o: OUTLINE, w: BONE, W: BONE_SHADOW, m: '#a0a8b0', y: '#8a6a3a' },
    pixels: [
      '..o.............',
      '.omo.oooo.......',
      '.omoowwwwo......',
      '.omoowwowo......',
      '.omoowwwwo......',
      'oyyyo.oWwo......',
      '.owo..owo.oooo..',
      '.owwowWwWoTTTto.',
      '..o.owWwWoTyTto.',
      '....owWwWoTTTto.',
      '.....owWwotttto.',
      '.....owowo.oo...',
      '.....owowo......',
      '.....owowo......',
      '.....owowo......',
      '.....owwowwo....',
    ],
  },
  walkingDead: {
    palette: {
      o: OUTLINE,
      g: '#8a9a6a',
      G: '#5a6a44',
      r: '#e03020',
      w: '#d8d0b0',
    },
    pixels: [
      '................',
      '................',
      '....oooo........',
      '...oggggo.oooo..',
      '..oTTggggoggggo.',
      '..oTtGgggogggro.',
      '..oGGtGgggggggo.',
      '..oGGGtGgggowwo.',
      '..oGGGtGGgggooo.',
      '..oGGGGtGoggggo.',
      '...oGGGtGo.ogogo',
      '...otTtTto......',
      '...oGo.oGo......',
      '..oGo..oGo......',
      '..oGo...oGo.....',
      '.oGGo...oGGo....',
    ],
  },
  wight: {
    palette: {
      o: '#0a0810',
      P: '#3a3650',
      k: '#000000',
      e: '#7af0ff',
      c: '#a8b0c0',
    },
    pixels: [
      '................',
      '.....oooo.......',
      '....oPPPPo......',
      '...oPPPPPPo.....',
      '...oPPkekeko....',
      '...oPPkkkkko....',
      '..oPPPPkkkPo....',
      '..oPTPPPPPPPcco.',
      '.oPPPTPPPPPPoco.',
      '.oPPPPTPPPPPo...',
      '.oPPPPPtPPPo....',
      '..oPPPPPtPo.....',
      '...oPPPTo.......',
      '..oPPo.otTo.....',
      '.oPPo....oo.....',
      'oPo.............',
    ],
  },
  vampire: {
    palette: {
      o: OUTLINE,
      s: '#dcd8e4',
      h: '#141018',
      r: '#e02020',
      k: '#241a26',
      K: '#3e2c40',
      w: '#f0f0f0',
    },
    pixels: [
      '................',
      '......oooo......',
      '.....ohhhho.....',
      'o...ohhssso...o.',
      'oo.oTohssro..oo.',
      'oTooTtosswo.oTo.',
      'oTTtoKkkwkKotTTo',
      'oTTTtKkkkkKtTTTo',
      'oTTTtKkkkkKtTTTo',
      'otTTtKkkkkKtTTto',
      'oo.otKkkkkKto.oo',
      '.....oKkkKo.....',
      '......oKKo......',
      '......okko......',
      '.......oo.......',
      '................',
    ],
  },
  lich: {
    palette: {
      o: OUTLINE,
      w: BONE,
      W: BONE_SHADOW,
      p: '#4a3462',
      P: '#2e1f40',
      g: '#70ff90',
      G: '#20a040',
      y: '#d0a030',
      n: '#5a4030',
    },
    pixels: [
      '.....y.y.y..ooo.',
      '....oyyyyyoogggo',
      '....owwwwwooggGo',
      '....owwwgwo.oGo.',
      '....owwwWwo.ono.',
      '.....owowo..ono.',
      '..oTTTTTTTToono.',
      '..opppppppTowwo.',
      '..oPppppppToono.',
      '..oPPpppppToono.',
      '..oPPpppppToono.',
      '.oPPPpppppToono.',
      '.oPPPpppppToono.',
      'oPPPPpppppToono.',
      'oPoPPoppoTToono.',
      'o.o..o..o.o..o..',
    ],
  },
  blackKnight: {
    palette: {
      o: OUTLINE,
      a: '#3a3a44',
      A: '#22222a',
      n: '#5a4030',
      w: '#c8c0a8',
      r: '#ff3020',
    },
    pixels: [
      'oooon...........',
      'oTTTn.o..o......',
      'oTtTn.oaao......',
      'oTTTnoaarro.....',
      'otTon.oaaao.oo..',
      '.o.on.oAaaAowwo.',
      '....noAaaaaowrwo',
      '....noAaaaAowwwo',
      '.ooooooooowwooo.',
      'oTTTTATTTTwwo...',
      'otTTTATTTTto....',
      'otTTTTTTTTto....',
      'otttttttttto....',
      '.owowo....owowo.',
      '.owowo....owowo.',
      '.oAoAo....oAoAo.',
    ],
  },
  troglodyte: {
    palette: { o: OUTLINE, g: '#7a8a6a', G: '#566248', m: BONE, w: WOOD },
    pixels: [
      '................',
      '................',
      '....oooo........',
      '...oggggo.......',
      '..oggggggo......',
      '..ogGgggggo..o..',
      '..oggggmmmo.owo.',
      '...ogggggo.owo..',
      '..oggggggoowo...',
      '.ogggggggggo....',
      '.ogoTTTTTogo....',
      '.o.oTTTTTo.o....',
      '...otttto.......',
      '...ogo.ogo......',
      '...ogo.ogo......',
      '..oggo.oggo.....',
    ],
  },
  harpy: {
    palette: { o: OUTLINE, h: '#3a2a3a', s: SKIN, y: '#e0a020' },
    pixels: [
      '................',
      '.....oooo.......',
      '....ohhhho......',
      '...ohhsssso.....',
      '...ohhsoso......',
      '...ohhsssso.....',
      'oo..ohsso....oo.',
      'oTo.oTTTTo..oTo.',
      'oTTooTTTTooTTto.',
      '.otTTTTTTTTTto..',
      '..ootTTTTTtoo...',
      '....otttto......',
      '....oyoyo.......',
      '....oyoyo.......',
      '...oyyoyyo......',
      '................',
    ],
  },
  beholder: {
    palette: { o: OUTLINE, p: '#8a4a8a', P: '#5a2e5a', w: '#f0f0f0', k: '#141018', m: BONE },
    pixels: [
      '...T.....T......',
      '...o..T..o...T..',
      '....o.o.o...o...',
      '.....oooooooo...',
      '...oopppppppoo..',
      '..oppppppppppo..',
      '.oppppowwwopppo.',
      '.opppowwwwwoppo.',
      '.opppowwwkkoppo.',
      '.opppowwwwwoppo.',
      '.oppppowwwopppo.',
      '..oPppppppppTo..',
      '..oPPmmmmmmPTo..',
      '...oPPPPPPPPo...',
      '.....oooooo.....',
      '................',
    ],
  },
  medusa: {
    palette: { o: OUTLINE, g: '#6a9a4a', G: '#4a6a3a', s: '#c8d8a8', r: '#e02020', w: WOOD },
    pixels: [
      '...g.g.g........',
      '..ogogogo...o...',
      '.ogggggggo.owo..',
      '.oggssssgo.o.wo.',
      '..ogssrso..o.wo.',
      '..ogsssso..o..wo',
      '...ossso...o..wo',
      '..oTTTTToooooswo',
      '.osTTTTTo..o..wo',
      '.os.TTTo...o.wo.',
      '...oGGGGo..o.wo.',
      '....oGGGGo..owo.',
      '.....oGGGGo..o..',
      '....oGGGGGo.....',
      '..ooGGGGGo......',
      '.oGGGGGooo......',
    ],
  },
  minotaur: {
    palette: { o: OUTLINE, h: BONE, b: '#6a4028', n: '#c08868', k: '#e02020', M: STEEL, w: WOOD },
    pixels: [
      '..o.......o.....',
      '..oho....oho....',
      '...ohooooho.....',
      '....obbbbbo.....',
      '...obbbbbkbo....',
      '...obbbbbnnno...',
      '....obbbbnno....',
      '..oobbbbboo..oo.',
      '.obbTTTTTbbo.oMo',
      '.obbTTTTTbobooMo',
      '.obotTTTtobbwMMo',
      '..o.ottto..owoo.',
      '....obobo..wo...',
      '....obobo.wo....',
      '...obbobbo......',
      '...oooooooo.....',
    ],
  },
  angel: {
    palette: { o: OUTLINE, s: SKIN, h: GOLD, w: '#f4f4f8', W: '#c8ccd8', m: STEEL, y: '#fff4b0' },
    pixels: [
      '.....yyyy.......',
      'oo..oooooo......',
      'owo.ohhhho......',
      'owwoohssso......',
      'oWwwohssso....o.',
      '.oWwwossso...omo',
      '.oWwwoTTTToo.omo',
      '..oWwTTTTTssoomo',
      '..oWwTTTTToooomo',
      '...oWtTTTto..oho',
      '....owTTTTo.oooo',
      '....owTTTTTo....',
      '....owwTTTTo....',
      '.....owtttto....',
      '......owwwwo....',
      '......oooooo....',
    ],
  },
  boneDragon: {
    palette: { o: OUTLINE, b: BONE, B: BONE_SHADOW, g: '#60f0a0', k: '#2a2430' },
    pixels: [
      '..oo............',
      '..oBo.......oo..',
      '..oBBo.....obbo.',
      '..oBkBo...obbgbo',
      '..oBkkBoooobbbbo',
      '..oBkkkBobboobo.',
      '.ooBkkkbobbo....',
      'obboTtbobbo.....',
      'obobTTtbkbo.....',
      '.obkbkbkbkbo....',
      '..obkbkbkbbo....',
      '..obbbbbbbbbo...',
      '...oBkBkBkBbo...',
      '...obBo..obBoo..',
      '...obko..obko...',
      '..oooo..oooo....',
    ],
  },
  manticore: {
    palette: { o: OUTLINE, l: '#c88a3a', L: '#8a5a20', m: '#a03028', s: '#e0b088', k: '#6a1c50', K: '#3a1030', r: '#e02020' },
    pixels: [
      '.oo.........oo..',
      'okKo.......ommo.',
      'okkKo.....omrmo.',
      'okkkKo...omssso.',
      'oTkkkKo..omssso.',
      '.oTtkkKoomsssmo.',
      'oo.oTtkKommmmo..',
      'oko.oTtlllllmo..',
      'okKoolllllllllo.',
      '.okkolllTTTlllo.',
      '..oolllTTTTTllo.',
      '....oLlltttllLo.',
      '....oLLo...oLLo.',
      '....oLLo...oLLo.',
      '...oLLo...oLLo..',
      '...oooo...oooo..',
    ],
  },
  redDragon: {
    palette: { o: OUTLINE, k: '#b02a1c', K: '#e0583a', y: '#f0c040', f: '#ff8a20' },
    pixels: [
      '..oo............',
      '..oTo.......oo..',
      '..oTTo.....okko.',
      '..oTtTo...okkyko',
      '..oTttToookkkkfo',
      '..oTtttTkkkkoff.',
      '.ooTtttkkkkko...',
      'okkoTtkkkkko....',
      'okkkkkkkkkko....',
      '.okkkkkkkkkko...',
      '..okKkKkKkKko...',
      '..okkkkkkkkkko..',
      '...oKKKKKKKKko..',
      '...okKo..okKoo..',
      '...okko..okko...',
      '..oooo..oooo....',
    ],
  },
  rock: {
    palette: { o: OUTLINE, l: '#b4b4b8', g: '#8a8a8e', G: '#5e5e62', d: '#3e3e44' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oollllgoo...',
      '...ollllggggo...',
      '..ollgllgggggo..',
      '..olggggggggGo..',
      '.oolgggggggGGo..',
      '.olgggggggGGGGo.',
      '.oggggggGGGGdGo.',
      '.oGgggGGGGGdddo.',
      '.oGGGGGGGGddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  tree: {
    palette: {
      o: OUTLINE,
      l: '#5aa040',
      g: '#3a7a2a',
      G: '#245018',
      b: '#7a4e2a',
      B: '#4a2e18',
    },
    pixels: [
      '.....oooooo.....',
      '...oollllggo....',
      '..olllllggggo...',
      '.ollllgllgggGo..',
      '.olllggggggGGo..',
      'ollgggggggggGGo.',
      'olggglgggggGGGo.',
      'oggggggggGGGGGo.',
      '.oGgggggGGGGGo..',
      '..oGGGGoGGGGo...',
      '...oooobBoooo...',
      '......obBo......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '.....oooooo.....',
    ],
  },
  deadTree: {
    palette: { o: OUTLINE, b: '#6a5240', B: '#3a2c22' },
    pixels: [
      '.oo........oo...',
      '.obo......obo...',
      '..obo....obo..o.',
      '...obo..obo..obo',
      '....oboobo..obo.',
      'oo...obbo..obo..',
      'obo..obBo.obo...',
      '.obo.obBoobo....',
      '..obbobBbbo.....',
      '...oobBbo.......',
      '.....obBo.......',
      '.....obBo.......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '....oobbBBoo....',
    ],
  },
  tombstone: {
    palette: { o: OUTLINE, l: '#9a9aa2', g: '#6a6a72', d: '#3a3230' },
    pixels: [
      '................',
      '................',
      '................',
      '.....oooooo.....',
      '....ollllllo....',
      '...ollllllllo...',
      '...olllolllgo...',
      '...ollooolggo...',
      '...olllolllgo...',
      '...olllolllgo...',
      '...ollllllggo...',
      '...ollllllggo...',
      '...olllllgggo...',
      '..oooooooooooo..',
      '.odddddddddddddo',
      '..oooooooooooo..',
    ],
  },
  stalagmite: {
    palette: { o: OUTLINE, l: '#a08a74', g: '#7a6656', G: '#54443a', d: '#2e2620' },
    pixels: [
      '................',
      '.......oo.......',
      '.......olo......',
      '......ollgo.....',
      '......ollgo.....',
      '.....olllggo....',
      '.....ollgggo..o.',
      '....ollllggo.olo',
      '....olllgggoolgo',
      '...olllggggoolgo',
      '...ollllgggGolgo',
      '..olllgggggGolGo',
      '..ollggggggGGlGo',
      '.ollgggggGGGGgGo',
      '.odddddddddddddo',
      '..oooooooooooooo',
    ],
  },
  crystal: {
    palette: {
      o: '#1a1030',
      w: '#ffffff',
      c: '#7af0ff',
      C: '#30b0d0',
      p: '#c080ff',
      P: '#6a28b0',
    },
    pixels: [
      '.......oo.......',
      '......owco......',
      '......owcCo.....',
      '.....owccCo.....',
      '.....owccCo.o...',
      '.....owccCoopo..',
      '..o..owccCoppPo.',
      '.opo.owccCoppPo.',
      '.oppoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowcCCoppPo.',
      'oPPPooCCCCoPPPo.',
      '.oooooooooooooo.',
      '................',
    ],
  },
  // Hero portraits, facing the viewer. Castle hides its faces, Necropolis is bone and bat, Dungeon is beast and dragon.
  tyris: {
    palette: { o: OUTLINE, M: STEEL, N: DARK_STEEL, d: '#141018' },
    pixels: [
      '.......TT.......',
      '......TTtT......',
      '.....oooooo.....',
      '....oMMMMMMo....',
      '...oMMMMMMMNo...',
      '...oMMMMMMMNo...',
      '...oMddddddNo...',
      '...oMMMMMMMNo...',
      '...oMMdMMdMNo...',
      '...oMMMMMMMNo...',
      '....oMMMMMNo....',
      '..ooMMMMMMMMoo..',
      '.oMMTTTTTTTTMMo.',
      '.oMTTTTTTTTTTMo.',
      '.oMTTTTttTTTTMo.',
      '.oooooooooooooo.',
    ],
  },
  edric: {
    palette: { o: OUTLINE, M: STEEL, N: DARK_STEEL, d: '#141018', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oMMMMMMo....',
      '...oMMMMMMMNo...',
      '...oMMMMMMMNo...',
      '...oMddddddNo...',
      '...oMMMddMMNo...',
      '...oMMMddMMNo...',
      '...oMMMMMMMNo...',
      '...oyyyyyyyyo...',
      '....oooooooo....',
      '..ooMMMMMMMMoo..',
      '.oMMTTTTTTTTMMo.',
      '.oMTTTTyyTTTTMo.',
      '.oMTTTyyyyTTTMo.',
      '.oooooooooooooo.',
    ],
  },
  adela: {
    palette: { o: OUTLINE, k: '#1e1a22', w: '#f0ece0', s: SKIN, e: OUTLINE, v: '#3a3440', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....okkkkkko....',
      '...okkkkkkkko...',
      '...okwwwwwwko...',
      '...okwessewko...',
      '...okwvvvvwko...',
      '...okwvvvvwko...',
      '...okwwvvwwko...',
      '...okkwwwwkko...',
      '...okkkkkkkko...',
      '..ookkkkkkkkoo..',
      '.oTkkkkkkkkkkTo.',
      '.oTkkkkyykkkkTo.',
      '.oTkkkyyyykkkTo.',
      '.oooooooooooooo.',
    ],
  },
  vokial: {
    palette: { o: OUTLINE, k: '#2a2030', f: '#4a3440', r: '#ff3030', p: '#d07890', w: '#f0f0f0' },
    pixels: [
      '.o............o.',
      '.oo..........oo.',
      '.oko..oooo..oko.',
      '.okkooffffookko.',
      '..okkffffffkko..',
      '...offrffrffo...',
      '...offffffffo...',
      '...offfppfffo...',
      '...offwffwffo...',
      '....offffffo....',
      '.....oooooo.....',
      '.oooooTTTTooooo.',
      '.okkooTTTTookko.',
      '.okkkkTTTTkkkko.',
      '.okkkkTTttkkkko.',
      '.oooooooooooooo.',
    ],
  },
  septienna: {
    palette: { o: OUTLINE, k: '#2a1e30', b: BONE, v: '#c060ff', d: '#141018', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....okkkkkko....',
      '...okkkkkkkko...',
      '...okkbbbbkko...',
      '...okbbbbbbko...',
      '...okdvbbvdko...',
      '...okbbbbbbko...',
      '...okbbddbbko...',
      '...okkbdbdkko...',
      '.oko.okkkko.oko.',
      '.okkooTTTTookko.',
      '.okkkoTTTTokkko.',
      '.okkkkTyyTkkkko.',
      '.okkkkTTTTkkkko.',
      '.oooooooooooooo.',
    ],
  },
  thant: {
    palette: { o: OUTLINE, y: GOLD, b: BONE, g: '#40e060', d: '#141018', k: '#2a2a22' },
    pixels: [
      '....y..yy..y....',
      '...oyyyyyyyyo...',
      '..obbbbbbbbbbo..',
      '..obbbbbbbbbbo..',
      '..obggbbbbggbo..',
      '..obddbbbbddbo..',
      '..obbbbddbbbbo..',
      '..oobbbbbbbboo..',
      '...obdbdbdbdo...',
      '...obbbbbbbbo...',
      '....oooooooo....',
      '.ookkkobbokkkoo.',
      '.okTbbbbbbbbTko.',
      '.okTkkkkkkkkTko.',
      '.okTbbbbbbbbTko.',
      '.oooooooooooooo.',
    ],
  },
  lorelei: {
    palette: { o: OUTLINE, f: '#6a3a8a', y: '#ffd040', b: '#d8a030' },
    pixels: [
      '.....o.oo.o.....',
      '....ofoffofo....',
      '...offffffffo...',
      '..offffffffffo..',
      '..offyffffyffo..',
      '..offffbbffffo..',
      '..offfbbbbfffo..',
      '...offfbbfffo...',
      '....offbbffo....',
      '.....offffo.....',
      '......oooo......',
      '.offoTTTTTToffo.',
      '.offfoTTTTofffo.',
      '.offffTTTTffffo.',
      '.offffTTttffffo.',
      '.oooooooooooooo.',
    ],
  },
  dace: {
    palette: { o: OUTLINE, h: BONE, n: '#6a4a2a', r: '#e02020', s: '#b08868', d: '#141018', y: GOLD },
    pixels: [
      '.o............o.',
      '.oho........oho.',
      '.ohhoooooooohho.',
      '..oonnnnnnnnoo..',
      '...onnnnnnnno...',
      '...onrnnnnrno...',
      '...onnnnnnnno...',
      '....onssssno....',
      '....osdssdso....',
      '....ossyysso....',
      '.....oooooo.....',
      '.oonnnTTTTnnnoo.',
      '.onnnTTTTTTnnno.',
      '.onnnTTyyTTnnno.',
      '.onnnTTTTTTnnno.',
      '.oooooooooooooo.',
    ],
  },
  deemer: {
    palette: { o: OUTLINE, k: '#2a2430', K: '#4a3e58', r: '#ff3020', d: '#141018', w: '#f0f0f0', f: '#ff8a20', y: GOLD },
    pixels: [
      '.o............o.',
      '.oko........oko.',
      '..okooooooooko..',
      '...okkkkkkkko...',
      '..okkKkkkkKkko..',
      '..okrrkkkkrrko..',
      '..okkkkkkkkkko..',
      '...okKKKKKKko...',
      '...okkkkkkkko...',
      '...okdkkkkdko...',
      '...owkwwwwkwo...',
      '....offffffo....',
      '.okkkTTTTTTkkko.',
      '.okkTTTTTTTTkko.',
      '.okkTTTyyTTTkko.',
      '.oooooooooooooo.',
    ],
  },
  // Rampart, Stronghold and Inferno: creatures, hero portraits and homeland obstacles.
  centaur: {
    palette: { o: OUTLINE, s: SKIN, h: '#5a3a1e', c: '#a0662e', C: '#6e4420', w: WOOD },
    pixels: [
      '.......oooo.....',
      '......ohhhho....',
      '......ohssso....',
      '......ohsoso..o.',
      '.......ossso.owo',
      '......oTTTTooowo',
      '.....oTTTTTsswo.',
      '.....otTTTTooowo',
      '..ooocTTTTco.owo',
      '.occccccccccoo..',
      'ohcccccccccccCo.',
      'oh.oCcccccccCo..',
      '...oCCo...oCCo..',
      '...oCo.....oCo..',
      '...oCo.....oCo..',
      '...ooo.....ooo..',
    ],
  },
  dwarf: {
    palette: { o: OUTLINE, s: SKIN, r: '#c0642a', R: '#8a4018', m: STEEL, M: DARK_STEEL, w: WOOD, b: BOOTS },
    pixels: [
      '..............o.',
      '.............omo',
      '.....oooooo.oMMo',
      '....ommmmmmo.ow.',
      '...oMmmmmmmMoow.',
      '...osssssssso.w.',
      '...ossosssoso.w.',
      '...orrrrrrrro.w.',
      '..orrrrrrrrrrow.',
      '..oTrrRrrRrrTow.',
      '.oTTTRrrrrRTTow.',
      '.osTTTRRRRTTssw.',
      '..otTTTTTTTTtow.',
      '...otttttttto.o.',
      '...obbbo.obbbo..',
      '..obbbbo.obbbbo.',
    ],
  },
  woodElf: {
    palette: { o: OUTLINE, s: SKIN, h: '#e8d070', g: '#3a7a2a', G: '#245018', w: WOOD, b: BOOTS },
    pixels: [
      '..........o.....',
      '....oooo..ow....',
      '...ohhhho.o.w...',
      '..ohhssso.o..w..',
      '..ohssoso.o..w..',
      '.oshhsssoo...w..',
      '...ohsso.o...w..',
      '...oGTTTTo...w..',
      '..oGTTTTTsssssw.',
      '..oGTTTTTo...w..',
      '...otTTTto...w..',
      '...ogggggo..w...',
      '...oggogg.o.w...',
      '...obo.obooow...',
      '...obo.obo..o...',
      '..obbo.obbo.....',
    ],
  },
  pegasus: {
    palette: { o: OUTLINE, f: '#f4f4f8', F: '#c0c4d4', y: '#f0d060', b: '#8ab0e0' },
    pixels: [
      '................',
      '..oo.......oo...',
      '.obbo.....offo..',
      '.obbbo...offyfo.',
      '..obbbo.offffo..',
      '..obbbboffffoo..',
      '...obbbbffffo...',
      '...oTTTTTffo....',
      '.oofTTTTTTfo....',
      'offfffffffffo...',
      'offfffffffffFo..',
      '.ofoFffffffFo...',
      '...oFFo..oFFo...',
      '...oFo....oFo...',
      '...oFo....oFo...',
      '...ooo....ooo...',
    ],
  },
  dendroidGuard: {
    palette: { o: OUTLINE, b: '#7a4e2a', B: '#4a2e18', l: '#5aa040', g: '#3a7a2a', G: '#245018', y: '#f0d040' },
    pixels: [
      '....oo.oo.oo....',
      '...olloggolgo...',
      '..olgggllggggo..',
      '..ogglgggglgGo..',
      '...oogbbbbgoo...',
      '....obybbybo....',
      '....obbbbbbo....',
      '..oobTTTTTbBoo..',
      '.obbbTTTTTbbBBo.',
      '.ob.oTTttTTo.Bo.',
      '.oo.obbbbbBo.oo.',
      '....obbbbbBo....',
      '....obBo.obBo...',
      '....obBo.obBo...',
      '...obbBo.obbBo..',
      '...ooooo.ooooo..',
    ],
  },
  unicorn: {
    palette: { o: OUTLINE, f: '#f8f6ff', F: '#c8c4e0', y: GOLD, m: '#e080c0' },
    pixels: [
      '.............y..',
      '............yo..',
      '........oooyo...',
      '.......offffoo..',
      '......omffofffo.',
      '.....ommfffoffo.',
      '.....omfo.oooo..',
      '....omTfo.......',
      '.oooffTTfo......',
      'omffffTTffffo...',
      'om.fffffffffFo..',
      '.o.oFfffffffFo..',
      '...oFFo...oFFo..',
      '...oFo.....oFo..',
      '...oFo.....oFo..',
      '...ooo.....ooo..',
    ],
  },
  greenDragon: {
    palette: { o: OUTLINE, g: '#3a9a3a', G: '#1e5e24', y: '#e0e040', r: '#e02020' },
    pixels: [
      '..oo............',
      '..oTo.......oo..',
      '..oTTo.....oggo.',
      '..oTtTo...oggrgo',
      '..oTttToooggggyo',
      '..oTtttTggggoyy.',
      '.ooTtttggggggo..',
      'oggoTtggggggo...',
      'oggggggggggo....',
      '.ogggggggggyo...',
      '..oggggggggyo...',
      '..oggggggggyyo..',
      '...oGGGGGGGGgo..',
      '...ogGo..ogGoo..',
      '...oggo..oggo...',
      '..oooo..oooo....',
    ],
  },
  ivor: {
    palette: { o: OUTLINE, s: SKIN, h: '#e8d070', H: '#b89a40', g: '#3a7a2a', G: '#245018', e: '#2a6a2a' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oggggggo....',
      '...oggggggggo...',
      '..oGhhhhhhhhGo..',
      '.o.ohssssssho.o.',
      '.sohsessesshos..',
      '..ohssssssssho..',
      '..ohssssssssho..',
      '..oHhsssssshHo..',
      '...oHhssssHHo...',
      '....oohsshoo....',
      '..ooggTTTTggoo..',
      '.ogGTTTTTTTTGgo.',
      '.ogTTTTttTTTTgo.',
      '.oooooooooooooo.',
    ],
  },
  ryland: {
    palette: { o: OUTLINE, s: SKIN, h: '#7a4a24', b: '#7a4e2a', l: '#5aa040', g: '#3a7a2a', d: '#141018' },
    pixels: [
      '...oo.oooo.oo...',
      '..olloggllgllo..',
      '...oglllggggo...',
      '....ohhhhhho....',
      '...ohssssssho...',
      '...ohsdssdsho...',
      '...ohssssssho...',
      '...ohhssssshho..',
      '...ohhhsshhhho..',
      '....ohhhhhhho...',
      '.....ohhhhho....',
      '..oooboooooboo..',
      '.obbTTTTTTTTbbo.',
      '.obTTTTggTTTTbo.',
      '.obTTTggggTTTbo.',
      '.oooooooooooooo.',
    ],
  },
  uland: {
    palette: { o: OUTLINE, s: SKIN, w: '#e8e8e0', W: '#b8b8b0', l: '#5aa040', g: '#3a7a2a', d: '#141018' },
    pixels: [
      '.....ol.lo......',
      '....olglglo.....',
      '...oggggggggo...',
      '...ogwwwwwwgo...',
      '...owssssssWo...',
      '...owsdssdsWo...',
      '...owssssssWo...',
      '...owwssssWWo...',
      '...owwwwwwwWo...',
      '....owwwwwWo....',
      '....owwwwwWo....',
      '..ooTowwwWoToo..',
      '.oTTTTowwoTTTTo.',
      '.oTTTTTooTTTTTo.',
      '.oTTTTTttTTTTTo.',
      '.oooooooooooooo.',
    ],
  },
  oak: {
    palette: { o: OUTLINE, l: '#7ab84a', g: '#4a8a30', G: '#2e5c1c', b: '#6a4424', B: '#3e2614' },
    pixels: [
      '....oooooooo....',
      '..oollllgggGoo..',
      '.olllllgggggGGo.',
      'olllgllggglgGGGo',
      'ollggggggggggGGo',
      'oglggglggggGgGGo',
      'oggggggggGGGGGGo',
      '.oGggGGgGGGoGGo.',
      '..ooGGoGGGGooo..',
      '....oobbBBoo....',
      '......obBo......',
      '.....obbBBo.....',
      '.....obbBBo.....',
      '....obbbBBBo....',
      '...obBobBoBBo...',
      '...oooooooooo...',
    ],
  },
  mushroom: {
    palette: { o: OUTLINE, r: '#c83030', R: '#8a1e1e', w: '#f4f0e0', W: '#c8c0a8' },
    pixels: [
      '................',
      '................',
      '.....oooooo.....',
      '...oorrwrrrroo..',
      '..orrrrrrrwrrro.',
      '.orwwrrrrrrrrRo.',
      '.orwwrrrwwrrRRo.',
      'orrrrrrrwwrRRRRo',
      'oRRRRRRRRRRRRRRo',
      '.oooowwwwWWoooo.',
      '.....owwwwWo....',
      '.....owwwwWo....',
      '.....owwwwWo....',
      '....owwwwwWWo...',
      '....owwwwWWWo...',
      '.....oooooooo...',
    ],
  },
  goblin: {
    palette: { o: OUTLINE, g: '#8aa040', G: '#5e7028', y: '#f0d020', w: WOOD, M: STEEL, b: BOOTS },
    pixels: [
      '................',
      '................',
      '..o.............',
      '..ogoooo........',
      '...ogggggo......',
      '...oggyggo...o..',
      '..oggggggGo.oMo.',
      '...oGgggGo..oMo.',
      '....ooooo..owo..',
      '...oTTTTToowo...',
      '..ogTTTTTggo....',
      '..oooTTTto......',
      '....otttto......',
      '....ogo.ogo.....',
      '....ogo.ogo.....',
      '...obbo.obbo....',
    ],
  },
  wolfRider: {
    palette: { o: OUTLINE, g: '#8aa040', G: '#5e7028', f: '#8a8a90', F: '#5a5a62', w: WOOD, M: STEEL, r: '#e02020', h: BONE },
    pixels: [
      '................',
      '......o.........',
      '.....ogoo.......',
      '.....oggGo..o...',
      '.....ogggo.oMo..',
      '....oTTTToowo...',
      '....oTTTTgwo....',
      '.....ottooo..oo.',
      '.o..offffffoofFo',
      'oFooffffffffffro',
      'offfffffffffffho',
      '.offffffffffooo.',
      '..ofFo....oFfo..',
      '..ofo.....ofo...',
      '.ofo.......ofo..',
      '.oo.........oo..',
    ],
  },
  orc: {
    palette: { o: OUTLINE, g: '#6a8a4a', G: '#4a6232', h: BONE, w: WOOD, b: BOOTS, r: '#c03020', M: STEEL },
    pixels: [
      '................',
      '....ooooo.......',
      '...ogggggo......',
      '..oggggrgGo.....',
      '..ogggggggo.....',
      '..oggghgho......',
      '...ooggggo...o..',
      '..oTTTTTTo..oMo.',
      '.ogTTTTTTTooMMo.',
      '.ogTTTTTTggoMo..',
      '.oooTTTTTo..o...',
      '...otttttwo.....',
      '...ottttto......',
      '...obo.obo......',
      '...obo.obo......',
      '..obbo.obbo.....',
    ],
  },
  ogre: {
    palette: { o: OUTLINE, s: '#c0a070', S: '#8a7048', h: BONE, w: WOOD, W: '#5a3a1e', b: BOOTS },
    pixels: [
      '............oo..',
      '....ooooo..oWWo.',
      '...ossssso.oWWo.',
      '..osssssSso.owo.',
      '..osshssShooWo..',
      '...ossssso.owo..',
      '..oosssSoooWo...',
      '.osTTTTTTsswo...',
      '.osTTTTTTTsso...',
      '.osTTTTTTTso....',
      '.oooTTTTTTo.....',
      '...otttttto.....',
      '...osssssso.....',
      '...osso.osso....',
      '...osso.osso....',
      '..obbbo.obbbo...',
    ],
  },
  roc: {
    palette: { o: OUTLINE, f: '#8a5a30', F: '#5e3a1a', y: GOLD, Y: '#c08a10', w: '#f0ead8', r: '#e02020' },
    pixels: [
      '................',
      '.oo.............',
      '.ofoo.......ooo.',
      '.offfoo....owwwo',
      '..offffoo.orwwyo',
      '..offFfffoowwwyo',
      '...offFFfffwwYo.',
      '...ooffFffffoo..',
      '..offfTTTTffo...',
      '.offfTTTTTfffo..',
      '.oFffTTTTffffo..',
      '..oFFftttfFFo...',
      '...ooofffooo....',
      '.....oyo.oyo....',
      '....oyyo.oyyo...',
      '................',
    ],
  },
  cyclops: {
    palette: { o: OUTLINE, s: '#c08a68', S: '#8a6048', w: '#f0f0f0', r: '#e02020', l: '#7a7a80', b: BOOTS },
    pixels: [
      '.........oo.....',
      '....oooooll.....',
      '...osssssolo....',
      '..ossswwssol....',
      '..ossswrssso....',
      '..osssssSso.....',
      '...ossSSso......',
      '..oosssssoo.....',
      '.osTTTTTTTso....',
      '.osTTTTTTTso....',
      '.osoTTTTTosso...',
      '.oo.ottttoooo...',
      '....ottttto.....',
      '...osso.osso....',
      '...osso.osso....',
      '..obbbo.obbbo...',
    ],
  },
  behemoth: {
    palette: { o: OUTLINE, f: '#9a7a5a', F: '#6a5038', h: BONE, r: '#e02020', k: '#2a1c12' },
    pixels: [
      '................',
      '.........o.o....',
      '........ohoho...',
      '.......offfffo..',
      '.ooo..offffrfo..',
      'ofFfoofffffffho.',
      'ofFffffffffhkho.',
      '.offfTTTTffffo..',
      '.ofTTTTTTTTffo..',
      '.ofTTTTTTTTTfo..',
      '.oFtttttttttFo..',
      '.oFFffffffffFo..',
      '..offo...offo...',
      '..offo...offo...',
      '.ohfho..ohfho...',
      '.ooooo..ooooo...',
    ],
  },
  jabarkas: {
    palette: { o: OUTLINE, g: '#6a8a4a', G: '#4a6232', h: BONE, r: '#c03020', d: '#141018', y: GOLD, f: '#8a5a30' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....offffffo....',
      '...offffffffo...',
      '...oggggggggo...',
      '..ooggggggggoo..',
      '..ogggrggrgggo..',
      '..ogggggggggGo..',
      '...oggGggGggo...',
      '...oghggggho....',
      '....oggggggo....',
      '.....oooooo.....',
      '.offfTTTTTTfffo.',
      '.offTTTTTTTTffo.',
      '.offTTTyyTTTffo.',
      '.oooooooooooooo.',
    ],
  },
  shiva: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', n: '#3a2414', d: '#141018', r: '#c03020', w: '#f0ead8', f: '#8a5a30', y: GOLD },
    pixels: [
      '.......oo.......',
      '......owwo......',
      '.....owffwo.....',
      '....onnnnnno....',
      '...onnnnnnnno...',
      '...onsssssssno..',
      '...onsdsssdsno..',
      '...onsssssssno..',
      '...onssSSSssno..',
      '...onssrrrssno..',
      '....onsssssno...',
      '.....ooooooo....',
      '.onnnTTTTTTnnno.',
      '.onnTTTTTTTTnno.',
      '.onnTTTyyTTTnno.',
      '.oooooooooooooo.',
    ],
  },
  terek: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', n: '#3a2414', d: '#141018', h: STEEL, H: DARK_STEEL, c: '#40c0f0', y: GOLD },
    pixels: [
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhhcchhho...',
      '..oHhhhhhhhhHo..',
      '..oHHHHHHHHHHo..',
      '...osssssssso...',
      '...osdssssdso...',
      '...ossssssss....',
      '...ossSSSSsso...',
      '...onnnnnnnno...',
      '....onnnnnno....',
      '.....oonnoo.....',
      '.occcTTTTTTccco.',
      '.occTTTTTTTTcco.',
      '.occTTTyyTTTcco.',
      '.oooooooooooooo.',
    ],
  },
  boulder: {
    palette: { o: OUTLINE, l: '#e0c890', s: '#c8a868', S: '#a08048', d: '#6a5030' },
    pixels: [
      '................',
      '................',
      '................',
      '.......ooooo....',
      '.....oollllso...',
      '....ollsssssSo..',
      '...olsssssSsSo..',
      '..olssSssssSSo..',
      '..olsssssSSSSSo.',
      '.oolssssSSSSdSo.',
      '.olsssSSSSSSdSo.',
      '.osssSSSSdSddSo.',
      '.oSssSSSSdddddo.',
      '.oSSSSSSddddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  totem: {
    palette: { o: OUTLINE, w: '#a06a32', W: '#6a4220', r: '#c03020', y: GOLD, k: '#141018', g: '#4a8a3a' },
    pixels: [
      '..oo...oo...oo..',
      '..oyo.ogo..oyo..',
      '...oyoooooooyo..',
      '....oooyyyoooo..',
      '.....owwwwwo....',
      '.....okwwwko....',
      '.....owwrwwo....',
      '.....oWkkkWo....',
      '.....owwwwwo....',
      '.....oyrwryo....',
      '.....owwwwwo....',
      '.....oWkkkWo....',
      '.....owwwwwo....',
      '.....owWwWwo....',
      '....owwwwwwwo...',
      '...ooooooooooo..',
    ],
  },
  imp: {
    palette: { o: OUTLINE, r: '#c0302a', R: '#7a1c18', y: '#ffd040', h: BONE, k: '#141018' },
    pixels: [
      '................',
      '................',
      '................',
      '.....o...o......',
      '....oho.oho.....',
      '....orrrrro.....',
      '...orrryrryo....',
      '...orrrrrrro....',
      '....orrkkro.....',
      '.oo..orrro..oo..',
      '.oRooTTTTooRo...',
      '..oRRTTTTRRo....',
      '....otttto......',
      '....oro.oro...o.',
      '....oro.oro..oro',
      '...orro.orroorRo',
    ],
  },
  gog: {
    palette: { o: OUTLINE, g: '#8a6a3a', G: '#5a4224', r: '#e02020', f: '#ff8a20', y: '#ffe060', b: BOOTS },
    pixels: [
      '................',
      '.....oooo.......',
      '....oggggo......',
      '...ogggggo......',
      '...oggrgrgo.....',
      '...ogggggggo....',
      '....oggGGo..oo..',
      '...oTTTTTTooyfo.',
      '..oTTTTTTggoffyo',
      '..ogTTTTToo.offo',
      '..ogtTTTto...oo.',
      '...otttttto.....',
      '....oGo.oGo.....',
      '....oGo.oGo.....',
      '....obo.obo.....',
      '...obbo.obbo....',
    ],
  },
  hellHound: {
    palette: { o: OUTLINE, r: '#8a2a1a', R: '#5a1a10', f: '#ff8a20', y: '#ffd040', k: '#141018', w: '#f0f0f0' },
    pixels: [
      '................',
      '................',
      '..........o.o...',
      '.........oroRo..',
      '........orrrrro.',
      'f......orrryrrro',
      'ff.....orrrrrwwo',
      '.fo..ooorrrrkko.',
      '..orrrrrrrrrro..',
      '..orTTTTTTrrro..',
      '..orTTTTTTrrro..',
      '..orrttttRRRro..',
      '..oRRo...oRRo...',
      '..oRo.....oRo...',
      '..oRo.....oRo...',
      '.oko.....oko....',
    ],
  },
  demon: {
    palette: { o: OUTLINE, r: '#b03024', R: '#6e1a14', h: BONE, y: '#ffd040', k: '#141018' },
    pixels: [
      '...o.....o......',
      '...oho..oho.....',
      '....ohoooho.....',
      '....orrrrro.....',
      '...orryrryro....',
      '...orrrrrrro....',
      '....orkkkro.....',
      '..oooorrrooooo..',
      '.orrrTTTTTTrrro.',
      '.orrTTTTTTTTrro.',
      '.orotTTTTTTtoro.',
      '.oho.ottttto.oho',
      '....oRRo.oRRo...',
      '....oRo...oRo...',
      '...oRRo...oRRo..',
      '...ooo.....ooo..',
    ],
  },
  pitFiend: {
    palette: { o: OUTLINE, r: '#8a2440', R: '#521428', s: '#8a2440', h: BONE, y: '#ffd040', M: STEEL, w: WOOD },
    pixels: [
      '..o.......o.....',
      '..oho....oho....',
      '...ohooooho...o.',
      '...orrrrrro..oMo',
      '..orryrryrro.oMo',
      '..orrrrrrrro.oMo',
      '...orrhhrro..owo',
      '.ooorrrrrrooooso',
      'orrrTTTTTTrrrowo',
      'orRrTTTTTTrrRowo',
      'oRrotTTTTtorRowo',
      '.oo.otttto.oo.wo',
      '....oRRoRRo...wo',
      '....oRo.oRo...o.',
      '...oRRo.oRRo....',
      '...oooo.oooo....',
    ],
  },
  efreet: {
    palette: { o: OUTLINE, f: '#ff8a20', F: '#e0501a', y: '#ffe060', r: '#c02818', k: '#141018' },
    pixels: [
      '.....y..y.......',
      '....yfyyfy......',
      '....offffo......',
      '...offkfkfo.....',
      '...offffffo.....',
      '....offFfo......',
      '.ooooTTTTooooo..',
      'offfTTTTTTfffo..',
      'oFfoTTTTTToFfo..',
      '.oo.otTTto.oo...',
      '.....offfo......',
      '.....oFffyo.....',
      '......oFfyo.....',
      '.......oFfo.....',
      '........oyo.....',
      '.........o......',
    ],
  },
  devil: {
    palette: { o: OUTLINE, r: '#9a1a1a', R: '#5a0e0e', h: BONE, k: '#141018', y: '#ffd040', M: STEEL },
    pixels: [
      '..oo......oo....',
      '.oho.oooo.oho...',
      '..oooorrrooo..o.',
      'oo..orryryro.oMo',
      'oRo.orrrrrro.oMo',
      'oRRo.orkkro..oMo',
      'oRRRoorrroo.oMMo',
      'oRRRTTTTTTTrrro.',
      'oRRoTTTTTTTo.o..',
      '.oo.otTTTTto....',
      '....otttttto....',
      '....orro.orro...',
      '....oro...oro...',
      '....oro...oro...',
      '...orro...orro..',
      '...oooo...oooo..',
    ],
  },
  lavaRock: {
    palette: { o: OUTLINE, g: '#4a3a38', G: '#2e2422', d: '#1c1614', f: '#ff8a20', y: '#ffd040', r: '#e0401a' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oogggggoo...',
      '...oggggGgggo...',
      '..oggfgGGgggGo..',
      '..ogGfyfgGgGGo..',
      '.ooggGrfggGGGo..',
      '.ogggGGrfGGGGGo.',
      '.ogggGGGfyfGdGo.',
      '.oGgggGGGGrfddo.',
      '.oGGrfGGGGddddo.',
      '..odddddddddddo.',
      '...ooooooooooo..',
    ],
  },
  fireVent: {
    palette: { o: OUTLINE, y: '#ffe060', f: '#ff8a20', r: '#e0401a', s: '#c8b040', S: '#8a7428', d: '#3a2e1c' },
    pixels: [
      '................',
      '.......y........',
      '......yfy.......',
      '.....yffy.y.....',
      '.....fyfffy.....',
      '....ffyyyff.....',
      '....frfyyfr.....',
      '.....rffffr.....',
      '......rffr......',
      '....oooooooo....',
      '...osSddddSso...',
      '..ossSddddSsso..',
      '.ossssSSSSssSso.',
      '.oSssssssssSSdo.',
      '..odddddddddddo.',
      '...ooooooooooo..',
    ],
  },
  fiona: {
    palette: { o: OUTLINE, h: '#c02818', H: '#7a1810', s: SKIN, d: '#141018', r: '#e02020', y: GOLD, m: BONE },
    pixels: [
      '.o............o.',
      '.omo........omo.',
      '..ohoooooooooo..',
      '..ohhhhhhhhhho..',
      '.ohhhssssssshho.',
      '.ohhssssssssHho.',
      '.ohhsddssddsHho.',
      '.ohhssssssssHho.',
      '.ohhssssssssHho.',
      '.oHhsssrrsssHho.',
      '.oHHossssssoHHo.',
      '.oHHHoooooooHHo.',
      '.ooHHTTTTTTHHoo.',
      '.oTTTTTTTTTTTTo.',
      '.oTTTTTyyTTTTTo.',
      '.oooooooooooooo.',
    ],
  },
  rashka: {
    palette: { o: OUTLINE, f: '#ff8a20', F: '#e0501a', y: '#ffe060', r: '#c02818', k: '#141018', g: GOLD },
    pixels: [
      '....y..y..y.....',
      '...yfyyfyyfy....',
      '...offfffffo....',
      '..offfFFFfffo...',
      '..offfffffffo...',
      '..ofkkfffkkfo...',
      '..offyfffyffo...',
      '..offffffffFo...',
      '...offrrrrfo....',
      '...oFffffffo....',
      '....oFFFFFo.....',
      '..oooggoooooo...',
      '.offTTTTTTTffo..',
      '.ofTTTTTTTTTfo..',
      '.oFTTTTggTTTFo..',
      '.ooooooooooooo..',
    ],
  },
  xyron: {
    palette: { o: OUTLINE, h: '#3a1a2a', H: '#24101a', s: '#d89878', d: '#141018', r: '#ff3020', m: BONE, y: GOLD, f: '#ff8a20' },
    pixels: [
      '..o..........o..',
      '..omo......omo..',
      '...omooooooomo..',
      '...ohhhhhhhhho..',
      '..ohhhssssshhho.',
      '..ohhssssssshho.',
      '..ohsrrssrrsHho.',
      '..ohssssssssHho.',
      '..ohhsssdssshho.',
      '..oHhssssssHHho.',
      '..oHHosssssoHHo.',
      '..oHHHofffoHHHo.',
      '.ohHHTTTTTTTHHho',
      '.ohTTTTTTTTTTTho',
      '.ohTTTTTyyTTTTho',
      '.ooooooooooooooo',
    ],
  },
  // ---------- Town emblems (one per faction) ----------
  castle: {
    palette: { o: OUTLINE, g: '#c4c0b4', G: '#8a867c', w: '#2a2440', d: WOOD },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '.....o.o.o......',
      '.....ooooo......',
      '.....oGgGo......',
      'o.o.oogwgoo.o.o.',
      'oooooogggoooooo.',
      'ogggooGgGoogggo.',
      'oGwGoogggooGwGo.',
      'ogggoogggoogggo.',
      'ogggoogdgoogggo.',
      'oGggoodddooggGo.',
      'ogggoodddoogggo.',
      'oGgGoodddooGgGo.',
      'ooooooooooooooo.',
    ],
  },
  rampart: {
    palette: { o: OUTLINE, w: '#ece6d4', W: '#b4ac98', L: '#3f8a3a', l: '#74c864', d: '#3a2a1a', b: WOOD },
    pixels: [
      '.......oT.......',
      '.......oTT......',
      '.......o........',
      '......owo.......',
      '...oo.owWo.oo...',
      '..oLlooWWooLlo..',
      '.oLlLLowWoLLlLo.',
      '.oLLLLowWoLLLLo.',
      '..oLLLowWoLLLo..',
      '...oooowWoooo...',
      '.....owwWWo.....',
      '.....owwWWo.....',
      '.....owddWo.....',
      '....owwddWWo....',
      '...obbbddbbbo...',
      '..ooooooooooooo.',
    ],
  },
  stronghold: {
    palette: { o: OUTLINE, h: BONE, y: '#d0a858', Y: '#8a6a2a', w: WOOD, W: '#5a3a1e', d: '#2a1a10' },
    pixels: [
      '.o............o.',
      '.oh..........ho.',
      '..oh...oo...ho..',
      '...oho.oo.ohoo..',
      '....ohoyyohoo...',
      '....oyyYyyyo....',
      '...oyyYyyYyyo...',
      '..oyYyyyyyyYyo..',
      '.oyyyyYyyYyyyyo.',
      '.oooooooooooooo.',
      '.owWwWoddoWwWwo.',
      '.owWwWoddoWwWwo.',
      '.owWwWoddoWwWwo.',
      'oowWwWoddoWwWwoo',
      'o.o.o.oddo.o.o.o',
      'oooooooooooooooo',
    ],
  },
  necropolis: {
    palette: { o: OUTLINE, p: '#6a6478', P: '#3e3850', g: '#7cff8a', b: BONE },
    pixels: [
      '.......o........',
      '.......o........',
      '......opo.......',
      '......opo.......',
      '.....oppPo......',
      '.o...opgPo...o..',
      'opo..oppPo..opo.',
      'opo..oppPo..opo.',
      'opPooopgPoooopPo',
      'ogPoopppPPoopgPo',
      'opPoopppPPoopPPo',
      'opPooooooooopPPo',
      'opPoobbbbbboopPo',
      'opPoobobbobPopPo',
      'opPoobbbbbbPopPo',
      'oooooooooooooooo',
    ],
  },
  dungeon: {
    palette: { o: OUTLINE, r: '#7a6a5e', R: '#4e423a', k: '#0a0608', e: '#ff3a2a', c: '#c890ff', C: '#7a38c8' },
    pixels: [
      '................',
      '......oooo......',
      '....oorrRroo....',
      '...orrrRrrrro...',
      '.oorrRrrrrRrroo.',
      'ocorrrrrrrrrroco',
      'occorRroooRrocCo',
      'oCcorrokkkoRocCo',
      'oCCorokkkkkorCCo',
      '.oCoroekkkeoroCo',
      '.ooRrokkkkkorRoo',
      '.orrrokkkkkorrro',
      'oRrrrokkkkkorRro',
      'orrRrokkkkkorrRo',
      'orrrrokkkkkorrro',
      'oooooooooooooooo',
    ],
  },
  inferno: {
    palette: { o: OUTLINE, s: '#3a2020', S: '#5e3030', f: '#ff6a00', F: '#ffd040', l: '#c02010' },
    pixels: [
      '..o....o....o...',
      '..o...oFo...o...',
      '.oso..oso..oso..',
      '.oso.ossso.oso..',
      '.oSo.osSso.oSo..',
      '.ofo.osfso.ofo..',
      'ossSoossSooossSo',
      'osssoossssooSsso',
      'osfsoosffsoosfso',
      'osssooosssooosso',
      'osSSssSoooSsSSso',
      'ossssssofossssso',
      'oSsssssofFossSso',
      'ossSsssoFfoSssso',
      'olllllllllllllll',
      'oooooooooooooooo',
    ],
  },
  gremlin: {
    palette: { o: OUTLINE, g: '#8a9ab0', G: '#5a6a80', y: '#f0e040', k: '#141018', m: DARK_STEEL, M: STEEL },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '.o.....o........',
      '.ogoooogo.......',
      '..ogggggo.......',
      '..oggyggyo......',
      '..ogggggGo......',
      '...ogkkgo.......',
      '..oTTTTTgoo.....',
      '..oTtttTo.m.....',
      '...oGGGo...ooo..',
      '...ogoGo..oMMMo.',
      '..oggogGo.oMmmo.',
      '..ooo.ooo..ooo..',
    ],
  },
  stoneGargoyle: {
    palette: { o: OUTLINE, s: '#9a9aa0', S: '#6a6a72', d: '#4a4a52', r: '#e02020' },
    pixels: [
      '................',
      '.oo.............',
      '.oSoo......o.o..',
      '.oSSSoo....oooo.',
      '..oSSSSo..osssso',
      '..oSdSSSo.ossrso',
      '...oSdSSSoosssso',
      '....oSSdSoTTsso.',
      '.....oSSoTTTsso.',
      '......ooTtTssso.',
      '.......osssssSo.',
      '......osssSssSo.',
      '......osSo.osSo.',
      '.....osSo..osSo.',
      '.....osso..ossso',
      '.....oooo..ooooo',
    ],
  },
  stoneGolem: {
    palette: { o: OUTLINE, s: '#a8a4a0', S: '#7a7672', d: '#4e4a48', y: '#60c0ff' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....osssssSo....',
      '....osssysyo....',
      '....osSSSSSo....',
      '..ooooooooooooo.',
      '.ossSoTTTTosssSo',
      '.osSSoTtTToSssSo',
      '.osSSossssoSdSSo',
      '.oSSoosssSooSSo.',
      '.ossoossSSoosso.',
      '.oooooSSSSSoooo.',
      '....ossSoosSSo..',
      '....osdSoosSdo..',
      '...osssSoossSSo.',
      '...oooooooooooo.',
    ],
  },
  mage: {
    palette: { o: OUTLINE, s: SKIN, k: '#141018', r: '#5a4ab0', R: '#3a2e78', w: WOOD, c: '#80e0ff' },
    pixels: [
      '.......o....oo..',
      '......oro..occo.',
      '.....orRo..occo.',
      '....orrRRo..ow..',
      '...oooooooo..w..',
      '....ossskso..w..',
      '.....osssso..w..',
      '...orrTTTrrosw..',
      '...orrrTrrro.w..',
      '...orrrTrrRo.w..',
      '..orrrrTrrRRow..',
      '..orrrrTrrRRow..',
      '.orrrrrtrrRRow..',
      '.orrrrrrrrRRRo..',
      '.oRrrrrrrRRRRo..',
      '..ooooooooooo...',
    ],
  },
  genie: {
    palette: { o: OUTLINE, b: '#5a8ae0', B: '#3a5aa8', y: GOLD, w: '#f0f0f0', k: '#141018', c: '#a0d0ff' },
    pixels: [
      '.....oooo.......',
      '....owwwwo......',
      '....owwywo......',
      '....obbbkbo.....',
      '....obbbbbo.....',
      '.....obbbo......',
      '.ooooTTTTToooo..',
      'obbbTTTTTTTbbbo.',
      'oBbooTTTTTooBbo.',
      '.oo..otttto.oo..',
      '.....obbbbo.....',
      '.....oBbbbbo....',
      '......oBbbco....',
      '.......oBcco....',
      '........oco.....',
      '.........o......',
    ],
  },
  naga: {
    palette: { o: OUTLINE, k: OUTLINE, s: '#d8a878', h: '#2a1c30', g: '#5a9a7a', G: '#3a6a52', y: GOLD, m: STEEL },
    pixels: [
      '.......ooo......',
      '.m....ohhho...m.',
      '.m...ohhsso...m.',
      '.m...ohhsko...m.',
      '.y...oohsso...y.',
      '.so..oossoo..os.',
      '..sssoTTTTosss..',
      'mysooTTTTTToosym',
      '...ooosTTsooo...',
      'mysoossssssoosym',
      '....ogggggGo....',
      '.....oggggGo....',
      '....ogggGGo.....',
      '..oogggGGooooo..',
      '.ogggGGGGGgggGo.',
      '..oooooooooooo..',
    ],
  },
  giant: {
    palette: { o: OUTLINE, s: '#d8a888', S: '#a07058', h: '#6a4a2a', k: '#141018', b: BOOTS },
    pixels: [
      '.....oooooo.....',
      '....ohhhhhho....',
      '....ohsssssso...',
      '....ohsssksso...',
      '....ohsssssso...',
      '.....osssSSo....',
      '..ooooSssSoooo..',
      '.ossssssssssssso',
      'ossSssssssssSsso',
      'ossoSssssssSosso',
      'ossoSSsssSSSosso',
      'ossoTTTTTTTTosso',
      'oSSotTTTTTTtoSSo',
      '.oo.ossSoossSo..',
      '....ossSoossSo..',
      '...obbbboobbbbo.',
    ],
  },
  piquedram: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', w: '#e8e8e8', g: '#60c0a0', y: GOLD, b: '#8a5a30' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....osssssso....',
      '...ossssssssso..',
      '..owyyyyyyyyywo.',
      '..owoggoooggowo.',
      '..owssssssssswo.',
      '..owsssssSssswo.',
      '..oowwwwwwwwwoo.',
      '...owwwssswwwo..',
      '....owwwwwwwo...',
      '..ooooowwwooooo.',
      '.obbbTTTTTTbbbo.',
      '.obbTTTTyTTTTbbo',
      '.obTTTTyyyTTTTbo',
      '.ooooooooooooooo',
    ],
  },
  thane: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', h: '#4a2e1a', H: '#2e1c10', k: '#141018', b: '#7a5a9a', f: '#60e0a0' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhhhhhhHo...',
      '...ohhsssssHo...',
      '...ohssssssHo...',
      '...ohskssksHo...',
      '...ohssssssHo...',
      '...oHssssSsHo...',
      '...oHsskkssHo...',
      '....oHsHHsHo....',
      '..oooooHHooooo..',
      '.obbTTTTTTTTbbo.',
      '.obTTTTTTTTTTbo.',
      '.obTTTTffTTTTbo.',
      '.oooooooooooooo.',
    ],
  },
  solmyr: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', k: '#141018', b: '#3a6ad0', B: '#24408a', w: '#e8e8f0', W: '#a8a8b8', y: GOLD },
    pixels: [
      '.......oo.......',
      '......obbo......',
      '.....obbyBo.....',
      '....obbbbBBo....',
      '..oooooooooooo..',
      '...osssssssso...',
      '...osksssskso...',
      '...ossssSssso...',
      '...owwsssswwo...',
      '...owwwwwwwWo...',
      '....owwwwwWo....',
      '..oobowwwWobboo.',
      '.obbTTowWoTTbbo.',
      '.obTTTTooTTTTbo.',
      '.oBbbTTTTTTbbBo.',
      '.oooooooooooooo.',
    ],
  },
  tower: {
    palette: { o: OUTLINE, w: '#eef2f8', W: '#b8c4d8', b: '#4a7ad0', B: '#2a4a90', d: '#2a2440' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......obo.......',
      '......obBo......',
      '.....obbBBo.....',
      '.o...owwwWo...o.',
      'obo..owdwWo..obo',
      'obBo.owdwWo.obBo',
      'owWo.owwwWo.owWo',
      'owdWoowwwWoowdWo',
      'owwWoowwwWoowwWo',
      'owwWowwddWWowwWo',
      'owwWowwddWWowwWo',
      'oWWWowwddWWoWWWo',
      'oooooooooooooooo',
    ],
  },
  snowPine: {
    palette: { o: OUTLINE, w: '#f4f8ff', W: '#c0d0e8', g: '#2e6a4a', G: '#1c4630', b: '#7a4e2a', B: '#4a2e18' },
    pixels: [
      '.......oo.......',
      '......owwo......',
      '.....owwGo......',
      '.....ogggGo.....',
      '....owwwgGGo....',
      '....ogggGGGo....',
      '...owwwwwgGGo...',
      '...oggggGGGGo...',
      '..owwwwwwwgGGo..',
      '..ogggggGGGGGo..',
      '.owwwwwwwwwgGGo.',
      '.oggggggGGGGGGo.',
      '.oooooobBoooooo.',
      '......obBo......',
      '....wwobBowww...',
      '...owwwwwwwwWWo.',
    ],
  },
  iceRock: {
    palette: { o: OUTLINE, w: '#e8f4ff', i: '#a8d0f0', I: '#6aa0d0', g: '#7a8a98', G: '#4e5a68', d: '#34404c' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oowwwwioo...',
      '...owwwwiiiio...',
      '..owwiwwiiiiIo..',
      '..owiiiiiiiiIo..',
      '.oowiiiigiiIIo..',
      '.owiiiiggggIIIo.',
      '.oiiiigggGGIdIo.',
      '.oIiigGGGGGdddo.',
      '.oIIGGGGGGddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  gnoll: {
    palette: { o: OUTLINE, f: '#b8905a', F: '#7a5a30', s: '#4a3420', k: '#e02020', d: '#2a2018', w: WOOD, M: STEEL, N: DARK_STEEL },
    pixels: [
      '..oo............',
      '..oFo..oo.......',
      '..ofFoofFo......',
      '..offffffoo.....',
      '..offfkfffffo...',
      '..offfffffffddo.',
      '...offsffsfoooo.',
      '....offssfo.....',
      '...offTTTTfoowo.',
      '..offfTTTTfffwo.',
      '..ofooTTTTooowo.',
      '..ofo.tTTto..oNo',
      '...o.ofoofo.oMMo',
      '.....ofoofo.oMNo',
      '....offoffo..oo.',
      '....ooo.ooo.....',
    ],
  },
  lizardman: {
    palette: { o: OUTLINE, g: '#5a9a3a', G: '#3a6a2a', y: '#c8c878', r: '#e0c020', w: WOOD },
    pixels: [
      '................',
      '...oooo.....o...',
      '..oggggo...owo..',
      '..oggrggo..o.wo.',
      '..ogggggggoo.wo.',
      '...oGGGGoo.o..wo',
      '....oggyo..o..wo',
      '..ooyyyyooooogwo',
      '.ogoTTTTo..o..wo',
      '.og.TTTTo..o.wo.',
      '.oooGtGto..o.wo.',
      'oGo.oggggo..owo.',
      'oGo.ogooggo..o..',
      '.oGoogo.ogo.....',
      '..ooggo.oggo....',
      '...oooo.oooo....',
    ],
  },
  serpentFly: {
    palette: { o: OUTLINE, g: '#5aa04a', G: '#2e6a2a', w: '#c8e8f0', W: '#88b0c0', r: '#e02020' },
    pixels: [
      '................',
      '.oo.......oo....',
      'owwo.....owwo...',
      'owWwo...owWwo...',
      '.owWwo.owWwo....',
      '..owWwoowWwo....',
      '...owwoowwo..oo.',
      '....ooooooooorro',
      'ooogtgTgTgggorro',
      '.oooGGGGGGggggo.',
      '...owwoowwoooo..',
      '..owWwoowWwo....',
      '.owWwo..owWwo...',
      'owWwo....owWwo..',
      'owwo......owwo..',
      '.oo........oo...',
    ],
  },
  basilisk: {
    palette: { o: OUTLINE, g: '#5a8a3a', G: '#3a5a24', y: '#c8c070', r: '#ff4020', k: '#2a3a1a' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '....o.o.o..ooo..',
      '...okokokooggoo.',
      '..oggggggggggrgo',
      'ooggTTTTgggggggo',
      'oGggttttggggoyyo',
      '.oGGGGGGGGGGoyo.',
      '..oyyyyyyyyyyo..',
      '..ogGogGogGogGo.',
      '..ogGogGogGogGo.',
      '.oggoggoggoggo..',
      '.ooooooooooooo..',
    ],
  },
  gorgon: {
    palette: { o: OUTLINE, n: '#a8b8a0', m: '#8a9a88', M: '#5a6a5a', h: BONE, r: '#60f060', d: '#2a3028' },
    pixels: [
      '................',
      '................',
      '................',
      '...........o..o.',
      '..oooooooooho.ho',
      '.onnmnnmnnohmmho',
      'onmmmmmmmmmommmo',
      'omMmMmMmMmmmmrmo',
      'omTTTTTTmmmmmmmo',
      'oMttttttMMmmddmo',
      '.oMMMMMMMMoommo.',
      '..omMo..omMooo..',
      '..omMo..omMo....',
      '..omMo..omMo....',
      '.oddMo.oddMo....',
      '.ooooo.ooooo....',
    ],
  },
  wyvern: {
    palette: { o: OUTLINE, g: '#6aa040', G: '#3a6a24', y: '#d0c060', r: '#e02020', h: BONE },
    pixels: [
      '................',
      '.oo.........oo..',
      '.oTo.......oggo.',
      '.oTTo.....oggrgo',
      '.oTtTo...oggggyo',
      '.oTttToooggoyyo.',
      '.oTtttTgggo.oo..',
      '..oTttgggggo....',
      '...oTggggggo....',
      '..oogggggyyo....',
      '.ogo.ogggyyo....',
      'ogo..oGGGGo.....',
      'oho...ogoGo.....',
      '.o...ogo.oGo....',
      '.....ogo..ogo...',
      '....oooo.oooo...',
    ],
  },
  hydra: {
    palette: { o: OUTLINE, g: '#4a8a5a', G: '#2a5a38', y: '#c8c070', r: '#e02020' },
    pixels: [
      '.ooo......ooo...',
      'oggro....oggro..',
      'ogggoo.ooogggoo.',
      '.ogo..oggroogo..',
      '.ogo..ogggoogo..',
      '.ogo...ogo.ogo..',
      '..ogo..ogo.ogo..',
      '..ogo.ogo.ogo...',
      '...ogoogoogo....',
      '..ooggggggggo...',
      '.ogTTTTTggggyo..',
      'ogtTTTTtgggggyo.',
      'oGGgggggggggyyo.',
      '.oGGGGGGGGGGGo..',
      'oGGo.....oGGo...',
      'ooo.......ooo...',
    ],
  },
  broghild: {
    palette: { o: OUTLINE, f: '#6a4a2a', F: '#4a3018', s: SKIN, S: '#b88060', d: '#141018', b: '#c08040', h: BONE },
    pixels: [
      '................',
      '....oo....oo....',
      '...oFfoooofFo...',
      '...offffffffo...',
      '...ohffffffho...',
      '...osssssssSo...',
      '...ossdssdsSo...',
      '...osssssssSo...',
      '...osbbbbbbSo...',
      '...obbbbbbbbo...',
      '....obbbbbbo....',
      '..ooffbbbbffoo..',
      '.offTTTTTTTTffo.',
      '.offTTTTTTTTffo.',
      '.offTTThhTTTffo.',
      '.oooooooooooooo.',
    ],
  },
  wystan: {
    palette: { o: OUTLINE, g: '#5a8a3a', G: '#3a5a24', h: BONE, H: BONE_SHADOW, s: SKIN, S: '#b88060', d: '#141018', k: '#3a2a1a', r: '#c03020' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhHo....',
      '...ohhdhhdhHo...',
      '...ohhhhhhhHo...',
      '...ohohohohoo...',
      '...okssssssko...',
      '...okrdssdrko...',
      '...okssssssko...',
      '...okssSSssko...',
      '....osssssso....',
      '..ooggggggggoo..',
      '.oggTTTTTTTTggo.',
      '.oggTTThhTTTggo.',
      '.oGgTTTTTTTTgGo.',
      '.oooooooooooooo.',
    ],
  },
  merist: {
    palette: { o: OUTLINE, c: '#3a5a3a', C: '#24402a', s: SKIN, S: '#b88060', d: '#141018', l: '#8a3a6a', w: '#d8d8c8', y: GOLD },
    pixels: [
      '.......oo.......',
      '......occo......',
      '.....occcco.....',
      '....occcccco....',
      '...occccccCCo...',
      '...occCCCCCCo...',
      '...ocCssssSCo...',
      '...ocsdssdSCo...',
      '...ocwsllswCo...',
      '...occwssSwCo...',
      '....occCCCCco...',
      '..ooccccccCCoo..',
      '.occcTTTTTTcCCo.',
      '.occcTTyyTTcCCo.',
      '.occcctTTtccCCo.',
      '.oooooooooooooo.',
    ],
  },
  fortress: {
    palette: { o: OUTLINE, r: '#8a8a40', R: '#5a5a28', w: WOOD, W: '#5a3a1a', d: '#2a1a10', m: '#3a5a3a', M: '#24402a' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......orro......',
      '.....orRrro.....',
      '....orrrRrro....',
      '.o.orRrrrrRro.o.',
      'owoorrrrRrrroowo',
      'owoooooooooooowo',
      'owo.owWddWwo.owo',
      'owo.owWddWwo.owo',
      'oWo.owWddWwo.oWo',
      'oooooooooooooooo',
      '.W..W..W..W..W..',
      'ommMmmmMmmmMmmmo',
      'oooooooooooooooo',
    ],
  },
  reeds: {
    palette: { o: OUTLINE, g: '#6a9a3a', G: '#3a6a24', b: '#7a4a24', B: '#4a2c14', m: '#3a5a4a' },
    pixels: [
      '..o.......o.....',
      '.obo...o..obo...',
      '.obBo.obo.obBo..',
      '.obBo.obBoobBo..',
      '.obBo.obBoobBo..',
      '..ogo.obBo.ogo..',
      '..ogo..ogo.ogo..',
      'o.ogo..ogo.ogo.o',
      'ogogo..ogo.ogoGo',
      '.oGgo.ogGo.ogGo.',
      '..oGgoGgoGogGo..',
      '..oGgGgoGgGgo...',
      '...oGgGgGgGgo...',
      '..omGGGGGGGGmo..',
      '.ommmmmmmmmmmmo.',
      '..oooooooooooo..',
    ],
  },
  swampLog: {
    palette: { o: OUTLINE, b: '#6a4a2a', B: '#4a3018', r: '#c09a60', R: '#8a6a40', g: '#6a9a3a', G: '#3a6a24' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..ooo...ooo.....',
      '.ogggooogggoooo.',
      'ogGgbbgGgbboRRRo',
      'obbbbbbbbbboRrRo',
      'oBbbBbbBbbboRBRo',
      'oBBBBBBBBBBoRrRo',
      'oBBBBBBBBBBoRRRo',
      '.oooooooooooooo.',
    ],
  },
  pixie: {
    palette: { o: OUTLINE, s: SKIN, h: '#f0a0d0', w: '#c8f0ff', W: '#80c8e8', y: '#fff4b0' },
    pixels: [
      '................',
      '................',
      '.........hh.....',
      '..oo....ohhho...',
      '.owWo..ohssso...',
      '.owwWo.ohsoso...',
      '..owwWoohsso....',
      '...owwWoTTo.....',
      '..owwWWoTTso....',
      '.owwWWooTTo.....',
      '.oWWoo.ottto....',
      '..oo....oso.....',
      '........o.o.....',
      '................',
      '.....y.....y....',
      '...y...y........',
    ],
  },
  airElemental: {
    palette: { o: OUTLINE, w: '#f0f8ff', a: '#c0e0f0', A: '#80b0d0', k: '#2a4058' },
    pixels: [
      '................',
      '......oooo......',
      '.....owwwao.....',
      '.....owwkwko....',
      '.....owwwwao....',
      '..oo..oaao..oo..',
      '.owaoowwwaooawo.',
      '..oaawwTTwwaao..',
      '...ooawTtwaoo...',
      '.....oawwao.....',
      '....oaawwaAo....',
      '...owwaaAAo.....',
      '....oaawwo......',
      '.....oAao.......',
      '......oao.......',
      '.......o........',
    ],
  },
  waterElemental: {
    palette: { o: OUTLINE, b: '#4080d0', B: '#2a5098', l: '#90c8f0', w: '#e0f4ff' },
    pixels: [
      '................',
      '.......oooo.....',
      '......olllbo....',
      '......olwlwo....',
      '......obllbo....',
      '...oo..obbo.....',
      '..olboobbbboo...',
      '..obblbTTbbllo..',
      '...oobTTtbBbbo..',
      '.....obbbbBoo...',
      '.....obblbBo....',
      '....obblbbBBo...',
      '...obblbbbbBo...',
      '..oblbbbbbbBBo..',
      '.olbbblbbbbbBBo.',
      '.oooooooooooooo.',
    ],
  },
  fireElemental: {
    palette: { o: OUTLINE, r: '#d02810', R: '#901808', f: '#f08020', y: '#ffe060' },
    pixels: [
      '.......o........',
      '......ofo...o...',
      '.....ofyfo.ofo..',
      '.....ofyyfoofo..',
      '.....ofyoyfo....',
      '..o..offyffo....',
      '.ofo..orffro..o.',
      '.oyfoorfTTrfoofo',
      '..ofrrfTtTrrffyo',
      '...oorfTTfroooo.',
      '.....orffffo....',
      '....orfyyfRo....',
      '....ofyffyfRo...',
      '...orfyo.ofRo...',
      '...ofRo...ofRo..',
      '..ooooo..ooooo..',
    ],
  },
  earthElemental: {
    palette: { o: OUTLINE, e: '#9a7048', E: '#6a4a28', d: '#4a3018', g: '#6a8a3a', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oggeeeEo....',
      '....oeeyeyEo....',
      '..oooeeeeEEooo..',
      '.ogeeoEEEEoeego.',
      'oeeeEeeTTeeeEEEo',
      'oeEEoeTTtTeoEEEo',
      'oeEEoeeTTeEoeEEo',
      'oEdEoeeeeEEoeEdo',
      '.ooo.oeEEEEo.oo.',
      '....oeeEoeEEo...',
      '....oeEEoeEEo...',
      '...oeeEo.oeEEo..',
      '..oeeEEo.oeeEEo.',
      '..ooooooooooooo.',
    ],
  },
  psychicElemental: {
    palette: { o: OUTLINE, p: '#9a60d0', P: '#6a3a9a', l: '#d0a0ff', y: '#fff0ff' },
    pixels: [
      '......llll......',
      '.....lyyyyl.....',
      '....oyyyyyyo....',
      '....oyypyypo....',
      '....olyyyylo....',
      '.....ollllo.....',
      '...ooppppppoo...',
      '..opllpTTpplPo..',
      '.oplooTtTTooPPo.',
      '.olo.opTTppo.oPo',
      '.oo..opppPPo..oo',
      '.....oppoPPo....',
      '....oplo.oPPo...',
      '....opo...oPo...',
      '...olpo...oPPo..',
      '...oooo...oooo..',
    ],
  },
  firebird: {
    palette: { o: OUTLINE, r: '#d02810', R: '#901808', f: '#f08020', y: '#ffe060', k: GOLD },
    pixels: [
      'oo..............',
      'ofoo............',
      '.ofyfo..........',
      '.ofyyfo.....ooo.',
      '..ofyyfo...offfo',
      '..ofyyyfo.offoyo',
      '...ofyyyfoffffkk',
      '....ofyyfTTffoo.',
      'oo...ofTTtTfo...',
      'ofoooffTTTffo...',
      '.offfyfffffro...',
      '..ofyyoffrRro...',
      '...oyo.ofrRRo...',
      '..oyo...orRo....',
      '..oo.....oyo....',
      '.........o.o....',
    ],
  },
  monere: {
    palette: { o: OUTLINE, s: SKIN, S: '#b88860', h: '#5a3a8a', H: '#3a2060', y: '#80e0ff', g: GOLD },
    pixels: [
      '......oooo......',
      '.....ohhhho.....',
      '....ohhhhhHo....',
      '...ohhhgghhHo...',
      '...ohhoooohHo...',
      '...ohosssSoHo...',
      '...ohoysySoHo...',
      '...ohossssoHo...',
      '...ohoSssSoHo...',
      '...ohhoSSohHo...',
      '....ohhoohHo....',
      '..oohhhhhhhHoo..',
      '.ohhTTTggTTTHHo.',
      '.ohTTTTggTTTTHo.',
      '.ohTTTTttTTTTHo.',
      '.oooooooooooooo.',
    ],
  },
  erdamon: {
    palette: { o: OUTLINE, s: SKIN, S: '#b88860', b: '#7a5030', B: '#4a3018', e: '#9a8060', E: '#6a5a40', y: '#80c040' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '...obbbbbbbBo...',
      '...obsssssbBo...',
      '...osossosSBo...',
      '...ossssssSBo...',
      '...obsssssbBo...',
      '...obbsSSbbBo...',
      '...obbbbbbbBo...',
      '....obbbbbBo....',
      '..ooeobbbBoeoo..',
      '.oeeeoTTTToeeEo.',
      '.oeTTTTyyTTTTEo.',
      '.oeTTTTttTTTTEo.',
      '.oooooooooooooo.',
    ],
  },
  ciele: {
    palette: { o: OUTLINE, s: SKIN, h: '#4080d0', H: '#2a5098', g: GOLD, c: '#80e0ff', r: '#c04050' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhgcgghHo...',
      '...ohssssssHo...',
      '...ohsossosHo...',
      '...ohssssssHo...',
      '..ohhssrrsshHo..',
      '..ohhossssohHo..',
      '..ohhhossohhHo..',
      '..ohhhhooohhHo..',
      '.ohhhoTTTTohhHo.',
      '.ohhTTTTTTTTHHo.',
      '.ohTTTTccTTTTHo.',
      '.ohTTTTttTTTTHo.',
      '.oooooooooooooo.',
    ],
  },
  conflux: {
    palette: { o: OUTLINE, a: '#d0f0ff', p: '#b080e0', r: '#e05020', R: '#a03010', b: '#4080d0', B: '#2a5098', e: '#8a6a3a', E: '#5a4020', g: '#c4c0b4', G: '#8a867c' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......oao.......',
      '......oapo......',
      '..o...oapo...o..',
      '.oro..oapo..obo.',
      '.orRo.oapo.obBo.',
      '.orRo.oapo.obBo.',
      '.orRooaappoobBo.',
      '.orRooaappoobBo.',
      'ooooooooooooooo.',
      '.oeeeeggggeeeeo.',
      '..oeeEEgGEEeeo..',
      '....oeeEEeeo....',
      '......oooo......',
    ],
  },
  runestone: {
    palette: { o: OUTLINE, g: '#9a988c', G: '#6a685e', c: '#60e0ff', d: '#3a7a2a' },
    pixels: [
      '................',
      '................',
      '.....oooo.......',
      '....oggggo......',
      '...oggggGGo.....',
      '...ogcggGGo.....',
      '...ogcgcgGo.....',
      '...ogcccgGo.....',
      '...oggcggGo.....',
      '...ogggggGGo....',
      '...ogcgcgGGo....',
      '...oggcggGGo....',
      '..ogggcgggGGo...',
      '..oggggggGGGGo..',
      '.oddggggggGGGddo',
      '.ooooooooooooooo',
    ],
  },
  elementalShard: {
    palette: { o: OUTLINE, w: '#ffffff', a: '#d0f0ff', r: '#e05020', R: '#a03010', b: '#4080d0', B: '#2a5098', g: '#60c060', e: '#8a6a3a', s: '#2a2440' },
    pixels: [
      '.......oo.......',
      '......owao......',
      '......owaao.....',
      '.....owaaabo....',
      '.....orwabbo....',
      '....orrwabbbo...',
      '....orrwabbBo...',
      '...orrrRwbbbBo..',
      '...orrrRgbbbBo..',
      '....orRggggBo...',
      '....orggggeo....',
      '.....oggeeo.....',
      '......oeeo......',
      '.......oo.......',
      '................',
      '....ssssssss....',
    ],
  },
}

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
const UPGRADE_TINTS: Record<UpgradedCreature, string> = {
  halberdier: '#e8c860',
  marksman: '#3a8a3a',
  royalGriffin: '#f0c040',
  crusader: '#f0d070',
  zealot: '#f0e0a0',
  champion: '#f0c040',
  archangel: '#ffb000',
  centaurCaptain: '#c08040',
  battleDwarf: '#c0c8d0',
  grandElf: '#40c060',
  silverPegasus: '#90b0d8',
  dendroidSoldier: '#8a6a30',
  warUnicorn: '#f0e0ff',
  goldDragon: '#ffcc30',
  hobgoblin: '#c06030',
  wolfRaider: '#606870',
  orcChieftain: '#c03030',
  ogreMage: '#6040c0',
  thunderbird: '#40a0ff',
  cyclopsKing: '#c0a040',
  ancientBehemoth: '#d8c8a0',
  skeletonWarrior: '#a0b0c0',
  zombie: '#60a060',
  wraith: '#7040a0',
  vampireLord: '#c02040',
  powerLich: '#40e080',
  dreadKnight: '#6020a0',
  ghostDragon: '#a0f0ff',
  infernalTroglodyte: '#c04020',
  harpyHag: '#a040a0',
  evilEye: '#40c040',
  medusaQueen: '#c0a020',
  minotaurKing: '#f0c040',
  scorpicore: '#c04040',
  blackDragon: '#202028',
  familiar: '#ff8020',
  magog: '#ff4000',
  cerberus: '#802020',
  hornedDemon: '#a02060',
  pitLord: '#ff6000',
  efreetSultan: '#ffd040',
  archDevil: '#500818',
  masterGremlin: '#4a7ad8',
  obsidianGargoyle: '#202030',
  ironGolem: '#8a8e98',
  archMage: '#8040d0',
  masterGenie: '#40d0ff',
  nagaQueen: '#f0c040',
  titan: '#e0e8ff',
  gnollMarauder: '#a05030',
  lizardWarrior: '#2a8a5a',
  dragonFly: '#40c0e0',
  greaterBasilisk: '#a0c040',
  mightyGorgon: '#406040',
  wyvernMonarch: '#c0a030',
  chaosHydra: '#802040',
  sprite: '#ff90e0',
  stormElemental: '#6080ff',
  iceElemental: '#c0f0ff',
  energyElemental: '#ffe040',
  magmaElemental: '#ff5020',
  magicElemental: '#e060ff',
  phoenix: '#ffb020',
}

/** How far each color moves toward the upgrade's tint. */
const TINT_STRENGTH = 0.5

const channels = (color: string) => [1, 3, 5].map((start) => parseInt(color.slice(start, start + 2), 16))

/** Outlines, skin and near-black shadows keep their color, so the creature still reads as itself. */
function keepsColor(color: string): boolean {
  const [red, green, blue] = channels(color)

  return color === OUTLINE || color === SKIN || 0.3 * red + 0.59 * green + 0.11 * blue < 40
}

function mix(color: string, tint: string): string {
  const tintChannels = channels(tint)

  return `#${channels(color)
    .map((channel, index) => Math.round(channel + (tintChannels[index] - channel) * TINT_STRENGTH).toString(16).padStart(2, '0'))
    .join('')}`
}

function tinted(sprite: Sprite, tint: string): Sprite {
  const palette = Object.fromEntries(
    Object.entries(sprite.palette).map(([character, color]) => [character, keepsColor(color) ? color : mix(color, tint)]),
  )

  return { palette, pixels: sprite.pixels }
}

const UPGRADE_SPRITES = Object.fromEntries(
  Object.entries(UPGRADES).map(([base, upgrade]) => [upgrade, tinted(BASE_SPRITES[base as BaseCreature], UPGRADE_TINTS[upgrade])]),
) as Record<UpgradedCreature, Sprite>

export const SPRITES: Record<SpriteId, Sprite> = { ...BASE_SPRITES, ...UPGRADE_SPRITES }
