import type { Sprite } from './sprites'

export type UiIconId =
  | 'attack'
  | 'defense'
  | 'spellPower'
  | 'morale'
  | 'luck'
  | 'retreat'
  | 'spellbook'
  | 'wait'
  | 'trophy'
  | 'gold'
  | 'star'

const GOLD_PALETTE = { o: '#2a1a00', y: '#ffd040', Y: '#c89a20', w: '#fff4c0' }

/** Pixel-art icons for stats, actions and rewards, in the same 16 × 16 format as the unit sprites. */
export const UI_ICONS: Record<UiIconId, Sprite> = {
  attack: {
    palette: { o: '#101010', s: '#e8eef4', y: '#f0c040', h: '#8a5a2b' },
    pixels: [
      'o..............o',
      'oso..........oso',
      '.oso........oso.',
      '..oso......oso..',
      '...oso....oso...',
      '....oso..oso....',
      '.....osooso.....',
      '......osso......',
      '.....osooso.....',
      '..y.oso..oso.y..',
      '...yyo....oyy...',
      '..oyhy....yhyo..',
      '.ohho......ohho.',
      'oho..........oho',
      'oo............oo',
      '................',
    ],
  },
  defense: {
    palette: { o: '#101010', s: '#c8d0d8', S: '#7a8490', b: '#3060c0', B: '#1c3a80' },
    pixels: [
      '................',
      '.oooooooooooooo.',
      '.osssssssssssSo.',
      '.osbbbbbbbbbbSo.',
      '.osbbbbsbbbbBSo.',
      '.osbbbbsbbbbBSo.',
      '.osbsssssssbBSo.',
      '.osbbbbsbbbbBSo.',
      '..osbbbsbbbBSo..',
      '..osbbbsbbbBSo..',
      '...osbbsbbBSo...',
      '....osbsbBSo....',
      '.....osbBSo.....',
      '......osSo......',
      '.......oo.......',
      '................',
    ],
  },
  spellPower: {
    palette: { o: '#100818', p: '#b070ff', P: '#6a30b0', w: '#f0e0ff', g: '#c89a20', G: '#8a6a20' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....owwppppo....',
      '...owwpppppPo...',
      '..owpppppppPPo..',
      '..oppppppppPPo..',
      '..opppppppPPPo..',
      '..oPppppppPPPo..',
      '...oPPpppPPPo...',
      '....oPPPPPPo....',
      '.....oooooo.....',
      '......ogGo......',
      '.....oggGGo.....',
      '....oggggGGo....',
      '....oooooooo....',
      '................',
    ],
  },
  morale: {
    palette: { o: '#2a1a00', y: '#ffd040', Y: '#c89a20', k: '#2a1a00' },
    pixels: [
      '................',
      '.....oooooo.....',
      '...ooyyyyyyoo...',
      '..oyyyyyyyyyYo..',
      '.oyyyyyyyyyyYo..',
      '.oyyykyyykyyyYo.',
      'oyyyykyyykyyyYYo',
      'oyyyyyyyyyyyyYYo',
      'oyykyyyyyyykyYYo',
      'oyyykyyyyykyyYYo',
      '.oyyykkkkkyyYYo.',
      '.oyyyyyyyyyYYYo.',
      '..oYyyyyyyYYYo..',
      '...ooYYYYYYoo...',
      '.....oooooo.....',
      '................',
    ],
  },
  luck: {
    palette: { o: '#101010', s: '#e0e4ea', S: '#8a94a0', k: '#101010' },
    pixels: [
      '................',
      '....oooooooo....',
      '..ooSssssssSoo..',
      '.oSsskooookssSo.',
      '.oSsoo....oosSo.',
      'oSsko......oksSo',
      'oSso........osSo',
      'oSso........osSo',
      'oSko........okSo',
      'oSso........osSo',
      'oSso........osSo',
      'oSso........osSo',
      'oSSo........oSSo',
      'oooo........oooo',
      '................',
      '................',
    ],
  },
  retreat: {
    palette: { o: '#101010', w: '#f4f4f4', W: '#b8b8b8', p: '#8a5a2b' },
    pixels: [
      '...oo...........',
      '...opoooooooo...',
      '...opwwwwwwwwo..',
      '...opwwwwwwwwWo.',
      '...opwwwwwwwWWWo',
      '...opwwwwwwwwWo.',
      '...opwwwwwwwwo..',
      '...opwwwwWoooo..',
      '...opoooooo.....',
      '...op...........',
      '...op...........',
      '...op...........',
      '...op...........',
      '...op...........',
      '..oppo..........',
      '..oooo..........',
    ],
  },
  spellbook: {
    palette: { o: '#1a0a00', c: '#7a2a14', C: '#4a160a', p: '#f0e6c8', y: '#f0c040' },
    pixels: [
      '................',
      '..oooooooooooo..',
      '..occccccccCpo..',
      '..occcyycccCpo..',
      '..occyccyccCpo..',
      '..ocyccccycCpo..',
      '..occyccyccCpo..',
      '..occcyycccCpo..',
      '..occccccccCpo..',
      '..occccccccCpo..',
      '..oCCCCCCCCCpo..',
      '..oppppppppppo..',
      '..oooooooooooo..',
      '................',
      '................',
      '................',
    ],
  },
  wait: {
    palette: { o: '#2a1a00', f: '#c89a20', s: '#f0d080', g: '#a8d0f0' },
    pixels: [
      '..oooooooooooo..',
      '..offffffffffo..',
      '...oggggggggo...',
      '...ogssssssgo...',
      '....ogssssgo....',
      '.....ogssgo.....',
      '......osgo......',
      '......ogso......',
      '......ogso......',
      '.....oggsgo.....',
      '....oggssggo....',
      '...ogggssgggo...',
      '...ogssssssgo...',
      '..offffffffffo..',
      '..oooooooooooo..',
      '................',
    ],
  },
  trophy: {
    palette: GOLD_PALETTE,
    pixels: [
      '................',
      '...oooooooooo...',
      'oooowyyyyyyYoooo',
      'oyoowyyyyyyYooyo',
      'oyoowyyyyyyYooyo',
      '.oooyyyyyyYYooo.',
      '...oyyyyyyYYo...',
      '....oyyyyYYo....',
      '.....oyyYYo.....',
      '......oyYo......',
      '......oyYo......',
      '.....oyyYYo.....',
      '....oyyyyYYo....',
      '....oooooooo....',
      '................',
      '................',
    ],
  },
  gold: {
    palette: GOLD_PALETTE,
    pixels: [
      '................',
      '.....oooooo.....',
      '...ooyyyyyyoo...',
      '..oywwyyyyyyYo..',
      '.oywyyYYYYyyyYo.',
      '.oyyyYyyyyYyyYo.',
      'oyyyYyyyyyyYyyYo',
      'oyyyYyyyyyyYyyYo',
      'oyyyYyyyyyyYyyYo',
      'oyyyYyyyyyyYyyYo',
      '.oyyyYyyyyYyyYo.',
      '.oyyyyYYYYyyYYo.',
      '..oyyyyyyyyYYo..',
      '...ooYYYYYYoo...',
      '.....oooooo.....',
      '................',
    ],
  },
  star: {
    palette: GOLD_PALETTE,
    pixels: [
      '.......oo.......',
      '......oyyo......',
      '......oyyo......',
      '.....owyyYo.....',
      'oooooowyyYoooooo',
      'oyywwwyyyyyyYYYo',
      '.oyyyyyyyyyyYYo.',
      '..oyyyyyyyyYYo..',
      '...oyyyyyyYYo...',
      '...oyyyyyyYYo...',
      '..oyyyYooYyyYo..',
      '..oyyYo..oYyYo..',
      '.oyYoo....ooYYo.',
      '.ooo........ooo.',
      '................',
      '................',
    ],
  },
}
