import type { SpellId } from '../../game'
import type { Sprite } from './sprites'

/** Pixel-art spellbook icons, in the same 16 × 16 format as the unit sprites. */
export const SPELL_ICONS: Record<SpellId, Sprite> = {
  magicArrow: {
    palette: { o: '#0a1430', w: '#ffffff', c: '#a8e0ff', b: '#3a8cff' },
    pixels: [
      '................',
      '..........oooooo',
      '..........owwwco',
      '...........owwco',
      '..........owcwbo',
      '.........owcobbo',
      '........owco.obo',
      '.......owco...oo',
      '......owco......',
      '.....owco.......',
      '..o.owco........',
      '.obowco.........',
      '.obbco..........',
      '.obbbo..........',
      '..ooo...........',
      '................',
    ],
  },
  lightningBolt: {
    palette: { o: '#2a1a00', y: '#ffe040', Y: '#ffa800', w: '#fffbe0' },
    pixels: [
      '.........oooo...',
      '........owyYo...',
      '.......owyYo....',
      '......owyYo.....',
      '.....owyYo......',
      '....owyyYoooo...',
      '...owyyyyyyYo...',
      '...oooooowyYo...',
      '.......owyYo....',
      '......owyYo.....',
      '.....owyYoooo...',
      '....owyyyyyYo...',
      '....ooooowYo....',
      '.......owYo.....',
      '......oYo.......',
      '......oo........',
    ],
  },
  haste: {
    palette: { o: '#0a2a0a', g: '#7cf07c', G: '#2aa02a', w: '#e8ffe8' },
    pixels: [
      '................',
      '................',
      '.ooo....ooo.....',
      '.owgo...owgo....',
      '..owgo...owgo...',
      '...owgo...owgo..',
      '....owgo...owgo.',
      '.....owgo...owgo',
      '.....oGgo...oGgo',
      '....oGgo...oGgo.',
      '...oGgo...oGgo..',
      '..oGgo...oGgo...',
      '.oGgo...oGgo....',
      '.ooo....ooo.....',
      '................',
      '................',
    ],
  },
  slow: {
    palette: { o: '#101010', i: '#6e6a62', I: '#3a3834', w: '#c8c4bc', c: '#a8a49c' },
    pixels: [
      '................',
      '.oooo...........',
      'oc..co..........',
      'oc..co..........',
      '.occo...........',
      '....oco.........',
      '.....oco........',
      '......oco.......',
      '........oooo....',
      '......ooiiiioo..',
      '.....owwiiiiIo..',
      '.....owiiiiiIo..',
      '.....oiiiiiIIo..',
      '.....oiiiiIIIo..',
      '......ooIIIIoo..',
      '........oooo....',
    ],
  },
  bless: {
    palette: { o: '#2a1a00', y: '#ffe060', Y: '#c89a20', s: '#e8eef4', S: '#8a94a0', h: '#8a5a2b' },
    pixels: [
      '..y....oo....y..',
      '...y..osso..y...',
      '......osSo......',
      '.y....osSo....y.',
      '......osSo......',
      '......osSo......',
      '......osSo......',
      '......osSo......',
      '......osSo......',
      '...oooooooooo...',
      '...oyyYyyYyyo...',
      '...oooohhoooo...',
      '......ohho......',
      '......ohho......',
      '......oyyo......',
      '.......oo.......',
    ],
  },
  curse: {
    palette: { o: '#100818', b: '#c8a8e8', B: '#7a5aa8', k: '#100818', e: '#40ff60' },
    pixels: [
      '................',
      '....oooooooo....',
      '...obbbbbbbbo...',
      '..obbbbbbbbbbo..',
      '..obbbbbbbbbBo..',
      '..obkkbbbbkkBo..',
      '..obkebbbbekBo..',
      '..obkkbbbbkkBo..',
      '..obbbbkkbbbBo..',
      '...obbbkkbbBo...',
      '....obbbbbBo....',
      '....obobobBo....',
      '....oooooooo....',
      '................',
      '................',
      '................',
    ],
  },
  stoneSkin: {
    palette: { o: '#101010', g: '#a8a49c', G: '#6e6a62', w: '#d8d4cc' },
    pixels: [
      '................',
      '..oooooooooooo..',
      '..owwwggggggGo..',
      '..owwggggggGGo..',
      '..owgggGggggGo..',
      '..oggggGGgggGo..',
      '..ogGggggggGGo..',
      '..oggggggGgGGo..',
      '...ogggGgggGo...',
      '...oggggggGGo...',
      '....oggGggGo....',
      '....ogggggGo....',
      '.....oggGGo.....',
      '......oGGo......',
      '.......oo.......',
      '................',
    ],
  },
  cure: {
    palette: { o: '#0a2010', g: '#50e070', G: '#209040', w: '#e8ffe8' },
    pixels: [
      '................',
      '.....oooooo.....',
      '.....owwggo.....',
      '.....owgggo.....',
      '.....oggggo.....',
      'oooooogggGoooooo',
      'owwggggggggggGGo',
      'owgggggggggggGGo',
      'oggggggggggggGGo',
      'oGGGGGggGGGGGGGo',
      'oooooogggGoooooo',
      '.....ogggGo.....',
      '.....ogggGo.....',
      '.....oggGGo.....',
      '.....oooooo.....',
      '................',
    ],
  },
  deathRipple: {
    palette: { o: '#08040c', p: '#b060ff', P: '#6020a0', k: '#200830' },
    pixels: [
      '.....oooooo.....',
      '...ooPPPPPPoo...',
      '..oPPkkkkkkPPo..',
      '.oPkkppppppkkPo.',
      '.oPkpPPPPPPpkPo.',
      'oPkpPkkkkkkPpkPo',
      'oPkpPkppppkPpkPo',
      'oPkpPkpkkpkPpkPo',
      'oPkpPkpkkpkPpkPo',
      'oPkpPkppppkPpkPo',
      'oPkpPkkkkkkPpkPo',
      '.oPkpPPPPPPpkPo.',
      '.oPkkppppppkkPo.',
      '..oPPkkkkkkPPo..',
      '...ooPPPPPPoo...',
      '.....oooooo.....',
    ],
  },
  animateDead: {
    palette: { o: '#101010', b: '#e8e0c8', B: '#a89c80', g: '#70ff90' },
    pixels: [
      '................',
      '..g..........g..',
      '.oo..........oo.',
      'obbo........obbo',
      'obbbo......obbbo',
      '.oobbo....obboo.',
      '...obbo..obbo...',
      '....obboobbo....',
      '.....obbbbo.....',
      '.....obBBbo.....',
      '....obboobbo....',
      '...obbo..obbo...',
      '.oobbo....obboo.',
      'obbbo......obbbo',
      'obbo........obbo',
      '.oo..g....g..oo.',
    ],
  },
  meteorShower: {
    palette: { o: '#1a0a00', r: '#7a5040', R: '#4a2a20', f: '#ff7a10', F: '#ffd040' },
    pixels: [
      '.............Ff.',
      '...Ff......Fff..',
      '..Fff.....Fff...',
      '.ooo.....Fff....',
      '.oro....Fff.....',
      '.ooo...Fff......',
      '......Fff.......',
      '....fFFf........',
      '..ooooff........',
      '.orrrRof........',
      'orrRrrRo........',
      'orRrrrRo........',
      'orrrrRRo........',
      '.oRrRRo.........',
      '..oooo..........',
      '................',
    ],
  },
  inferno: {
    palette: { o: '#1a0600', r: '#c02010', f: '#ff6a00', F: '#ffd040', w: '#fff8d0' },
    pixels: [
      '.......o........',
      '......ofo....o..',
      '..o...ofo...ofo.',
      '.ofo.orfo...ofo.',
      '.ofo.orffo.orfo.',
      '.orfoorfFfoorfo.',
      'oorffrffFFfrffo.',
      'orfffffFFFffffo.',
      'orffFFFFwFFFffro',
      'orfFFFwwwwFFFfro',
      'orfFFwwwwwwFFfro',
      'orffFFwwwwFFffro',
      '.orffFFFFFFffro.',
      '..orrffffffrro..',
      '...oorrrrrroo...',
      '.....oooooo.....',
    ],
  },
}
