import type { UpgradedCreature } from '../../game'
import { OUTLINE, SKIN, GOLD, type Sprite } from './shared'

/** Conflux: its creatures, heroes, town emblem and homeland obstacles. */
export const CONFLUX_SPRITES = {
  pixie: {
    palette: { o: OUTLINE, s: SKIN, h: '#f0a0d0', w: '#c8f0ff', W: '#80c8e8', y: '#fff4b0' },
    pixels: [
      '................',
      '................',
      '.........hh.....',
      '..oo....ohhho...',
      '.owWo..ohssso...',
      '.owwWo.ohsoso...',
      '..owwWoohsso....',
      '...owwWoTTo.....',
      '..owwWWoTTso....',
      '.owwWWooTTo.....',
      '.oWWoo.ottto....',
      '..oo....oso.....',
      '........o.o.....',
      '................',
      '.....y.....y....',
      '...y...y........',
    ],
  },
  airElemental: {
    palette: { o: OUTLINE, w: '#f0f8ff', a: '#c0e0f0', A: '#80b0d0', k: '#2a4058' },
    pixels: [
      '................',
      '......oooo......',
      '.....owwwao.....',
      '.....owwkwko....',
      '.....owwwwao....',
      '..oo..oaao..oo..',
      '.owaoowwwaooawo.',
      '..oaawwTTwwaao..',
      '...ooawTtwaoo...',
      '.....oawwao.....',
      '....oaawwaAo....',
      '...owwaaAAo.....',
      '....oaawwo......',
      '.....oAao.......',
      '......oao.......',
      '.......o........',
    ],
  },
  waterElemental: {
    palette: { o: OUTLINE, b: '#4080d0', B: '#2a5098', l: '#90c8f0', w: '#e0f4ff' },
    pixels: [
      '................',
      '.......oooo.....',
      '......olllbo....',
      '......olwlwo....',
      '......obllbo....',
      '...oo..obbo.....',
      '..olboobbbboo...',
      '..obblbTTbbllo..',
      '...oobTTtbBbbo..',
      '.....obbbbBoo...',
      '.....obblbBo....',
      '....obblbbBBo...',
      '...obblbbbbBo...',
      '..oblbbbbbbBBo..',
      '.olbbblbbbbbBBo.',
      '.oooooooooooooo.',
    ],
  },
  fireElemental: {
    palette: { o: OUTLINE, r: '#d02810', R: '#901808', f: '#f08020', y: '#ffe060' },
    pixels: [
      '.......o........',
      '......ofo...o...',
      '.....ofyfo.ofo..',
      '.....ofyyfoofo..',
      '.....ofyoyfo....',
      '..o..offyffo....',
      '.ofo..orffro..o.',
      '.oyfoorfTTrfoofo',
      '..ofrrfTtTrrffyo',
      '...oorfTTfroooo.',
      '.....orffffo....',
      '....orfyyfRo....',
      '....ofyffyfRo...',
      '...orfyo.ofRo...',
      '...ofRo...ofRo..',
      '..ooooo..ooooo..',
    ],
  },
  earthElemental: {
    palette: { o: OUTLINE, e: '#9a7048', E: '#6a4a28', d: '#4a3018', g: '#6a8a3a', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oggeeeEo....',
      '....oeeyeyEo....',
      '..oooeeeeEEooo..',
      '.ogeeoEEEEoeego.',
      'oeeeEeeTTeeeEEEo',
      'oeEEoeTTtTeoEEEo',
      'oeEEoeeTTeEoeEEo',
      'oEdEoeeeeEEoeEdo',
      '.ooo.oeEEEEo.oo.',
      '....oeeEoeEEo...',
      '....oeEEoeEEo...',
      '...oeeEo.oeEEo..',
      '..oeeEEo.oeeEEo.',
      '..ooooooooooooo.',
    ],
  },
  psychicElemental: {
    palette: { o: OUTLINE, p: '#9a60d0', P: '#6a3a9a', l: '#d0a0ff', y: '#fff0ff' },
    pixels: [
      '......llll......',
      '.....lyyyyl.....',
      '....oyyyyyyo....',
      '....oyypyypo....',
      '....olyyyylo....',
      '.....ollllo.....',
      '...ooppppppoo...',
      '..opllpTTpplPo..',
      '.oplooTtTTooPPo.',
      '.olo.opTTppo.oPo',
      '.oo..opppPPo..oo',
      '.....oppoPPo....',
      '....oplo.oPPo...',
      '....opo...oPo...',
      '...olpo...oPPo..',
      '...oooo...oooo..',
    ],
  },
  firebird: {
    palette: { o: OUTLINE, r: '#d02810', R: '#901808', f: '#f08020', y: '#ffe060', k: GOLD },
    pixels: [
      'oo..............',
      'ofoo............',
      '.ofyfo..........',
      '.ofyyfo.....ooo.',
      '..ofyyfo...offfo',
      '..ofyyyfo.offoyo',
      '...ofyyyfoffffkk',
      '....ofyyfTTffoo.',
      'oo...ofTTtTfo...',
      'ofoooffTTTffo...',
      '.offfyfffffro...',
      '..ofyyoffrRro...',
      '...oyo.ofrRRo...',
      '..oyo...orRo....',
      '..oo.....oyo....',
      '.........o.o....',
    ],
  },
  monere: {
    palette: { o: OUTLINE, s: SKIN, S: '#b88860', h: '#5a3a8a', H: '#3a2060', y: '#80e0ff', g: GOLD },
    pixels: [
      '......oooo......',
      '.....ohhhho.....',
      '....ohhhhhHo....',
      '...ohhhgghhHo...',
      '...ohhoooohHo...',
      '...ohosssSoHo...',
      '...ohoysySoHo...',
      '...ohossssoHo...',
      '...ohoSssSoHo...',
      '...ohhoSSohHo...',
      '....ohhoohHo....',
      '..oohhhhhhhHoo..',
      '.ohhTTTggTTTHHo.',
      '.ohTTTTggTTTTHo.',
      '.ohTTTTttTTTTHo.',
      '.oooooooooooooo.',
    ],
  },
  erdamon: {
    palette: { o: OUTLINE, s: SKIN, S: '#b88860', b: '#7a5030', B: '#4a3018', e: '#9a8060', E: '#6a5a40', y: '#80c040' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '...obbbbbbbBo...',
      '...obsssssbBo...',
      '...osossosSBo...',
      '...ossssssSBo...',
      '...obsssssbBo...',
      '...obbsSSbbBo...',
      '...obbbbbbbBo...',
      '....obbbbbBo....',
      '..ooeobbbBoeoo..',
      '.oeeeoTTTToeeEo.',
      '.oeTTTTyyTTTTEo.',
      '.oeTTTTttTTTTEo.',
      '.oooooooooooooo.',
    ],
  },
  ciele: {
    palette: { o: OUTLINE, s: SKIN, h: '#4080d0', H: '#2a5098', g: GOLD, c: '#80e0ff', r: '#c04050' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhgcgghHo...',
      '...ohssssssHo...',
      '...ohsossosHo...',
      '...ohssssssHo...',
      '..ohhssrrsshHo..',
      '..ohhossssohHo..',
      '..ohhhossohhHo..',
      '..ohhhhooohhHo..',
      '.ohhhoTTTTohhHo.',
      '.ohhTTTTTTTTHHo.',
      '.ohTTTTccTTTTHo.',
      '.ohTTTTttTTTTHo.',
      '.oooooooooooooo.',
    ],
  },
  conflux: {
    palette: { o: OUTLINE, a: '#d0f0ff', p: '#b080e0', r: '#e05020', R: '#a03010', b: '#4080d0', B: '#2a5098', e: '#8a6a3a', E: '#5a4020', g: '#c4c0b4', G: '#8a867c' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......oao.......',
      '......oapo......',
      '..o...oapo...o..',
      '.oro..oapo..obo.',
      '.orRo.oapo.obBo.',
      '.orRo.oapo.obBo.',
      '.orRooaappoobBo.',
      '.orRooaappoobBo.',
      'ooooooooooooooo.',
      '.oeeeeggggeeeeo.',
      '..oeeEEgGEEeeo..',
      '....oeeEEeeo....',
      '......oooo......',
    ],
  },
  runestone: {
    palette: { o: OUTLINE, g: '#9a988c', G: '#6a685e', c: '#60e0ff', d: '#3a7a2a' },
    pixels: [
      '................',
      '................',
      '.....oooo.......',
      '....oggggo......',
      '...oggggGGo.....',
      '...ogcggGGo.....',
      '...ogcgcgGo.....',
      '...ogcccgGo.....',
      '...oggcggGo.....',
      '...ogggggGGo....',
      '...ogcgcgGGo....',
      '...oggcggGGo....',
      '..ogggcgggGGo...',
      '..oggggggGGGGo..',
      '.oddggggggGGGddo',
      '.ooooooooooooooo',
    ],
  },
  elementalShard: {
    palette: { o: OUTLINE, w: '#ffffff', a: '#d0f0ff', r: '#e05020', R: '#a03010', b: '#4080d0', B: '#2a5098', g: '#60c060', e: '#8a6a3a', s: '#2a2440' },
    pixels: [
      '.......oo.......',
      '......owao......',
      '......owaao.....',
      '.....owaaabo....',
      '.....orwabbo....',
      '....orrwabbbo...',
      '....orrwabbBo...',
      '...orrrRwbbbBo..',
      '...orrrRgbbbBo..',
      '....orRggggBo...',
      '....orggggeo....',
      '.....oggeeo.....',
      '......oeeo......',
      '.......oo.......',
      '................',
      '....ssssssss....',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const CONFLUX_TINTS = {
  sprite: '#ff90e0',
  stormElemental: '#6080ff',
  iceElemental: '#c0f0ff',
  energyElemental: '#ffe040',
  magmaElemental: '#ff5020',
  magicElemental: '#e060ff',
  phoenix: '#ffb020',
} satisfies Partial<Record<UpgradedCreature, string>>
