import type { UpgradedCreature } from '../../game'
import { OUTLINE, SKIN, STEEL, WOOD, BONE, GOLD, type Sprite } from './shared'

/** Dungeon: its creatures, heroes, town emblem and homeland obstacles. */
export const DUNGEON_SPRITES = {
  troglodyte: {
    palette: { o: OUTLINE, g: '#7a8a6a', G: '#566248', m: BONE, w: WOOD },
    pixels: [
      '................',
      '................',
      '....oooo........',
      '...oggggo.......',
      '..oggggggo......',
      '..ogGgggggo..o..',
      '..oggggmmmo.owo.',
      '...ogggggo.owo..',
      '..oggggggoowo...',
      '.ogggggggggo....',
      '.ogoTTTTTogo....',
      '.o.oTTTTTo.o....',
      '...otttto.......',
      '...ogo.ogo......',
      '...ogo.ogo......',
      '..oggo.oggo.....',
    ],
  },
  harpy: {
    palette: { o: OUTLINE, h: '#3a2a3a', s: SKIN, y: '#e0a020' },
    pixels: [
      '................',
      '.....oooo.......',
      '....ohhhho......',
      '...ohhsssso.....',
      '...ohhsoso......',
      '...ohhsssso.....',
      'oo..ohsso....oo.',
      'oTo.oTTTTo..oTo.',
      'oTTooTTTTooTTto.',
      '.otTTTTTTTTTto..',
      '..ootTTTTTtoo...',
      '....otttto......',
      '....oyoyo.......',
      '....oyoyo.......',
      '...oyyoyyo......',
      '................',
    ],
  },
  beholder: {
    palette: { o: OUTLINE, p: '#8a4a8a', P: '#5a2e5a', w: '#f0f0f0', k: '#141018', m: BONE },
    pixels: [
      '...T.....T......',
      '...o..T..o...T..',
      '....o.o.o...o...',
      '.....oooooooo...',
      '...oopppppppoo..',
      '..oppppppppppo..',
      '.oppppowwwopppo.',
      '.opppowwwwwoppo.',
      '.opppowwwkkoppo.',
      '.opppowwwwwoppo.',
      '.oppppowwwopppo.',
      '..oPppppppppTo..',
      '..oPPmmmmmmPTo..',
      '...oPPPPPPPPo...',
      '.....oooooo.....',
      '................',
    ],
  },
  medusa: {
    palette: { o: OUTLINE, g: '#6a9a4a', G: '#4a6a3a', s: '#c8d8a8', r: '#e02020', w: WOOD },
    pixels: [
      '...g.g.g........',
      '..ogogogo...o...',
      '.ogggggggo.owo..',
      '.oggssssgo.o.wo.',
      '..ogssrso..o.wo.',
      '..ogsssso..o..wo',
      '...ossso...o..wo',
      '..oTTTTToooooswo',
      '.osTTTTTo..o..wo',
      '.os.TTTo...o.wo.',
      '...oGGGGo..o.wo.',
      '....oGGGGo..owo.',
      '.....oGGGGo..o..',
      '....oGGGGGo.....',
      '..ooGGGGGo......',
      '.oGGGGGooo......',
    ],
  },
  minotaur: {
    palette: { o: OUTLINE, h: BONE, b: '#6a4028', n: '#c08868', k: '#e02020', M: STEEL, w: WOOD },
    pixels: [
      '..o.......o.....',
      '..oho....oho....',
      '...ohooooho.....',
      '....obbbbbo.....',
      '...obbbbbkbo....',
      '...obbbbbnnno...',
      '....obbbbnno....',
      '..oobbbbboo..oo.',
      '.obbTTTTTbbo.oMo',
      '.obbTTTTTbobooMo',
      '.obotTTTtobbwMMo',
      '..o.ottto..owoo.',
      '....obobo..wo...',
      '....obobo.wo....',
      '...obbobbo......',
      '...oooooooo.....',
    ],
  },
  manticore: {
    palette: { o: OUTLINE, l: '#c88a3a', L: '#8a5a20', m: '#a03028', s: '#e0b088', k: '#6a1c50', K: '#3a1030', r: '#e02020' },
    pixels: [
      '.oo.........oo..',
      'okKo.......ommo.',
      'okkKo.....omrmo.',
      'okkkKo...omssso.',
      'oTkkkKo..omssso.',
      '.oTtkkKoomsssmo.',
      'oo.oTtkKommmmo..',
      'oko.oTtlllllmo..',
      'okKoolllllllllo.',
      '.okkolllTTTlllo.',
      '..oolllTTTTTllo.',
      '....oLlltttllLo.',
      '....oLLo...oLLo.',
      '....oLLo...oLLo.',
      '...oLLo...oLLo..',
      '...oooo...oooo..',
    ],
  },
  redDragon: {
    palette: { o: OUTLINE, k: '#b02a1c', K: '#e0583a', y: '#f0c040', f: '#ff8a20' },
    pixels: [
      '..oo............',
      '..oTo.......oo..',
      '..oTTo.....okko.',
      '..oTtTo...okkyko',
      '..oTttToookkkkfo',
      '..oTtttTkkkkoff.',
      '.ooTtttkkkkko...',
      'okkoTtkkkkko....',
      'okkkkkkkkkko....',
      '.okkkkkkkkkko...',
      '..okKkKkKkKko...',
      '..okkkkkkkkkko..',
      '...oKKKKKKKKko..',
      '...okKo..okKoo..',
      '...okko..okko...',
      '..oooo..oooo....',
    ],
  },
  stalagmite: {
    palette: { o: OUTLINE, l: '#a08a74', g: '#7a6656', G: '#54443a', d: '#2e2620' },
    pixels: [
      '................',
      '.......oo.......',
      '.......olo......',
      '......ollgo.....',
      '......ollgo.....',
      '.....olllggo....',
      '.....ollgggo..o.',
      '....ollllggo.olo',
      '....olllgggoolgo',
      '...olllggggoolgo',
      '...ollllgggGolgo',
      '..olllgggggGolGo',
      '..ollggggggGGlGo',
      '.ollgggggGGGGgGo',
      '.odddddddddddddo',
      '..oooooooooooooo',
    ],
  },
  crystal: {
    palette: {
      o: '#1a1030',
      w: '#ffffff',
      c: '#7af0ff',
      C: '#30b0d0',
      p: '#c080ff',
      P: '#6a28b0',
    },
    pixels: [
      '.......oo.......',
      '......owco......',
      '......owcCo.....',
      '.....owccCo.....',
      '.....owccCo.o...',
      '.....owccCoopo..',
      '..o..owccCoppPo.',
      '.opo.owccCoppPo.',
      '.oppoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowcCCoppPo.',
      'oPPPooCCCCoPPPo.',
      '.oooooooooooooo.',
      '................',
    ],
  },
  lorelei: {
    palette: { o: OUTLINE, f: '#6a3a8a', y: '#ffd040', b: '#d8a030' },
    pixels: [
      '.....o.oo.o.....',
      '....ofoffofo....',
      '...offffffffo...',
      '..offffffffffo..',
      '..offyffffyffo..',
      '..offffbbffffo..',
      '..offfbbbbfffo..',
      '...offfbbfffo...',
      '....offbbffo....',
      '.....offffo.....',
      '......oooo......',
      '.offoTTTTTToffo.',
      '.offfoTTTTofffo.',
      '.offffTTTTffffo.',
      '.offffTTttffffo.',
      '.oooooooooooooo.',
    ],
  },
  dace: {
    palette: { o: OUTLINE, h: BONE, n: '#6a4a2a', r: '#e02020', s: '#b08868', d: '#141018', y: GOLD },
    pixels: [
      '.o............o.',
      '.oho........oho.',
      '.ohhoooooooohho.',
      '..oonnnnnnnnoo..',
      '...onnnnnnnno...',
      '...onrnnnnrno...',
      '...onnnnnnnno...',
      '....onssssno....',
      '....osdssdso....',
      '....ossyysso....',
      '.....oooooo.....',
      '.oonnnTTTTnnnoo.',
      '.onnnTTTTTTnnno.',
      '.onnnTTyyTTnnno.',
      '.onnnTTTTTTnnno.',
      '.oooooooooooooo.',
    ],
  },
  deemer: {
    palette: { o: OUTLINE, k: '#2a2430', K: '#4a3e58', r: '#ff3020', d: '#141018', w: '#f0f0f0', f: '#ff8a20', y: GOLD },
    pixels: [
      '.o............o.',
      '.oko........oko.',
      '..okooooooooko..',
      '...okkkkkkkko...',
      '..okkKkkkkKkko..',
      '..okrrkkkkrrko..',
      '..okkkkkkkkkko..',
      '...okKKKKKKko...',
      '...okkkkkkkko...',
      '...okdkkkkdko...',
      '...owkwwwwkwo...',
      '....offffffo....',
      '.okkkTTTTTTkkko.',
      '.okkTTTTTTTTkko.',
      '.okkTTTyyTTTkko.',
      '.oooooooooooooo.',
    ],
  },
  dungeon: {
    palette: { o: OUTLINE, r: '#7a6a5e', R: '#4e423a', k: '#0a0608', e: '#ff3a2a', c: '#c890ff', C: '#7a38c8' },
    pixels: [
      '................',
      '......oooo......',
      '....oorrRroo....',
      '...orrrRrrrro...',
      '.oorrRrrrrRrroo.',
      'ocorrrrrrrrrroco',
      'occorRroooRrocCo',
      'oCcorrokkkoRocCo',
      'oCCorokkkkkorCCo',
      '.oCoroekkkeoroCo',
      '.ooRrokkkkkorRoo',
      '.orrrokkkkkorrro',
      'oRrrrokkkkkorRro',
      'orrRrokkkkkorrRo',
      'orrrrokkkkkorrro',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const DUNGEON_TINTS = {
  infernalTroglodyte: '#c04020',
  harpyHag: '#a040a0',
  evilEye: '#40c040',
  medusaQueen: '#c0a020',
  minotaurKing: '#f0c040',
  scorpicore: '#c04040',
  blackDragon: '#202028',
} satisfies Partial<Record<UpgradedCreature, string>>
