import type { UpgradedCreature } from '../../game'
import { OUTLINE, BONE, BONE_SHADOW, GOLD, type Sprite } from './shared'

/** Necropolis: its creatures, heroes, town emblem and homeland obstacles. */
export const NECROPOLIS_SPRITES = {
  skeleton: {
    palette: { o: OUTLINE, w: BONE, W: BONE_SHADOW, m: '#a0a8b0', y: '#8a6a3a' },
    pixels: [
      '..o.............',
      '.omo.oooo.......',
      '.omoowwwwo......',
      '.omoowwowo......',
      '.omoowwwwo......',
      'oyyyo.oWwo......',
      '.owo..owo.oooo..',
      '.owwowWwWoTTTto.',
      '..o.owWwWoTyTto.',
      '....owWwWoTTTto.',
      '.....owWwotttto.',
      '.....owowo.oo...',
      '.....owowo......',
      '.....owowo......',
      '.....owowo......',
      '.....owwowwo....',
    ],
  },
  walkingDead: {
    palette: {
      o: OUTLINE,
      g: '#8a9a6a',
      G: '#5a6a44',
      r: '#e03020',
      w: '#d8d0b0',
    },
    pixels: [
      '................',
      '................',
      '....oooo........',
      '...oggggo.oooo..',
      '..oTTggggoggggo.',
      '..oTtGgggogggro.',
      '..oGGtGgggggggo.',
      '..oGGGtGgggowwo.',
      '..oGGGtGGgggooo.',
      '..oGGGGtGoggggo.',
      '...oGGGtGo.ogogo',
      '...otTtTto......',
      '...oGo.oGo......',
      '..oGo..oGo......',
      '..oGo...oGo.....',
      '.oGGo...oGGo....',
    ],
  },
  wight: {
    palette: {
      o: '#0a0810',
      P: '#3a3650',
      k: '#000000',
      e: '#7af0ff',
      c: '#a8b0c0',
    },
    pixels: [
      '................',
      '.....oooo.......',
      '....oPPPPo......',
      '...oPPPPPPo.....',
      '...oPPkekeko....',
      '...oPPkkkkko....',
      '..oPPPPkkkPo....',
      '..oPTPPPPPPPcco.',
      '.oPPPTPPPPPPoco.',
      '.oPPPPTPPPPPo...',
      '.oPPPPPtPPPo....',
      '..oPPPPPtPo.....',
      '...oPPPTo.......',
      '..oPPo.otTo.....',
      '.oPPo....oo.....',
      'oPo.............',
    ],
  },
  vampire: {
    palette: {
      o: OUTLINE,
      s: '#dcd8e4',
      h: '#141018',
      r: '#e02020',
      k: '#241a26',
      K: '#3e2c40',
      w: '#f0f0f0',
    },
    pixels: [
      '................',
      '......oooo......',
      '.....ohhhho.....',
      'o...ohhssso...o.',
      'oo.oTohssro..oo.',
      'oTooTtosswo.oTo.',
      'oTTtoKkkwkKotTTo',
      'oTTTtKkkkkKtTTTo',
      'oTTTtKkkkkKtTTTo',
      'otTTtKkkkkKtTTto',
      'oo.otKkkkkKto.oo',
      '.....oKkkKo.....',
      '......oKKo......',
      '......okko......',
      '.......oo.......',
      '................',
    ],
  },
  lich: {
    palette: {
      o: OUTLINE,
      w: BONE,
      W: BONE_SHADOW,
      p: '#4a3462',
      P: '#2e1f40',
      g: '#70ff90',
      G: '#20a040',
      y: '#d0a030',
      n: '#5a4030',
    },
    pixels: [
      '.....y.y.y..ooo.',
      '....oyyyyyoogggo',
      '....owwwwwooggGo',
      '....owwwgwo.oGo.',
      '....owwwWwo.ono.',
      '.....owowo..ono.',
      '..oTTTTTTTToono.',
      '..opppppppTowwo.',
      '..oPppppppToono.',
      '..oPPpppppToono.',
      '..oPPpppppToono.',
      '.oPPPpppppToono.',
      '.oPPPpppppToono.',
      'oPPPPpppppToono.',
      'oPoPPoppoTToono.',
      'o.o..o..o.o..o..',
    ],
  },
  blackKnight: {
    palette: {
      o: OUTLINE,
      a: '#3a3a44',
      A: '#22222a',
      n: '#5a4030',
      w: '#c8c0a8',
      r: '#ff3020',
    },
    pixels: [
      'oooon...........',
      'oTTTn.o..o......',
      'oTtTn.oaao......',
      'oTTTnoaarro.....',
      'otTon.oaaao.oo..',
      '.o.on.oAaaAowwo.',
      '....noAaaaaowrwo',
      '....noAaaaAowwwo',
      '.ooooooooowwooo.',
      'oTTTTATTTTwwo...',
      'otTTTATTTTto....',
      'otTTTTTTTTto....',
      'otttttttttto....',
      '.owowo....owowo.',
      '.owowo....owowo.',
      '.oAoAo....oAoAo.',
    ],
  },
  boneDragon: {
    palette: { o: OUTLINE, b: BONE, B: BONE_SHADOW, g: '#60f0a0', k: '#2a2430' },
    pixels: [
      '..oo............',
      '..oBo.......oo..',
      '..oBBo.....obbo.',
      '..oBkBo...obbgbo',
      '..oBkkBoooobbbbo',
      '..oBkkkBobboobo.',
      '.ooBkkkbobbo....',
      'obboTtbobbo.....',
      'obobTTtbkbo.....',
      '.obkbkbkbkbo....',
      '..obkbkbkbbo....',
      '..obbbbbbbbbo...',
      '...oBkBkBkBbo...',
      '...obBo..obBoo..',
      '...obko..obko...',
      '..oooo..oooo....',
    ],
  },
  deadTree: {
    palette: { o: OUTLINE, b: '#6a5240', B: '#3a2c22' },
    pixels: [
      '.oo........oo...',
      '.obo......obo...',
      '..obo....obo..o.',
      '...obo..obo..obo',
      '....oboobo..obo.',
      'oo...obbo..obo..',
      'obo..obBo.obo...',
      '.obo.obBoobo....',
      '..obbobBbbo.....',
      '...oobBbo.......',
      '.....obBo.......',
      '.....obBo.......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '....oobbBBoo....',
    ],
  },
  tombstone: {
    palette: { o: OUTLINE, l: '#9a9aa2', g: '#6a6a72', d: '#3a3230' },
    pixels: [
      '................',
      '................',
      '................',
      '.....oooooo.....',
      '....ollllllo....',
      '...ollllllllo...',
      '...olllolllgo...',
      '...ollooolggo...',
      '...olllolllgo...',
      '...olllolllgo...',
      '...ollllllggo...',
      '...ollllllggo...',
      '...olllllgggo...',
      '..oooooooooooo..',
      '.odddddddddddddo',
      '..oooooooooooo..',
    ],
  },
  vokial: {
    palette: { o: OUTLINE, k: '#2a2030', f: '#4a3440', r: '#ff3030', p: '#d07890', w: '#f0f0f0' },
    pixels: [
      '.o............o.',
      '.oo..........oo.',
      '.oko..oooo..oko.',
      '.okkooffffookko.',
      '..okkffffffkko..',
      '...offrffrffo...',
      '...offffffffo...',
      '...offfppfffo...',
      '...offwffwffo...',
      '....offffffo....',
      '.....oooooo.....',
      '.oooooTTTTooooo.',
      '.okkooTTTTookko.',
      '.okkkkTTTTkkkko.',
      '.okkkkTTttkkkko.',
      '.oooooooooooooo.',
    ],
  },
  septienna: {
    palette: { o: OUTLINE, k: '#2a1e30', b: BONE, v: '#c060ff', d: '#141018', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....okkkkkko....',
      '...okkkkkkkko...',
      '...okkbbbbkko...',
      '...okbbbbbbko...',
      '...okdvbbvdko...',
      '...okbbbbbbko...',
      '...okbbddbbko...',
      '...okkbdbdkko...',
      '.oko.okkkko.oko.',
      '.okkooTTTTookko.',
      '.okkkoTTTTokkko.',
      '.okkkkTyyTkkkko.',
      '.okkkkTTTTkkkko.',
      '.oooooooooooooo.',
    ],
  },
  thant: {
    palette: { o: OUTLINE, y: GOLD, b: BONE, g: '#40e060', d: '#141018', k: '#2a2a22' },
    pixels: [
      '....y..yy..y....',
      '...oyyyyyyyyo...',
      '..obbbbbbbbbbo..',
      '..obbbbbbbbbbo..',
      '..obggbbbbggbo..',
      '..obddbbbbddbo..',
      '..obbbbddbbbbo..',
      '..oobbbbbbbboo..',
      '...obdbdbdbdo...',
      '...obbbbbbbbo...',
      '....oooooooo....',
      '.ookkkobbokkkoo.',
      '.okTbbbbbbbbTko.',
      '.okTkkkkkkkkTko.',
      '.okTbbbbbbbbTko.',
      '.oooooooooooooo.',
    ],
  },
  necropolis: {
    palette: { o: OUTLINE, p: '#6a6478', P: '#3e3850', g: '#7cff8a', b: BONE },
    pixels: [
      '.......o........',
      '.......o........',
      '......opo.......',
      '......opo.......',
      '.....oppPo......',
      '.o...opgPo...o..',
      'opo..oppPo..opo.',
      'opo..oppPo..opo.',
      'opPooopgPoooopPo',
      'ogPoopppPPoopgPo',
      'opPoopppPPoopPPo',
      'opPooooooooopPPo',
      'opPoobbbbbboopPo',
      'opPoobobbobPopPo',
      'opPoobbbbbbPopPo',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const NECROPOLIS_TINTS = {
  skeletonWarrior: '#a0b0c0',
  zombie: '#60a060',
  wraith: '#7040a0',
  vampireLord: '#c02040',
  powerLich: '#40e080',
  dreadKnight: '#6020a0',
  ghostDragon: '#a0f0ff',
} satisfies Partial<Record<UpgradedCreature, string>>
