import type { UpgradedCreature } from '../../game'
import { OUTLINE, SKIN, STEEL, DARK_STEEL, WOOD, BOOTS, BONE, GOLD, type Sprite } from './shared'

/** Stronghold: its creatures, heroes, town emblem and homeland obstacles. */
export const STRONGHOLD_SPRITES = {
  goblin: {
    palette: { o: OUTLINE, g: '#8aa040', G: '#5e7028', y: '#f0d020', w: WOOD, M: STEEL, b: BOOTS },
    pixels: [
      '................',
      '................',
      '..o.............',
      '..ogoooo........',
      '...ogggggo......',
      '...oggyggo...o..',
      '..oggggggGo.oMo.',
      '...oGgggGo..oMo.',
      '....ooooo..owo..',
      '...oTTTTToowo...',
      '..ogTTTTTggo....',
      '..oooTTTto......',
      '....otttto......',
      '....ogo.ogo.....',
      '....ogo.ogo.....',
      '...obbo.obbo....',
    ],
  },
  wolfRider: {
    palette: { o: OUTLINE, g: '#8aa040', G: '#5e7028', f: '#8a8a90', F: '#5a5a62', w: WOOD, M: STEEL, r: '#e02020', h: BONE },
    pixels: [
      '................',
      '......o.........',
      '.....ogoo.......',
      '.....oggGo..o...',
      '.....ogggo.oMo..',
      '....oTTTToowo...',
      '....oTTTTgwo....',
      '.....ottooo..oo.',
      '.o..offffffoofFo',
      'oFooffffffffffro',
      'offfffffffffffho',
      '.offffffffffooo.',
      '..ofFo....oFfo..',
      '..ofo.....ofo...',
      '.ofo.......ofo..',
      '.oo.........oo..',
    ],
  },
  orc: {
    palette: { o: OUTLINE, g: '#6a8a4a', G: '#4a6232', h: BONE, w: WOOD, b: BOOTS, r: '#c03020', M: STEEL },
    pixels: [
      '................',
      '....ooooo.......',
      '...ogggggo......',
      '..oggggrgGo.....',
      '..ogggggggo.....',
      '..oggghgho......',
      '...ooggggo...o..',
      '..oTTTTTTo..oMo.',
      '.ogTTTTTTTooMMo.',
      '.ogTTTTTTggoMo..',
      '.oooTTTTTo..o...',
      '...otttttwo.....',
      '...ottttto......',
      '...obo.obo......',
      '...obo.obo......',
      '..obbo.obbo.....',
    ],
  },
  ogre: {
    palette: { o: OUTLINE, s: '#c0a070', S: '#8a7048', h: BONE, w: WOOD, W: '#5a3a1e', b: BOOTS },
    pixels: [
      '............oo..',
      '....ooooo..oWWo.',
      '...ossssso.oWWo.',
      '..osssssSso.owo.',
      '..osshssShooWo..',
      '...ossssso.owo..',
      '..oosssSoooWo...',
      '.osTTTTTTsswo...',
      '.osTTTTTTTsso...',
      '.osTTTTTTTso....',
      '.oooTTTTTTo.....',
      '...otttttto.....',
      '...osssssso.....',
      '...osso.osso....',
      '...osso.osso....',
      '..obbbo.obbbo...',
    ],
  },
  roc: {
    palette: { o: OUTLINE, f: '#8a5a30', F: '#5e3a1a', y: GOLD, Y: '#c08a10', w: '#f0ead8', r: '#e02020' },
    pixels: [
      '................',
      '.oo.............',
      '.ofoo.......ooo.',
      '.offfoo....owwwo',
      '..offffoo.orwwyo',
      '..offFfffoowwwyo',
      '...offFFfffwwYo.',
      '...ooffFffffoo..',
      '..offfTTTTffo...',
      '.offfTTTTTfffo..',
      '.oFffTTTTffffo..',
      '..oFFftttfFFo...',
      '...ooofffooo....',
      '.....oyo.oyo....',
      '....oyyo.oyyo...',
      '................',
    ],
  },
  cyclops: {
    palette: { o: OUTLINE, s: '#c08a68', S: '#8a6048', w: '#f0f0f0', r: '#e02020', l: '#7a7a80', b: BOOTS },
    pixels: [
      '.........oo.....',
      '....oooooll.....',
      '...osssssolo....',
      '..ossswwssol....',
      '..ossswrssso....',
      '..osssssSso.....',
      '...ossSSso......',
      '..oosssssoo.....',
      '.osTTTTTTTso....',
      '.osTTTTTTTso....',
      '.osoTTTTTosso...',
      '.oo.ottttoooo...',
      '....ottttto.....',
      '...osso.osso....',
      '...osso.osso....',
      '..obbbo.obbbo...',
    ],
  },
  behemoth: {
    palette: { o: OUTLINE, f: '#9a7a5a', F: '#6a5038', h: BONE, r: '#e02020', k: '#2a1c12' },
    pixels: [
      '................',
      '.........o.o....',
      '........ohoho...',
      '.......offfffo..',
      '.ooo..offffrfo..',
      'ofFfoofffffffho.',
      'ofFffffffffhkho.',
      '.offfTTTTffffo..',
      '.ofTTTTTTTTffo..',
      '.ofTTTTTTTTTfo..',
      '.oFtttttttttFo..',
      '.oFFffffffffFo..',
      '..offo...offo...',
      '..offo...offo...',
      '.ohfho..ohfho...',
      '.ooooo..ooooo...',
    ],
  },
  jabarkas: {
    palette: { o: OUTLINE, g: '#6a8a4a', G: '#4a6232', h: BONE, r: '#c03020', d: '#141018', y: GOLD, f: '#8a5a30' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....offffffo....',
      '...offffffffo...',
      '...oggggggggo...',
      '..ooggggggggoo..',
      '..ogggrggrgggo..',
      '..ogggggggggGo..',
      '...oggGggGggo...',
      '...oghggggho....',
      '....oggggggo....',
      '.....oooooo.....',
      '.offfTTTTTTfffo.',
      '.offTTTTTTTTffo.',
      '.offTTTyyTTTffo.',
      '.oooooooooooooo.',
    ],
  },
  shiva: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', n: '#3a2414', d: '#141018', r: '#c03020', w: '#f0ead8', f: '#8a5a30', y: GOLD },
    pixels: [
      '.......oo.......',
      '......owwo......',
      '.....owffwo.....',
      '....onnnnnno....',
      '...onnnnnnnno...',
      '...onsssssssno..',
      '...onsdsssdsno..',
      '...onsssssssno..',
      '...onssSSSssno..',
      '...onssrrrssno..',
      '....onsssssno...',
      '.....ooooooo....',
      '.onnnTTTTTTnnno.',
      '.onnTTTTTTTTnno.',
      '.onnTTTyyTTTnno.',
      '.oooooooooooooo.',
    ],
  },
  terek: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', n: '#3a2414', d: '#141018', h: STEEL, H: DARK_STEEL, c: '#40c0f0', y: GOLD },
    pixels: [
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhhcchhho...',
      '..oHhhhhhhhhHo..',
      '..oHHHHHHHHHHo..',
      '...osssssssso...',
      '...osdssssdso...',
      '...ossssssss....',
      '...ossSSSSsso...',
      '...onnnnnnnno...',
      '....onnnnnno....',
      '.....oonnoo.....',
      '.occcTTTTTTccco.',
      '.occTTTTTTTTcco.',
      '.occTTTyyTTTcco.',
      '.oooooooooooooo.',
    ],
  },
  boulder: {
    palette: { o: OUTLINE, l: '#e0c890', s: '#c8a868', S: '#a08048', d: '#6a5030' },
    pixels: [
      '................',
      '................',
      '................',
      '.......ooooo....',
      '.....oollllso...',
      '....ollsssssSo..',
      '...olsssssSsSo..',
      '..olssSssssSSo..',
      '..olsssssSSSSSo.',
      '.oolssssSSSSdSo.',
      '.olsssSSSSSSdSo.',
      '.osssSSSSdSddSo.',
      '.oSssSSSSdddddo.',
      '.oSSSSSSddddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  totem: {
    palette: { o: OUTLINE, w: '#a06a32', W: '#6a4220', r: '#c03020', y: GOLD, k: '#141018', g: '#4a8a3a' },
    pixels: [
      '..oo...oo...oo..',
      '..oyo.ogo..oyo..',
      '...oyoooooooyo..',
      '....oooyyyoooo..',
      '.....owwwwwo....',
      '.....okwwwko....',
      '.....owwrwwo....',
      '.....oWkkkWo....',
      '.....owwwwwo....',
      '.....oyrwryo....',
      '.....owwwwwo....',
      '.....oWkkkWo....',
      '.....owwwwwo....',
      '.....owWwWwo....',
      '....owwwwwwwo...',
      '...ooooooooooo..',
    ],
  },
  stronghold: {
    palette: { o: OUTLINE, h: BONE, y: '#d0a858', Y: '#8a6a2a', w: WOOD, W: '#5a3a1e', d: '#2a1a10' },
    pixels: [
      '.o............o.',
      '.oh..........ho.',
      '..oh...oo...ho..',
      '...oho.oo.ohoo..',
      '....ohoyyohoo...',
      '....oyyYyyyo....',
      '...oyyYyyYyyo...',
      '..oyYyyyyyyYyo..',
      '.oyyyyYyyYyyyyo.',
      '.oooooooooooooo.',
      '.owWwWoddoWwWwo.',
      '.owWwWoddoWwWwo.',
      '.owWwWoddoWwWwo.',
      'oowWwWoddoWwWwoo',
      'o.o.o.oddo.o.o.o',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const STRONGHOLD_TINTS = {
  hobgoblin: '#c06030',
  wolfRaider: '#606870',
  orcChieftain: '#c03030',
  ogreMage: '#6040c0',
  thunderbird: '#40a0ff',
  cyclopsKing: '#c0a040',
  ancientBehemoth: '#d8c8a0',
} satisfies Partial<Record<UpgradedCreature, string>>
