import type { UpgradedCreature } from '../../game'
import { OUTLINE, SKIN, STEEL, DARK_STEEL, WOOD, BOOTS, GOLD, type Sprite } from './shared'

/** Tower: its creatures, heroes, town emblem and homeland obstacles. */
export const TOWER_SPRITES = {
  gremlin: {
    palette: { o: OUTLINE, g: '#8a9ab0', G: '#5a6a80', y: '#f0e040', k: '#141018', m: DARK_STEEL, M: STEEL },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '.o.....o........',
      '.ogoooogo.......',
      '..ogggggo.......',
      '..oggyggyo......',
      '..ogggggGo......',
      '...ogkkgo.......',
      '..oTTTTTgoo.....',
      '..oTtttTo.m.....',
      '...oGGGo...ooo..',
      '...ogoGo..oMMMo.',
      '..oggogGo.oMmmo.',
      '..ooo.ooo..ooo..',
    ],
  },
  stoneGargoyle: {
    palette: { o: OUTLINE, s: '#9a9aa0', S: '#6a6a72', d: '#4a4a52', r: '#e02020' },
    pixels: [
      '................',
      '.oo.............',
      '.oSoo......o.o..',
      '.oSSSoo....oooo.',
      '..oSSSSo..osssso',
      '..oSdSSSo.ossrso',
      '...oSdSSSoosssso',
      '....oSSdSoTTsso.',
      '.....oSSoTTTsso.',
      '......ooTtTssso.',
      '.......osssssSo.',
      '......osssSssSo.',
      '......osSo.osSo.',
      '.....osSo..osSo.',
      '.....osso..ossso',
      '.....oooo..ooooo',
    ],
  },
  stoneGolem: {
    palette: { o: OUTLINE, s: '#a8a4a0', S: '#7a7672', d: '#4e4a48', y: '#60c0ff' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....osssssSo....',
      '....osssysyo....',
      '....osSSSSSo....',
      '..ooooooooooooo.',
      '.ossSoTTTTosssSo',
      '.osSSoTtTToSssSo',
      '.osSSossssoSdSSo',
      '.oSSoosssSooSSo.',
      '.ossoossSSoosso.',
      '.oooooSSSSSoooo.',
      '....ossSoosSSo..',
      '....osdSoosSdo..',
      '...osssSoossSSo.',
      '...oooooooooooo.',
    ],
  },
  mage: {
    palette: { o: OUTLINE, s: SKIN, k: '#141018', r: '#5a4ab0', R: '#3a2e78', w: WOOD, c: '#80e0ff' },
    pixels: [
      '.......o....oo..',
      '......oro..occo.',
      '.....orRo..occo.',
      '....orrRRo..ow..',
      '...oooooooo..w..',
      '....ossskso..w..',
      '.....osssso..w..',
      '...orrTTTrrosw..',
      '...orrrTrrro.w..',
      '...orrrTrrRo.w..',
      '..orrrrTrrRRow..',
      '..orrrrTrrRRow..',
      '.orrrrrtrrRRow..',
      '.orrrrrrrrRRRo..',
      '.oRrrrrrrRRRRo..',
      '..ooooooooooo...',
    ],
  },
  genie: {
    palette: { o: OUTLINE, b: '#5a8ae0', B: '#3a5aa8', y: GOLD, w: '#f0f0f0', k: '#141018', c: '#a0d0ff' },
    pixels: [
      '.....oooo.......',
      '....owwwwo......',
      '....owwywo......',
      '....obbbkbo.....',
      '....obbbbbo.....',
      '.....obbbo......',
      '.ooooTTTTToooo..',
      'obbbTTTTTTTbbbo.',
      'oBbooTTTTTooBbo.',
      '.oo..otttto.oo..',
      '.....obbbbo.....',
      '.....oBbbbbo....',
      '......oBbbco....',
      '.......oBcco....',
      '........oco.....',
      '.........o......',
    ],
  },
  naga: {
    palette: { o: OUTLINE, k: OUTLINE, s: '#d8a878', h: '#2a1c30', g: '#5a9a7a', G: '#3a6a52', y: GOLD, m: STEEL },
    pixels: [
      '.......ooo......',
      '.m....ohhho...m.',
      '.m...ohhsso...m.',
      '.m...ohhsko...m.',
      '.y...oohsso...y.',
      '.so..oossoo..os.',
      '..sssoTTTTosss..',
      'mysooTTTTTToosym',
      '...ooosTTsooo...',
      'mysoossssssoosym',
      '....ogggggGo....',
      '.....oggggGo....',
      '....ogggGGo.....',
      '..oogggGGooooo..',
      '.ogggGGGGGgggGo.',
      '..oooooooooooo..',
    ],
  },
  giant: {
    palette: { o: OUTLINE, s: '#d8a888', S: '#a07058', h: '#6a4a2a', k: '#141018', b: BOOTS },
    pixels: [
      '.....oooooo.....',
      '....ohhhhhho....',
      '....ohsssssso...',
      '....ohsssksso...',
      '....ohsssssso...',
      '.....osssSSo....',
      '..ooooSssSoooo..',
      '.ossssssssssssso',
      'ossSssssssssSsso',
      'ossoSssssssSosso',
      'ossoSSsssSSSosso',
      'ossoTTTTTTTTosso',
      'oSSotTTTTTTtoSSo',
      '.oo.ossSoossSo..',
      '....ossSoossSo..',
      '...obbbboobbbbo.',
    ],
  },
  piquedram: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', w: '#e8e8e8', g: '#60c0a0', y: GOLD, b: '#8a5a30' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....osssssso....',
      '...ossssssssso..',
      '..owyyyyyyyyywo.',
      '..owoggoooggowo.',
      '..owssssssssswo.',
      '..owsssssSssswo.',
      '..oowwwwwwwwwoo.',
      '...owwwssswwwo..',
      '....owwwwwwwo...',
      '..ooooowwwooooo.',
      '.obbbTTTTTTbbbo.',
      '.obbTTTTyTTTTbbo',
      '.obTTTTyyyTTTTbo',
      '.ooooooooooooooo',
    ],
  },
  thane: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', h: '#4a2e1a', H: '#2e1c10', k: '#141018', b: '#7a5a9a', f: '#60e0a0' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhhhhhhHo...',
      '...ohhsssssHo...',
      '...ohssssssHo...',
      '...ohskssksHo...',
      '...ohssssssHo...',
      '...oHssssSsHo...',
      '...oHsskkssHo...',
      '....oHsHHsHo....',
      '..oooooHHooooo..',
      '.obbTTTTTTTTbbo.',
      '.obTTTTTTTTTTbo.',
      '.obTTTTffTTTTbo.',
      '.oooooooooooooo.',
    ],
  },
  solmyr: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', k: '#141018', b: '#3a6ad0', B: '#24408a', w: '#e8e8f0', W: '#a8a8b8', y: GOLD },
    pixels: [
      '.......oo.......',
      '......obbo......',
      '.....obbyBo.....',
      '....obbbbBBo....',
      '..oooooooooooo..',
      '...osssssssso...',
      '...osksssskso...',
      '...ossssSssso...',
      '...owwsssswwo...',
      '...owwwwwwwWo...',
      '....owwwwwWo....',
      '..oobowwwWobboo.',
      '.obbTTowWoTTbbo.',
      '.obTTTTooTTTTbo.',
      '.oBbbTTTTTTbbBo.',
      '.oooooooooooooo.',
    ],
  },
  tower: {
    palette: { o: OUTLINE, w: '#eef2f8', W: '#b8c4d8', b: '#4a7ad0', B: '#2a4a90', d: '#2a2440' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......obo.......',
      '......obBo......',
      '.....obbBBo.....',
      '.o...owwwWo...o.',
      'obo..owdwWo..obo',
      'obBo.owdwWo.obBo',
      'owWo.owwwWo.owWo',
      'owdWoowwwWoowdWo',
      'owwWoowwwWoowwWo',
      'owwWowwddWWowwWo',
      'owwWowwddWWowwWo',
      'oWWWowwddWWoWWWo',
      'oooooooooooooooo',
    ],
  },
  snowPine: {
    palette: { o: OUTLINE, w: '#f4f8ff', W: '#c0d0e8', g: '#2e6a4a', G: '#1c4630', b: '#7a4e2a', B: '#4a2e18' },
    pixels: [
      '.......oo.......',
      '......owwo......',
      '.....owwGo......',
      '.....ogggGo.....',
      '....owwwgGGo....',
      '....ogggGGGo....',
      '...owwwwwgGGo...',
      '...oggggGGGGo...',
      '..owwwwwwwgGGo..',
      '..ogggggGGGGGo..',
      '.owwwwwwwwwgGGo.',
      '.oggggggGGGGGGo.',
      '.oooooobBoooooo.',
      '......obBo......',
      '....wwobBowww...',
      '...owwwwwwwwWWo.',
    ],
  },
  iceRock: {
    palette: { o: OUTLINE, w: '#e8f4ff', i: '#a8d0f0', I: '#6aa0d0', g: '#7a8a98', G: '#4e5a68', d: '#34404c' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oowwwwioo...',
      '...owwwwiiiio...',
      '..owwiwwiiiiIo..',
      '..owiiiiiiiiIo..',
      '.oowiiiigiiIIo..',
      '.owiiiiggggIIIo.',
      '.oiiiigggGGIdIo.',
      '.oIiigGGGGGdddo.',
      '.oIIGGGGGGddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const TOWER_TINTS = {
  masterGremlin: '#4a7ad8',
  obsidianGargoyle: '#202030',
  ironGolem: '#8a8e98',
  archMage: '#8040d0',
  masterGenie: '#40d0ff',
  nagaQueen: '#f0c040',
  titan: '#e0e8ff',
} satisfies Partial<Record<UpgradedCreature, string>>
