import { OUTLINE, STEEL, DARK_STEEL, WOOD, type Sprite } from './shared'

/** The machines any army can buy. */
export const WAR_MACHINE_SPRITES = {
  ballista: {
    palette: { o: OUTLINE, w: WOOD, W: '#5a3a1a', m: STEEL, M: DARK_STEEL },
    pixels: [
      '................',
      '..........oo....',
      '..........omo...',
      '.......oo.oMo...',
      '.....oo...oMo...',
      '...oo.....oMo...',
      '.oo.......oMo...',
      'owwwwwwwwwwwwwmo',
      'oWWWWWWWWWWWWWoo',
      '.oo...oTo.oMo...',
      '...oo.oTo.oMo...',
      '.....ooTo.oMo...',
      '......oTooomo...',
      '.....oTtTo.oo...',
      '....owwwwwo.....',
      '....oWWWWWo.....',
    ],
  },
  firstAidTent: {
    palette: { o: OUTLINE, c: '#f0ead8', C: '#b8ae98', r: '#d02828', W: '#5a3a1a' },
    pixels: [
      '.......o........',
      '.......oTTo.....',
      '.......oTo......',
      '.......o........',
      '......ooo.......',
      '.....occCo......',
      '....occcCCo.....',
      '...occcccCCo....',
      '..occcrcccCCo...',
      '.occcrrrcccCCo..',
      'occcccrcccccCCo.',
      'occcccccccccCCo.',
      'occcoooooccCCCo.',
      'occcoWWWoccCCCo.',
      'occcoWWWoccCCCo.',
      'ooooooooooooooo.',
    ],
  },
  ammoCart: {
    palette: { o: OUTLINE, w: WOOD, W: '#5a3a1a', m: STEEL, M: DARK_STEEL },
    pixels: [
      '................',
      '................',
      '....o.o.o.o.....',
      '...omomomomo....',
      '....owowowo.....',
      '....owowowo.....',
      '..ooowowowooo...',
      '..owwwwwwwwwo...',
      '..owTTTTTTTwo...',
      '..owtttttttwo...',
      '..oWWWWWWWWWoooo',
      '...ooo....ooo..o',
      '..oMMMo..oMMMo..',
      '..oMoMo..oMoMo..',
      '..oMMMo..oMMMo..',
      '...ooo....ooo...',
    ],
  },
} satisfies Record<string, Sprite>
