import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, DARK_STEEL, WOOD, BOOTS, GOLD, type Sprite } from './shared'

/** Castle: its creatures, heroes, town emblem and homeland obstacles. */
export const CASTLE_SPRITES = {
  pikeman: {
    palette: { o: OUTLINE, s: SKIN, m: STEEL, M: DARK_STEEL, w: WOOD, b: BOOTS },
    pixels: [
      '................',
      '................',
      '................',
      '....oooo........',
      '...ommmmo.......',
      '..ommmmmmo......',
      '..oMMMMMMMo.....',
      '..oMssssoso....o',
      '...osssssso..oom',
      '..oTTTTTTTooowwo',
      '.omTTTTTTosswoo.',
      '.omTTTTTTo.oo...',
      '.ootTTTTto......',
      'owottttto.......',
      'woobo..obo......',
      'o.obbo.obbo.....',
    ],
  },
  archer: {
    palette: { o: OUTLINE, s: SKIN, k: '#2a2024', h: '#6b4a2a', m: '#c8d0d8', M: DARK_STEEL, l: '#7a5530', L: '#5a3a1e', q: '#4a3020', f: '#ece4cc', b: BOOTS, w: WOOD, S: '#e8e0c8' },
    pixels: [
      '.....oooo.......',
      '....ommmmo......',
      '...ommmmmmo.....',
      '...oMMMMMMMo....',
      '....ohsskoo..o..',
      '....ohssso..oMo.',
      '....oossoo.oSMo.',
      '...oTTTTlloSoMoo',
      '..ooTTTTwswswwwm',
      '.offTTTTTooSoMoo',
      '..oqTtttto.oSMo.',
      '..oqllllllo.oMo.',
      '..oqoLooLo...o..',
      '...ooLooLo......',
      '....oLooLo......',
      '...obboobbo.....',
    ],
  },
  griffin: {
    palette: { o: OUTLINE, g: '#c8963c', G: '#9a6a28', w: '#ece6d6', W: '#b8b0a0', y: '#e8b030', f: '#a8742c', F: '#7a4e1c', k: OUTLINE },
    pixels: [
      '.....o.o........',
      '...ooFoFo.......',
      '..oFffffo.......',
      '..offffffo......',
      '.offffffffoooo..',
      '.oofFfFfFowwkwo.',
      'oFooffffoowwwwyo',
      'oGooogggggWWwwyy',
      '.oGgggggggTToooo',
      '..ogggggggggo...',
      '..ogggggggggo...',
      '...oGGggGGyo....',
      '...oGoGoooyo....',
      '...oGoGo..oyo...',
      '..oGGoGGo.oyyo..',
      '...oo.oo...oo...',
    ],
  },
  swordsman: {
    palette: { o: OUTLINE, m: STEEL, M: '#7a848e', n: '#4e5864', k: '#141018', b: '#e6ecf2', y: '#e0b840' },
    pixels: [
      '................',
      '.....ooo......o.',
      '....oTTmo....obo',
      '...oTmmmmo..obo.',
      '....ommmkkoobo..',
      '..ooommmmoybo...',
      '.oTTommmoomyo...',
      'oTTTTmmmmmoo....',
      'oTTyTmmmmo......',
      'oTyyymTTmo......',
      'oTTyTmTTmo......',
      'oTTyTnnnnno.....',
      '.oTToMooMo......',
      '..oooMooMo......',
      '....oMooMo......',
      '...onnoonno.....',
    ],
  },
  monk: {
    palette: { o: OUTLINE, s: SKIN, r: '#8a6440', R: '#5e4228', w: WOOD, y: '#fff6b0', Y: GOLD },
    pixels: [
      '............ooo.',
      '...........oyyyo',
      '.....ooo...oyyyo',
      '....orrro...oYo.',
      '...orrrsso..owo.',
      '...orrsoso..owo.',
      '...orrssso..owo.',
      '..orrrrTro..owo.',
      '..orRrrTrrossso.',
      '..orRrrTrro.owo.',
      '..oRRrrtrro.owo.',
      '.oRRrrrtrro.owo.',
      '.oRRrrrtrrroowo.',
      'oRRRrrrtrrrrowo.',
      'oRRRRrrtrrrrowo.',
      '.ooooooooooo.o..',
    ],
  },
  cavalier: {
    palette: { o: OUTLINE, h: '#ecece8', H: '#a8aab0', k: '#2a2024', m: '#c0c8d0', M: DARK_STEEL, w: WOOD, b: '#e6ecf2' },
    pixels: [
      '.....oToo.......',
      '.....oTmmo......',
      '.....ommko......',
      '....oommoooooooo',
      '...owwwwwMwwwwwb',
      '....ommmmoooohoo',
      '....ommmmooMMkho',
      '..oohhmmhhhohhhH',
      '.oHhhhhmhhhhhooo',
      'oHoTTTTTTTTTo...',
      'oHoTtTtTtTtTo...',
      '.ooHohooooHoho..',
      '..oHoho..oHoho..',
      '..oHoho..oHoho..',
      '..okoko..okoko..',
      '...o.o....o.o...',
    ],
  },
  angel: {
    palette: { o: OUTLINE, w: '#ffffff', W: '#b8c4d8', r: '#f0e0b0', R: '#c8b078', y: '#e0b840', s: '#f0c8a0', h: '#f0d060', k: '#2a2024', b: '#e6ecf2' },
    pixels: [
      '..oooo.......o..',
      '.owwWwo.oo..obo.',
      'owWwwwWohho.obo.',
      'oWwwwwWhsskoobo.',
      'owwwwwWhsso.obo.',
      'oWwwwwWhsso.obo.',
      'owwwwwWoooooybyo',
      '.oWwwwWrrrrrsoo.',
      '.owwwwWTTTTooyo.',
      '..oWoorrrrro.o..',
      '...o.orrrrro....',
      '.....orrrrro....',
      '.....orRrrro....',
      '......oRrro.....',
      '......oRrro.....',
      '.....oyyyyyo....',
    ],
  },
  rock: {
    palette: { o: OUTLINE, l: '#b4b4b8', g: '#8a8a8e', G: '#5e5e62', d: '#3e3e44' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oollllgoo...',
      '...ollllggggo...',
      '..ollgllgggggo..',
      '..olggggggggGo..',
      '.oolgggggggGGo..',
      '.olgggggggGGGGo.',
      '.oggggggGGGGdGo.',
      '.oGgggGGGGGdddo.',
      '.oGGGGGGGGddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  tree: {
    palette: {
      o: OUTLINE,
      l: '#5aa040',
      g: '#3a7a2a',
      G: '#245018',
      b: '#7a4e2a',
      B: '#4a2e18',
    },
    pixels: [
      '.....oooooo.....',
      '...oollllggo....',
      '..olllllggggo...',
      '.ollllgllgggGo..',
      '.olllggggggGGo..',
      'ollgggggggggGGo.',
      'olggglgggggGGGo.',
      'oggggggggGGGGGo.',
      '.oGgggggGGGGGo..',
      '..oGGGGoGGGGo...',
      '...oooobBoooo...',
      '......obBo......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '.....oooooo.....',
    ],
  },
  tyris: {
    palette: { o: OUTLINE, M: STEEL, N: DARK_STEEL, d: '#141018' },
    pixels: [
      '.......TT.......',
      '......TTtT......',
      '.....oooooo.....',
      '....oMMMMMMo....',
      '...oMMMMMMMNo...',
      '...oMMMMMMMNo...',
      '...oMddddddNo...',
      '...oMMMMMMMNo...',
      '...oMMdMMdMNo...',
      '...oMMMMMMMNo...',
      '....oMMMMMNo....',
      '..ooMMMMMMMMoo..',
      '.oMMTTTTTTTTMMo.',
      '.oMTTTTTTTTTTMo.',
      '.oMTTTTttTTTTMo.',
      '.oooooooooooooo.',
    ],
  },
  edric: {
    palette: { o: OUTLINE, M: STEEL, N: DARK_STEEL, d: '#141018', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oMMMMMMo....',
      '...oMMMMMMMNo...',
      '...oMMMMMMMNo...',
      '...oMddddddNo...',
      '...oMMMddMMNo...',
      '...oMMMddMMNo...',
      '...oMMMMMMMNo...',
      '...oyyyyyyyyo...',
      '....oooooooo....',
      '..ooMMMMMMMMoo..',
      '.oMMTTTTTTTTMMo.',
      '.oMTTTTyyTTTTMo.',
      '.oMTTTyyyyTTTMo.',
      '.oooooooooooooo.',
    ],
  },
  adela: {
    palette: { o: OUTLINE, k: '#1e1a22', w: '#f0ece0', s: SKIN, e: OUTLINE, v: '#3a3440', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....okkkkkko....',
      '...okkkkkkkko...',
      '...okwwwwwwko...',
      '...okwessewko...',
      '...okwvvvvwko...',
      '...okwvvvvwko...',
      '...okwwvvwwko...',
      '...okkwwwwkko...',
      '...okkkkkkkko...',
      '..ookkkkkkkkoo..',
      '.oTkkkkkkkkkkTo.',
      '.oTkkkkyykkkkTo.',
      '.oTkkkyyyykkkTo.',
      '.oooooooooooooo.',
    ],
  },
  castle: {
    palette: { o: OUTLINE, g: '#c4c0b4', G: '#8a867c', w: '#2a2440', d: WOOD },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '.....o.o.o......',
      '.....ooooo......',
      '.....oGgGo......',
      'o.o.oogwgoo.o.o.',
      'oooooogggoooooo.',
      'ogggooGgGoogggo.',
      'oGwGoogggooGwGo.',
      'ogggoogggoogggo.',
      'ogggoogdgoogggo.',
      'oGggoodddooggGo.',
      'ogggoodddoogggo.',
      'oGgGoodddooGgGo.',
      'ooooooooooooooo.',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const CASTLE_TINTS = {
  halberdier: '#e8c860',
  marksman: '#3a8a3a',
  royalGriffin: '#f0c040',
  crusader: '#f0d070',
  zealot: '#f0e0a0',
  champion: '#f0c040',
  archangel: '#ffb000',
} satisfies Partial<Record<UpgradedCreature, string>>
