import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, DARK_STEEL, WOOD, BOOTS, GOLD, type Sprite } from './shared'

/** Castle: its creatures, heroes, town emblem and homeland obstacles. */
export const CASTLE_SPRITES = {
  pikeman: {
    palette: { o: OUTLINE, s: SKIN, m: STEEL, M: DARK_STEEL, w: WOOD, b: BOOTS },
    pixels: [
      '............o...',
      '...........omo..',
      '...........omo..',
      '....oooo...owo..',
      '...ommmmo..owo..',
      '..ommmmmmo.owo..',
      '..oMMMMMMMoowo..',
      '..oMssssosoowo..',
      '...ossssssoowo..',
      '..oTTTTTTToowo..',
      '.omTTTTTTossso..',
      '.omTTTTTTo.owo..',
      '..otTTTTto.owo..',
      '..ottttto..owo..',
      '..obo..obo.owo..',
      '..obbo.obbooooo.',
    ],
  },
  archer: {
    palette: { o: OUTLINE, s: SKIN, h: '#6b4a2a', l: '#5a3a1e', w: WOOD, b: BOOTS },
    pixels: [
      '................',
      '.....oooo.......',
      '....ohhhho......',
      '...ohhhhhho.....',
      '...ohhsssso.....',
      '...ohhssoso.....',
      '...ohhsssso...o.',
      '....ohhsso...owo',
      '...oTTTTTToooowo',
      '..oTTTTTssllllwo',
      '..oTTTTTTooooowo',
      '..otTTTTto...owo',
      '..ottttto.....o.',
      '...obo.obo......',
      '...obo.obo......',
      '...obbo.obbo....',
    ],
  },
  griffin: {
    palette: {
      o: OUTLINE,
      f: '#f0ead8',
      g: '#c8902e',
      G: '#8a5a1e',
      y: '#f0b020',
      w: '#6a3e1c',
      W: '#a8743c',
    },
    pixels: [
      '................',
      '.oo........ooo..',
      '.oWo......offfo.',
      '.oWWwo...offofo.',
      '..oWWwo.offffyyo',
      '..oWWWwoofffoyo.',
      'o..oWWWwofffo...',
      '.o.oWWWWwffo....',
      '.o.oTTTTTwffo...',
      '.ooggTTTTTggggo.',
      '..ogggggggggggo.',
      '..oGgggggggggGo.',
      '..oGGoGo..oyoyo.',
      '..oGGoGo..oyoyo.',
      '..oGGoGo..oyoyo.',
      '..oooooo..ooooo.',
    ],
  },
  swordsman: {
    palette: { o: OUTLINE, s: SKIN, m: STEEL, M: DARK_STEEL, y: '#e0b030', b: BOOTS },
    pixels: [
      '..o.............',
      '.omo............',
      '.omo..oooo......',
      '.omo.ommmmo.....',
      '.omo.ommMMo.....',
      '.omo.ommmmo.....',
      'oyyyo.ommmoooooo',
      '.oso.oMmmmoTyTto',
      '.ossooMmmmoyyyto',
      '..o..oMmmmoTyTto',
      '.....oMmmmoTyTto',
      '.....oMMMMoTTTto',
      '.....oMo.oMotto.',
      '.....oMo.oMoo...',
      '.....obo.obo....',
      '.....obbo.obbo..',
    ],
  },
  monk: {
    palette: {
      o: OUTLINE,
      s: SKIN,
      r: '#ece8dc',
      R: '#b8b0a0',
      w: WOOD,
      y: '#fff6b0',
      Y: '#f0c040',
    },
    pixels: [
      '............ooo.',
      '...........oyyyo',
      '.....ooo...oyyyo',
      '....orrro...oYo.',
      '...orrrsso..owo.',
      '...orrsoso..owo.',
      '...orrssso..owo.',
      '..orrrrTro..owo.',
      '..orRrrTrrossso.',
      '..orRrrTrro.owo.',
      '..oRRrrtrro.owo.',
      '.oRRrrrtrro.owo.',
      '.oRRrrrtrrroowo.',
      'oRRRrrrtrrrrowo.',
      'oRRRRrrtrrrrowo.',
      '.ooooooooooo.o..',
    ],
  },
  cavalier: {
    palette: {
      o: OUTLINE,
      h: '#d8d0c4',
      m: STEEL,
      M: DARK_STEEL,
      w: '#c8a060',
      b: BOOTS,
      s: SKIN,
    },
    pixels: [
      '....oo.........m',
      '...oTTo.......w.',
      '...ommmo.....w..',
      '...omMMo....w...',
      '...ommmo...woo..',
      '..oTTTTTo.wohho.',
      '..oTTTTTsw.ohoho',
      '..otTTTto.ohhhho',
      '.ooooooooohhooo.',
      'oTTTTMTTTThho...',
      'oTTTTMTTTTTo....',
      'otTTTTTTTTto....',
      'otttttttttto....',
      '.ohoho....ohoho.',
      '.ohoho....ohoho.',
      '.obobo....obobo.',
    ],
  },
  angel: {
    palette: { o: OUTLINE, s: SKIN, h: GOLD, w: '#f4f4f8', W: '#c8ccd8', m: STEEL, y: '#fff4b0' },
    pixels: [
      '.....yyyy.......',
      'oo..oooooo......',
      'owo.ohhhho......',
      'owwoohssso......',
      'oWwwohssso....o.',
      '.oWwwossso...omo',
      '.oWwwoTTTToo.omo',
      '..oWwTTTTTssoomo',
      '..oWwTTTTToooomo',
      '...oWtTTTto..oho',
      '....owTTTTo.oooo',
      '....owTTTTTo....',
      '....owwTTTTo....',
      '.....owtttto....',
      '......owwwwo....',
      '......oooooo....',
    ],
  },
  rock: {
    palette: { o: OUTLINE, l: '#b4b4b8', g: '#8a8a8e', G: '#5e5e62', d: '#3e3e44' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oollllgoo...',
      '...ollllggggo...',
      '..ollgllgggggo..',
      '..olggggggggGo..',
      '.oolgggggggGGo..',
      '.olgggggggGGGGo.',
      '.oggggggGGGGdGo.',
      '.oGgggGGGGGdddo.',
      '.oGGGGGGGGddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  tree: {
    palette: {
      o: OUTLINE,
      l: '#5aa040',
      g: '#3a7a2a',
      G: '#245018',
      b: '#7a4e2a',
      B: '#4a2e18',
    },
    pixels: [
      '.....oooooo.....',
      '...oollllggo....',
      '..olllllggggo...',
      '.ollllgllgggGo..',
      '.olllggggggGGo..',
      'ollgggggggggGGo.',
      'olggglgggggGGGo.',
      'oggggggggGGGGGo.',
      '.oGgggggGGGGGo..',
      '..oGGGGoGGGGo...',
      '...oooobBoooo...',
      '......obBo......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '.....oooooo.....',
    ],
  },
  tyris: {
    palette: { o: OUTLINE, M: STEEL, N: DARK_STEEL, d: '#141018' },
    pixels: [
      '.......TT.......',
      '......TTtT......',
      '.....oooooo.....',
      '....oMMMMMMo....',
      '...oMMMMMMMNo...',
      '...oMMMMMMMNo...',
      '...oMddddddNo...',
      '...oMMMMMMMNo...',
      '...oMMdMMdMNo...',
      '...oMMMMMMMNo...',
      '....oMMMMMNo....',
      '..ooMMMMMMMMoo..',
      '.oMMTTTTTTTTMMo.',
      '.oMTTTTTTTTTTMo.',
      '.oMTTTTttTTTTMo.',
      '.oooooooooooooo.',
    ],
  },
  edric: {
    palette: { o: OUTLINE, M: STEEL, N: DARK_STEEL, d: '#141018', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oMMMMMMo....',
      '...oMMMMMMMNo...',
      '...oMMMMMMMNo...',
      '...oMddddddNo...',
      '...oMMMddMMNo...',
      '...oMMMddMMNo...',
      '...oMMMMMMMNo...',
      '...oyyyyyyyyo...',
      '....oooooooo....',
      '..ooMMMMMMMMoo..',
      '.oMMTTTTTTTTMMo.',
      '.oMTTTTyyTTTTMo.',
      '.oMTTTyyyyTTTMo.',
      '.oooooooooooooo.',
    ],
  },
  adela: {
    palette: { o: OUTLINE, k: '#1e1a22', w: '#f0ece0', s: SKIN, e: OUTLINE, v: '#3a3440', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....okkkkkko....',
      '...okkkkkkkko...',
      '...okwwwwwwko...',
      '...okwessewko...',
      '...okwvvvvwko...',
      '...okwvvvvwko...',
      '...okwwvvwwko...',
      '...okkwwwwkko...',
      '...okkkkkkkko...',
      '..ookkkkkkkkoo..',
      '.oTkkkkkkkkkkTo.',
      '.oTkkkkyykkkkTo.',
      '.oTkkkyyyykkkTo.',
      '.oooooooooooooo.',
    ],
  },
  castle: {
    palette: { o: OUTLINE, g: '#c4c0b4', G: '#8a867c', w: '#2a2440', d: WOOD },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '.....o.o.o......',
      '.....ooooo......',
      '.....oGgGo......',
      'o.o.oogwgoo.o.o.',
      'oooooogggoooooo.',
      'ogggooGgGoogggo.',
      'oGwGoogggooGwGo.',
      'ogggoogggoogggo.',
      'ogggoogdgoogggo.',
      'oGggoodddooggGo.',
      'ogggoodddoogggo.',
      'oGgGoodddooGgGo.',
      'ooooooooooooooo.',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const CASTLE_TINTS = {
  halberdier: '#e8c860',
  marksman: '#3a8a3a',
  royalGriffin: '#f0c040',
  crusader: '#f0d070',
  zealot: '#f0e0a0',
  champion: '#f0c040',
  archangel: '#ffb000',
} satisfies Partial<Record<UpgradedCreature, string>>
