import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, DARK_STEEL, WOOD, BOOTS, GOLD, type Sprite } from './shared'

/** Castle: its creatures, heroes, town emblem and homeland obstacles. */
export const CASTLE_SPRITES = {
  pikeman: {
    palette: { o: OUTLINE, s: SKIN, m: STEEL, M: DARK_STEEL, w: WOOD, b: BOOTS },
    pixels: [
      '................',
      '................',
      '................',
      '....oooo........',
      '...ommmmo.......',
      '..ommmmmmo......',
      '..oMMMMMMMo.....',
      '..oMssssoso....o',
      '...osssssso..oom',
      '..oTTTTTTTooowwo',
      '.omTTTTTTosswoo.',
      '.omTTTTTTo.oo...',
      '.ootTTTTto......',
      'owottttto.......',
      'woobo..obo......',
      'o.obbo.obbo.....',
    ],
  },
  archer: {
    palette: { o: OUTLINE, s: SKIN, k: '#2a2024', h: '#6b4a2a', m: '#c8d0d8', M: DARK_STEEL, l: '#7a5530', L: '#5a3a1e', q: '#4a3020', f: '#ece4cc', b: BOOTS, w: WOOD, S: '#e8e0c8' },
    pixels: [
      '.....oooo.......',
      '....ommmmo......',
      '...ommmmmmo.....',
      '...oMMMMMMMo....',
      '....ohsskoo..o..',
      '....ohssso..oMo.',
      '....oossoo.oSMo.',
      '...oTTTTlloSoMoo',
      '..ooTTTTwswswwwm',
      '.offTTTTTooSoMoo',
      '..oqTtttto.oSMo.',
      '..oqllllllo.oMo.',
      '..oqoLooLo...o..',
      '...ooLooLo......',
      '....oLooLo......',
      '...obboobbo.....',
    ],
  },
  griffin: {
    palette: { o: OUTLINE, g: '#c8963c', G: '#9a6a28', w: '#ece6d6', W: '#b8b0a0', y: '#e8b030', f: '#a8742c', F: '#7a4e1c', k: OUTLINE },
    pixels: [
      '.....o.o........',
      '...ooFoFo.......',
      '..oFffffo.......',
      '..offffffo......',
      '.offffffffoooo..',
      '.oofFfFfFowwkwo.',
      'oFooffffoowwwwyo',
      'oGooogggggWWwwyy',
      '.oGgggggggTToooo',
      '..ogggggggggo...',
      '..ogggggggggo...',
      '...oGGggGGyo....',
      '...oGoGoooyo....',
      '...oGoGo..oyo...',
      '..oGGoGGo.oyyo..',
      '...oo.oo...oo...',
    ],
  },
  swordsman: {
    palette: { o: OUTLINE, m: STEEL, M: '#7a848e', n: '#4e5864', k: '#141018', b: '#e6ecf2', y: '#e0b840' },
    pixels: [
      '................',
      '.....ooo......o.',
      '....oTTmo....obo',
      '...oTmmmmo..obo.',
      '....ommmkkoobo..',
      '..ooommmmoybo...',
      '.oTTommmoomyo...',
      'oTTTTmmmmmoo....',
      'oTTyTmmmmo......',
      'oTyyymTTmo......',
      'oTTyTmTTmo......',
      'oTTyTnnnnno.....',
      '.oTToMooMo......',
      '..oooMooMo......',
      '....oMooMo......',
      '...onnoonno.....',
    ],
  },
  monk: {
    palette: { o: OUTLINE, r: '#9a7448', R: '#6a4c2c', h: '#c09868', k: '#1a1008', f: '#5a3e22' },
    pixels: [
      '.......o........',
      '......oroo......',
      '.....oRrrro.....',
      '....orrrkkho....',
      '....orrrkko.....',
      '....oRrrkko.....',
      '....oRrrro......',
      '...oRoRrrhoo....',
      '....ooRhhhhko...',
      '....oRrrRRRko...',
      '....oRrrrhoo....',
      '....oTTTTTTo....',
      '....oRrRrtho....',
      '...oRrrRrtho....',
      '...oRrrRrrho....',
      '....offooffo....',
    ],
  },
  cavalier: {
    palette: { o: OUTLINE, H: '#ecece8', h: '#a8aab0', m: '#8a8e96', e: '#1a1410', n: '#c8b8b0', k: '#2a2024', M: '#c0c8d0', w: '#8a5a2b' },
    pixels: [
      '........oTooowTToo......',
      '.......oTMMMowTooHo.....',
      '........oMkkowomHHHo....',
      '........oMMMowmoHHeHo...',
      '........oMMoowmHHHHHHo..',
      '.......oMTTMMMoHHHHHHno.',
      '...oooooMTTMowHHHHHHHno.',
      '..omHHHTTMMTHwHHHHoooo..',
      '.omHHHTTTTMTTwHHHo......',
      'ommHHHTTTTMTTwHHHo......',
      'ommHHHttttMMtHHHHo......',
      'omooHHhhhhhhhhHHo.......',
      '.omoHHohoooooHHoho......',
      '..o.oHoho....oHoho......',
      '....oHoho....oHoho......',
      '....okoko....okoko......',
    ],
  },
  angel: {
    palette: { o: OUTLINE, w: '#ffffff', W: '#b8c4d8', r: '#f0e0b0', R: '#c8b078', y: '#e0b840', s: '#f0c8a0', h: '#f0d060', k: '#2a2024', b: '#e6ecf2' },
    pixels: [
      '..oooo.......o..',
      '.owwWwo.oo..obo.',
      'owWwwwWohho.obo.',
      'oWwwwwWhsskoobo.',
      'owwwwwWhsso.obo.',
      'oWwwwwWhsso.obo.',
      'owwwwwWoooooybyo',
      '.oWwwwWrrrrrsoo.',
      '.owwwwWTTTTooyo.',
      '..oWoorrrrro.o..',
      '...o.orrrrro....',
      '.....orrrrro....',
      '.....orRrrro....',
      '......oRrro.....',
      '......oRrro.....',
      '.....oyyyyyo....',
    ],
  },
  rock: {
    palette: { o: OUTLINE, l: '#b4b4b8', g: '#8a8a8e', G: '#5e5e62', d: '#3e3e44' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oollllgoo...',
      '...ollllggggo...',
      '..ollgllgggggo..',
      '..olggggggggGo..',
      '.oolgggggggGGo..',
      '.olgggggggGGGGo.',
      '.oggggggGGGGdGo.',
      '.oGgggGGGGGdddo.',
      '.oGGGGGGGGddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  tree: {
    palette: {
      o: OUTLINE,
      l: '#5aa040',
      g: '#3a7a2a',
      G: '#245018',
      b: '#7a4e2a',
      B: '#4a2e18',
    },
    pixels: [
      '.....oooooo.....',
      '...oollllggo....',
      '..olllllggggo...',
      '.ollllgllgggGo..',
      '.olllggggggGGo..',
      'ollgggggggggGGo.',
      'olggglgggggGGGo.',
      'oggggggggGGGGGo.',
      '.oGgggggGGGGGo..',
      '..oGGGGoGGGGo...',
      '...oooobBoooo...',
      '......obBo......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '.....oooooo.....',
    ],
  },
  tyris: {
    palette: { o: OUTLINE, M: STEEL, N: DARK_STEEL, d: '#141018' },
    pixels: [
      '.......TT.......',
      '......TTtT......',
      '.....oooooo.....',
      '....oMMMMMMo....',
      '...oMMMMMMMNo...',
      '...oMMMMMMMNo...',
      '...oMddddddNo...',
      '...oMMMMMMMNo...',
      '...oMMdMMdMNo...',
      '...oMMMMMMMNo...',
      '....oMMMMMNo....',
      '..ooMMMMMMMMoo..',
      '.oMMTTTTTTTTMMo.',
      '.oMTTTTTTTTTTMo.',
      '.oMTTTTttTTTTMo.',
      '.oooooooooooooo.',
    ],
  },
  edric: {
    palette: { o: OUTLINE, M: STEEL, N: DARK_STEEL, d: '#141018', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oMMMMMMo....',
      '...oMMMMMMMNo...',
      '...oMMMMMMMNo...',
      '...oMddddddNo...',
      '...oMMMddMMNo...',
      '...oMMMddMMNo...',
      '...oMMMMMMMNo...',
      '...oyyyyyyyyo...',
      '....oooooooo....',
      '..ooMMMMMMMMoo..',
      '.oMMTTTTTTTTMMo.',
      '.oMTTTTyyTTTTMo.',
      '.oMTTTyyyyTTTMo.',
      '.oooooooooooooo.',
    ],
  },
  adela: {
    palette: { o: OUTLINE, k: '#1e1a22', w: '#f0ece0', s: SKIN, e: OUTLINE, v: '#3a3440', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....okkkkkko....',
      '...okkkkkkkko...',
      '...okwwwwwwko...',
      '...okwessewko...',
      '...okwvvvvwko...',
      '...okwvvvvwko...',
      '...okwwvvwwko...',
      '...okkwwwwkko...',
      '...okkkkkkkko...',
      '..ookkkkkkkkoo..',
      '.oTkkkkkkkkkkTo.',
      '.oTkkkkyykkkkTo.',
      '.oTkkkyyyykkkTo.',
      '.oooooooooooooo.',
    ],
  },
  castle: {
    palette: { o: OUTLINE, g: '#c4c0b4', G: '#8a867c', w: '#2a2440', d: WOOD },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '.....o.o.o......',
      '.....ooooo......',
      '.....oGgGo......',
      'o.o.oogwgoo.o.o.',
      'oooooogggoooooo.',
      'ogggooGgGoogggo.',
      'oGwGoogggooGwGo.',
      'ogggoogggoogggo.',
      'ogggoogdgoogggo.',
      'oGggoodddooggGo.',
      'ogggoodddoogggo.',
      'oGgGoodddooGgGo.',
      'ooooooooooooooo.',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const CASTLE_TINTS = {
  halberdier: '#e8c860',
  marksman: '#3a8a3a',
  royalGriffin: '#f0c040',
  crusader: '#f0d070',
  zealot: '#f0e0a0',
  champion: '#f0c040',
  archangel: '#ffb000',
} satisfies Partial<Record<UpgradedCreature, string>>

/** Upgrades that look different enough to need their own drawing rather than a tint of the base creature. */
export const CASTLE_UPGRADE_SPRITES = {
  // The Halberdier trades the pike for an axe-headed halberd and the tunic for plate, under a crested helm.
  halberdier: {
    palette: { o: OUTLINE, s: SKIN, m: STEEL, M: DARK_STEEL, w: WOOD, y: GOLD },
    pixels: [
      '............o...',
      '...........omo..',
      '.....oo....omooo',
      '....oyyo...owmmo',
      '...oommmo..owmMo',
      '..ommmmmmo.owmMo',
      '..oMMMMMMMoowooo',
      '..oMssssoso.owo.',
      '...osssssso.owo.',
      '..oommTTTmmosso.',
      '.ommmmTTTmmmsso.',
      '.oMmmoTTTo.owo..',
      '..oMotTTto.owo..',
      '..omMoooMmoowo..',
      '..omMo.oMmo.oo..',
      '.oMMMo.oMMMo....',
    ],
  },
  // The Marksman swaps the kettle helm for a plumed hat and carries a steel-limbed crossbow.
  marksman: {
    palette: { o: OUTLINE, s: SKIN, k: '#2a2024', h: '#6b4a2a', g: '#2e6a3a', G: '#1e4628', W: '#f4f0e4', y: GOLD, m: '#c8d0d8', M: DARK_STEEL, l: '#7a5530', L: '#5a3a1e', q: '#4a3020', f: '#ece4cc', b: BOOTS, w: WOOD, S: '#e8e0c8' },
    pixels: [
      '.oo...ooo.......',
      'oWWo.oggGo......',
      '.oWWoyyyyGo.....',
      '..ooGGGGGGGGo...',
      '....ohsskoo..o..',
      '....ohssso..oMo.',
      '....oossoo.oSMo.',
      '...oTTTTlloSoMoo',
      '..ooTTTTmsmsmmmm',
      '.offTTTTTooSoMoo',
      '..oqTyyyto.oSMo.',
      '..oqllllllo.oMo.',
      '..oqoLooLo...o..',
      '...ooLooLo......',
      '....oLooLo......',
      '...obboobbo.....',
    ],
  },
  // The Crusader drops the shield to fight with a sword in each hand, in a white tabard with a red cross.
  crusader: {
    palette: { o: OUTLINE, m: STEEL, M: '#7a848e', n: '#4e5864', k: '#141018', b: '#e6ecf2', y: '#e0b840', w: '#ece8dc', r: '#c02020' },
    pixels: [
      '.....oo.......o.',
      '....orroo....obo',
      'o...oorrmo..obo.',
      'obo.ommmmmo.obo.',
      '.obo.ommkkoobo..',
      '..oyommmmoybo...',
      '..omyowwwoomyo..',
      '..ommwwrwwmoo...',
      '..omwwrrrwwo....',
      '...owwwrwwwo....',
      '...owwwrwwwo....',
      '...oTTTTTTTo....',
      '...owwwwwwwo....',
      '....oMooMo......',
      '....oMooMo......',
      '...onnoonno.....',
    ],
  },
  // The Champion rides a fully barded horse: a steel chanfron and crinet over a long, gold-hemmed caparison.
  champion: {
    palette: { o: OUTLINE, H: '#ecece8', h: '#a8aab0', m: '#c0c8d0', e: '#1a1410', n: '#c8b8b0', k: '#2a2024', M: '#c0c8d0', w: '#8a5a2b', y: GOLD },
    pixels: [
      '........oTToowTToo......',
      '.......oTMMMowTooHo.....',
      '........oMkkowommmmo....',
      '........oMMMowmoHmemo...',
      '........oMMoowmmmmmHHo..',
      '.......oMTTMMMoHHHHHHno.',
      '...oooooMTTMowHHHHHHHno.',
      '..omTTTTTyyTTwHHHHoooo..',
      '.omTTTTTTTMTTwTTHo......',
      'ommTTTTTTTMTTwTTHo......',
      'ommTTTTTTTMMTTTTHo......',
      'omooyyyyyyyyyyyyo.......',
      '.omoHHohoooooHHoho......',
      '..o.oHoho....oHoho......',
      '....oHoho....oHoho......',
      '....okoko....okoko......',
    ],
  },
  // The Archangel spreads larger wings and wears gold over a red robe, raising a flaming sword.
  archangel: {
    palette: { o: OUTLINE, w: '#ffffff', W: '#b8c4d8', r: '#c83030', R: '#8a1e1e', y: GOLD, Y: '#b08820', s: '#f0c8a0', h: '#f0d060', k: '#2a2024', f: '#ff8020', F: '#ffe060' },
    pixels: [
      'oo....oWWo...o..',
      'owooooWwwWo.oFo.',
      'owwWwwohhoo.oFfo',
      'oWwwwwWhsskooFfo',
      'owwwwwWhsso.oFfo',
      'oWwwwwWhsso.oFfo',
      'owwwwwWoooooyyyo',
      'oWwwwwWyyyyysoo.',
      'owwwwwWyTTyoyo..',
      'oWwwwWoyyyyo.o..',
      '.owwWorrrrro....',
      '..oWo.orrrrro...',
      '...o..orRrrro...',
      '......orRrrro...',
      '......oRrrrro...',
      '.....oYyyyyyYo..',
    ],
  },
  // The Zealot wears the Monk's habit in dark blue, trimmed with gold.
  zealot: {
    palette: { o: '#0e1228', r: '#2c3e86', R: '#1a2656', h: '#4a62b0', k: '#0a0c1a', f: '#5a3e22', y: '#e6b43c' },
    pixels: [
      '.......o........',
      '......oroo......',
      '.....oRrrro.....',
      '....orrrkkyo....',
      '....orrrkko.....',
      '....oRrrkko.....',
      '....oRrrro......',
      '...oRoRrrhoo....',
      '....ooRhhhyko...',
      '....oRrrRRyko...',
      '....oRrrrhoo....',
      '....oTTTTTTo....',
      '....oRrRrtho....',
      '...oRrrRrtho....',
      '...oyyyyyyyo....',
      '....offooffo....',
    ],
  },
} satisfies Partial<Record<UpgradedCreature, Sprite>>
