import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, GOLD, type Sprite } from './shared'

/** Conflux: its creatures, heroes, town emblem and homeland obstacles. */
export const CONFLUX_SPRITES = {
  pixie: {
    palette: { o: '#2a1a2a', s: '#f0c8a8', h: '#f080c0', k: '#2a1a2a', w: '#c8e8ff', W: '#a0c8f0', v: '#f0a0d0', y: '#fff0a0' },
    pixels: [
      '................',
      '................',
      '....oooo........',
      '...owwwwoo......',
      '...owvwwhho.....',
      '...owwwhhsko....',
      '....owwhssooy...',
      '....oWWoTTsso...',
      '....oWvWTToo....',
      '....oWWoTTo.....',
      '.....oo.oso.....',
      '.......oso......',
      '....y...o.......',
      '......y.........',
      '...y............',
      '.......y........',
    ],
  },
  airElemental: {
    palette: { o: '#1e2a44', a: '#c8e0f4', A: '#8ab0d8', W: '#f4fbff', e: '#ffffff' },
    pixels: [
      '................',
      '.....o.oo.......',
      '....oAoaao......',
      '...oAAaaaeo.....',
      '....ooaaaao...a.',
      '....oaaaao..oo..',
      '....oaWaaoooaao.',
      '...oAaaaaaaaoo..',
      '..oAoaaTaooo....',
      '...ooaaaaoo.....',
      '...oaAaaAaao..a.',
      '..a.oaaAaaAo.A..',
      '.A..oaAaaAo.....',
      '.....oaaAao.....',
      '......oAao......',
      '......oao.......',
    ],
  },
  waterElemental: {
    palette: { o: '#142446', b: '#3a7ad0', B: '#a0d0ff', d: '#24508a', f: '#e8f6ff', e: '#ffffff' },
    pixels: [
      '................',
      '......oooo......',
      '.....obbbbo.....',
      '....odbbbeo.....',
      '....odbbbbo.....',
      '...odbbbbo.oo..B',
      '..B.obBbboobboo.',
      '...obbBbbbboobfo',
      '...odbBbbbo..oo.',
      '.BodobbTbo..oo..',
      '...oobbbbo.offo.',
      '....oobbooooBBo.',
      '..oobbbbbbbooBo.',
      '.obfbbfbbbfbbo..',
      '.obbbbbbbbbbbo..',
      '.obbbbbbbbbbbo..',
    ],
  },
  fireElemental: {
    palette: { o: '#4a1206', f: '#ffb030', y: '#fff0a0', r: '#e04010' },
    pixels: [
      '....yoroo.......',
      '....orrryo......',
      '....ooryfo......',
      '...orrffyo......',
      '....oofffo.oo...',
      '...r.ooooooyyor.',
      '....offfoffyyo..',
      '...offfyfoooo.r.',
      '..yofffyfo......',
      '...offyTfo......',
      '....ooffo.......',
      '...r.ofofo......',
      '.....ofofo......',
      '....ofo.ofo.....',
      '....ofo.ofo.....',
      '...orro.orro....',
    ],
  },
  earthElemental: {
    palette: { o: OUTLINE, e: '#8a6a44', E: '#5e4630', k: '#3a2a1c', g: '#6a9a3a', y: '#ffd060' },
    pixels: [
      '................',
      '................',
      '.........ooo....',
      '...oooo.oeeeo...',
      '..oeggeoggeyo...',
      '..oeeeeeeeeo....',
      '...oeekeeeeo....',
      '..oEeeeeekoeo...',
      '.oEeeeeeeeeoeo..',
      '.oEokeeeTeooeo..',
      '.oEoekeeeeooeo..',
      'oEEEoEEEEo.oEEo.',
      '.oEooEoooEoEEEo.',
      '..o.oEo.oEoEEEo.',
      '....oEo.oEoooo..',
      '...oEEo.oEEo....',
    ],
  },
  psychicElemental: {
    palette: { o: '#1e1240', p: '#6a4ab0', P: '#4a3080', m: '#b8b8d8', M: '#7a7aa0', k: '#1e1240', w: '#e8e0ff' },
    pixels: [
      '.....oMMMo......',
      '.....ommmo......',
      '....ommmmmo.....',
      '....oMmmkwo.w...',
      '....oMmmmo......',
      '....opppTpo.....',
      '.w.opppppppo....',
      '...opPppPppo....',
      '...opPppPppo.w..',
      '..oppPppPppo....',
      '..oppPppPpppo...',
      '..oppPppPpppo...',
      '.opppPppPpppo...',
      '.opppPppPppppo..',
      '.opppPppPppppo..',
      '..oPoPoPoPoPo...',
    ],
  },
  firebird: {
    palette: { o: '#3a1206', f: '#f0a020', y: '#ffe080', r: '#d04020', k: '#4a1a0a' },
    pixels: [
      '....ooooooo.....',
      '...orfrfrrro....',
      '..orfffffrrooo..',
      '..offfffffrorro.',
      '..ofyyffffrrffoo',
      '...oofyyoroffkyy',
      '.....oooooofoooo',
      '.....offffffo...',
      '.....offfTfo....',
      '....ooffyyyo....',
      '..oorroooko.....',
      'forrofo..oko....',
      'oroofo....o.....',
      'roofo...........',
      'oofo............',
      '..o.............',
    ],
  },
  monere: {
    palette: { o: OUTLINE, s: SKIN, S: '#b88860', h: '#5a3a8a', H: '#3a2060', y: '#80e0ff', g: GOLD },
    pixels: [
      '......oooo......',
      '.....ohhhho.....',
      '....ohhhhhHo....',
      '...ohhhgghhHo...',
      '...ohhoooohHo...',
      '...ohosssSoHo...',
      '...ohoysySoHo...',
      '...ohossssoHo...',
      '...ohoSssSoHo...',
      '...ohhoSSohHo...',
      '....ohhoohHo....',
      '..oohhhhhhhHoo..',
      '.ohhTTTggTTTHHo.',
      '.ohTTTTggTTTTHo.',
      '.ohTTTTttTTTTHo.',
      '.oooooooooooooo.',
    ],
  },
  erdamon: {
    palette: { o: OUTLINE, s: SKIN, S: '#b88860', b: '#7a5030', B: '#4a3018', e: '#9a8060', E: '#6a5a40', y: '#80c040' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '...obbbbbbbBo...',
      '...obsssssbBo...',
      '...osossosSBo...',
      '...ossssssSBo...',
      '...obsssssbBo...',
      '...obbsSSbbBo...',
      '...obbbbbbbBo...',
      '....obbbbbBo....',
      '..ooeobbbBoeoo..',
      '.oeeeoTTTToeeEo.',
      '.oeTTTTyyTTTTEo.',
      '.oeTTTTttTTTTEo.',
      '.oooooooooooooo.',
    ],
  },
  ciele: {
    palette: { o: OUTLINE, s: SKIN, h: '#4080d0', H: '#2a5098', g: GOLD, c: '#80e0ff', r: '#c04050' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhgcgghHo...',
      '...ohssssssHo...',
      '...ohsossosHo...',
      '...ohssssssHo...',
      '..ohhssrrsshHo..',
      '..ohhossssohHo..',
      '..ohhhossohhHo..',
      '..ohhhhooohhHo..',
      '.ohhhoTTTTohhHo.',
      '.ohhTTTTTTTTHHo.',
      '.ohTTTTccTTTTHo.',
      '.ohTTTTttTTTTHo.',
      '.oooooooooooooo.',
    ],
  },
  conflux: {
    palette: { o: OUTLINE, a: '#d0f0ff', p: '#b080e0', r: '#e05020', R: '#a03010', b: '#4080d0', B: '#2a5098', e: '#8a6a3a', E: '#5a4020', g: '#c4c0b4', G: '#8a867c' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......oao.......',
      '......oapo......',
      '..o...oapo...o..',
      '.oro..oapo..obo.',
      '.orRo.oapo.obBo.',
      '.orRo.oapo.obBo.',
      '.orRooaappoobBo.',
      '.orRooaappoobBo.',
      'ooooooooooooooo.',
      '.oeeeeggggeeeeo.',
      '..oeeEEgGEEeeo..',
      '....oeeEEeeo....',
      '......oooo......',
    ],
  },
  runestone: {
    palette: { o: OUTLINE, g: '#9a988c', G: '#6a685e', c: '#60e0ff', d: '#3a7a2a' },
    pixels: [
      '................',
      '................',
      '.....oooo.......',
      '....oggggo......',
      '...oggggGGo.....',
      '...ogcggGGo.....',
      '...ogcgcgGo.....',
      '...ogcccgGo.....',
      '...oggcggGo.....',
      '...ogggggGGo....',
      '...ogcgcgGGo....',
      '...oggcggGGo....',
      '..ogggcgggGGo...',
      '..oggggggGGGGo..',
      '.oddggggggGGGddo',
      '.ooooooooooooooo',
    ],
  },
  elementalShard: {
    palette: { o: OUTLINE, w: '#ffffff', a: '#d0f0ff', r: '#e05020', R: '#a03010', b: '#4080d0', B: '#2a5098', g: '#60c060', e: '#8a6a3a', s: '#2a2440' },
    pixels: [
      '.......oo.......',
      '......owao......',
      '......owaao.....',
      '.....owaaabo....',
      '.....orwabbo....',
      '....orrwabbbo...',
      '....orrwabbBo...',
      '...orrrRwbbbBo..',
      '...orrrRgbbbBo..',
      '....orRggggBo...',
      '....orggggeo....',
      '.....oggeeo.....',
      '......oeeo......',
      '.......oo.......',
      '................',
      '....ssssssss....',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const CONFLUX_TINTS = {
  sprite: '#ff90e0',
  stormElemental: '#6080ff',
  iceElemental: '#c0f0ff',
  energyElemental: '#ffe040',
  magmaElemental: '#ff5020',
  magicElemental: '#e060ff',
  phoenix: '#ffb020',
} satisfies Partial<Record<UpgradedCreature, string>>
