import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, GOLD, type Sprite } from './shared'

/** Conflux: its creatures, heroes, town emblem and homeland obstacles. */
export const CONFLUX_SPRITES = {
  pixie: {
    palette: { o: '#2a1a2a', s: '#f0c8a8', h: '#f080c0', k: '#2a1a2a', w: '#c8e8ff', W: '#a0c8f0', v: '#f0a0d0', y: '#fff0a0' },
    pixels: [
      '................',
      '................',
      '....oooo........',
      '...owwwwoo......',
      '...owvwwhho.....',
      '...owwwhhsko....',
      '....owwhssooy...',
      '....oWWoTTsso...',
      '....oWvWTToo....',
      '....oWWoTTo.....',
      '.....oo.oso.....',
      '.......oso......',
      '....y...o.......',
      '......y.........',
      '...y............',
      '.......y........',
    ],
  },
  airElemental: {
    palette: { o: '#1e2a44', a: '#c8e0f4', A: '#8ab0d8', W: '#f4fbff', e: '#ffffff' },
    pixels: [
      '................',
      '.....o.oo.......',
      '....oAoaao......',
      '...oAAaaaeo.....',
      '....ooaaaao...a.',
      '....oaaaao..oo..',
      '....oaWaaoooaao.',
      '...oAaaaaaaaoo..',
      '..oAoaaTaooo....',
      '...ooaaaaoo.....',
      '...oaAaaAaao..a.',
      '..a.oaaAaaAo.A..',
      '.A..oaAaaAo.....',
      '.....oaaAao.....',
      '......oAao......',
      '......oao.......',
    ],
  },
  waterElemental: {
    palette: { o: '#142446', b: '#3a7ad0', B: '#a0d0ff', d: '#24508a', f: '#e8f6ff', e: '#ffffff' },
    pixels: [
      '........................',
      '..........oooo..........',
      '.........obbbbo.........',
      '........odbbbeo.........',
      '........odbbbbo.........',
      '.......odbbbbo..oooo...B',
      '.....B.obBbbooooobbbboo.',
      '.......obbBbbbbbooooobfo',
      '.......odbBbbbo.....oo..',
      '.....BodobbTbo....oo....',
      '.......oobbbbo...offo...',
      '...oo...oobbooooooBBo...',
      '..obbo.oobbbbbbbbooBo...',
      '.obfbbobfbbfbbbfbbbo....',
      '.obbbbbbbbbbbbbbbbbbo...',
      '.obbbbbbbbbbbbbbbbbbbo..',
    ],
  },
  fireElemental: {
    palette: { o: '#4a1206', f: '#ffb030', y: '#fff0a0', r: '#e04010' },
    pixels: [
      '....yoroo.......',
      '....orrryo......',
      '....ooryfo......',
      '...orrffyo......',
      '....oofffo.oo...',
      '...r.ooooooyyor.',
      '....offfoffyyo..',
      '...offfyfoooo.r.',
      '..yofffyfo......',
      '...offyTfo......',
      '....ooffo.......',
      '...r.ofofo......',
      '.....ofofo......',
      '....ofo.ofo.....',
      '....ofo.ofo.....',
      '...orro.orro....',
    ],
  },
  earthElemental: {
    palette: { o: OUTLINE, e: '#8a6a44', E: '#5e4630', k: '#3a2a1c', g: '#6a9a3a', y: '#ffd060' },
    pixels: [
      '................',
      '................',
      '.........ooo....',
      '...oooo.oeeeo...',
      '..oeggeoggeyo...',
      '..oeeeeeeeeo....',
      '...oeekeeeeo....',
      '..oEeeeeekoeo...',
      '.oEeeeeeeeeoeo..',
      '.oEokeeeTeooeo..',
      '.oEoekeeeeooeo..',
      'oEEEoEEEEo.oEEo.',
      '.oEooEoooEoEEEo.',
      '..o.oEo.oEoEEEo.',
      '....oEo.oEoooo..',
      '...oEEo.oEEo....',
    ],
  },
  psychicElemental: {
    palette: { o: '#1e1240', p: '#6a4ab0', P: '#4a3080', m: '#b8b8d8', M: '#7a7aa0', k: '#1e1240', w: '#e8e0ff' },
    pixels: [
      '.....oMMMo......',
      '.....ommmo......',
      '....ommmmmo.....',
      '....oMmmkwo.w...',
      '....oMmmmo......',
      '....opppTpo.....',
      '.w.opppppppo....',
      '...opPppPppo....',
      '...opPppPppo.w..',
      '..oppPppPppo....',
      '..oppPppPpppo...',
      '..oppPppPpppo...',
      '.opppPppPpppo...',
      '.opppPppPppppo..',
      '.opppPppPppppo..',
      '..oPoPoPoPoPo...',
    ],
  },
  firebird: {
    palette: { o: '#3a1206', f: '#f0a020', y: '#ffe080', r: '#d04020', k: '#4a1a0a' },
    pixels: [
      '.....oooooooooo.........',
      '....orfrfrfrrrrro.......',
      '...orffffffffffrrroooo..',
      '...offfffffffffffrrorro.',
      '...ofyyyyyffffffffrrffoo',
      '....ofyyyyyyyffooroffkyy',
      '.....orfrfroooooooofoooo',
      '......o.offffffffffffo..',
      '........offfffTTfffo....',
      '.......oooffffyyyyyo....',
      '...oorrrrooooooooko.....',
      '.forrrofo........oko....',
      'orroofo...........o.....',
      'rroofo..................',
      'oofo....................',
      '..o.....................',
    ],
  },
  monere: {
    palette: { o: OUTLINE, s: SKIN, S: '#b88860', h: '#5a3a8a', H: '#3a2060', y: '#80e0ff', g: GOLD },
    pixels: [
      '......oooo......',
      '.....ohhhho.....',
      '....ohhhhhHo....',
      '...ohhhgghhHo...',
      '...ohhoooohHo...',
      '...ohosssSoHo...',
      '...ohoysySoHo...',
      '...ohossssoHo...',
      '...ohoSssSoHo...',
      '...ohhoSSohHo...',
      '....ohhoohHo....',
      '..oohhhhhhhHoo..',
      '.ohhTTTggTTTHHo.',
      '.ohTTTTggTTTTHo.',
      '.ohTTTTttTTTTHo.',
      '.oooooooooooooo.',
    ],
  },
  erdamon: {
    palette: { o: OUTLINE, s: SKIN, S: '#b88860', b: '#7a5030', B: '#4a3018', e: '#9a8060', E: '#6a5a40', y: '#80c040' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '...obbbbbbbBo...',
      '...obsssssbBo...',
      '...osossosSBo...',
      '...ossssssSBo...',
      '...obsssssbBo...',
      '...obbsSSbbBo...',
      '...obbbbbbbBo...',
      '....obbbbbBo....',
      '..ooeobbbBoeoo..',
      '.oeeeoTTTToeeEo.',
      '.oeTTTTyyTTTTEo.',
      '.oeTTTTttTTTTEo.',
      '.oooooooooooooo.',
    ],
  },
  ciele: {
    palette: { o: OUTLINE, s: SKIN, h: '#4080d0', H: '#2a5098', g: GOLD, c: '#80e0ff', r: '#c04050' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhgcgghHo...',
      '...ohssssssHo...',
      '...ohsossosHo...',
      '...ohssssssHo...',
      '..ohhssrrsshHo..',
      '..ohhossssohHo..',
      '..ohhhossohhHo..',
      '..ohhhhooohhHo..',
      '.ohhhoTTTTohhHo.',
      '.ohhTTTTTTTTHHo.',
      '.ohTTTTccTTTTHo.',
      '.ohTTTTttTTTTHo.',
      '.oooooooooooooo.',
    ],
  },
  conflux: {
    palette: { o: OUTLINE, a: '#d0f0ff', p: '#b080e0', r: '#e05020', R: '#a03010', b: '#4080d0', B: '#2a5098', e: '#8a6a3a', E: '#5a4020', g: '#c4c0b4', G: '#8a867c' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......oao.......',
      '......oapo......',
      '..o...oapo...o..',
      '.oro..oapo..obo.',
      '.orRo.oapo.obBo.',
      '.orRo.oapo.obBo.',
      '.orRooaappoobBo.',
      '.orRooaappoobBo.',
      'ooooooooooooooo.',
      '.oeeeeggggeeeeo.',
      '..oeeEEgGEEeeo..',
      '....oeeEEeeo....',
      '......oooo......',
    ],
  },
  runestone: {
    palette: { o: OUTLINE, g: '#9a988c', G: '#6a685e', c: '#60e0ff', d: '#3a7a2a' },
    pixels: [
      '................',
      '................',
      '.....oooo.......',
      '....oggggo......',
      '...oggggGGo.....',
      '...ogcggGGo.....',
      '...ogcgcgGo.....',
      '...ogcccgGo.....',
      '...oggcggGo.....',
      '...ogggggGGo....',
      '...ogcgcgGGo....',
      '...oggcggGGo....',
      '..ogggcgggGGo...',
      '..oggggggGGGGo..',
      '.oddggggggGGGddo',
      '.ooooooooooooooo',
    ],
  },
  elementalShard: {
    palette: { o: OUTLINE, w: '#ffffff', a: '#d0f0ff', r: '#e05020', R: '#a03010', b: '#4080d0', B: '#2a5098', g: '#60c060', e: '#8a6a3a', s: '#2a2440' },
    pixels: [
      '.......oo.......',
      '......owao......',
      '......owaao.....',
      '.....owaaabo....',
      '.....orwabbo....',
      '....orrwabbbo...',
      '....orrwabbBo...',
      '...orrrRwbbbBo..',
      '...orrrRgbbbBo..',
      '....orRggggBo...',
      '....orggggeo....',
      '.....oggeeo.....',
      '......oeeo......',
      '.......oo.......',
      '................',
      '....ssssssss....',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const CONFLUX_TINTS = {
  sprite: '#ff90e0',
  stormElemental: '#6080ff',
  iceElemental: '#c0f0ff',
  energyElemental: '#ffe040',
  magmaElemental: '#ff5020',
  magicElemental: '#e060ff',
  phoenix: '#ffb020',
} satisfies Partial<Record<UpgradedCreature, string>>

/** Upgrades that look different enough to need their own drawing rather than a tint of the base creature. */
export const CONFLUX_UPGRADE_SPRITES = {
  // The Sprite has green hair and two pairs of long dragonfly wings.
  sprite: {
    palette: { o: '#1a2a2a', s: '#f0c8a8', h: '#60c080', k: '#1a2a2a', w: '#d0fff0', W: '#90e0d0', v: '#80c0ff', y: '#fff0a0' },
    pixels: [
      '.ooo............',
      'owwwoo..........',
      'owvwwwo.........',
      '.oWwvwwooo......',
      '..oWwwwohho.....',
      '...oWWohhhso....',
      '....oohhhssko...',
      '..ooohhhssooy...',
      '.owwwoTTssso....',
      'owvwwWTTToo.....',
      '.oWWWoTTo.......',
      '..ooo.oso.......',
      '.....oso........',
      '....y.o.........',
      '..y.....y.......',
      '.....y..........',
    ],
  },
  // The Storm Elemental is a dark thundercloud crackling with lightning.
  stormElemental: {
    palette: { o: '#10141e', a: '#5a6478', A: '#363c50', W: '#8a94b0', e: '#fff8a0', y: '#ffe040' },
    pixels: [
      '....oo.ooo......',
      '...oAAoaaao.....',
      '..oAAaaaaaao....',
      '...oAAaaaaeo....',
      '....ooaaaaao..y.',
      '....oaaWaao..y..',
      '...oaaWaaaooaaoy',
      '..oAaaaaaaaaoyy.',
      '.oAAoaaTaooo..y.',
      '..oooaaaaoo..y..',
      '..y.oaAaaAao....',
      '.y..oaaAaaAo....',
      'yy..oaAaaAo..y..',
      '.y...oaaAao.y...',
      '......oAao.y....',
      '......oao.......',
    ],
  },
  // The Ice Elemental is built from pale blue crystal, standing on a mound of ice.
  iceElemental: {
    palette: { o: '#1a3050', i: '#c8ecff', I: '#88bce0', w: '#ffffff', e: '#2a6aa0' },
    pixels: [
      '.........o..o...........',
      '........owooiwo.........',
      '........oiwiiio.........',
      '........oIiiieo.........',
      '........oIiiiio.........',
      '.......oIiiiio..oooo...w',
      '.....w.oiwiiooooowiiwoo.',
      '.......oiiwiiiiioooooiwo',
      '.......oIiwiiio.....oo..',
      '.....wooIoiTio..........',
      '.......ooiiiio......ow..',
      '........ooiiooo....owio.',
      '..o.....oiiiiiiiiioowio.',
      '.owoiiwiiiiwiiiiwiiiiio.',
      '.oiiiiiiiiiiiiiiiiiiiio.',
      '.oIIIIIIIIIIIIIIIIIIIIo.',
    ],
  },
  // The Energy Elemental burns with blue-white energy instead of orange flame.
  energyElemental: {
    palette: { o: '#0e1a4a', f: '#70c8ff', y: '#f0faff', r: '#3060f0', p: '#c0a0ff' },
    pixels: [
      '..p.yoryo...p...',
      '...oryrryo......',
      '....orryfo......',
      '...orrffyo......',
      '....oofffo.oop..',
      '.p.r.ooooooyyor.',
      '....offfoffyyop.',
      '...offfyfoooo.r.',
      '..yofffyfo...p..',
      '.p.offyTfo......',
      '....ooffo....p..',
      '..pr.ofofo......',
      '.....ofofo......',
      '....ofo.ofo.....',
      '..p.ofo.ofo.p...',
      '...orro.orro....',
    ],
  },
  // The Magma Elemental is dark volcanic rock split by glowing lava cracks.
  magmaElemental: {
    palette: { o: '#140c08', e: '#4a3a34', E: '#2e2420', l: '#ff6020', y: '#ffd040' },
    pixels: [
      '................',
      '.........y......',
      '.........ooo....',
      '...oooo.oeeeo...',
      '..oellyolleyo...',
      '..oeeleeeeeo....',
      '...oeeleeeeo....',
      '..oEeeelleloeo..',
      '.oEeeeeeeleoeo..',
      '.oElleeeTeooelo.',
      '.oEoeleeeeoolo..',
      'oEElolEEEo.oEEo.',
      '.oEooEoooEoElEo.',
      '..o.olo.oEoEEEo.',
      '....oEo.oloooo..',
      '...olEo.oEEo....',
    ],
  },
  // The Magic Elemental shimmers in every color under its helmet and cloak.
  magicElemental: {
    palette: { o: '#1e1240', m: '#f0d870', M: '#b89a40', r: '#e04080', y: '#f0c040', g: '#40c080', b: '#4080e0', v: '#9050d0', k: '#1e1240', w: '#ffffff' },
    pixels: [
      '.....oMMMo......',
      '.....ommmo....y.',
      '....ommmmmo.....',
      '....oMmmkwo.w...',
      '....oMmmmo......',
      '....orrrTro.....',
      '.g.orrrrrrro..b.',
      '...oyyryyryo....',
      '...oyyygyyyo.w..',
      '..oggygggygo....',
      '..ogggbgggbgo...',
      '.r.obbbgbbbbo...',
      '.obbbvbbbvbbo...',
      '.ovvvbvvvvbvvo..',
      '.ovvvvrvvvvrvo..',
      '..oror.oror.o...',
    ],
  },
  // The Phoenix spreads both burning wings wide and trails a long fiery tail.
  phoenix: {
    palette: { o: '#3a1206', f: '#f0a020', y: '#ffe080', w: '#fff8e0', r: '#d04020', k: '#4a1a0a' },
    pixels: [
      'y.r..................r.y',
      'ryo..................oyr',
      'ofyo................oyfo',
      'offyyo............oyyffo',
      '.offfyyo...oo...oyyfffo.',
      '.offffffyoorroyffffffo..',
      '..ooffffffyfrrfyffffoo..',
      '....oofffffffffffoooooy.',
      '........offwfffffffofkyy',
      '........offffTTfffffooo.',
      '.......offyyyyyyffo.....',
      '....oorrrffffffoo.ko....',
      '..orryyrrroo.....ok.....',
      'oryyrrfoo...............',
      'ryyrofo.................',
      'y.r..r..................',
    ],
  },
} satisfies Partial<Record<UpgradedCreature, Sprite>>
