import type { UpgradedCreature } from '../../../game'
import { OUTLINE, STEEL, WOOD, BONE, GOLD, type Sprite } from './shared'

/** Dungeon: its creatures, heroes, town emblem and homeland obstacles. */
export const DUNGEON_SPRITES = {
  troglodyte: {
    palette: { o: OUTLINE, s: '#7a8aa8', S: '#4e5a74', b: '#a8b4c8', y: '#8a6a3a', m: '#c8d0d8', w: '#efe7cf', k: '#1a1418' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '........ooo.....',
      '.......oSSsoo...',
      '.....ooossssko..',
      '....ossssssssooo',
      '...osssssoowyymm',
      '...ossssssyyoooo',
      '...osssbbooo....',
      '..oSoTTTTo......',
      '.oSooSttSo......',
      'oSooSooooSo.....',
      '.o.oSo..oSo.....',
      '..oSSo..oSSo....',
    ],
  },
  harpy: {
    palette: { o: OUTLINE, f: '#6a5444', F: '#40322a', s: '#e0c0a0', h: '#2a1e1a', y: '#d8a040', k: '#1a1418' },
    pixels: [
      '....oo..........',
      '...oFFoooo......',
      '..oFFFFhhho.....',
      '.oFFFFfhssko....',
      '.oFFffhfsso.....',
      '..oFfffffo......',
      '.oFofffffo......',
      '..o.offfTso.....',
      '.....oosso......',
      '.....offffo.....',
      '.....offffo.....',
      '......offo......',
      '......oyoyo.....',
      '......oyoyo.....',
      '.....oyoyoyo....',
      '......o.o.o.....',
    ],
  },
  beholder: {
    palette: { o: OUTLINE, p: '#c88a78', P: '#8a5a50', w: '#f0ece0', g: '#60c060', k: '#1a1418' },
    pixels: [
      '.....o...o......',
      '....oPo.oPo.og..',
      '.....oPoPo.oPo..',
      '....oopppooPo...',
      '...opppppppo....',
      '..oppppppwwpo...',
      '..opppppwwwwo...',
      '..opTpppwwgko...',
      '..opTppppwwpo...',
      '..oPppppppppo...',
      '..oPppppppppko..',
      '...oPpppwkwko...',
      '....oPpppooo....',
      '.....oooo.......',
      '................',
      '................',
    ],
  },
  medusa: {
    palette: { o: OUTLINE, g: '#4a8a4a', G: '#2e5e2e', s: '#d8b898', h: '#5aa050', r: '#e02020', b: WOOD, S: BONE, a: '#c8a070', m: STEEL },
    pixels: [
      '....ohoho.......',
      '....ooho...o....',
      '...ohhhho.obo...',
      '..ohohhhsooSbo..',
      '...ooohssroobo..',
      '...ohoossoSobo..',
      '....oossooooboo.',
      '....osssssssaamo',
      '....osTTsoooboo.',
      '.o..ossssoSobo..',
      'ogo.oosso.oSbo..',
      'ogooggggooobo...',
      '.oggggggggoo....',
      '.oggggggggo.....',
      '..ogGGGGGo......',
      '...oooooo.......',
    ],
  },
  minotaur: {
    palette: { o: OUTLINE, f: '#7a4a2a', F: '#a0683e', n: '#c09070', k: '#1a1418', r: '#e02020', w: '#efe7cf', y: '#8a6a3a', m: '#c8d0d8', M: '#6a7480' },
    pixels: [
      '........o...o...',
      '.......owo.owo..',
      '.......owooowo.o',
      '........owfwomom',
      '.......offrfomMm',
      '......ooffffnmMm',
      '.....offfoookoyo',
      '....offFFfooooyo',
      '....offFffffffyo',
      '....offfffooooyo',
      '....offfffo..oyo',
      '....oTTTTTTo.oyo',
      '.....ofttfo..oyo',
      '.....ofoofo..oyo',
      '.....ofoofo...o.',
      '....okkookko....',
    ],
  },
  manticore: {
    palette: { o: OUTLINE, l: '#c09050', L: '#8a6430', m: '#8a5a28', w: '#8a3a2a', W: '#5a2418', s: '#6a4a30', r: '#e02020', k: '#1a1418' },
    pixels: [
      '......oo........',
      '...ooowWo.o.....',
      '..oWkowWoowo....',
      '..oskwwwowwWo...',
      '.osooowwWwWooo..',
      'oso..oWwwwwmmmo.',
      'oso...owwwmmmmmo',
      'oso.ooooWWmmllro',
      '.osollllllmmlllo',
      '..oslllllllmmmok',
      '...olllTTllloo.o',
      '...oLoLoooLoLo..',
      '...oLoLo.oLoLo..',
      '...oLoLo.oLoLo..',
      '..oLLoLLooLLLLo.',
      '...oo.oo..oooo..',
    ],
  },
  redDragon: {
    palette: { o: OUTLINE, r: '#c02020', R: '#801414', b: '#e07040', W: '#6a1010', w: '#efe7cf', y: '#ffd040' },
    pixels: [
      '...o..oRo.......',
      '..oRooWWo..o....',
      '...oRoWRo.owo...',
      '...oWoWWWoWRwoo.',
      '....oRWWRWWoryro',
      '.....oWWWWRorrrr',
      '......oRWWWoroor',
      '.....oooWRRrro.o',
      '...oorrrrWrro...',
      '..orrrrrrrro....',
      '.oorrrrrTrro....',
      'orrrrrrrrrro....',
      'roooRbbbbbRo....',
      'o..oRRooooRRo...',
      '....oo....oo....',
      '................',
    ],
  },
  stalagmite: {
    palette: { o: OUTLINE, l: '#a08a74', g: '#7a6656', G: '#54443a', d: '#2e2620' },
    pixels: [
      '................',
      '.......oo.......',
      '.......olo......',
      '......ollgo.....',
      '......ollgo.....',
      '.....olllggo....',
      '.....ollgggo..o.',
      '....ollllggo.olo',
      '....olllgggoolgo',
      '...olllggggoolgo',
      '...ollllgggGolgo',
      '..olllgggggGolGo',
      '..ollggggggGGlGo',
      '.ollgggggGGGGgGo',
      '.odddddddddddddo',
      '..oooooooooooooo',
    ],
  },
  crystal: {
    palette: {
      o: '#1a1030',
      w: '#ffffff',
      c: '#7af0ff',
      C: '#30b0d0',
      p: '#c080ff',
      P: '#6a28b0',
    },
    pixels: [
      '.......oo.......',
      '......owco......',
      '......owcCo.....',
      '.....owccCo.....',
      '.....owccCo.o...',
      '.....owccCoopo..',
      '..o..owccCoppPo.',
      '.opo.owccCoppPo.',
      '.oppoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowccCoppPo.',
      'oppPoowcCCoppPo.',
      'oPPPooCCCCoPPPo.',
      '.oooooooooooooo.',
      '................',
    ],
  },
  lorelei: {
    palette: { o: OUTLINE, f: '#6a3a8a', y: '#ffd040', b: '#d8a030' },
    pixels: [
      '.....o.oo.o.....',
      '....ofoffofo....',
      '...offffffffo...',
      '..offffffffffo..',
      '..offyffffyffo..',
      '..offffbbffffo..',
      '..offfbbbbfffo..',
      '...offfbbfffo...',
      '....offbbffo....',
      '.....offffo.....',
      '......oooo......',
      '.offoTTTTTToffo.',
      '.offfoTTTTofffo.',
      '.offffTTTTffffo.',
      '.offffTTttffffo.',
      '.oooooooooooooo.',
    ],
  },
  dace: {
    palette: { o: OUTLINE, h: BONE, n: '#6a4a2a', r: '#e02020', s: '#b08868', d: '#141018', y: GOLD },
    pixels: [
      '.o............o.',
      '.oho........oho.',
      '.ohhoooooooohho.',
      '..oonnnnnnnnoo..',
      '...onnnnnnnno...',
      '...onrnnnnrno...',
      '...onnnnnnnno...',
      '....onssssno....',
      '....osdssdso....',
      '....ossyysso....',
      '.....oooooo.....',
      '.oonnnTTTTnnnoo.',
      '.onnnTTTTTTnnno.',
      '.onnnTTyyTTnnno.',
      '.onnnTTTTTTnnno.',
      '.oooooooooooooo.',
    ],
  },
  deemer: {
    palette: { o: OUTLINE, k: '#2a2430', K: '#4a3e58', r: '#ff3020', d: '#141018', w: '#f0f0f0', f: '#ff8a20', y: GOLD },
    pixels: [
      '.o............o.',
      '.oko........oko.',
      '..okooooooooko..',
      '...okkkkkkkko...',
      '..okkKkkkkKkko..',
      '..okrrkkkkrrko..',
      '..okkkkkkkkkko..',
      '...okKKKKKKko...',
      '...okkkkkkkko...',
      '...okdkkkkdko...',
      '...owkwwwwkwo...',
      '....offffffo....',
      '.okkkTTTTTTkkko.',
      '.okkTTTTTTTTkko.',
      '.okkTTTyyTTTkko.',
      '.oooooooooooooo.',
    ],
  },
  dungeon: {
    palette: { o: OUTLINE, r: '#7a6a5e', R: '#4e423a', k: '#0a0608', e: '#ff3a2a', c: '#c890ff', C: '#7a38c8' },
    pixels: [
      '................',
      '......oooo......',
      '....oorrRroo....',
      '...orrrRrrrro...',
      '.oorrRrrrrRrroo.',
      'ocorrrrrrrrrroco',
      'occorRroooRrocCo',
      'oCcorrokkkoRocCo',
      'oCCorokkkkkorCCo',
      '.oCoroekkkeoroCo',
      '.ooRrokkkkkorRoo',
      '.orrrokkkkkorrro',
      'oRrrrokkkkkorRro',
      'orrRrokkkkkorrRo',
      'orrrrokkkkkorrro',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const DUNGEON_TINTS = {
  infernalTroglodyte: '#c04020',
  harpyHag: '#a040a0',
  evilEye: '#40c040',
  medusaQueen: '#c0a020',
  minotaurKing: '#f0c040',
  scorpicore: '#c04040',
  blackDragon: '#202028',
} satisfies Partial<Record<UpgradedCreature, string>>

/** Upgrades that look different enough to need their own drawing rather than a tint of the base creature. */
export const DUNGEON_UPGRADE_SPRITES = {
  // The Scorpicore has a thick, segmented scorpion tail with a pale stinger, in darker colors.
  scorpicore: {
    palette: { o: OUTLINE, l: '#9a5a3a', L: '#6a3a22', m: '#4a2014', w: '#5a1a28', W: '#3a0e18', s: '#6a4a48', S: '#2e2222', x: '#e8e0d0', r: '#ff3020', k: '#1a1418' },
    pixels: [
      '.ooo..oo........',
      'osSsxowWo.o.....',
      'oSo.xowWoowo....',
      'oSo.owwwowwWo...',
      'oSo.oowwWwWooo..',
      'osSo.oWwwwwmmmo.',
      'oSso..owwwmmmmmo',
      '.oSsooooWWmmllro',
      '..oSllllllmmlllo',
      '..oslllllllmmmok',
      '...olllTTllloo.o',
      '...oLoLoooLoLo..',
      '...oLoLo.oLoLo..',
      '...oLoLo.oLoLo..',
      '..oLLoLLooLLLLo.',
      '...oo.oo..oooo..',
    ],
  },
  // The Minotaur King wears gold armor and wields a much taller double-bladed axe.
  minotaurKing: {
    palette: { o: OUTLINE, f: '#7a4a2a', n: '#c09070', k: '#1a1418', r: '#e02020', w: '#efe7cf', y: '#8a6a3a', m: '#c8d0d8', M: '#6a7480', a: GOLD, A: '#a07820' },
    pixels: [
      '......o...o...o.',
      '......owo.owomMm',
      '.......owoowomMm',
      '........owfwomMm',
      '.......offrfomMm',
      '......ooffffnmMm',
      '.....oaaaoookmMm',
      '....oaAaaaooooyo',
      '....ofAaAffffoyo',
      '....offaffooooyo',
      '....offfffo..oyo',
      '....oTTTTTTo.oyo',
      '.....ofttfo..oyo',
      '.....oaooao..oyo',
      '.....ofoofo...o.',
      '....okkookko....',
    ],
  },
  // The Medusa Queen wears a gold crown and jewelry over a deep teal tail.
  medusaQueen: {
    palette: { o: OUTLINE, g: '#3a8a7a', G: '#245a50', s: '#d8b898', h: '#5aa050', r: '#e02020', b: WOOD, S: BONE, a: '#c8a070', m: STEEL, y: GOLD },
    pixels: [
      '....yoyoy.......',
      '...oyyyyyo.o....',
      '..hohhhho.obo...',
      '..ohohhhsooSbo..',
      '...ooohssroobo..',
      '...ohoossoSobo..',
      '....ooyyooooboo.',
      '....osssssssaamo',
      '....osTTsoooboo.',
      '.o..ossssoSobo..',
      'ogo.oosso.oSbo..',
      'ogooyyyyooobo...',
      '.oggggggggoo....',
      '.ogyggyggyo.....',
      '..ogGGGGGo......',
      '...oooooo.......',
    ],
  },
  // The Evil Eye is darker, with more eye-tipped stalks and a red iris.
  evilEye: {
    palette: { o: OUTLINE, p: '#7a5a78', P: '#4a3048', w: '#f0ece0', r: '#e02020', g: '#60c060', k: '#1a1418' },
    pixels: [
      '..ogo.ogo..ogo..',
      '...oPo.oPooPo...',
      '.ogoPoPoPoPo....',
      '..oPooppppooogo.',
      '...opppppppoPo..',
      '..oppppppwwpo...',
      '..opppppwwwwo...',
      '..opTpppwwrko...',
      '..opTppppwwpo...',
      '..oPppppppppo...',
      '..oPppppppppko..',
      '...oPpppwkwko...',
      '....oPpppooo....',
      '....oPooooPo....',
      '...ogo...ogo....',
      '................',
    ],
  },
  // The Harpy Hag has a wild white mane, red eyes, grey skin and dark violet feathers.
  harpyHag: {
    palette: { o: OUTLINE, f: '#4a3a5a', F: '#2a2034', s: '#8a8aa0', h: '#e0d8e0', H: '#9890a0', r: '#ff3030', y: '#c8c0b8', k: '#1a1418' },
    pixels: [
      '...o.o.o........',
      '..ohohoho.......',
      '..oFhhhhhoo.....',
      '.oFFhHhhssko....',
      'oFFFFhHrsso.....',
      '.oFFFfhfso......',
      'oFoFfffffo......',
      '.o.o.offfTso....',
      '.....oosso......',
      '.....offffo.....',
      '.....offffo.....',
      '......offo......',
      '......oyoyo.....',
      '......oyoyo.....',
      '.....oyoyoyo....',
      '......o.o.o.....',
    ],
  },
} satisfies Partial<Record<UpgradedCreature, Sprite>>
