import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, DARK_STEEL, WOOD, BONE, BONE_SHADOW, GOLD, type Sprite } from './shared'

/** Fortress: its creatures, heroes, town emblem and homeland obstacles. */
export const FORTRESS_SPRITES = {
  gnoll: {
    palette: { o: OUTLINE, f: '#b8905a', F: '#7a5a30', s: '#4a3420', k: '#e02020', d: '#2a2018', w: WOOD, M: STEEL, N: DARK_STEEL },
    pixels: [
      '..oo............',
      '..oFo..oo.......',
      '..ofFoofFo......',
      '..offffffoo.....',
      '..offfkfffffo...',
      '..offfffffffddo.',
      '...offsffsfoooo.',
      '....offssfo.....',
      '...offTTTTfoowo.',
      '..offfTTTTfffwo.',
      '..ofooTTTTooowo.',
      '..ofo.tTTto..oNo',
      '...o.ofoofo.oMMo',
      '.....ofoofo.oMNo',
      '....offoffo..oo.',
      '....ooo.ooo.....',
    ],
  },
  lizardman: {
    palette: { o: OUTLINE, g: '#5a9a3a', G: '#3a6a2a', y: '#c8c878', r: '#e0c020', w: WOOD },
    pixels: [
      '................',
      '...oooo.....o...',
      '..oggggo...owo..',
      '..oggrggo..o.wo.',
      '..ogggggggoo.wo.',
      '...oGGGGoo.o..wo',
      '....oggyo..o..wo',
      '..ooyyyyooooogwo',
      '.ogoTTTTo..o..wo',
      '.og.TTTTo..o.wo.',
      '.oooGtGto..o.wo.',
      'oGo.oggggo..owo.',
      'oGo.ogooggo..o..',
      '.oGoogo.ogo.....',
      '..ooggo.oggo....',
      '...oooo.oooo....',
    ],
  },
  serpentFly: {
    palette: { o: OUTLINE, g: '#5aa04a', G: '#2e6a2a', w: '#c8e8f0', W: '#88b0c0', r: '#e02020' },
    pixels: [
      '................',
      '.oo.......oo....',
      'owwo.....owwo...',
      'owWwo...owWwo...',
      '.owWwo.owWwo....',
      '..owWwoowWwo....',
      '...owwoowwo..oo.',
      '....ooooooooorro',
      'ooogtgTgTgggorro',
      '.oooGGGGGGggggo.',
      '...owwoowwoooo..',
      '..owWwoowWwo....',
      '.owWwo..owWwo...',
      'owWwo....owWwo..',
      'owwo......owwo..',
      '.oo........oo...',
    ],
  },
  basilisk: {
    palette: { o: OUTLINE, g: '#5a8a3a', G: '#3a5a24', y: '#c8c070', r: '#ff4020', k: '#2a3a1a' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '....o.o.o..ooo..',
      '...okokokooggoo.',
      '..oggggggggggrgo',
      'ooggTTTTgggggggo',
      'oGggttttggggoyyo',
      '.oGGGGGGGGGGoyo.',
      '..oyyyyyyyyyyo..',
      '..ogGogGogGogGo.',
      '..ogGogGogGogGo.',
      '.oggoggoggoggo..',
      '.ooooooooooooo..',
    ],
  },
  gorgon: {
    palette: { o: OUTLINE, n: '#a8b8a0', m: '#8a9a88', M: '#5a6a5a', h: BONE, r: '#60f060', d: '#2a3028' },
    pixels: [
      '................',
      '................',
      '................',
      '...........o..o.',
      '..oooooooooho.ho',
      '.onnmnnmnnohmmho',
      'onmmmmmmmmmommmo',
      'omMmMmMmMmmmmrmo',
      'omTTTTTTmmmmmmmo',
      'oMttttttMMmmddmo',
      '.oMMMMMMMMoommo.',
      '..omMo..omMooo..',
      '..omMo..omMo....',
      '..omMo..omMo....',
      '.oddMo.oddMo....',
      '.ooooo.ooooo....',
    ],
  },
  wyvern: {
    palette: { o: OUTLINE, g: '#6aa040', G: '#3a6a24', y: '#d0c060', r: '#e02020', h: BONE },
    pixels: [
      '................',
      '.oo.........oo..',
      '.oTo.......oggo.',
      '.oTTo.....oggrgo',
      '.oTtTo...oggggyo',
      '.oTttToooggoyyo.',
      '.oTtttTgggo.oo..',
      '..oTttgggggo....',
      '...oTggggggo....',
      '..oogggggyyo....',
      '.ogo.ogggyyo....',
      'ogo..oGGGGo.....',
      'oho...ogoGo.....',
      '.o...ogo.oGo....',
      '.....ogo..ogo...',
      '....oooo.oooo...',
    ],
  },
  hydra: {
    palette: { o: OUTLINE, g: '#4a8a5a', G: '#2a5a38', y: '#c8c070', r: '#e02020' },
    pixels: [
      '.ooo......ooo...',
      'oggro....oggro..',
      'ogggoo.ooogggoo.',
      '.ogo..oggroogo..',
      '.ogo..ogggoogo..',
      '.ogo...ogo.ogo..',
      '..ogo..ogo.ogo..',
      '..ogo.ogo.ogo...',
      '...ogoogoogo....',
      '..ooggggggggo...',
      '.ogTTTTTggggyo..',
      'ogtTTTTtgggggyo.',
      'oGGgggggggggyyo.',
      '.oGGGGGGGGGGGo..',
      'oGGo.....oGGo...',
      'ooo.......ooo...',
    ],
  },
  broghild: {
    palette: { o: OUTLINE, f: '#6a4a2a', F: '#4a3018', s: SKIN, S: '#b88060', d: '#141018', b: '#c08040', h: BONE },
    pixels: [
      '................',
      '....oo....oo....',
      '...oFfoooofFo...',
      '...offffffffo...',
      '...ohffffffho...',
      '...osssssssSo...',
      '...ossdssdsSo...',
      '...osssssssSo...',
      '...osbbbbbbSo...',
      '...obbbbbbbbo...',
      '....obbbbbbo....',
      '..ooffbbbbffoo..',
      '.offTTTTTTTTffo.',
      '.offTTTTTTTTffo.',
      '.offTTThhTTTffo.',
      '.oooooooooooooo.',
    ],
  },
  wystan: {
    palette: { o: OUTLINE, g: '#5a8a3a', G: '#3a5a24', h: BONE, H: BONE_SHADOW, s: SKIN, S: '#b88060', d: '#141018', k: '#3a2a1a', r: '#c03020' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhHo....',
      '...ohhdhhdhHo...',
      '...ohhhhhhhHo...',
      '...ohohohohoo...',
      '...okssssssko...',
      '...okrdssdrko...',
      '...okssssssko...',
      '...okssSSssko...',
      '....osssssso....',
      '..ooggggggggoo..',
      '.oggTTTTTTTTggo.',
      '.oggTTThhTTTggo.',
      '.oGgTTTTTTTTgGo.',
      '.oooooooooooooo.',
    ],
  },
  merist: {
    palette: { o: OUTLINE, c: '#3a5a3a', C: '#24402a', s: SKIN, S: '#b88060', d: '#141018', l: '#8a3a6a', w: '#d8d8c8', y: GOLD },
    pixels: [
      '.......oo.......',
      '......occo......',
      '.....occcco.....',
      '....occcccco....',
      '...occccccCCo...',
      '...occCCCCCCo...',
      '...ocCssssSCo...',
      '...ocsdssdSCo...',
      '...ocwsllswCo...',
      '...occwssSwCo...',
      '....occCCCCco...',
      '..ooccccccCCoo..',
      '.occcTTTTTTcCCo.',
      '.occcTTyyTTcCCo.',
      '.occcctTTtccCCo.',
      '.oooooooooooooo.',
    ],
  },
  fortress: {
    palette: { o: OUTLINE, r: '#8a8a40', R: '#5a5a28', w: WOOD, W: '#5a3a1a', d: '#2a1a10', m: '#3a5a3a', M: '#24402a' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......orro......',
      '.....orRrro.....',
      '....orrrRrro....',
      '.o.orRrrrrRro.o.',
      'owoorrrrRrrroowo',
      'owoooooooooooowo',
      'owo.owWddWwo.owo',
      'owo.owWddWwo.owo',
      'oWo.owWddWwo.oWo',
      'oooooooooooooooo',
      '.W..W..W..W..W..',
      'ommMmmmMmmmMmmmo',
      'oooooooooooooooo',
    ],
  },
  reeds: {
    palette: { o: OUTLINE, g: '#6a9a3a', G: '#3a6a24', b: '#7a4a24', B: '#4a2c14', m: '#3a5a4a' },
    pixels: [
      '..o.......o.....',
      '.obo...o..obo...',
      '.obBo.obo.obBo..',
      '.obBo.obBoobBo..',
      '.obBo.obBoobBo..',
      '..ogo.obBo.ogo..',
      '..ogo..ogo.ogo..',
      'o.ogo..ogo.ogo.o',
      'ogogo..ogo.ogoGo',
      '.oGgo.ogGo.ogGo.',
      '..oGgoGgoGogGo..',
      '..oGgGgoGgGgo...',
      '...oGgGgGgGgo...',
      '..omGGGGGGGGmo..',
      '.ommmmmmmmmmmmo.',
      '..oooooooooooo..',
    ],
  },
  swampLog: {
    palette: { o: OUTLINE, b: '#6a4a2a', B: '#4a3018', r: '#c09a60', R: '#8a6a40', g: '#6a9a3a', G: '#3a6a24' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..ooo...ooo.....',
      '.ogggooogggoooo.',
      'ogGgbbgGgbboRRRo',
      'obbbbbbbbbboRrRo',
      'oBbbBbbBbbboRBRo',
      'oBBBBBBBBBBoRrRo',
      'oBBBBBBBBBBoRRRo',
      '.oooooooooooooo.',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const FORTRESS_TINTS = {
  gnollMarauder: '#a05030',
  lizardWarrior: '#2a8a5a',
  dragonFly: '#40c0e0',
  greaterBasilisk: '#a0c040',
  mightyGorgon: '#406040',
  wyvernMonarch: '#c0a030',
  chaosHydra: '#802040',
} satisfies Partial<Record<UpgradedCreature, string>>
