import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, WOOD, BONE, BONE_SHADOW, GOLD, type Sprite } from './shared'

/** Fortress: its creatures, heroes, town emblem and homeland obstacles. */
export const FORTRESS_SPRITES = {
  gnoll: {
    palette: { o: OUTLINE, f: '#c8a25a', F: '#8a6a34', m: '#5a3e22', l: '#6a4a2a', k: '#2a2024', W: WOOD, K: '#3a3a40', c: '#9aa0a8' },
    pixels: [
      'KKo......o......',
      'KKco....oFo.....',
      'ooWo...ooFFo....',
      '..oWo.omfffoo...',
      '...ofoomfffkfoo.',
      '....ofomffffffko',
      '.....ofooooofoo.',
      '.....olfffo.o...',
      '....offlfofo....',
      '....ofFfloofo...',
      '.....offfo.o....',
      '.....oTTTo......',
      '.....ofoofo.....',
      '.....ofoofo.....',
      '....ofo..ofo....',
      '...oFFo..oFFo...',
    ],
  },
  lizardman: {
    palette: { o: OUTLINE, g: '#4a7a3a', G: '#2e5226', y: '#a0b060', e: '#ffd040', w: WOOD, S: BONE, a: '#c8a070', m: STEEL },
    pixels: [
      '................',
      '...........o....',
      '.......oooowo...',
      '......oggeoSwo..',
      '.....oggggggowo.',
      '......oggoSGowo.',
      '.....oggoSooowo.',
      '....ogggogooowoo',
      '....oTggygggaaam',
      '....ogTgyoSoowoo',
      '....oggTyoSoowo.',
      '....ooggo.ooowo.',
      '...ogogogooSwo..',
      '.oogoogogoowo...',
      'oggoogo.ogoo....',
      '.oooGGo.oGGo....',
    ],
  },
  serpentFly: {
    palette: { o: OUTLINE, g: '#4a9a6a', G: '#2e6a4a', y: '#d8c04a', r: '#e02020', k: '#1e2a1a', w: '#c8e8f0', W: '#98c0d0' },
    pixels: [
      '..oo........o...',
      '.owwo......oWo..',
      '..owwo....oWWo..',
      '...owwo..oWWo...',
      '....owwo.oWWoo..',
      '.....owwoWWGrro.',
      '......ogggGGrro.',
      '......ogTgGGGroo',
      '......oggTgGGGok',
      '.....oyyokokoo.o',
      '....oggookoko...',
      '...oyyo..o.o....',
      '...oggo.........',
      '....oyyoo.......',
      '.....oggko......',
      '......ooo.......',
    ],
  },
  basilisk: {
    palette: { o: OUTLINE, g: '#5a7a3a', G: '#3a5226', y: '#c8b878', r: '#ff4020', w: '#efe7cf', k: '#2a3a1a' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '...o.o.o.o.ooo..',
      '..oGoGoGoGoGggo.',
      '..ogggggggggrggo',
      '.ogggTTTTggggggg',
      'ogggggggggggGwGw',
      'GGgyyyyyyyygoooo',
      'oooGoGoooGoGoo..',
      'okGokGo..oGkGko.',
      '.oo.oo....oooo..',
      '................',
    ],
  },
  gorgon: {
    palette: { o: OUTLINE, n: '#4e9a42', m: '#2a2f2a', M: '#141814', h: BONE, r: '#60f060', d: '#3a6a32' },
    pixels: [
      '................',
      '................',
      '................',
      '...........o..o.',
      '..oooooooooho.ho',
      '.onnmnnmnnohmmho',
      'onmmnmmnmmmommmo',
      'omMmMmMmMmmmmrmo',
      'omTTTTTTnmmnmmmo',
      'oMttttttMMmmddmo',
      '.oMMMMMMMMoommo.',
      '..omMo..omMooo..',
      '..omMo..omMo....',
      '..omMo..omMo....',
      '.oddMo.oddMo....',
      '.ooooo.ooooo....',
    ],
  },
  wyvern: {
    palette: { o: OUTLINE, g: '#6a8a3a', G: '#46602a', y: '#c8c070', m: '#8a9a4a', r: '#ff4020', k: '#2a3a1a' },
    pixels: [
      '.....o..........',
      '..oooGooooo.....',
      '.oGmmmmmmGGo....',
      '.ommmmGmmmGoo...',
      '.ommmGmmGmGGGo..',
      '..ommmmmmooggroo',
      '...ommmmGooggggg',
      '....oggggoogoogo',
      '...ogggTTggo..o.',
      'oo.oggggggo.....',
      'kkooggyyyyo.....',
      'googoooGoGo.....',
      'oggo..oGooGoo...',
      '.oo....oGkoGko..',
      '........oo.oo...',
      '................',
    ],
  },
  hydra: {
    palette: { o: OUTLINE, g: '#4a8a4a', G: '#2e5a2e', y: '#a8c070', r: '#ff4020' },
    pixels: [
      '................',
      '........ooo.....',
      '.......ogrgooo..',
      '........ogoogro.',
      '........ogooggo.',
      '.......ogo.ogo..',
      '.......ogoogooo.',
      '....o.oogogoogro',
      'o.ooGoGoggoooggo',
      'gogggggggggggoo.',
      'ogggTTTgggoooro.',
      '.ogggggggggggggo',
      '.oggggggggooooo.',
      '.oGyyyyyyoGo....',
      '.oGooGooGoo.....',
      '..o..o..o.......',
    ],
  },
  broghild: {
    palette: { o: OUTLINE, f: '#6a4a2a', F: '#4a3018', s: SKIN, S: '#b88060', d: '#141018', b: '#c08040', h: BONE },
    pixels: [
      '................',
      '....oo....oo....',
      '...oFfoooofFo...',
      '...offffffffo...',
      '...ohffffffho...',
      '...osssssssSo...',
      '...ossdssdsSo...',
      '...osssssssSo...',
      '...osbbbbbbSo...',
      '...obbbbbbbbo...',
      '....obbbbbbo....',
      '..ooffbbbbffoo..',
      '.offTTTTTTTTffo.',
      '.offTTTTTTTTffo.',
      '.offTTThhTTTffo.',
      '.oooooooooooooo.',
    ],
  },
  wystan: {
    palette: { o: OUTLINE, g: '#5a8a3a', G: '#3a5a24', h: BONE, H: BONE_SHADOW, s: SKIN, S: '#b88060', d: '#141018', k: '#3a2a1a', r: '#c03020' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhHo....',
      '...ohhdhhdhHo...',
      '...ohhhhhhhHo...',
      '...ohohohohoo...',
      '...okssssssko...',
      '...okrdssdrko...',
      '...okssssssko...',
      '...okssSSssko...',
      '....osssssso....',
      '..ooggggggggoo..',
      '.oggTTTTTTTTggo.',
      '.oggTTThhTTTggo.',
      '.oGgTTTTTTTTgGo.',
      '.oooooooooooooo.',
    ],
  },
  merist: {
    palette: { o: OUTLINE, c: '#3a5a3a', C: '#24402a', s: SKIN, S: '#b88060', d: '#141018', l: '#8a3a6a', w: '#d8d8c8', y: GOLD },
    pixels: [
      '.......oo.......',
      '......occo......',
      '.....occcco.....',
      '....occcccco....',
      '...occccccCCo...',
      '...occCCCCCCo...',
      '...ocCssssSCo...',
      '...ocsdssdSCo...',
      '...ocwsllswCo...',
      '...occwssSwCo...',
      '....occCCCCco...',
      '..ooccccccCCoo..',
      '.occcTTTTTTcCCo.',
      '.occcTTyyTTcCCo.',
      '.occcctTTtccCCo.',
      '.oooooooooooooo.',
    ],
  },
  fortress: {
    palette: { o: OUTLINE, r: '#8a8a40', R: '#5a5a28', w: WOOD, W: '#5a3a1a', d: '#2a1a10', m: '#3a5a3a', M: '#24402a' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......orro......',
      '.....orRrro.....',
      '....orrrRrro....',
      '.o.orRrrrrRro.o.',
      'owoorrrrRrrroowo',
      'owoooooooooooowo',
      'owo.owWddWwo.owo',
      'owo.owWddWwo.owo',
      'oWo.owWddWwo.oWo',
      'oooooooooooooooo',
      '.W..W..W..W..W..',
      'ommMmmmMmmmMmmmo',
      'oooooooooooooooo',
    ],
  },
  reeds: {
    palette: { o: OUTLINE, g: '#6a9a3a', G: '#3a6a24', b: '#7a4a24', B: '#4a2c14', m: '#3a5a4a' },
    pixels: [
      '..o.......o.....',
      '.obo...o..obo...',
      '.obBo.obo.obBo..',
      '.obBo.obBoobBo..',
      '.obBo.obBoobBo..',
      '..ogo.obBo.ogo..',
      '..ogo..ogo.ogo..',
      'o.ogo..ogo.ogo.o',
      'ogogo..ogo.ogoGo',
      '.oGgo.ogGo.ogGo.',
      '..oGgoGgoGogGo..',
      '..oGgGgoGgGgo...',
      '...oGgGgGgGgo...',
      '..omGGGGGGGGmo..',
      '.ommmmmmmmmmmmo.',
      '..oooooooooooo..',
    ],
  },
  swampLog: {
    palette: { o: OUTLINE, b: '#6a4a2a', B: '#4a3018', r: '#c09a60', R: '#8a6a40', g: '#6a9a3a', G: '#3a6a24' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..ooo...ooo.....',
      '.ogggooogggoooo.',
      'ogGgbbgGgbboRRRo',
      'obbbbbbbbbboRrRo',
      'oBbbBbbBbbboRBRo',
      'oBBBBBBBBBBoRrRo',
      'oBBBBBBBBBBoRRRo',
      '.oooooooooooooo.',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const FORTRESS_TINTS = {
  gnollMarauder: '#a05030',
  lizardWarrior: '#2a8a5a',
  dragonFly: '#40c0e0',
  greaterBasilisk: '#a0c040',
  mightyGorgon: '#406040',
  wyvernMonarch: '#c0a030',
  chaosHydra: '#802040',
} satisfies Partial<Record<UpgradedCreature, string>>

/** Upgrades that look different enough to need their own drawing rather than a tint of the base creature. */
export const FORTRESS_UPGRADE_SPRITES = {
  // The Gnoll Marauder has darker fur, a spiked shoulder guard and swings a spiked flail.
  gnollMarauder: {
    palette: { o: OUTLINE, f: '#a86a40', F: '#6a4020', m: '#3a2412', l: '#4a3020', k: '#2a2024', c: '#d8dce4', K: '#4a4a52', s: '#d0d4dc' },
    pixels: [
      '.sos.....o......',
      'sKKKs...oFo.....',
      'oKkKo..ooFFo....',
      '.oco..omfffoo...',
      '...cfoomfffkfoo.',
      '....ofomffffffko',
      '.....ofooooofoo.',
      '....osslffo.o...',
      '....osslfofo....',
      '....ofFfloofo...',
      '.....offfo.o....',
      '.....oTTTo......',
      '.....ofoofo.....',
      '.....ofoofo.....',
      '....ofo..ofo....',
      '...oFFo..oFFo...',
    ],
  },
  // The Dragon Fly is bigger than the Serpent Fly, with a striped blue body and four shimmering wings.
  dragonFly: {
    palette: { o: '#14203a', b: '#3ac0e0', B: '#2070b0', y: '#f0a030', R: '#e04040', e: '#ffe060', k: '#1e2a3a', w: '#e8faff', W: '#a0d8f0', v: '#c890f0' },
    pixels: [
      '.oo..........oo.',
      'ovwo........owvo',
      'oWwwo......owwWo',
      '.oWwwo....owwWo.',
      '..oWwwo..owwWo..',
      '...oWwwooowWo...',
      'owvwwWoBbbboRRo.',
      '.oowwoBbbybobeRo',
      '....obybBoooRRo.',
      '...obyBo.ok.ko..',
      '..obyBo.........',
      '..oybo..........',
      '.obyo...........',
      '.oyBo...........',
      'obyo............',
      'ooo.............',
    ],
  },
  // The Greater Basilisk grows a row of tall bone spikes along its back and a horn on its snout.
  greaterBasilisk: {
    palette: { o: OUTLINE, g: '#6a7a4a', G: '#44502e', y: '#d8c890', r: '#ff4020', w: '#efe7cf', k: '#2a3a1a', h: '#e8dcb0', H: '#a89870' },
    pixels: [
      '................',
      '................',
      '................',
      '...o..o..o......',
      '..oho.oho.oho...',
      '..ohHoohHoohHo..',
      '..oHHoHHHoHHHoo.',
      '..oGoGoGoGoGggoo',
      '..ogggggggggrggh',
      '.ogggTTTTggggggg',
      'ogggggggggggGwGw',
      'GGgyyyyyyyygoooo',
      'oooGoGoooGoGoo..',
      'okGokGo..oGkGko.',
      '.oo.oo....oooo..',
      '................',
    ],
  },
  // The Mighty Gorgon is darker, with tall green armour plates along its back and longer horns.
  mightyGorgon: {
    palette: { o: OUTLINE, n: '#4e9a42', N: '#8ad070', m: '#202520', M: '#0e110e', h: BONE, r: '#80ff60', d: '#3a6a32' },
    pixels: [
      '................',
      '................',
      '..o..o..o..o..o.',
      '.oNooNooNooho.ho',
      '.onNnnNnnNoho.ho',
      '.onnnnnnnnohmmho',
      'onmmnmmnmmmommmo',
      'omMmMmMmMmmmmrmo',
      'omTTTTTTnmmnmmmo',
      'oMttttttMMmmddmo',
      '.oMMMMMMMMoommo.',
      '..onMo..onMooo..',
      '..omMo..omMo....',
      '..omMo..omMo....',
      '.oddMo.oddMo....',
      '.ooooo.ooooo....',
    ],
  },
  // The Wyvern Monarch is darker and grows a venomous stinger on its tail.
  wyvernMonarch: {
    palette: { o: OUTLINE, g: '#3e5a22', G: '#263a14', y: '#c8a858', m: '#56662a', r: '#ff4020', k: '#1a2a10', h: BONE },
    pixels: [
      '.....o..........',
      '..oooGooooo.....',
      '.oGmmmmmmGGo....',
      '.ommmmGmmmGoo...',
      'hommmGmmGmGGGoho',
      'hhommmmmmooggroo',
      'og.ommmmGooggggg',
      'og..oggggoogoogo',
      'og.ogggTTggo..o.',
      'ogooggggggo.....',
      'ogggggyyyyo.....',
      'oooooooGoGo.....',
      '......oGooGoo...',
      '.......oGkoGko..',
      '........oo.oo...',
      '................',
    ],
  },
  // The Chaos Hydra is darker and sprouts more heads.
  chaosHydra: {
    palette: { o: OUTLINE, g: '#2e6a32', G: '#1a4420', y: '#b8b060', r: '#ffd020' },
    pixels: [
      '...ooo..ooo.....',
      '..ogrgoogrgooo..',
      '...ogo..ogoogro.',
      '...ogo..ogooggo.',
      '....ogo.ogo.ogo.',
      '.....ogoogooogoo',
      '......ogogoogogr',
      '.ooo.oogogoogggo',
      '.ooGoGoggooooggo',
      'gogggggggggggoo.',
      'ogggTTTgggoooroo',
      '.ogggggggggggggo',
      '.oggggggggooooro',
      '.oGyyyyyyoGo.oo.',
      '.oGooGooGoo.....',
      '..o..o..o.......',
    ],
  },
} satisfies Partial<Record<UpgradedCreature, Sprite>>
