import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, WOOD, BONE, BONE_SHADOW, GOLD, type Sprite } from './shared'

/** Fortress: its creatures, heroes, town emblem and homeland obstacles. */
export const FORTRESS_SPRITES = {
  gnoll: {
    palette: { o: OUTLINE, f: '#c8a25a', F: '#8a6a34', m: '#5a3e22', s: '#6a4a2a', e: '#e8a020', k: '#2a2024', B: '#a87a4a', h: BONE, L: '#7a5232', l: '#5a3a22', W: WOOD, K: '#4a4a52', c: STEEL },
    pixels: [
      'oKo....o.o......',
      'KKKo..oFoFo.....',
      'oKco.omffffooo..',
      '.oWoommffeffFko.',
      '..oWomfffffFho..',
      '..ofommfsfooo...',
      '..ofLLLLLffo....',
      '...oLBLLLofo....',
      '...olLBLLoso....',
      '...olLLBLofo....',
      '...oTTTTToffo...',
      '...oLlLLlooo....',
      '...oFFoffo......',
      '...oFo.oso......',
      '..oFFo.offoo....',
      '.oFFo...offko...',
    ],
  },
  lizardman: {
    palette: { o: OUTLINE, g: '#4a8a3a', G: '#2e5a26', y: '#c8c070', r: '#c84020', e: '#ffd040', B: WOOD, s: BONE },
    pixels: [
      '.....o.o........',
      '....ororo....so.',
      '...orggggooosoBo',
      '...orggeggggsoBo',
      '....ogggyGGGsoBo',
      '....ogggooos.oBo',
      '...ogGggyosoooBo',
      '..ogGgggyggggggo',
      '...oGggyooosooBo',
      '..oogGgyo...soBo',
      '.oggTTTTo...soBo',
      'oggoTtTtoo...so.',
      'ggo.oggoggo.....',
      'go..oGo.ogo.....',
      'o...oGGooggoo...',
      '...oGGo..ogggo..',
    ],
  },
  serpentFly: {
    palette: { o: OUTLINE, b: '#4a9a5a', B: '#2e6a3a', y: '#d8c04a', R: '#d02020', E: '#ff8060', k: '#1e2a1a', w: '#d8f0e0', W: '#b0d4c4', V: '#88b0a0' },
    pixels: [
      '...owwo....oWWo.',
      '....owwo..oWWo..',
      '.oo..owwooWoWoo.',
      'oVVoooowwoWWooVo',
      'oVVVVVoowwWVVVVo',
      '.ooVVVVVooVbEoo.',
      '...oooVVbbbbRRo.',
      '......obbbbbbRo.',
      '.....oBBBBbobk..',
      '....oyyookoko...',
      '...oBBo.k...k...',
      '..oyyo..........',
      '.oBBo...........',
      '.oyyo...........',
      'oBBo............',
      '.ko.............',
    ],
  },
  basilisk: {
    palette: { o: OUTLINE, g: '#6a7a52', G: '#46523a', y: '#c8bc88', S: '#a8a888', e: '#ffe040', E: '#c8ff60', w: BONE, k: '#2a2a20', m: '#5a1a14' },
    pixels: [
      '........................',
      '........................',
      '........................',
      '........................',
      '.................o......',
      '.....o.o.o.o.o.ooSooo...',
      '....oSoSoSoSoSoSgggeEooo',
      '.o.ooogggggggggggggggggg',
      'oSoSggggTTTTggggggggwmwm',
      'ogggGgggttttgggggGGGGwgo',
      'GGggGGGggggggggggoooooo.',
      'ooooogyyyyyyyyygooo.....',
      '....ogggoGGoogggoGGo....',
      '...oggoo.oGo.ooggoGo....',
      '...oggo..oGGo.oggoGGo...',
      '..okkkko.okkkokkkkkkko..',
    ],
  },
  gorgon: {
    palette: { o: OUTLINE, m: '#2a2e2a', M: '#161a16', g: '#4a524a', n: '#3e8a3a', N: '#6ac05a', d: '#1e4a1e', h: BONE, H: BONE_SHADOW, r: '#70ff50' },
    pixels: [
      '........................',
      '........................',
      '...........ooooo.o.....o',
      '.........ooNNNNNoHo..ooh',
      '......oooNNndnndnHo.ohho',
      '..ooooNNNdnndnndnmHohoo.',
      '.omnndnndnmTTmmmmmnNNo..',
      'omommmmmmmmTTmmmmmmnnro.',
      'omommmmmmmmTTmmmmMmmmmmo',
      'omoMMMmmmmmTTmmmmMMmmmgg',
      'MMoomMMMMMMttMMMmooMmggM',
      'Mo.ommmMMoooommgMMoooooo',
      'o...onnoMMo.onnoMMo.....',
      '....omgoMMo.omgoMMo.....',
      '....omgoMMo.omgoMMo.....',
      '....oddoddo.oddoddo.....',
    ],
  },
  wyvern: {
    palette: { o: OUTLINE, D: '#7a9a3a', d: '#4e6a26', B: '#d8c888', W: '#a8b058', w: '#788232', s: '#4a5420', S: BONE, e: '#ff4020', f: BONE, m: '#5a1a14', k: '#2a2a1a' },
    pixels: [
      '..ooWWoosWooko...o......',
      '.oksWWWWWsWoso..oSoo....',
      '..oWssWWWsWWso.oSDDDooo.',
      '...oWwssWWsWsooSoDDeDDDo',
      '...oWWwwswWssWooDDDDDfmo',
      '....oWWwwssWssSDDBoDDDfo',
      '.....ooWWwwsssDDBo.oooo.',
      'oo.....oooWWDsDoo.......',
      'SSo....oDDTTTDDDo.......',
      'SDo...oDDDDDBBBBo.......',
      'SoDooooDddDBDDBo........',
      'ooDDDDDoddoDDDo.........',
      '..ooooooddooDDo.........',
      '........odooDo..........',
      '........oddoDDo.........',
      '.......okkkokkko........',
    ],
  },
  hydra: {
    palette: { o: OUTLINE, B: '#4a8a3a', b: '#2e5e24', L: '#c8d088', N: '#5aa046', H: '#6ab452', j: '#2e5e24', e: '#ffe040', r: '#e03030', k: '#2a2018' },
    pixels: [
      '..........oHeHooHeHo....',
      '..........ojjjoojjjro...',
      '......ooo.oNNo.oNNooooo.',
      '.....oHeHooNNo.oNNooHeHo',
      '....orjjjo.oNNooNNoojjjo',
      '.....ooNNoooNNooNNooNNo.',
      '.......oNNNoNNooNNooNo..',
      '........ooNNNoNoNooNNoo.',
      '.........oNNoNNNNNNNHeHo',
      '....ooooooBNNNNNNNoojjjr',
      '...oBBBBBBBBBBBBBBooNNoo',
      '.ooBBBBBBBBBBBBBNNNNNo..',
      'oBBBbbbBBBBBBBBBBoooo...',
      'BBBoBBLLLLLLLLBBo.......',
      'ooooBBooboooboBBo.......',
      '...okkooko.okokkko......',
    ],
  },
  broghild: {
    palette: { o: OUTLINE, f: '#6a4a2a', F: '#4a3018', s: SKIN, S: '#b88060', d: '#141018', b: '#c08040', h: BONE },
    pixels: [
      '................',
      '....oo....oo....',
      '...oFfoooofFo...',
      '...offffffffo...',
      '...ohffffffho...',
      '...osssssssSo...',
      '...ossdssdsSo...',
      '...osssssssSo...',
      '...osbbbbbbSo...',
      '...obbbbbbbbo...',
      '....obbbbbbo....',
      '..ooffbbbbffoo..',
      '.offTTTTTTTTffo.',
      '.offTTTTTTTTffo.',
      '.offTTThhTTTffo.',
      '.oooooooooooooo.',
    ],
  },
  wystan: {
    palette: { o: OUTLINE, g: '#5a8a3a', G: '#3a5a24', h: BONE, H: BONE_SHADOW, s: SKIN, S: '#b88060', d: '#141018', k: '#3a2a1a', r: '#c03020' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhHo....',
      '...ohhdhhdhHo...',
      '...ohhhhhhhHo...',
      '...ohohohohoo...',
      '...okssssssko...',
      '...okrdssdrko...',
      '...okssssssko...',
      '...okssSSssko...',
      '....osssssso....',
      '..ooggggggggoo..',
      '.oggTTTTTTTTggo.',
      '.oggTTThhTTTggo.',
      '.oGgTTTTTTTTgGo.',
      '.oooooooooooooo.',
    ],
  },
  merist: {
    palette: { o: OUTLINE, c: '#3a5a3a', C: '#24402a', s: SKIN, S: '#b88060', d: '#141018', l: '#8a3a6a', w: '#d8d8c8', y: GOLD },
    pixels: [
      '.......oo.......',
      '......occo......',
      '.....occcco.....',
      '....occcccco....',
      '...occccccCCo...',
      '...occCCCCCCo...',
      '...ocCssssSCo...',
      '...ocsdssdSCo...',
      '...ocwsllswCo...',
      '...occwssSwCo...',
      '....occCCCCco...',
      '..ooccccccCCoo..',
      '.occcTTTTTTcCCo.',
      '.occcTTyyTTcCCo.',
      '.occcctTTtccCCo.',
      '.oooooooooooooo.',
    ],
  },
  fortress: {
    palette: { o: OUTLINE, r: '#8a8a40', R: '#5a5a28', w: WOOD, W: '#5a3a1a', d: '#2a1a10', m: '#3a5a3a', M: '#24402a' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......orro......',
      '.....orRrro.....',
      '....orrrRrro....',
      '.o.orRrrrrRro.o.',
      'owoorrrrRrrroowo',
      'owoooooooooooowo',
      'owo.owWddWwo.owo',
      'owo.owWddWwo.owo',
      'oWo.owWddWwo.oWo',
      'oooooooooooooooo',
      '.W..W..W..W..W..',
      'ommMmmmMmmmMmmmo',
      'oooooooooooooooo',
    ],
  },
  reeds: {
    palette: { o: OUTLINE, g: '#6a9a3a', G: '#3a6a24', b: '#7a4a24', B: '#4a2c14', m: '#3a5a4a' },
    pixels: [
      '..o.......o.....',
      '.obo...o..obo...',
      '.obBo.obo.obBo..',
      '.obBo.obBoobBo..',
      '.obBo.obBoobBo..',
      '..ogo.obBo.ogo..',
      '..ogo..ogo.ogo..',
      'o.ogo..ogo.ogo.o',
      'ogogo..ogo.ogoGo',
      '.oGgo.ogGo.ogGo.',
      '..oGgoGgoGogGo..',
      '..oGgGgoGgGgo...',
      '...oGgGgGgGgo...',
      '..omGGGGGGGGmo..',
      '.ommmmmmmmmmmmo.',
      '..oooooooooooo..',
    ],
  },
  swampLog: {
    palette: { o: OUTLINE, b: '#6a4a2a', B: '#4a3018', r: '#c09a60', R: '#8a6a40', g: '#6a9a3a', G: '#3a6a24' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..ooo...ooo.....',
      '.ogggooogggoooo.',
      'ogGgbbgGgbboRRRo',
      'obbbbbbbbbboRrRo',
      'oBbbBbbBbbboRBRo',
      'oBBBBBBBBBBoRrRo',
      'oBBBBBBBBBBoRRRo',
      '.oooooooooooooo.',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const FORTRESS_TINTS = {
  gnollMarauder: '#a05030',
  lizardWarrior: '#2a8a5a',
  dragonFly: '#40c0e0',
  greaterBasilisk: '#a0c040',
  mightyGorgon: '#406040',
  wyvernMonarch: '#c0a030',
  chaosHydra: '#802040',
} satisfies Partial<Record<UpgradedCreature, string>>

/** Upgrades that look different enough to need their own drawing rather than a tint of the base creature. */
export const FORTRESS_UPGRADE_SPRITES = {
  // The Gnoll Marauder has darker fur, a steel pauldron and studded breastplate, and swings a spiked flail.
  gnollMarauder: {
    palette: { o: OUTLINE, f: '#a86a40', F: '#6a4020', m: '#2a1a12', s: '#4a2a18', e: '#ff4020', k: '#1a1418', B: '#6a6a72', h: '#e0e4ea', L: '#3e2e26', l: '#2a1e18', W: '#5a3a1a', K: '#4a4a52', c: '#9aa0aa' },
    pixels: [
      'hKho...o.o......',
      'KKKo..oFoFo.....',
      'hKco.omffffooo..',
      'ooWoommffeffFko.',
      '..oWomfffffFho..',
      '..ohommfsfooo...',
      '..ofcccLLffo....',
      '...occLcLofo....',
      '...olLBLLoso....',
      '...olLcBLofo....',
      '...oTTTTToffo...',
      '...oLlLLlooo....',
      '...oFFoffo......',
      '...oFo.oso......',
      '..oFFo.offoo....',
      '.oFFo...offko...',
    ],
  },
  // The Lizard Warrior wears a bronze breastplate and red war-paint, with a gold-capped recurve bow and a taller crest.
  lizardWarrior: {
    palette: { o: OUTLINE, g: '#3a7a3a', G: '#22481e', y: '#c8b060', r: '#d83020', e: '#ffd040', B: '#6a2a1a', s: BONE, a: '#c89040', A: '#8a5a24', Y: GOLD },
    pixels: [
      '....oYoYo.......',
      '....ororo....so.',
      '...orggggooosoYo',
      '...orrgeggggsoBo',
      '....ogggyGGGsoBo',
      '....ogrgooos.oBo',
      '...ogaaAyosoooBo',
      '..ograaaygggggYo',
      '...oGAayooosooBo',
      '..oogAayo...soBo',
      '.oggTTTTo...soBo',
      'oggoTtTtoo..oso.',
      'ggo.oggoggooYo..',
      'go..oGo.ogo.o...',
      'o...oGGooggoo...',
      '...oGGo..ogggo..',
    ],
  },
  // The Dragon Fly shimmers blue and cyan, with longer violet-tipped wings and a golden eye.
  dragonFly: {
    palette: { o: OUTLINE, b: '#3ac0e0', B: '#2070b0', y: '#a0f0ff', R: '#f0a020', E: '#fff080', k: '#14203a', w: '#f0fcff', W: '#b8e4f8', V: '#80c0e8', v: '#c890f0' },
    pixels: [
      '..ovo.......ovWo',
      'ooowwoo....oWWoo',
      'vVoowwwo..oWWoov',
      'VVVVowwwooWWoVVV',
      'ooVVVVowwWWVVVVo',
      '..ooVVVVwoVbEoo.',
      '....ooVVbbbbRRo.',
      '......obbbbbbRo.',
      '.....oBBBBbobk..',
      '....oyyookoko...',
      '...oBBo.k...k...',
      '..oyyo..........',
      '.oBBo...........',
      '.oyyo...........',
      'oBBo............',
      '.ko.............',
    ],
  },
  // The Greater Basilisk grows tall fiery spines along its back and a horn on its snout.
  greaterBasilisk: {
    palette: { o: OUTLINE, g: '#5a6a4a', G: '#3a4430', y: '#d8c890', S: '#e07020', R: '#e83a18', e: '#ffe040', E: '#c8ff60', w: BONE, k: '#2a2a20', m: '#5a1a14' },
    pixels: [
      '........................',
      '........................',
      '........................',
      '.................oo.....',
      '.....o.o.o.o.o.ooRRo..o.',
      '....oRoRoRoRoRoRoSSoooRo',
      '....oSoSoSoSoSoSgggeEoSo',
      '.o.ooogggggggggggggggggg',
      'oSoSggggTTTTggggggggwmwm',
      'ogggGgggttttgggggGGGGwgo',
      'GGggGGGggggggggggoooooo.',
      'ooooogyyyyyyyyygooo.....',
      '....ogggoGGoogggoGGo....',
      '...oggoo.oGo.ooggoGo....',
      '...oggo..oGGo.oggoGGo...',
      '..okkkko.okkkokkkkkkko..',
    ],
  },
  // The Mighty Gorgon is blacker, with plates over its flank and haunch, a spiked back and longer horns.
  mightyGorgon: {
    palette: { o: OUTLINE, m: '#1c201c', M: '#0c0e0c', g: '#3a403a', n: '#2e7a32', N: '#5ab04a', d: '#143a16', h: BONE, H: BONE_SHADOW, r: '#a0ff60' },
    pixels: [
      '................o......o',
      '...........o.o.oHo....oh',
      '.........ooNoNoNHo....oh',
      '.......ooNoNNNNNoHo..ooh',
      '......oNoNNndnndnHo.ohho',
      '..ooooNNNdnndnndnmHohoo.',
      '.omnndnndnmTTmmmmmnNNo..',
      'omomNNNNNmmTTmNNNmmnnro.',
      'omomnndnnmmTTmndnMmmmnno',
      'omoMMMmmmmmTTmmmmMMmmmgg',
      'MMoomMMMMMMttMMMmooMmggM',
      'Mo.ommmMMoooommgMMoooooo',
      'o...onnoMMo.onnoMMo.....',
      '....omgoMMo.omgoMMo.....',
      '....omgoMMo.omgoMMo.....',
      '....oddoddo.oddoddo.....',
    ],
  },
  // The Wyvern Monarch is darker with purple wings, a horn on its snout and a venomous stinger tail.
  wyvernMonarch: {
    palette: { o: OUTLINE, D: '#5a6a3a', d: '#38422a', B: '#b8a0c8', W: '#7a4a8a', w: '#56306a', s: '#2e1a3a', S: '#f0e0a0', e: '#ffd020', f: BONE, m: '#3a0a1a', k: '#1a1a10' },
    pixels: [
      '..ooWWoosWooko...ooo....',
      '.oksWWWWWsWoso..oSSSoo..',
      '..oWssWWWsWWso.oSDDDoSo.',
      '...oWwssWWsWsooSoDDeDDDo',
      '..ooWWwwswWssWooDDDDDfmo',
      '.oSSoWWwwssWssSDDBoDDDfo',
      '.oSo.ooWWwwsssDDBo.oooo.',
      'oDo....oooWWDsDoo.......',
      'oDo....oDDTTTDDDo.......',
      'oDo...oDDDDDBBBBo.......',
      '.oDooooDddDBDDBo........',
      '.oDDDDDoddoDDDo.........',
      '..ooooooddooDDo.........',
      '........odooDo..........',
      '........oddoDDo.........',
      '.......okkkokkko........',
    ],
  },
  // The Chaos Hydra is darker, sprouts six heads and glares with red eyes.
  chaosHydra: {
    palette: { o: OUTLINE, B: '#2e4a26', b: '#1a2e16', L: '#7a8a4a', N: '#3a5e2e', H: '#4a7038', j: '#1a2e16', e: '#ff2818', r: '#ff8a20', k: '#141010', S: '#c8b890' },
    pixels: [
      '..........oHeHooHeHo....',
      '..........ojjjoojjjro...',
      '......ooo.oNNo.oNNooooo.',
      '.....oHeHooNNo.oNNooHeHo',
      '....orjjjo.oNNooNNoojjjo',
      '..oooooNNoooNNooNNooNNo.',
      '.oHeHo.oNNNoNNooNNooNo..',
      '.ojjjo..ooNNNoNoNooNNoo.',
      '..oNNNoooSNNoNNNNNNNHeHo',
      '...ooNNNNoBNNNNNNNoojjjr',
      '...oBBBBNNNNBBBBBBooNNoo',
      '.ooBBBBBBBBBBBBBNNNNNo..',
      'oBBBbbbBBBBBBBBBBoooo...',
      'BBBoBBLLLLLLLLBBo.......',
      'ooooBBooboooboBBo.......',
      '...okkooko.okokkko......',
    ],
  },
} satisfies Partial<Record<UpgradedCreature, Sprite>>
