import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, BONE, BONE_SHADOW, GOLD, type Sprite } from './shared'

/** Inferno: its creatures, heroes, town emblem and homeland obstacles. */
export const INFERNO_SPRITES = {
  imp: {
    palette: { o: OUTLINE, r: '#d04020', R: '#902a14', W: '#7a1e10', y: '#ffd040', k: '#1a1418', w: '#f0f0f0' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......o.........',
      '.....oRo.o......',
      '......oRoRo.....',
      '...oo.orrro.....',
      '..oWWoorryo.....',
      '..oWoWrrrkwo....',
      '..ooWrrrrooro...',
      '.oRoorrrrrro....',
      '.oRooRrTooo.....',
      '..oRRororo......',
      '...ooororo......',
      '....oRRoRRo.....',
    ],
  },
  gog: {
    palette: { o: OUTLINE, g: '#a04a30', G: '#c87050', D: '#6a2a18', y: '#ffd040', k: '#1a1418', w: '#f0f0f0', h: '#3a2a24', f: '#ff9020' },
    pixels: [
      '................',
      '..y...o.........',
      '.foooohoo.......',
      '.offfoohgooo....',
      '.ofyfogggDDDo...',
      '.offfoggggyo....',
      '..oogogggggo....',
      '...ogoogggkko...',
      '....ogggggowo...',
      '....ogggggoo....',
      '...oggggGgggo...',
      '....ogggGGoogo..',
      '....ogTTTTo.o...',
      '.....ogoogo.....',
      '.....ogoogo.....',
      '....oDDooDDo....',
    ],
  },
  hellHound: {
    palette: { o: OUTLINE, d: '#6a2a1a', D: '#401810', f: '#ff8020', y: '#ffd040', k: '#1a1418', w: '#f0f0f0' },
    pixels: [
      '................',
      '................',
      '................',
      '...........o....',
      'y........yoDoo..',
      '.o......fofDddo.',
      'odo....yofodydoo',
      'odo.ooooffoddddd',
      '.ododddddddTokkw',
      '..oddddddddToooo',
      '..odddddddddo...',
      '..ododoooododo..',
      '..ododo..ododo..',
      '..ododo..ododo..',
      '.oDDoDDo.oDDDDo.',
      '..oo.oo...oooo..',
    ],
  },
  demon: {
    palette: { o: OUTLINE, r: '#c04040', R: '#8a2828', p: '#d86a6a', y: '#ffd040', k: '#1a1418', h: '#e8dcc0', w: '#efe7cf' },
    pixels: [
      '......ohhoohho..',
      '......oho.oho...',
      '.......ohoho....',
      '.......orrro....',
      '.......orrryo...',
      '.....ooorrroo...',
      '....orrrrrokwo..',
      '...oRrrrprroo...',
      '..oRrrrrrroro...',
      '..oRrrrrrroro...',
      '..oRorrrro.oro..',
      '..oRoTTTTToorwo.',
      '.owwooRooRoowwo.',
      '..oo.oRooRo.oo..',
      '.....oRooRo.....',
      '....okkookko....',
    ],
  },
  pitFiend: {
    palette: { o: OUTLINE, m: '#6a1a1a', M: '#4a1010', l: '#8a2a2a', y: '#ffb020', k: '#140c0c', h: '#d8ccb0', w: '#efe7cf' },
    pixels: [
      '.....oo..oho....',
      '....ohhooho.....',
      '.....oohmmo.....',
      '......ommyo.....',
      '......ommmo.....',
      '.....ommmoko....',
      '....ommmmmo..o..',
      '...oMmmllmmoowo.',
      '...oMmmmlmommo..',
      '...oMmmmmmooowo.',
      '....oTTTTTo..o..',
      'Mo..oMmoomo.....',
      'oMooMmo..omo....',
      '.oMMoomoomo.....',
      '..oo.omoomo.....',
      '....okkookko....',
    ],
  },
  efreet: {
    palette: { o: OUTLINE, r: '#e05020', R: '#b03818', f: '#ffa030', y: '#fff0a0', g: '#e6b43c', k: '#1a1418' },
    pixels: [
      '......yofo......',
      '......offo......',
      '.......orro.....',
      '......orryo.....',
      '......orrro.....',
      '.....ooroo..oo..',
      '....orrrrroorRo.',
      '...orrrRRrrgoo..',
      '...orrrrrroo....',
      '....orrrrro.....',
      '.....oTTTTo.....',
      '.....offfo......',
      '...f.offoy......',
      '....offo........',
      '...offo.........',
      '...yoo..........',
    ],
  },
  devil: {
    palette: { o: OUTLINE, d: '#401418', D: '#6a2028', W: '#6a2430', B: '#3a0e14', y: '#ffb020', h: '#d8ccb0', k: '#120808', w: '#efe7cf' },
    pixels: [
      '.ooWBooho.oho...',
      'oBoWBohBhoho....',
      'oWoWooWWdddo....',
      '.oWBWBWBddyo....',
      '.oWoWWWWdddo....',
      '..o.oBWddoko....',
      '.....oddddo..o..',
      '.....oddDddoowo.',
      '.....oddDdoddo..',
      '.....oddddooowo.',
      '.....odTTTo..o..',
      '....odododo.....',
      '...ododo.odo....',
      'Doodo.ododo.....',
      'oddo..ododo.....',
      '.oo..okkokko....',
    ],
  },
  lavaRock: {
    palette: { o: OUTLINE, g: '#4a3a38', G: '#2e2422', d: '#1c1614', f: '#ff8a20', y: '#ffd040', r: '#e0401a' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oogggggoo...',
      '...oggggGgggo...',
      '..oggfgGGgggGo..',
      '..ogGfyfgGgGGo..',
      '.ooggGrfggGGGo..',
      '.ogggGGrfGGGGGo.',
      '.ogggGGGfyfGdGo.',
      '.oGgggGGGGrfddo.',
      '.oGGrfGGGGddddo.',
      '..odddddddddddo.',
      '...ooooooooooo..',
    ],
  },
  fireVent: {
    palette: { o: OUTLINE, y: '#ffe060', f: '#ff8a20', r: '#e0401a', s: '#c8b040', S: '#8a7428', d: '#3a2e1c' },
    pixels: [
      '................',
      '.......y........',
      '......yfy.......',
      '.....yffy.y.....',
      '.....fyfffy.....',
      '....ffyyyff.....',
      '....frfyyfr.....',
      '.....rffffr.....',
      '......rffr......',
      '....oooooooo....',
      '...osSddddSso...',
      '..ossSddddSsso..',
      '.ossssSSSSssSso.',
      '.oSssssssssSSdo.',
      '..odddddddddddo.',
      '...ooooooooooo..',
    ],
  },
  fiona: {
    palette: { o: OUTLINE, h: '#c02818', H: '#7a1810', s: SKIN, d: '#141018', r: '#e02020', y: GOLD, m: BONE },
    pixels: [
      '.o............o.',
      '.omo........omo.',
      '..ohoooooooooo..',
      '..ohhhhhhhhhho..',
      '.ohhhssssssshho.',
      '.ohhssssssssHho.',
      '.ohhsddssddsHho.',
      '.ohhssssssssHho.',
      '.ohhssssssssHho.',
      '.oHhsssrrsssHho.',
      '.oHHossssssoHHo.',
      '.oHHHoooooooHHo.',
      '.ooHHTTTTTTHHoo.',
      '.oTTTTTTTTTTTTo.',
      '.oTTTTTyyTTTTTo.',
      '.oooooooooooooo.',
    ],
  },
  rashka: {
    palette: { o: OUTLINE, f: '#ff8a20', F: '#e0501a', y: '#ffe060', r: '#c02818', k: '#141018', g: GOLD },
    pixels: [
      '....y..y..y.....',
      '...yfyyfyyfy....',
      '...offfffffo....',
      '..offfFFFfffo...',
      '..offfffffffo...',
      '..ofkkfffkkfo...',
      '..offyfffyffo...',
      '..offffffffFo...',
      '...offrrrrfo....',
      '...oFffffffo....',
      '....oFFFFFo.....',
      '..oooggoooooo...',
      '.offTTTTTTTffo..',
      '.ofTTTTTTTTTfo..',
      '.oFTTTTggTTTFo..',
      '.ooooooooooooo..',
    ],
  },
  xyron: {
    palette: { o: OUTLINE, h: '#3a1a2a', H: '#24101a', s: '#d89878', d: '#141018', r: '#ff3020', m: BONE, y: GOLD, f: '#ff8a20' },
    pixels: [
      '..o..........o..',
      '..omo......omo..',
      '...omooooooomo..',
      '...ohhhhhhhhho..',
      '..ohhhssssshhho.',
      '..ohhssssssshho.',
      '..ohsrrssrrsHho.',
      '..ohssssssssHho.',
      '..ohhsssdssshho.',
      '..oHhssssssHHho.',
      '..oHHosssssoHHo.',
      '..oHHHofffoHHHo.',
      '.ohHHTTTTTTTHHho',
      '.ohTTTTTTTTTTTho',
      '.ohTTTTTyyTTTTho',
      '.ooooooooooooooo',
    ],
  },
  inferno: {
    palette: { o: OUTLINE, s: '#3a2020', S: '#5e3030', f: '#ff6a00', F: '#ffd040', l: '#c02010' },
    pixels: [
      '..o....o....o...',
      '..o...oFo...o...',
      '.oso..oso..oso..',
      '.oso.ossso.oso..',
      '.oSo.osSso.oSo..',
      '.ofo.osfso.ofo..',
      'ossSoossSooossSo',
      'osssoossssooSsso',
      'osfsoosffsoosfso',
      'osssooosssooosso',
      'osSSssSoooSsSSso',
      'ossssssofossssso',
      'oSsssssofFossSso',
      'ossSsssoFfoSssso',
      'olllllllllllllll',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const INFERNO_TINTS = {
  familiar: '#ff8020',
  magog: '#ff4000',
  cerberus: '#802020',
  hornedDemon: '#a02060',
  pitLord: '#ff6000',
  efreetSultan: '#ffd040',
  archDevil: '#500818',
} satisfies Partial<Record<UpgradedCreature, string>>

/** Upgrades that look different enough to need their own drawing rather than a tint of the base creature. */
export const INFERNO_UPGRADE_SPRITES = {
  // Cerberus has three snarling heads on one hound's body.
  cerberus: {
    palette: { o: OUTLINE, d: '#6a2a1a', D: '#401810', f: '#ff8020', y: '#ffd040', k: '#1a1418', w: '#f0f0f0' },
    pixels: [
      '........foDo....',
      '.y......oddddoo.',
      '.foDo...odyddddo',
      '.oddddooyoddkwwo',
      '.odyddddfoDoooo.',
      'y.oddkwwoddddoo.',
      'odooooooodyddddo',
      'odo.ooooooddkwwo',
      '.ododdddddooooo.',
      '..odddddddddTTo.',
      '..odddddddddTTo.',
      '..ododoooododo..',
      '..ododo..ododo..',
      '..ododo..ododo..',
      '.oDDoDDo.oDDDDo.',
      '..oo.oo...oooo..',
    ],
  },
  // The Pit Lord has bigger horns and wields a huge scythe.
  pitLord: {
    palette: { o: OUTLINE, m: '#6a1a1a', M: '#4a1010', l: '#8a2a2a', y: '#ffb020', k: '#140c0c', h: '#d8ccb0', w: '#efe7cf', n: '#5a4030', x: '#c8d0d8', X: '#7a8490' },
    pixels: [
      '...oo....ooooo..',
      '..ohhoo.oxxxxxo.',
      '...oohhoohooXxxo',
      '.....oohmmo.onXo',
      '......ommyo.on.o',
      '.....ommmoko.on.',
      '....ommmmmo..on.',
      '...oMmmllmmoowo.',
      '...oMmmmlmommo..',
      '...oMmmmmmooono.',
      '....oTTTTTo.ono.',
      'Mo..oMmoomo.ono.',
      'oMooMmo..omoono.',
      '.oMMoomoomo.ono.',
      '..oo.omoomo.ono.',
      '....okkookko.o..',
    ],
  },
  // The Horned Demon has huge curved horns and a darker hide.
  hornedDemon: {
    palette: { o: OUTLINE, r: '#a83050', R: '#701c38', p: '#c85a78', y: '#ffd040', k: '#1a1418', h: '#e8dcc0', H: BONE_SHADOW, w: '#efe7cf' },
    pixels: [
      '..oho......oho..',
      '..ohHo....oHho..',
      '...ohHoooohHo...',
      '....oohrrrHoo...',
      '.......orrryo...',
      '.....ooorrroo...',
      '....orrrrrokwo..',
      '...oRrrrprroo...',
      '..oRrrrrrroro...',
      '..oRrrrrrroro...',
      '..oRorrrro.oro..',
      '..oRoTTTTToorwo.',
      '.owwooRooRoowwo.',
      '..oo.oRooRo.oo..',
      '.....oRooRo.....',
      '....okkookko....',
    ],
  },
  // The Arch Devil has larger wings, a gold crown and a gold trident.
  archDevil: {
    palette: { o: OUTLINE, d: '#401418', D: '#6a2028', W: '#6a2430', B: '#3a0e14', y: GOLD, h: '#d8ccb0', k: '#120808', w: '#efe7cf', e: '#ffb020' },
    pixels: [
      'o.o.o..oh..ho.yo',
      'oWoWoo.ohooho.y.',
      'oWoWBo.oyyyyo.y.',
      'oWBWBohBdddo.yyy',
      'oWBWBWWdddeo..y.',
      'oWoWBWWBdddo..y.',
      '.oWoWBWddoko..y.',
      '.oo.oBdddddo.oyo',
      '.....oddDddooowo',
      '.....oddDdoddoyo',
      '.....oddddooo.y.',
      '.....oyTTyo...y.',
      '....odododo...y.',
      '...ododo.odo..y.',
      'Doodo.ododo...y.',
      'oddo.okkokko....',
    ],
  },
  // The Efreet Sultan is wreathed in flames from head to tail.
  efreetSultan: {
    palette: { o: OUTLINE, r: '#e05020', R: '#b03818', f: '#ffa030', F: '#ff6020', y: '#fff0a0', g: '#e6b43c' },
    pixels: [
      '......y.y.......',
      '.....yfyfy......',
      '....yFffffo.....',
      '...yfFforro.....',
      '..yfFforryo.....',
      '..yfFforrro.....',
      '..yfFooroo..oo..',
      '..yforrrrroorRoy',
      '.yfForrRRrrgoofy',
      '.yfForrrrroo.fy.',
      '..yfForrrrro....',
      '...yfoTTTTo.....',
      '...yfoffffoy....',
      '..yfofffoyf.....',
      '..yoffofy.......',
      '..yfooy.........',
    ],
  },
} satisfies Partial<Record<UpgradedCreature, Sprite>>
