import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, WOOD, BOOTS, BONE, GOLD, type Sprite } from './shared'

/** Inferno: its creatures, heroes, town emblem and homeland obstacles. */
export const INFERNO_SPRITES = {
  imp: {
    palette: { o: OUTLINE, r: '#c0302a', R: '#7a1c18', y: '#ffd040', h: BONE, k: '#141018' },
    pixels: [
      '................',
      '................',
      '................',
      '.....o...o......',
      '....oho.oho.....',
      '....orrrrro.....',
      '...orrryrryo....',
      '...orrrrrrro....',
      '....orrkkro.....',
      '.oo..orrro..oo..',
      '.oRooTTTTooRo...',
      '..oRRTTTTRRo....',
      '....otttto......',
      '....oro.oro...o.',
      '....oro.oro..oro',
      '...orro.orroorRo',
    ],
  },
  gog: {
    palette: { o: OUTLINE, g: '#8a6a3a', G: '#5a4224', r: '#e02020', f: '#ff8a20', y: '#ffe060', b: BOOTS },
    pixels: [
      '................',
      '.....oooo.......',
      '....oggggo......',
      '...ogggggo......',
      '...oggrgrgo.....',
      '...ogggggggo....',
      '....oggGGo..oo..',
      '...oTTTTTTooyfo.',
      '..oTTTTTTggoffyo',
      '..ogTTTTToo.offo',
      '..ogtTTTto...oo.',
      '...otttttto.....',
      '....oGo.oGo.....',
      '....oGo.oGo.....',
      '....obo.obo.....',
      '...obbo.obbo....',
    ],
  },
  hellHound: {
    palette: { o: OUTLINE, r: '#8a2a1a', R: '#5a1a10', f: '#ff8a20', y: '#ffd040', k: '#141018', w: '#f0f0f0' },
    pixels: [
      '................',
      '................',
      '..........o.o...',
      '.........oroRo..',
      '........orrrrro.',
      'f......orrryrrro',
      'ff.....orrrrrwwo',
      '.fo..ooorrrrkko.',
      '..orrrrrrrrrro..',
      '..orTTTTTTrrro..',
      '..orTTTTTTrrro..',
      '..orrttttRRRro..',
      '..oRRo...oRRo...',
      '..oRo.....oRo...',
      '..oRo.....oRo...',
      '.oko.....oko....',
    ],
  },
  demon: {
    palette: { o: OUTLINE, r: '#b03024', R: '#6e1a14', h: BONE, y: '#ffd040', k: '#141018' },
    pixels: [
      '...o.....o......',
      '...oho..oho.....',
      '....ohoooho.....',
      '....orrrrro.....',
      '...orryrryro....',
      '...orrrrrrro....',
      '....orkkkro.....',
      '..oooorrrooooo..',
      '.orrrTTTTTTrrro.',
      '.orrTTTTTTTTrro.',
      '.orotTTTTTTtoro.',
      '.oho.ottttto.oho',
      '....oRRo.oRRo...',
      '....oRo...oRo...',
      '...oRRo...oRRo..',
      '...ooo.....ooo..',
    ],
  },
  pitFiend: {
    palette: { o: OUTLINE, r: '#8a2440', R: '#521428', s: '#8a2440', h: BONE, y: '#ffd040', M: STEEL, w: WOOD },
    pixels: [
      '..o.......o.....',
      '..oho....oho....',
      '...ohooooho...o.',
      '...orrrrrro..oMo',
      '..orryrryrro.oMo',
      '..orrrrrrrro.oMo',
      '...orrhhrro..owo',
      '.ooorrrrrrooooso',
      'orrrTTTTTTrrrowo',
      'orRrTTTTTTrrRowo',
      'oRrotTTTTtorRowo',
      '.oo.otttto.oo.wo',
      '....oRRoRRo...wo',
      '....oRo.oRo...o.',
      '...oRRo.oRRo....',
      '...oooo.oooo....',
    ],
  },
  efreet: {
    palette: { o: OUTLINE, f: '#ff8a20', F: '#e0501a', y: '#ffe060', r: '#c02818', k: '#141018' },
    pixels: [
      '.....y..y.......',
      '....yfyyfy......',
      '....offffo......',
      '...offkfkfo.....',
      '...offffffo.....',
      '....offFfo......',
      '.ooooTTTTooooo..',
      'offfTTTTTTfffo..',
      'oFfoTTTTTToFfo..',
      '.oo.otTTto.oo...',
      '.....offfo......',
      '.....oFffyo.....',
      '......oFfyo.....',
      '.......oFfo.....',
      '........oyo.....',
      '.........o......',
    ],
  },
  devil: {
    palette: { o: OUTLINE, r: '#9a1a1a', R: '#5a0e0e', h: BONE, k: '#141018', y: '#ffd040', M: STEEL },
    pixels: [
      '..oo......oo....',
      '.oho.oooo.oho...',
      '..oooorrrooo..o.',
      'oo..orryryro.oMo',
      'oRo.orrrrrro.oMo',
      'oRRo.orkkro..oMo',
      'oRRRoorrroo.oMMo',
      'oRRRTTTTTTTrrro.',
      'oRRoTTTTTTTo.o..',
      '.oo.otTTTTto....',
      '....otttttto....',
      '....orro.orro...',
      '....oro...oro...',
      '....oro...oro...',
      '...orro...orro..',
      '...oooo...oooo..',
    ],
  },
  lavaRock: {
    palette: { o: OUTLINE, g: '#4a3a38', G: '#2e2422', d: '#1c1614', f: '#ff8a20', y: '#ffd040', r: '#e0401a' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oogggggoo...',
      '...oggggGgggo...',
      '..oggfgGGgggGo..',
      '..ogGfyfgGgGGo..',
      '.ooggGrfggGGGo..',
      '.ogggGGrfGGGGGo.',
      '.ogggGGGfyfGdGo.',
      '.oGgggGGGGrfddo.',
      '.oGGrfGGGGddddo.',
      '..odddddddddddo.',
      '...ooooooooooo..',
    ],
  },
  fireVent: {
    palette: { o: OUTLINE, y: '#ffe060', f: '#ff8a20', r: '#e0401a', s: '#c8b040', S: '#8a7428', d: '#3a2e1c' },
    pixels: [
      '................',
      '.......y........',
      '......yfy.......',
      '.....yffy.y.....',
      '.....fyfffy.....',
      '....ffyyyff.....',
      '....frfyyfr.....',
      '.....rffffr.....',
      '......rffr......',
      '....oooooooo....',
      '...osSddddSso...',
      '..ossSddddSsso..',
      '.ossssSSSSssSso.',
      '.oSssssssssSSdo.',
      '..odddddddddddo.',
      '...ooooooooooo..',
    ],
  },
  fiona: {
    palette: { o: OUTLINE, h: '#c02818', H: '#7a1810', s: SKIN, d: '#141018', r: '#e02020', y: GOLD, m: BONE },
    pixels: [
      '.o............o.',
      '.omo........omo.',
      '..ohoooooooooo..',
      '..ohhhhhhhhhho..',
      '.ohhhssssssshho.',
      '.ohhssssssssHho.',
      '.ohhsddssddsHho.',
      '.ohhssssssssHho.',
      '.ohhssssssssHho.',
      '.oHhsssrrsssHho.',
      '.oHHossssssoHHo.',
      '.oHHHoooooooHHo.',
      '.ooHHTTTTTTHHoo.',
      '.oTTTTTTTTTTTTo.',
      '.oTTTTTyyTTTTTo.',
      '.oooooooooooooo.',
    ],
  },
  rashka: {
    palette: { o: OUTLINE, f: '#ff8a20', F: '#e0501a', y: '#ffe060', r: '#c02818', k: '#141018', g: GOLD },
    pixels: [
      '....y..y..y.....',
      '...yfyyfyyfy....',
      '...offfffffo....',
      '..offfFFFfffo...',
      '..offfffffffo...',
      '..ofkkfffkkfo...',
      '..offyfffyffo...',
      '..offffffffFo...',
      '...offrrrrfo....',
      '...oFffffffo....',
      '....oFFFFFo.....',
      '..oooggoooooo...',
      '.offTTTTTTTffo..',
      '.ofTTTTTTTTTfo..',
      '.oFTTTTggTTTFo..',
      '.ooooooooooooo..',
    ],
  },
  xyron: {
    palette: { o: OUTLINE, h: '#3a1a2a', H: '#24101a', s: '#d89878', d: '#141018', r: '#ff3020', m: BONE, y: GOLD, f: '#ff8a20' },
    pixels: [
      '..o..........o..',
      '..omo......omo..',
      '...omooooooomo..',
      '...ohhhhhhhhho..',
      '..ohhhssssshhho.',
      '..ohhssssssshho.',
      '..ohsrrssrrsHho.',
      '..ohssssssssHho.',
      '..ohhsssdssshho.',
      '..oHhssssssHHho.',
      '..oHHosssssoHHo.',
      '..oHHHofffoHHHo.',
      '.ohHHTTTTTTTHHho',
      '.ohTTTTTTTTTTTho',
      '.ohTTTTTyyTTTTho',
      '.ooooooooooooooo',
    ],
  },
  inferno: {
    palette: { o: OUTLINE, s: '#3a2020', S: '#5e3030', f: '#ff6a00', F: '#ffd040', l: '#c02010' },
    pixels: [
      '..o....o....o...',
      '..o...oFo...o...',
      '.oso..oso..oso..',
      '.oso.ossso.oso..',
      '.oSo.osSso.oSo..',
      '.ofo.osfso.ofo..',
      'ossSoossSooossSo',
      'osssoossssooSsso',
      'osfsoosffsoosfso',
      'osssooosssooosso',
      'osSSssSoooSsSSso',
      'ossssssofossssso',
      'oSsssssofFossSso',
      'ossSsssoFfoSssso',
      'olllllllllllllll',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const INFERNO_TINTS = {
  familiar: '#ff8020',
  magog: '#ff4000',
  cerberus: '#802020',
  hornedDemon: '#a02060',
  pitLord: '#ff6000',
  efreetSultan: '#ffd040',
  archDevil: '#500818',
} satisfies Partial<Record<UpgradedCreature, string>>
