import type { UpgradedCreature } from '../../../game'
import { OUTLINE, BONE, BONE_SHADOW, GOLD, type Sprite } from './shared'

/** Necropolis: its creatures, heroes, town emblem and homeland obstacles. */
export const NECROPOLIS_SPRITES = {
  skeleton: {
    palette: { o: OUTLINE, w: BONE, W: BONE_SHADOW, k: '#2a2024', m: '#c8d0d8', y: '#8a6a3a' },
    pixels: [
      '.....oooo.......',
      '....owwwwo......',
      '...owwwwwwo.....',
      '...owwwwkko.....',
      '...oWwwwkwo....o',
      '...oWWwwwoko..om',
      '....oooWkWko.omo',
      '....ooWoooo.omo.',
      '...owwwwwoyomo..',
      '...oWwWwwoowo...',
      '..oWooWoowwoyo..',
      '..oWooWo.oo.o...',
      '...ooWWWo.......',
      '....oWoowo......',
      '...oWo..owo.....',
      '..oWWo..owwo....',
    ],
  },
  walkingDead: {
    palette: { o: OUTLINE, g: '#8a9a6a', G: '#5a6a44', r: '#6a5038', R: '#4a3626', k: '#2a2024', e: '#e03020' },
    pixels: [
      '................',
      '.......oo.......',
      '......okko......',
      '......ogggo.....',
      '......ogggeo....',
      '......ogggo.....',
      '.....orrrokoooo.',
      '....orrrrggggggo',
      '....orrTrGGGGGo.',
      '....orrrrroooo..',
      '.....oggro......',
      '.....oRooRo.....',
      '.....oRooRo.....',
      '.....oRooRo.....',
      '.....oRooRo.....',
      '....oGGooGGo....',
    ],
  },
  wight: {
    palette: { o: '#0a0810', h: '#dfe3ee', H: '#a8b0c4', s: '#c8d0dc', e: '#7af0ff', k: '#141018', P: '#5a6280', p: '#3a4060', c: '#a8b0c0' },
    pixels: [
      '....oohoo.......',
      '...ohhhhho......',
      '..ohhhhssso.....',
      '..ohhhsssso.....',
      '..ohhhssseo.....',
      '..ohhhsssso..o..',
      '..oHhhhssko.oco.',
      '..oHHhPPooooso..',
      '..oHPTPPPsssoco.',
      '.oHHPPTPPPoo.o..',
      '.oHHPPPTPPo.....',
      '.oHoPPPPTPo.....',
      '..ooPpPPPpo.....',
      '....oPpppoo.....',
      '...opopopopo....',
      '....opo.opo.....',
    ],
  },
  vampire: {
    palette: { o: OUTLINE, c: '#201820', r: '#a02020', s: '#d8d4e0', h: '#141018', k: '#3a2e48', e: '#ff2020', w: '#f0f0f0' },
    pixels: [
      '................',
      '.o.....ooo......',
      'oco...oshho.....',
      'occoo.ossseo....',
      'occccooossso....',
      'occcrrrcsswo....',
      'ccccrrrckooo.o..',
      'ccccrrrkTkssowo.',
      'ccccrrrkkTooswo.',
      'occcrrrkkko.oo..',
      '.oocrrrkkko.....',
      '...ooccoko......',
      '.....oookko.....',
      '.......okko.....',
      '.......okko.....',
      '......occcco....',
    ],
  },
  lich: {
    palette: { o: OUTLINE, p: '#3a2a4a', P: '#241830', y: '#d0a030', w: BONE, W: BONE_SHADOW, g: '#70ff90', n: '#5a4030' },
    pixels: [
      '.......oo..owog.',
      '......oppoowwgo.',
      '.....oppwpoowo..',
      '....oppwwgoonog.',
      '.....opwwwoono..',
      '.....oopWWoono..',
      '....opppyooono..',
      '...oppppypppwo..',
      '...oppppypoono..',
      '...opTTTypoono..',
      '...oppppypoono..',
      '...oppppypoono..',
      '...opPppypoono..',
      '...opPppypoono..',
      '....oPppyooono..',
      '...oyyyyyyyono..',
    ],
  },
  blackKnight: {
    palette: {
      o: OUTLINE,
      a: '#3a3a44',
      A: '#22222a',
      n: '#5a4030',
      w: '#c8c0a8',
      r: '#ff3020',
      k: '#1a1418',
    },
    pixels: [
      'oooon...........',
      'oTTTn.o..o......',
      'oTtTn.oaao......',
      'oTTTnoaawro.....',
      'otTon.oawko.oo..',
      '.o.on.oAaaAowwo.',
      '....noAaaaaowrwo',
      '....noAaaaAowwwo',
      '.ooooooooowwooo.',
      'oTTTTATTTTwwo...',
      'otTTTATTTTto....',
      'otTTTTTTTTto....',
      'otttttttttto....',
      '.owowo....owowo.',
      '.owowo....owowo.',
      '.oAoAo....oAoAo.',
    ],
  },
  boneDragon: {
    palette: { o: OUTLINE, b: BONE, B: BONE_SHADOW, g: '#60f0a0' },
    pixels: [
      '..o...o...oBo...',
      '.obo.obo.o.oBoo.',
      '..oboobooBoobbbo',
      '...obooboBoobgbb',
      '....oboboBobooob',
      '.....obobBobooBB',
      '....ooobbBTo..oo',
      '...obbbbbbo.....',
      'oo.obbobobo.....',
      'BBooobobobo.....',
      'ooBBobobobo.....',
      '..ooBoBoobbo....',
      '...oBoBo.obo....',
      '..oBooBo..obo...',
      '..oBo.o...obo...',
      '...o.......o....',
    ],
  },
  deadTree: {
    palette: { o: OUTLINE, b: '#6a5240', B: '#3a2c22' },
    pixels: [
      '.oo........oo...',
      '.obo......obo...',
      '..obo....obo..o.',
      '...obo..obo..obo',
      '....oboobo..obo.',
      'oo...obbo..obo..',
      'obo..obBo.obo...',
      '.obo.obBoobo....',
      '..obbobBbbo.....',
      '...oobBbo.......',
      '.....obBo.......',
      '.....obBo.......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '....oobbBBoo....',
    ],
  },
  tombstone: {
    palette: { o: OUTLINE, l: '#9a9aa2', g: '#6a6a72', d: '#3a3230' },
    pixels: [
      '................',
      '................',
      '................',
      '.....oooooo.....',
      '....ollllllo....',
      '...ollllllllo...',
      '...olllolllgo...',
      '...ollooolggo...',
      '...olllolllgo...',
      '...olllolllgo...',
      '...ollllllggo...',
      '...ollllllggo...',
      '...olllllgggo...',
      '..oooooooooooo..',
      '.odddddddddddddo',
      '..oooooooooooo..',
    ],
  },
  vokial: {
    palette: { o: OUTLINE, k: '#2a2030', f: '#4a3440', r: '#ff3030', p: '#d07890', w: '#f0f0f0' },
    pixels: [
      '.o............o.',
      '.oo..........oo.',
      '.oko..oooo..oko.',
      '.okkooffffookko.',
      '..okkffffffkko..',
      '...offrffrffo...',
      '...offffffffo...',
      '...offfppfffo...',
      '...offwffwffo...',
      '....offffffo....',
      '.....oooooo.....',
      '.oooooTTTTooooo.',
      '.okkooTTTTookko.',
      '.okkkkTTTTkkkko.',
      '.okkkkTTttkkkko.',
      '.oooooooooooooo.',
    ],
  },
  septienna: {
    palette: { o: OUTLINE, k: '#2a1e30', b: BONE, v: '#c060ff', d: '#141018', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....okkkkkko....',
      '...okkkkkkkko...',
      '...okkbbbbkko...',
      '...okbbbbbbko...',
      '...okdvbbvdko...',
      '...okbbbbbbko...',
      '...okbbddbbko...',
      '...okkbdbdkko...',
      '.oko.okkkko.oko.',
      '.okkooTTTTookko.',
      '.okkkoTTTTokkko.',
      '.okkkkTyyTkkkko.',
      '.okkkkTTTTkkkko.',
      '.oooooooooooooo.',
    ],
  },
  thant: {
    palette: { o: OUTLINE, y: GOLD, b: BONE, g: '#40e060', d: '#141018', k: '#2a2a22' },
    pixels: [
      '....y..yy..y....',
      '...oyyyyyyyyo...',
      '..obbbbbbbbbbo..',
      '..obbbbbbbbbbo..',
      '..obggbbbbggbo..',
      '..obddbbbbddbo..',
      '..obbbbddbbbbo..',
      '..oobbbbbbbboo..',
      '...obdbdbdbdo...',
      '...obbbbbbbbo...',
      '....oooooooo....',
      '.ookkkobbokkkoo.',
      '.okTbbbbbbbbTko.',
      '.okTkkkkkkkkTko.',
      '.okTbbbbbbbbTko.',
      '.oooooooooooooo.',
    ],
  },
  necropolis: {
    palette: { o: OUTLINE, p: '#6a6478', P: '#3e3850', g: '#7cff8a', b: BONE },
    pixels: [
      '.......o........',
      '.......o........',
      '......opo.......',
      '......opo.......',
      '.....oppPo......',
      '.o...opgPo...o..',
      'opo..oppPo..opo.',
      'opo..oppPo..opo.',
      'opPooopgPoooopPo',
      'ogPoopppPPoopgPo',
      'opPoopppPPoopPPo',
      'opPooooooooopPPo',
      'opPoobbbbbboopPo',
      'opPoobobbobPopPo',
      'opPoobbbbbbPopPo',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const NECROPOLIS_TINTS = {
  skeletonWarrior: '#a0b0c0',
  zombie: '#60a060',
  wraith: '#7040a0',
  vampireLord: '#c02040',
  powerLich: '#40e080',
  dreadKnight: '#6020a0',
  ghostDragon: '#a0f0ff',
} satisfies Partial<Record<UpgradedCreature, string>>
