import type { UpgradedCreature } from '../../../game'
import { OUTLINE, BONE, BONE_SHADOW, GOLD, type Sprite } from './shared'

/** Necropolis: its creatures, heroes, town emblem and homeland obstacles. */
export const NECROPOLIS_SPRITES = {
  skeleton: {
    palette: { o: OUTLINE, w: BONE, W: BONE_SHADOW, k: '#2a2024', m: '#c8d0d8', y: '#8a6a3a' },
    pixels: [
      '................',
      '......ooo.......',
      '.....owwwo......',
      '....owwwkwo.....',
      '....oWwwkwo....o',
      '.....oWwwko...om',
      '......oWkWo..omo',
      '....ooWoooo.omo.',
      '...owwwwwoyomo..',
      '...oWwWwwoowo...',
      '..oWooWoowwoyo..',
      '..oWooWo.oo.o...',
      '...ooWWWo.......',
      '....oWoowo......',
      '...oWo..owo.....',
      '..oWWo..owwo....',
    ],
  },
  walkingDead: {
    palette: { o: OUTLINE, g: '#7f93a8', G: '#55677c', r: '#6a5038', R: '#4a3626', k: '#2a2024' },
    pixels: [
      '................',
      '.......oo.......',
      '......okko......',
      '......ogggo.....',
      '......ogggko....',
      '......ogggo.....',
      '.....orrrokoooo.',
      '....orrrrggggggo',
      '....orrTrGGGGGo.',
      '....orrrrroooo..',
      '.....oggro......',
      '.....oRooRo.....',
      '.....oRooRo.....',
      '.....oRooRo.....',
      '.....oRooRo.....',
      '....oGGooGGo....',
    ],
  },
  wight: {
    palette: { o: '#0a0810', h: '#dfe3ee', H: '#a8b0c4', s: '#c8d0dc', e: '#7af0ff', k: '#141018', P: '#5a6280', p: '#3a4060', c: '#a8b0c0' },
    pixels: [
      '....oohoo.......',
      '...ohhhhho......',
      '..ohhhhssso.....',
      '..ohhhsssso.....',
      '..ohhhssseo.....',
      '..ohhhsssso..o..',
      '..oHhhhssko.oco.',
      '..oHHhPPooooso..',
      '..oHPTPPPsssoco.',
      '.oHHPPTPPPoo.o..',
      '.oHHPPPTPPo.....',
      '.oHoPPPPTPo.....',
      '..ooPpPPPpo.....',
      '....oPpppoo.....',
      '...opopopopo....',
      '....opo.opo.....',
    ],
  },
  vampire: {
    palette: { o: OUTLINE, c: '#201820', r: '#a02020', s: '#d8d4e0', h: '#141018', k: '#3a2e48', e: '#ff2020', w: '#f0f0f0' },
    pixels: [
      '................',
      '.o.....ooo......',
      'oco...oshho.....',
      'occoo.ossseo....',
      'occccooossso....',
      'occcrrrcsswo....',
      'ccccrrrckooo.o..',
      'ccccrrrkTkssowo.',
      'ccccrrrkkTooswo.',
      'occcrrrkkko.oo..',
      '.oocrrrkkko.....',
      '...ooccoko......',
      '.....oookko.....',
      '.......okko.....',
      '.......okko.....',
      '......occcco....',
    ],
  },
  lich: {
    palette: { o: OUTLINE, p: '#3a2a4a', P: '#241830', y: '#d0a030', w: BONE, W: BONE_SHADOW, g: '#70ff90', n: '#5a4030' },
    pixels: [
      '.......oo..owog.',
      '......oppoowwgo.',
      '.....oppwpoowo..',
      '....oppwwgoonog.',
      '.....opwwwoono..',
      '.....oopWWoono..',
      '....opppyooono..',
      '...oppppypppwo..',
      '...oppppypoono..',
      '...opTTTypoono..',
      '...oppppypoono..',
      '...oppppypoono..',
      '...opPppypoono..',
      '...opPppypoono..',
      '....oPppyooono..',
      '...oyyyyyyyono..',
    ],
  },
  blackKnight: {
    palette: {
      o: OUTLINE,
      a: '#3a3a44',
      A: '#22222a',
      n: '#5a4030',
      w: '#c8c0a8',
      r: '#ff3020',
      k: '#1a1418',
    },
    pixels: [
      'oooon...........',
      'oTTTn.o..o......',
      'oTtTn.oaao......',
      'oTTTnoaawro.....',
      'otTon.oawko.oo..',
      '.o.on.oAaaAowwo.',
      '....noAaaaaowrwo',
      '....noAaaaAowwwo',
      '.ooooooooowwooo.',
      'oTTTTATTTTwwo...',
      'otTTTATTTTto....',
      'otTTTTTTTTto....',
      'otttttttttto....',
      '.owowo....owowo.',
      '.owowo....owowo.',
      '.oAoAo....oAoAo.',
    ],
  },
  boneDragon: {
    palette: { o: OUTLINE, b: BONE, B: BONE_SHADOW, g: '#60f0a0' },
    pixels: [
      '..o...o...oBo...',
      '.obo.obo.o.oBoo.',
      '..oboobooBoobbbo',
      '...obooboBoobgbb',
      '....oboboBobooob',
      '.....obobBobooBB',
      '....ooobbBTo..oo',
      '...obbbbbbo.....',
      'oo.obbobobo.....',
      'BBooobobobo.....',
      'ooBBobobobo.....',
      '..ooBoBoobbo....',
      '...oBoBo.obo....',
      '..oBooBo..obo...',
      '..oBo.o...obo...',
      '...o.......o....',
    ],
  },
  deadTree: {
    palette: { o: OUTLINE, b: '#6a5240', B: '#3a2c22' },
    pixels: [
      '.oo........oo...',
      '.obo......obo...',
      '..obo....obo..o.',
      '...obo..obo..obo',
      '....oboobo..obo.',
      'oo...obbo..obo..',
      'obo..obBo.obo...',
      '.obo.obBoobo....',
      '..obbobBbbo.....',
      '...oobBbo.......',
      '.....obBo.......',
      '.....obBo.......',
      '......obBo......',
      '......obBo......',
      '.....obbBBo.....',
      '....oobbBBoo....',
    ],
  },
  tombstone: {
    palette: { o: OUTLINE, l: '#9a9aa2', g: '#6a6a72', d: '#3a3230' },
    pixels: [
      '................',
      '................',
      '................',
      '.....oooooo.....',
      '....ollllllo....',
      '...ollllllllo...',
      '...olllolllgo...',
      '...ollooolggo...',
      '...olllolllgo...',
      '...olllolllgo...',
      '...ollllllggo...',
      '...ollllllggo...',
      '...olllllgggo...',
      '..oooooooooooo..',
      '.odddddddddddddo',
      '..oooooooooooo..',
    ],
  },
  vokial: {
    palette: { o: OUTLINE, k: '#2a2030', f: '#4a3440', r: '#ff3030', p: '#d07890', w: '#f0f0f0' },
    pixels: [
      '.o............o.',
      '.oo..........oo.',
      '.oko..oooo..oko.',
      '.okkooffffookko.',
      '..okkffffffkko..',
      '...offrffrffo...',
      '...offffffffo...',
      '...offfppfffo...',
      '...offwffwffo...',
      '....offffffo....',
      '.....oooooo.....',
      '.oooooTTTTooooo.',
      '.okkooTTTTookko.',
      '.okkkkTTTTkkkko.',
      '.okkkkTTttkkkko.',
      '.oooooooooooooo.',
    ],
  },
  septienna: {
    palette: { o: OUTLINE, k: '#2a1e30', b: BONE, v: '#c060ff', d: '#141018', y: GOLD },
    pixels: [
      '................',
      '.....oooooo.....',
      '....okkkkkko....',
      '...okkkkkkkko...',
      '...okkbbbbkko...',
      '...okbbbbbbko...',
      '...okdvbbvdko...',
      '...okbbbbbbko...',
      '...okbbddbbko...',
      '...okkbdbdkko...',
      '.oko.okkkko.oko.',
      '.okkooTTTTookko.',
      '.okkkoTTTTokkko.',
      '.okkkkTyyTkkkko.',
      '.okkkkTTTTkkkko.',
      '.oooooooooooooo.',
    ],
  },
  thant: {
    palette: { o: OUTLINE, y: GOLD, b: BONE, g: '#40e060', d: '#141018', k: '#2a2a22' },
    pixels: [
      '....y..yy..y....',
      '...oyyyyyyyyo...',
      '..obbbbbbbbbbo..',
      '..obbbbbbbbbbo..',
      '..obggbbbbggbo..',
      '..obddbbbbddbo..',
      '..obbbbddbbbbo..',
      '..oobbbbbbbboo..',
      '...obdbdbdbdo...',
      '...obbbbbbbbo...',
      '....oooooooo....',
      '.ookkkobbokkkoo.',
      '.okTbbbbbbbbTko.',
      '.okTkkkkkkkkTko.',
      '.okTbbbbbbbbTko.',
      '.oooooooooooooo.',
    ],
  },
  necropolis: {
    palette: { o: OUTLINE, p: '#6a6478', P: '#3e3850', g: '#7cff8a', b: BONE },
    pixels: [
      '.......o........',
      '.......o........',
      '......opo.......',
      '......opo.......',
      '.....oppPo......',
      '.o...opgPo...o..',
      'opo..oppPo..opo.',
      'opo..oppPo..opo.',
      'opPooopgPoooopPo',
      'ogPoopppPPoopgPo',
      'opPoopppPPoopPPo',
      'opPooooooooopPPo',
      'opPoobbbbbboopPo',
      'opPoobobbobPopPo',
      'opPoobbbbbbPopPo',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const NECROPOLIS_TINTS = {
  skeletonWarrior: '#a0b0c0',
  zombie: '#60a060',
  wraith: '#7040a0',
  vampireLord: '#c02040',
  powerLich: '#40e080',
  dreadKnight: '#6020a0',
  ghostDragon: '#a0f0ff',
} satisfies Partial<Record<UpgradedCreature, string>>

/** Upgrades that look different enough to need their own drawing rather than a tint of the base creature. */
export const NECROPOLIS_UPGRADE_SPRITES = {
  // The Skeleton Warrior wears a steel helmet and carries a round shield.
  skeletonWarrior: {
    palette: { o: OUTLINE, w: BONE, W: BONE_SHADOW, k: '#2a2024', m: '#c8d0d8', M: '#6a7480', y: '#8a6a3a' },
    pixels: [
      '......ooo.......',
      '.....ommmo......',
      '....ommmmMo.....',
      '....oMMMMMo.....',
      '....oWwwkwo....o',
      '.....oWwwko...om',
      '......oWkWo..omo',
      '.oooooWoooo.omo.',
      'oMmmMowwwoyomo..',
      'omTTmoWwwoowo...',
      'omTMToWoowwoyo..',
      'omTTmoWo.oo.o...',
      'oMmmMoWWo.......',
      '.ooooWoowo......',
      '...oWo..owo.....',
      '..oWWo..owwo....',
    ],
  },
  // The Wraith is a darker, shadow-hooded Wight in tattered robes.
  wraith: {
    palette: { o: '#0a0810', h: '#5a5470', H: '#3a3448', s: '#b8c0d0', e: '#e070ff', k: '#100c14', P: '#3a2e4a', p: '#221a2c', c: '#d0d4e0' },
    pixels: [
      '....oohoo.......',
      '...ohhhhho......',
      '..ohhhhhkko.....',
      '.oHhhhkssso.....',
      '.oHhhhksseo.....',
      'oHoHhhkssso..o..',
      '.oHHhhhkkko.oco.',
      'oHoHHhPPooooso..',
      '.oHHPTPPPsssoco.',
      'oHoHPPTPPPoo.o..',
      'oHHPPPPTPPo.....',
      '.oHoPPPPTPo.....',
      '..ooPpPPPpo.....',
      '...oPpPpppo.....',
      '..opo.opopopo...',
      '..o...o.o.o.....',
    ],
  },
  // The Vampire Lord's cape rises into a tall gold-edged collar.
  vampireLord: {
    palette: { o: OUTLINE, c: '#201820', r: '#a02020', s: '#d8d4e0', h: '#141018', k: '#3a2e48', e: '#ff2020', w: '#f0f0f0', y: GOLD },
    pixels: [
      '...oo...........',
      '.o.oyo.ooo......',
      'ocoyrcoshho.....',
      'occyrcossseo....',
      'occyrcoossso....',
      'occcrrrcsswo....',
      'ccccrrrykooo.o..',
      'ccccrrrkTkssowo.',
      'ccccrrrkkTooswo.',
      'occcrrrkkko.oo..',
      'occcrrrkkko.....',
      '.occrrrckko.....',
      '..occrrckko.....',
      '...oocckkko.....',
      '.....oookko.....',
      '......occcco....',
    ],
  },
  // The Power Lich wears a gold crown and raises a staff topped with a large glowing orb.
  powerLich: {
    palette: { o: OUTLINE, p: '#4a1838', P: '#2e0c22', y: GOLD, w: BONE, W: BONE_SHADOW, g: '#70ff90', G: '#d0ffd8', n: '#5a4030' },
    pixels: [
      '......y.y.y.ooo.',
      '.....oyyyyyoggGo',
      '.....oppwwoogggo',
      '....oppwwgoogggo',
      '.....opwwwo.ooo.',
      '.....oopWWo.ono.',
      '....opppyoo.ono.',
      '...oppppyppppwo.',
      '...oppppypo.ono.',
      '...opTTTypo.ono.',
      '...oppppypo.ono.',
      '...oppppypo.ono.',
      '...opPppypo.ono.',
      '...opPppypo.ono.',
      '....oPppyoo.ono.',
      '...oyyyyyyyoono.',
    ],
  },
  // The Dread Knight trades the banner for a red cape and rides a skull-faced steed with a skull on its barding.
  dreadKnight: {
    palette: { o: OUTLINE, a: '#3a3a44', A: '#22222a', n: '#5a4030', w: '#c8c0a8', r: '#ff3020', k: '#1a1418', c: '#b01c1c', C: '#6a0e0e', b: BONE, B: BONE_SHADOW },
    pixels: [
      '....n.o...o.....',
      '....n.o..o......',
      '....n.oaao......',
      '....noaawro.....',
      '....n.oawko.oo..',
      '..occnoAaaAobbo.',
      '.occnoAaaaaokrbo',
      'occCnoAaaaAobbko',
      'occCCooooobbowwo',
      'oCcTTATTTTBbo...',
      'oCoTbbbTTTto....',
      'otTTkbkTTTto....',
      'otttttttttto....',
      '.obobo....obobo.',
      '.oBoBo....oBoBo.',
      '.okoko....okoko.',
    ],
  },
  // The Ghost Dragon is a pale, spectral Bone Dragon with torn membranes between its wing bones.
  ghostDragon: {
    palette: { o: OUTLINE, g: '#d8f0f0', G: '#90b8c0', m: '#4a7080', e: '#60f0ff' },
    pixels: [
      '..o...o...ogo...',
      '.ogomogomo.oGoo.',
      '..ogmmgmmGoogggo',
      '...ogmmgmGoogegg',
      '....ogmgmGogooog',
      '.....ogmgGogooGG',
      '....m.oggGTo..oo',
      '...oggggggo.....',
      'oo.oggGgGgo.....',
      'GGooggGgGgo.....',
      'ooGGogGgGgo.....',
      '..ooGoGoogGo....',
      '...oGoGo.oGo....',
      '..oGooGo..oGo...',
      '..g...g...g.g...',
      '................',
    ],
  },
} satisfies Partial<Record<UpgradedCreature, Sprite>>
