import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, WOOD, BOOTS, GOLD, type Sprite } from './shared'

/** Rampart: its creatures, heroes, town emblem and homeland obstacles. */
export const RAMPART_SPRITES = {
  centaur: {
    palette: { o: OUTLINE, c: '#8a5028', C: '#5e3418', s: '#d8a07a', h: '#5a3a1e', k: '#2a1c12', w: '#8a6a3a', m: '#c8d0d8' },
    pixels: [
      '..........oo....',
      '.........ohso..o',
      '.........ohskoom',
      '........ohhsoowo',
      '........ohssowo.',
      '........osTssso.',
      '........ossTwo..',
      '..ooooooosTso...',
      '.oCccccccwco....',
      'oCcccccccccco...',
      'oCoccccccccoo...',
      '.oCCocccooCoco..',
      '..oCocoo.oCoco..',
      '..oCoco..oCoco..',
      '..okoko..okoko..',
      '...o.o....o.o...',
    ],
  },
  dwarf: {
    palette: { o: OUTLINE, b: BOOTS, M: '#8a929a', y: '#e0b840', s: SKIN, m: STEEL, w: WOOD, r: '#d0602a', R: '#a03c18', k: '#2a1c12', W: '#e6ecf2', H: '#efe7cf' },
    pixels: [
      '....o...........',
      '...oHo......o...',
      '....oHoooo.oHooo',
      '....oHommmoHommW',
      '.....ommmmmoommW',
      '.....ommmmo.ommW',
      '......ossrkoowoo',
      '.....oosrrrsowo.',
      '....oMMMrrrrowo.',
      '...oMMMMrrrrowo.',
      '...oMMMMrRrRwo..',
      '...oMMMMMrRoo...',
      '...oTTTyTTTo....',
      '....ooboobo.....',
      '.....oboobo.....',
      '....obboobbo....',
    ],
  },
  woodElf: {
    palette: { o: OUTLINE, q: '#4a3020', f: '#ece4cc', L: '#5a3a1e', b: BOOTS, g: '#3a7a30', s: '#ecc4a0', h: '#e8c860', k: '#2a2024', w: WOOD, S: '#e8e0c8', a: '#c8a070', m: STEEL },
    pixels: [
      '...........o....',
      '.....oooo.owo...',
      '....ohhhhooSwo..',
      '...ohhssssooowo.',
      '..ofhssskoSoowo.',
      '.ofohssssoSoowo.',
      '.oqqhossoSo.owo.',
      '.oqqhhggosooowoo',
      '.oqqggggggggsaam',
      '.oqqgggggoSoowoo',
      '..oogggggoSoowo.',
      '...oTTTTToooowo.',
      '....oLooLooSowo.',
      '....oLooLooSwo..',
      '....oLooLoowo...',
      '...obboobboo....',
    ],
  },
  pegasus: {
    palette: { o: OUTLINE, h: '#e8e8ee', H: '#a8b0c0', w: '#ffffff', W: '#98a8c8', b: '#a8b8d0', k: '#2a2024', g: '#3a7a30', s: '#ecc4a0', y: '#e8c860', n: WOOD, m: '#c8d0d8' },
    pixels: [
      '..ooWoo.......om',
      '.oWwwwWoo....omo',
      '.owwwwwoyo..ono.',
      '.owwwwwyskoonoo.',
      '.owwwwwyssonbhho',
      '.owwwwwggonbhkho',
      '.oWwwwwTgnobhhoh',
      '..oWWWoTgoooho.o',
      '..ohhhhThhhho...',
      '.obhhhhhghhhho..',
      'obohhhhhghhho...',
      'oboHohooooHoho..',
      '.ooHoho..oHoho..',
      '..oHoho..oHoho..',
      '..okoko..okoko..',
      '...o.o....o.o...',
    ],
  },
  dendroidGuard: {
    palette: { o: OUTLINE, b: '#7a5432', B: '#4e341e', l: '#4a8a30', L: '#2e5e1e', y: GOLD },
    pixels: [
      '.....ooooo......',
      '....olllLlo.....',
      '...olLlllllo....',
      '...oLllllLlo....',
      '...ollLllllo....',
      '....olllllo.....',
      '.....obboyo.....',
      '....obBbboo.....',
      '.o..obbbBbbo..o.',
      'oBooBbBbboobooBo',
      '.oBBobbbBo.obbo.',
      '..oooTTTTTo.ooBo',
      '.....oBboo....o.',
      '....oBooBo......',
      '...oBBooBBo.....',
      '..oBooBBooBo....',
    ],
  },
  unicorn: {
    palette: { o: OUTLINE, h: '#f4f4f4', H: '#b8bcc8', p: '#c8a0e0', y: '#e8c860', Y: '#fff0b0', k: '#2a2024' },
    pixels: [
      '................',
      '...............o',
      '..............oY',
      '............oooy',
      '...........ophyo',
      '..........ophkho',
      '.....oooo.ophhoh',
      '...oohhhhoooho.o',
      '..ohhhhhhhhho...',
      '.ophhhhTThhhho..',
      'opohhhhhhhhho...',
      'opoHohooooHoho..',
      '.ooHoho..oHoho..',
      '..oHoho..oHoho..',
      '..okoko..okoko..',
      '...o.o....o.o...',
    ],
  },
  greenDragon: {
    palette: { o: OUTLINE, W: '#2e6a2a', g: '#3aa040', G: '#246a28', y: '#a8d060', w: '#efe7cf', r: '#ff3020' },
    pixels: [
      '...oooooo.......',
      '..ogWWWgWo.oo...',
      '.oWWWWWWWWowwoo.',
      '.oWWWgWgWWoogrgo',
      '.oWWWWWWWWoggggo',
      '..oWWWWgWo.oggog',
      '...oooWgoooggo.o',
      '...oggggggTgo...',
      '..oggggggggo....',
      '..oggggggggo....',
      '..oggggggggo....',
      '.ogoyyyyyyyo....',
      'ogo.oGoooGo.....',
      'ogoooGo..oGo....',
      '.ogGGoGo.oGGo...',
      '..ooo.o...oo....',
    ],
  },
  ivor: {
    palette: { o: OUTLINE, s: SKIN, h: '#e8d070', H: '#b89a40', g: '#3a7a2a', G: '#245018', e: '#2a6a2a' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oggggggo....',
      '...oggggggggo...',
      '..oGhhhhhhhhGo..',
      '.o.ohssssssho.o.',
      '.sohsessesshos..',
      '..ohssssssssho..',
      '..ohssssssssho..',
      '..oHhsssssshHo..',
      '...oHhssssHHo...',
      '....oohsshoo....',
      '..ooggTTTTggoo..',
      '.ogGTTTTTTTTGgo.',
      '.ogTTTTttTTTTgo.',
      '.oooooooooooooo.',
    ],
  },
  ryland: {
    palette: { o: OUTLINE, s: SKIN, h: '#7a4a24', b: '#7a4e2a', l: '#5aa040', g: '#3a7a2a', d: '#141018' },
    pixels: [
      '...oo.oooo.oo...',
      '..olloggllgllo..',
      '...oglllggggo...',
      '....ohhhhhho....',
      '...ohssssssho...',
      '...ohsdssdsho...',
      '...ohssssssho...',
      '...ohhssssshho..',
      '...ohhhsshhhho..',
      '....ohhhhhhho...',
      '.....ohhhhho....',
      '..oooboooooboo..',
      '.obbTTTTTTTTbbo.',
      '.obTTTTggTTTTbo.',
      '.obTTTggggTTTbo.',
      '.oooooooooooooo.',
    ],
  },
  uland: {
    palette: { o: OUTLINE, s: SKIN, w: '#e8e8e0', W: '#b8b8b0', l: '#5aa040', g: '#3a7a2a', d: '#141018' },
    pixels: [
      '.....ol.lo......',
      '....olglglo.....',
      '...oggggggggo...',
      '...ogwwwwwwgo...',
      '...owssssssWo...',
      '...owsdssdsWo...',
      '...owssssssWo...',
      '...owwssssWWo...',
      '...owwwwwwwWo...',
      '....owwwwwWo....',
      '....owwwwwWo....',
      '..ooTowwwWoToo..',
      '.oTTTTowwoTTTTo.',
      '.oTTTTTooTTTTTo.',
      '.oTTTTTttTTTTTo.',
      '.oooooooooooooo.',
    ],
  },
  oak: {
    palette: { o: OUTLINE, l: '#7ab84a', g: '#4a8a30', G: '#2e5c1c', b: '#6a4424', B: '#3e2614' },
    pixels: [
      '....oooooooo....',
      '..oollllgggGoo..',
      '.olllllgggggGGo.',
      'olllgllggglgGGGo',
      'ollggggggggggGGo',
      'oglggglggggGgGGo',
      'oggggggggGGGGGGo',
      '.oGggGGgGGGoGGo.',
      '..ooGGoGGGGooo..',
      '....oobbBBoo....',
      '......obBo......',
      '.....obbBBo.....',
      '.....obbBBo.....',
      '....obbbBBBo....',
      '...obBobBoBBo...',
      '...oooooooooo...',
    ],
  },
  mushroom: {
    palette: { o: OUTLINE, r: '#c83030', R: '#8a1e1e', w: '#f4f0e0', W: '#c8c0a8' },
    pixels: [
      '................',
      '................',
      '.....oooooo.....',
      '...oorrwrrrroo..',
      '..orrrrrrrwrrro.',
      '.orwwrrrrrrrrRo.',
      '.orwwrrrwwrrRRo.',
      'orrrrrrrwwrRRRRo',
      'oRRRRRRRRRRRRRRo',
      '.oooowwwwWWoooo.',
      '.....owwwwWo....',
      '.....owwwwWo....',
      '.....owwwwWo....',
      '....owwwwwWWo...',
      '....owwwwWWWo...',
      '.....oooooooo...',
    ],
  },
  rampart: {
    palette: { o: OUTLINE, w: '#ece6d4', W: '#b4ac98', L: '#3f8a3a', l: '#74c864', d: '#3a2a1a', b: WOOD },
    pixels: [
      '.......oT.......',
      '.......oTT......',
      '.......o........',
      '......owo.......',
      '...oo.owWo.oo...',
      '..oLlooWWooLlo..',
      '.oLlLLowWoLLlLo.',
      '.oLLLLowWoLLLLo.',
      '..oLLLowWoLLLo..',
      '...oooowWoooo...',
      '.....owwWWo.....',
      '.....owwWWo.....',
      '.....owddWo.....',
      '....owwddWWo....',
      '...obbbddbbbo...',
      '..ooooooooooooo.',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const RAMPART_TINTS = {
  centaurCaptain: '#c08040',
  battleDwarf: '#c0c8d0',
  grandElf: '#40c060',
  silverPegasus: '#90b0d8',
  dendroidSoldier: '#8a6a30',
  warUnicorn: '#f0e0ff',
  goldDragon: '#ffcc30',
} satisfies Partial<Record<UpgradedCreature, string>>
