import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, WOOD, BOOTS, GOLD, type Sprite } from './shared'

/** Rampart: its creatures, heroes, town emblem and homeland obstacles. */
export const RAMPART_SPRITES = {
  centaur: {
    palette: { o: OUTLINE, H: '#8a5028', h: '#5e3418', m: '#c8d0d8', k: '#2a1c12', s: '#d8a07a', w: '#8a6a3a' },
    pixels: [
      '...............ohhomo...',
      '..............ohhhmwmo..',
      '...............oskowo...',
      '..............osssswo...',
      '..............osssswo...',
      '..............oTTsswo...',
      '...ooooooooooooTTsowo...',
      '..omHHHHHHHHHHssssowo...',
      '.omHHHHHHHHHHHHHHoowo...',
      'ommHHHHHHHHHHHHHHoowo...',
      'ommHHHHHHHHHHHHHHoowo...',
      'omooHHhhhhhhhhHHo.owo...',
      '.omoHHohoooooHHoho.o....',
      '..o.oHoho....oHoho......',
      '....oHoho....oHoho......',
      '....okoko....okoko......',
    ],
  },
  dwarf: {
    palette: { o: OUTLINE, b: BOOTS, M: '#8a929a', y: '#e0b840', s: SKIN, m: STEEL, w: WOOD, r: '#d0602a', R: '#a03c18', k: '#2a1c12', W: '#e6ecf2', H: '#efe7cf' },
    pixels: [
      '....o...........',
      '...oHo......o...',
      '....oHoooo.oHooo',
      '....oHommmoHommW',
      '.....ommmmmoommW',
      '.....ommmmo.ommW',
      '......ossrkoowoo',
      '.....oosrrrsowo.',
      '....oMMMrrrrowo.',
      '...oMMMMrrrrowo.',
      '...oMMMMrRrRwo..',
      '...oMMMMMrRoo...',
      '...oTTTyTTTo....',
      '....ooboobo.....',
      '.....oboobo.....',
      '....obboobbo....',
    ],
  },
  woodElf: {
    palette: { o: OUTLINE, q: '#4a3020', f: '#ece4cc', L: '#5a3a1e', b: BOOTS, g: '#3a7a30', s: '#ecc4a0', h: '#e8c860', k: '#2a2024', w: WOOD, S: '#e8e0c8', a: '#c8a070', m: STEEL },
    pixels: [
      '...........o....',
      '.....oooo.owo...',
      '....ohhhhooSwo..',
      '...ohhssssooowo.',
      '..ofhssskoSoowo.',
      '.ofohssssoSoowo.',
      '.oqqhossoSo.owo.',
      '.oqqhhggosooowoo',
      '.oqqggggggggsaam',
      '.oqqgggggoSoowoo',
      '..oogggggoSoowo.',
      '...oTTTTToooowo.',
      '....oLooLooSowo.',
      '....oLooLooSwo..',
      '....oLooLoowo...',
      '...obboobboo....',
    ],
  },
  pegasus: {
    palette: { o: OUTLINE, H: '#e8e8ee', h: '#a8b0c0', m: '#c8d0d8', e: '#2a2024', n: '#8a5a2b', k: '#2a2024', W: '#ffffff', w: '#d8e0f0', g: '#3a7a30', s: '#ecc4a0', y: '#e8c860' },
    pixels: [
      '.....oWWWo....onTTo.....',
      '....oWWwwWo.ooonTHo.....',
      '....oWwWwwWoyyonHHHo....',
      '.....oWwWwwyssmnHHeHo...',
      '......oWwwwwssmnHHHHHo..',
      '.......oWWWWggonHHHHHno.',
      '...ooooooWWWggssHHHHHno.',
      '..omHHHHHHHHTTHnHHoooo..',
      '.omHHHHHHHHHHgHnHo......',
      'ommHHHHHHHHHHgHnHo......',
      'ommHHHHHHHHHHHHHHo......',
      'omooHHhhhhhhhhHHo.......',
      '.omoHHohoooooHHoho......',
      '..o.oHoho....oHoho......',
      '....oHoho....oHoho......',
      '....okoko....okoko......',
    ],
  },
  dendroidGuard: {
    palette: { o: OUTLINE, b: '#7a5432', B: '#4e341e', l: '#4a8a30', L: '#2e5e1e', y: GOLD },
    pixels: [
      '.....ooooo......',
      '....olllLlo.....',
      '...olLlllllo....',
      '...oLllllLlo....',
      '...ollLllllo....',
      '....olllllo.....',
      '.....obboyo.....',
      '....obBbboo.....',
      '.o..obbbBbbo..o.',
      'oBooBbBbboobooBo',
      '.oBBobbbBo.obbo.',
      '..oooTTTTTo.ooBo',
      '.....oBboo....o.',
      '....oBooBo......',
      '...oBBooBBo.....',
      '..oBooBBooBo....',
    ],
  },
  unicorn: {
    palette: { o: OUTLINE, H: '#f4f4f4', h: '#b8bcc8', m: '#c8a0e0', e: '#2a2024', n: '#d8c8d0', k: '#2a2024', y: '#e8c860', Y: '#fff0b0' },
    pixels: [
      '.................oooYo..',
      '...............ooHyYo...',
      '..............omHHHo....',
      '.............omoHHeHo...',
      '.............omHHHHHHo..',
      '............omoHHHHHHno.',
      '...oooooooooomHHHHHHHno.',
      '..omHHHHHHHHHHHHHHoooo..',
      '.omHHHHHHHHHHHHHHo......',
      'ommHHHHHHHHHHHHHHo......',
      'ommHHHHHHHHHHHHHHo......',
      'omooHHhhhhhhhhHHo.......',
      '.omoHHohoooooHHoho......',
      '..o.oHoho....oHoho......',
      '....oHoho....oHoho......',
      '....okoko....okoko......',
    ],
  },
  greenDragon: {
    palette: { o: OUTLINE, L: '#8ad048', D: '#3e8a2e', d: '#26601c', B: '#c8d860', S: '#e8e0a0', W: '#5aa83c', w: '#2e6a22', s: '#1e4a16', e: '#ffe040', f: '#f4f0e0', m: '#a82020', k: '#2a2018' },
    pixels: [
      '..ooWWookWooko..oSSooo..',
      '.oksWWWWWsWoso..oLoDeDoo',
      '..oWssWWWsWWso.oLoDDDDDD',
      '...oWwssWWsWso.oLoDDDDmf',
      '...oWWwwswWssWoooDDooooo',
      '....oWWwwssWssoLoDBo....',
      '.....ooWWwwsssLoDBo.....',
      '...oo..oooWWWsoDDBo.....',
      '..oLLooDDDDDDDDDoo......',
      '.oDLooDDDDDDDDDDDo......',
      'oDoooDDDBBBBBBBBDo......',
      'oDooDooDDoooooDDo.......',
      '.oDDo.oDodo.odoDo.......',
      '..oo..oDodo.odoDo.......',
      '......oDodo.odoDo.......',
      '.....okokko.okkoko......',
    ],
  },
  ivor: {
    palette: { o: OUTLINE, s: SKIN, h: '#e8d070', H: '#b89a40', g: '#3a7a2a', G: '#245018', e: '#2a6a2a' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oggggggo....',
      '...oggggggggo...',
      '..oGhhhhhhhhGo..',
      '.o.ohssssssho.o.',
      '.sohsessesshos..',
      '..ohssssssssho..',
      '..ohssssssssho..',
      '..oHhsssssshHo..',
      '...oHhssssHHo...',
      '....oohsshoo....',
      '..ooggTTTTggoo..',
      '.ogGTTTTTTTTGgo.',
      '.ogTTTTttTTTTgo.',
      '.oooooooooooooo.',
    ],
  },
  ryland: {
    palette: { o: OUTLINE, s: SKIN, h: '#7a4a24', b: '#7a4e2a', l: '#5aa040', g: '#3a7a2a', d: '#141018' },
    pixels: [
      '...oo.oooo.oo...',
      '..olloggllgllo..',
      '...oglllggggo...',
      '....ohhhhhho....',
      '...ohssssssho...',
      '...ohsdssdsho...',
      '...ohssssssho...',
      '...ohhssssshho..',
      '...ohhhsshhhho..',
      '....ohhhhhhho...',
      '.....ohhhhho....',
      '..oooboooooboo..',
      '.obbTTTTTTTTbbo.',
      '.obTTTTggTTTTbo.',
      '.obTTTggggTTTbo.',
      '.oooooooooooooo.',
    ],
  },
  uland: {
    palette: { o: OUTLINE, s: SKIN, w: '#e8e8e0', W: '#b8b8b0', l: '#5aa040', g: '#3a7a2a', d: '#141018' },
    pixels: [
      '.....ol.lo......',
      '....olglglo.....',
      '...oggggggggo...',
      '...ogwwwwwwgo...',
      '...owssssssWo...',
      '...owsdssdsWo...',
      '...owssssssWo...',
      '...owwssssWWo...',
      '...owwwwwwwWo...',
      '....owwwwwWo....',
      '....owwwwwWo....',
      '..ooTowwwWoToo..',
      '.oTTTTowwoTTTTo.',
      '.oTTTTTooTTTTTo.',
      '.oTTTTTttTTTTTo.',
      '.oooooooooooooo.',
    ],
  },
  oak: {
    palette: { o: OUTLINE, l: '#7ab84a', g: '#4a8a30', G: '#2e5c1c', b: '#6a4424', B: '#3e2614' },
    pixels: [
      '....oooooooo....',
      '..oollllgggGoo..',
      '.olllllgggggGGo.',
      'olllgllggglgGGGo',
      'ollggggggggggGGo',
      'oglggglggggGgGGo',
      'oggggggggGGGGGGo',
      '.oGggGGgGGGoGGo.',
      '..ooGGoGGGGooo..',
      '....oobbBBoo....',
      '......obBo......',
      '.....obbBBo.....',
      '.....obbBBo.....',
      '....obbbBBBo....',
      '...obBobBoBBo...',
      '...oooooooooo...',
    ],
  },
  mushroom: {
    palette: { o: OUTLINE, r: '#c83030', R: '#8a1e1e', w: '#f4f0e0', W: '#c8c0a8' },
    pixels: [
      '................',
      '................',
      '.....oooooo.....',
      '...oorrwrrrroo..',
      '..orrrrrrrwrrro.',
      '.orwwrrrrrrrrRo.',
      '.orwwrrrwwrrRRo.',
      'orrrrrrrwwrRRRRo',
      'oRRRRRRRRRRRRRRo',
      '.oooowwwwWWoooo.',
      '.....owwwwWo....',
      '.....owwwwWo....',
      '.....owwwwWo....',
      '....owwwwwWWo...',
      '....owwwwWWWo...',
      '.....oooooooo...',
    ],
  },
  rampart: {
    palette: { o: OUTLINE, w: '#ece6d4', W: '#b4ac98', L: '#3f8a3a', l: '#74c864', d: '#3a2a1a', b: WOOD },
    pixels: [
      '.......oT.......',
      '.......oTT......',
      '.......o........',
      '......owo.......',
      '...oo.owWo.oo...',
      '..oLlooWWooLlo..',
      '.oLlLLowWoLLlLo.',
      '.oLLLLowWoLLLLo.',
      '..oLLLowWoLLLo..',
      '...oooowWoooo...',
      '.....owwWWo.....',
      '.....owwWWo.....',
      '.....owddWo.....',
      '....owwddWWo....',
      '...obbbddbbbo...',
      '..ooooooooooooo.',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const RAMPART_TINTS = {
  centaurCaptain: '#c08040',
  battleDwarf: '#c0c8d0',
  grandElf: '#40c060',
  silverPegasus: '#90b0d8',
  dendroidSoldier: '#8a6a30',
  warUnicorn: '#f0e0ff',
  goldDragon: '#ffcc30',
} satisfies Partial<Record<UpgradedCreature, string>>

/** Upgrades that look different enough to need their own drawing rather than a tint of the base creature. */
export const RAMPART_UPGRADE_SPRITES = {
  // The Gold Dragon: the Green Dragon in gleaming gold, with burning red eyes.
  goldDragon: {
    palette: { o: OUTLINE, L: '#fff0a0', D: '#d8a028', d: '#9a6a10', B: '#fff0a0', S: '#fff8e0', W: '#f0c848', w: '#b07a18', s: '#7a4c08', e: '#ff3020', f: '#ffffff', m: '#a01818', k: '#3a2408' },
    pixels: [
      '..ooWWookWooko..oSSSSSo.',
      '.oksWWWWWsWoso..oLoDeDoo',
      '..oWssWWWsWWso.oLoDDDDDD',
      '...oWwssWWsWso.oLoDDDDmf',
      '...oWWwwswWssWoooDDooooo',
      '....oWWwwssWssoLoDBo....',
      '.....ooWWwwsssLoDBo.....',
      '...oo..oooWWWsoDDBo.....',
      '..oLLooDDDDDDDDDoo......',
      '.oDLooDDDDDDDDDDDo......',
      'oDoooDDDBBBBBBBBDo......',
      'oDooDooDDoooooDDo.......',
      '.oDDo.oDodo.odoDo.......',
      '..oo..oDodo.odoDo.......',
      '......oDodo.odoDo.......',
      '.....okokko.okkoko......',
    ],
  },
  // The Centaur Captain wears a steel helm and breastplate, with a green cape thrown over the horse's back.
  centaurCaptain: {
    palette: { o: OUTLINE, H: '#8a5028', h: '#5e3418', m: '#c8d0d8', k: '#2a1c12', s: '#d8a07a', w: '#8a6a3a', M: '#7a848e', g: '#3a8a30', G: '#245018', y: GOLD },
    pixels: [
      '...............oMMomo...',
      '..............oMMMmwmo..',
      '...............oskowo...',
      '..............osssswo...',
      '............oooMMMMwo...',
      '..........ooGGGMyMswo...',
      '...oooooooGGggGMyMowo...',
      '..omHHHHGGgggGssssowo...',
      '.omHHHHGGGGGHHHHHoowo...',
      'ommHHHHHHHHHHHHHHoowo...',
      'ommHHHHHHHHHHHHHHoowo...',
      'omooHHhhhhhhhhHHo.owo...',
      '.omoHHohoooooHHoho.o....',
      '..o.oHoho....oHoho......',
      '....oHoho....oHoho......',
      '....okoko....okoko......',
    ],
  },
  // The Battle Dwarf swaps the hammer for a great axe and wears gold-banded plate.
  battleDwarf: {
    palette: { o: OUTLINE, b: BOOTS, M: '#8a929a', y: '#e0b840', s: SKIN, m: STEEL, w: WOOD, r: '#d0602a', R: '#a03c18', k: '#2a1c12', H: '#efe7cf', W: '#f4f8fc' },
    pixels: [
      '....o.....oooo..',
      '...oHo....omwmo.',
      '....oHooooomwmmo',
      '....oHoyyyoowmmW',
      '.....ommmmmowmmW',
      '.....ommmmoowmmW',
      '......ossrkowomo',
      '.....oosrrrsswo.',
      '....ommmrrrrwo..',
      '...ommmyrrrrwo..',
      '...oMmmmrRrRwo..',
      '...oMMmmMrRoo...',
      '...oTTTyTTTo....',
      '....ooMooMo.....',
      '.....oMooMo.....',
      '....obboobbo....',
    ],
  },
  // The Grand Elf wears a green cap with a white feather and a gold-trimmed tunic.
  grandElf: {
    palette: { o: OUTLINE, q: '#4a3020', f: '#ece4cc', L: '#5a3a1e', b: BOOTS, g: '#3aa040', G: '#246a28', s: '#ecc4a0', h: '#e8c860', k: '#2a2024', w: WOOD, S: '#e8e0c8', a: '#c8a070', m: STEEL, W: '#f4f0e4', y: GOLD },
    pixels: [
      '.oo..oooo..o....',
      'oWWooggggoowo...',
      '.oWogggggGoSwo..',
      '..oyyyyyyyooowo.',
      '..ofhssskoSoowo.',
      '.ofohssssoSoowo.',
      '.oqqhossoSo.owo.',
      '.oqqhhggosooowoo',
      '.oqqggyggggggaam',
      '.oqqgggyGoSoowoo',
      '..oogggyGoSoowo.',
      '...oTTyTToooowo.',
      '....oLooLooSowo.',
      '....oLooLooSwo..',
      '....oLooLoowo...',
      '...obboobboo....',
    ],
  },
  // The Dendroid Soldier is a bigger, darker treant with a wide crown and twigs sprouting from its arms.
  dendroidSoldier: {
    palette: { o: OUTLINE, b: '#5e3e22', B: '#36220f', l: '#3a7a28', L: '#1e4a16', y: GOLD },
    pixels: [
      '...oo.oooo.oo...',
      '..olLoollLoolo..',
      '.olLlllLlllLllo.',
      '.oLllLllllLlLlo.',
      '..ollLllLlllLo..',
      '...oLlllllLlo...',
      '....oobbybyoo...',
      '...obbBbbbBbo...',
      'oo..obbbBbbo..oo',
      'oBooBbBbbbBooBBo',
      '.oBBobbBbbBobbo.',
      '..oooTTTTTTo.oBo',
      '....oBbBbBo..o..',
      '...oBBooBBo.....',
      '..oBBo..oBBo....',
      '.oBoBo..oBoBo...',
    ],
  },
  // The War Unicorn is barded in steel, with a chanfron on its head and a gold-hemmed caparison.
  warUnicorn: {
    palette: { o: OUTLINE, H: '#f4f4f4', h: '#b8bcc8', m: '#c8a0e0', e: '#2a2024', n: '#d8c8d0', k: '#2a2024', y: '#e8c860', Y: '#fff0b0', M: '#c0c8d0' },
    pixels: [
      '.................oooYo..',
      '...............ooHyYo...',
      '..............omMMHo....',
      '.............omoHMeHo...',
      '.............omMMMMHHo..',
      '............omoMMMHHHno.',
      '...oooooooooomHHHHHHHno.',
      '..omHTTTTTTTTTHHHHoooo..',
      '.omHTTTTTTTTTTTTHo......',
      'ommHTTTTTTTTTTTTHo......',
      'ommHyyyyyyyyyyyyHo......',
      'omooHHhhhhhhhhHHo.......',
      '.omoHHohoooooHHoho......',
      '..o.oHoho....oHoho......',
      '....oHoho....oHoho......',
      '....okoko....okoko......',
    ],
  },
} satisfies Partial<Record<UpgradedCreature, Sprite>>
