import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, DARK_STEEL, WOOD, BOOTS, GOLD, type Sprite } from './shared'

/** Rampart: its creatures, heroes, town emblem and homeland obstacles. */
export const RAMPART_SPRITES = {
  centaur: {
    palette: { o: OUTLINE, s: SKIN, h: '#5a3a1e', c: '#a0662e', C: '#6e4420', w: WOOD },
    pixels: [
      '.......oooo.....',
      '......ohhhho....',
      '......ohssso....',
      '......ohsoso..o.',
      '.......ossso.owo',
      '......oTTTTooowo',
      '.....oTTTTTsswo.',
      '.....otTTTTooowo',
      '..ooocTTTTco.owo',
      '.occccccccccoo..',
      'ohcccccccccccCo.',
      'oh.oCcccccccCo..',
      '...oCCo...oCCo..',
      '...oCo.....oCo..',
      '...oCo.....oCo..',
      '...ooo.....ooo..',
    ],
  },
  dwarf: {
    palette: { o: OUTLINE, s: SKIN, r: '#c0642a', R: '#8a4018', m: STEEL, M: DARK_STEEL, w: WOOD, b: BOOTS },
    pixels: [
      '..............o.',
      '.............omo',
      '.....oooooo.oMMo',
      '....ommmmmmo.ow.',
      '...oMmmmmmmMoow.',
      '...osssssssso.w.',
      '...ossosssoso.w.',
      '...orrrrrrrro.w.',
      '..orrrrrrrrrrow.',
      '..oTrrRrrRrrTow.',
      '.oTTTRrrrrRTTow.',
      '.osTTTRRRRTTssw.',
      '..otTTTTTTTTtow.',
      '...otttttttto.o.',
      '...obbbo.obbbo..',
      '..obbbbo.obbbbo.',
    ],
  },
  woodElf: {
    palette: { o: OUTLINE, s: SKIN, h: '#e8d070', g: '#3a7a2a', G: '#245018', w: WOOD, b: BOOTS },
    pixels: [
      '..........o.....',
      '....oooo..ow....',
      '...ohhhho.o.w...',
      '..ohhssso.o..w..',
      '..ohssoso.o..w..',
      '.oshhsssoo...w..',
      '...ohsso.o...w..',
      '...oGTTTTo...w..',
      '..oGTTTTTsssssw.',
      '..oGTTTTTo...w..',
      '...otTTTto...w..',
      '...ogggggo..w...',
      '...oggogg.o.w...',
      '...obo.obooow...',
      '...obo.obo..o...',
      '..obbo.obbo.....',
    ],
  },
  pegasus: {
    palette: { o: OUTLINE, f: '#f4f4f8', F: '#c0c4d4', y: '#f0d060', b: '#8ab0e0' },
    pixels: [
      '................',
      '..oo.......oo...',
      '.obbo.....offo..',
      '.obbbo...offyfo.',
      '..obbbo.offffo..',
      '..obbbboffffoo..',
      '...obbbbffffo...',
      '...oTTTTTffo....',
      '.oofTTTTTTfo....',
      'offfffffffffo...',
      'offfffffffffFo..',
      '.ofoFffffffFo...',
      '...oFFo..oFFo...',
      '...oFo....oFo...',
      '...oFo....oFo...',
      '...ooo....ooo...',
    ],
  },
  dendroidGuard: {
    palette: { o: OUTLINE, b: '#7a4e2a', B: '#4a2e18', l: '#5aa040', g: '#3a7a2a', G: '#245018', y: '#f0d040' },
    pixels: [
      '....oo.oo.oo....',
      '...olloggolgo...',
      '..olgggllggggo..',
      '..ogglgggglgGo..',
      '...oogbbbbgoo...',
      '....obybbybo....',
      '....obbbbbbo....',
      '..oobTTTTTbBoo..',
      '.obbbTTTTTbbBBo.',
      '.ob.oTTttTTo.Bo.',
      '.oo.obbbbbBo.oo.',
      '....obbbbbBo....',
      '....obBo.obBo...',
      '....obBo.obBo...',
      '...obbBo.obbBo..',
      '...ooooo.ooooo..',
    ],
  },
  unicorn: {
    palette: { o: OUTLINE, f: '#f8f6ff', F: '#c8c4e0', y: GOLD, m: '#e080c0' },
    pixels: [
      '.............y..',
      '............yo..',
      '........oooyo...',
      '.......offffoo..',
      '......omffofffo.',
      '.....ommfffoffo.',
      '.....omfo.oooo..',
      '....omTfo.......',
      '.oooffTTfo......',
      'omffffTTffffo...',
      'om.fffffffffFo..',
      '.o.oFfffffffFo..',
      '...oFFo...oFFo..',
      '...oFo.....oFo..',
      '...oFo.....oFo..',
      '...ooo.....ooo..',
    ],
  },
  greenDragon: {
    palette: { o: OUTLINE, g: '#3a9a3a', G: '#1e5e24', y: '#e0e040', r: '#e02020' },
    pixels: [
      '..oo............',
      '..oTo.......oo..',
      '..oTTo.....oggo.',
      '..oTtTo...oggrgo',
      '..oTttToooggggyo',
      '..oTtttTggggoyy.',
      '.ooTtttggggggo..',
      'oggoTtggggggo...',
      'oggggggggggo....',
      '.ogggggggggyo...',
      '..oggggggggyo...',
      '..oggggggggyyo..',
      '...oGGGGGGGGgo..',
      '...ogGo..ogGoo..',
      '...oggo..oggo...',
      '..oooo..oooo....',
    ],
  },
  ivor: {
    palette: { o: OUTLINE, s: SKIN, h: '#e8d070', H: '#b89a40', g: '#3a7a2a', G: '#245018', e: '#2a6a2a' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....oggggggo....',
      '...oggggggggo...',
      '..oGhhhhhhhhGo..',
      '.o.ohssssssho.o.',
      '.sohsessesshos..',
      '..ohssssssssho..',
      '..ohssssssssho..',
      '..oHhsssssshHo..',
      '...oHhssssHHo...',
      '....oohsshoo....',
      '..ooggTTTTggoo..',
      '.ogGTTTTTTTTGgo.',
      '.ogTTTTttTTTTgo.',
      '.oooooooooooooo.',
    ],
  },
  ryland: {
    palette: { o: OUTLINE, s: SKIN, h: '#7a4a24', b: '#7a4e2a', l: '#5aa040', g: '#3a7a2a', d: '#141018' },
    pixels: [
      '...oo.oooo.oo...',
      '..olloggllgllo..',
      '...oglllggggo...',
      '....ohhhhhho....',
      '...ohssssssho...',
      '...ohsdssdsho...',
      '...ohssssssho...',
      '...ohhssssshho..',
      '...ohhhsshhhho..',
      '....ohhhhhhho...',
      '.....ohhhhho....',
      '..oooboooooboo..',
      '.obbTTTTTTTTbbo.',
      '.obTTTTggTTTTbo.',
      '.obTTTggggTTTbo.',
      '.oooooooooooooo.',
    ],
  },
  uland: {
    palette: { o: OUTLINE, s: SKIN, w: '#e8e8e0', W: '#b8b8b0', l: '#5aa040', g: '#3a7a2a', d: '#141018' },
    pixels: [
      '.....ol.lo......',
      '....olglglo.....',
      '...oggggggggo...',
      '...ogwwwwwwgo...',
      '...owssssssWo...',
      '...owsdssdsWo...',
      '...owssssssWo...',
      '...owwssssWWo...',
      '...owwwwwwwWo...',
      '....owwwwwWo....',
      '....owwwwwWo....',
      '..ooTowwwWoToo..',
      '.oTTTTowwoTTTTo.',
      '.oTTTTTooTTTTTo.',
      '.oTTTTTttTTTTTo.',
      '.oooooooooooooo.',
    ],
  },
  oak: {
    palette: { o: OUTLINE, l: '#7ab84a', g: '#4a8a30', G: '#2e5c1c', b: '#6a4424', B: '#3e2614' },
    pixels: [
      '....oooooooo....',
      '..oollllgggGoo..',
      '.olllllgggggGGo.',
      'olllgllggglgGGGo',
      'ollggggggggggGGo',
      'oglggglggggGgGGo',
      'oggggggggGGGGGGo',
      '.oGggGGgGGGoGGo.',
      '..ooGGoGGGGooo..',
      '....oobbBBoo....',
      '......obBo......',
      '.....obbBBo.....',
      '.....obbBBo.....',
      '....obbbBBBo....',
      '...obBobBoBBo...',
      '...oooooooooo...',
    ],
  },
  mushroom: {
    palette: { o: OUTLINE, r: '#c83030', R: '#8a1e1e', w: '#f4f0e0', W: '#c8c0a8' },
    pixels: [
      '................',
      '................',
      '.....oooooo.....',
      '...oorrwrrrroo..',
      '..orrrrrrrwrrro.',
      '.orwwrrrrrrrrRo.',
      '.orwwrrrwwrrRRo.',
      'orrrrrrrwwrRRRRo',
      'oRRRRRRRRRRRRRRo',
      '.oooowwwwWWoooo.',
      '.....owwwwWo....',
      '.....owwwwWo....',
      '.....owwwwWo....',
      '....owwwwwWWo...',
      '....owwwwWWWo...',
      '.....oooooooo...',
    ],
  },
  rampart: {
    palette: { o: OUTLINE, w: '#ece6d4', W: '#b4ac98', L: '#3f8a3a', l: '#74c864', d: '#3a2a1a', b: WOOD },
    pixels: [
      '.......oT.......',
      '.......oTT......',
      '.......o........',
      '......owo.......',
      '...oo.owWo.oo...',
      '..oLlooWWooLlo..',
      '.oLlLLowWoLLlLo.',
      '.oLLLLowWoLLLLo.',
      '..oLLLowWoLLLo..',
      '...oooowWoooo...',
      '.....owwWWo.....',
      '.....owwWWo.....',
      '.....owddWo.....',
      '....owwddWWo....',
      '...obbbddbbbo...',
      '..ooooooooooooo.',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const RAMPART_TINTS = {
  centaurCaptain: '#c08040',
  battleDwarf: '#c0c8d0',
  grandElf: '#40c060',
  silverPegasus: '#90b0d8',
  dendroidSoldier: '#8a6a30',
  warUnicorn: '#f0e0ff',
  goldDragon: '#ffcc30',
} satisfies Partial<Record<UpgradedCreature, string>>
