import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, DARK_STEEL, WOOD, BOOTS, BONE, GOLD, type Sprite } from './shared'

/** Stronghold: its creatures, heroes, town emblem and homeland obstacles. */
export const STRONGHOLD_SPRITES = {
  goblin: {
    palette: { o: OUTLINE, g: '#8a9a40', G: '#5e6a2a', y: '#ffe040', k: '#2a2024', w: '#efe7cf', l: '#6a5238', b: BOOTS, W: '#6a4a28' },
    pixels: [
      '................',
      '................',
      '......o.........',
      '.....ogo........',
      '......ogooo..oo.',
      '.......ogggooWWo',
      '.......ogggyoWWo',
      '......oogggggWWo',
      '.....oTTTggkwWo.',
      '....oTTTTToooWo.',
      '....oTTTTTgggo..',
      '....oGtttoooo...',
      '.....ollllo.....',
      '.....ogoogo.....',
      '....ogo..ogo....',
      '...obbo..obbo...',
    ],
  },
  wolfRider: {
    palette: { o: OUTLINE, f: '#7a7068', F: '#4e4640', k: '#2a1a1a', w: '#efe7cf', r: '#ff4020', g: '#8a9a40', y: '#ffe040', W: '#6a4a28' },
    pixels: [
      '..........oo....',
      '.....o...oWWo...',
      '....ogoo.oWWo...',
      '.....oggooWo....',
      '.....oggyoWo....',
      '.....oogggo.....',
      '....oTTTgo.oo...',
      'oo..oTTTo.oFFo..',
      'FFooootTooofffoo',
      'ooFffffffffffrff',
      '.offfffffffffffw',
      '..offffffffoookk',
      '...oFoFooFoFo.oo',
      '..oFooFooFooFo..',
      '..oFooFooFooFo..',
      '...o..o..o..o...',
    ],
  },
  orc: {
    palette: { o: OUTLINE, g: '#7a8a4a', G: '#4e5a2e', l: '#6a4a2a', L: '#5a3a1e', w: '#efe7cf', r: '#e02020', W: WOOD, m: '#c8d0d8', b: BOOTS },
    pixels: [
      '..omo...........',
      '.ommo...........',
      '.omoWo..oooo....',
      '..o.oWoogGGGo...',
      '....ogogggro....',
      '....ogoggggo....',
      '.....ogggGGwo...',
      '....olggggoo....',
      '....oglggggoo...',
      '....ogglggogGo..',
      '....oggglgooo...',
      '....oTTTTTTo....',
      '.....otttto.....',
      '.....oLooLo.....',
      '.....oLooLo.....',
      '....obboobbo....',
    ],
  },
  ogre: {
    palette: { o: OUTLINE, s: '#d8a088', S: '#a8705a', k: '#2a2024', w: '#efe7cf', W: '#7a5230', K: '#4e3420', b: BOOTS },
    pixels: [
      '..oWWo..........',
      '.oWKWo..oooo....',
      '.oWWWo.ossSSo...',
      '..oooWooSsko....',
      '.....oWossso....',
      '.....ooWosowo...',
      '....osssssoo....',
      '...ossssssso....',
      '...ossssssso....',
      '...osssssssso...',
      '...osSsssssoso..',
      '....osSSSSooso..',
      '...oTTTTTTToSo..',
      '....ottttSo.o...',
      '....oSoooSoo....',
      '...obbboobbbo...',
    ],
  },
  roc: {
    palette: { o: OUTLINE, f: '#7a3a20', F: '#4e2414', h: '#e0c8a0', y: GOLD, k: '#1e1410' },
    pixels: [
      '....oFFoFoo.....',
      '...oFFffffFo....',
      '..oFFFfffffo....',
      '..oFFffffffo....',
      '...oFffffffooo..',
      '...oFFfffffhhkoo',
      '....ooFFFFohhhyy',
      '.oooffffffoThooy',
      'oFFffffffffoo..o',
      'oFFffffffffo....',
      '.ooooffffoo.....',
      '.....ooyoyo.....',
      '......oyoyo.....',
      '.....oyoyoyo....',
      '......o.o.o.....',
      '................',
    ],
  },
  cyclops: {
    palette: { o: OUTLINE, s: '#c08a68', S: '#8a6048', w: '#f0f0f0', r: '#e02020', k: '#2a1c12', l: '#7a7a80', L: '#a8a8b0', K: '#55555c', b: BOOTS },
    pixels: [
      '....oollllo.....',
      '...ollLLlllo....',
      '...ollllllllo...',
      '....olllllKo....',
      '...osoollooso...',
      '...osossSSoso...',
      '..osoosswrooso..',
      '..osoossssooso..',
      '..osssssskosso..',
      '...osssssssoo...',
      '...osssssso.....',
      '...osssssso.....',
      '...oTTTTTTo.....',
      '....ottttSo.....',
      '....oSoooSo.....',
      '...obbo.obbo....',
    ],
  },
  behemoth: {
    palette: { o: OUTLINE, f: '#a87c4c', F: '#6e5034', h: '#efe7cf', r: '#e02020', k: '#2a1c12' },
    pixels: [
      '................',
      '.....ooo........',
      '...oofffooooo...',
      '..offffffffFFo..',
      '.offffffffffrfo.',
      '.offffffffffffo.',
      '.offfffffffffo..',
      '.ofFffffffffkko.',
      '.oFfFFFFfffhoho.',
      '.oFFFFFFFffo.o..',
      '.oFTTTTTToffo...',
      '.oFFttttFooffo..',
      'ohhoFFFFFoofoho.',
      '.oooFFoFFoohhho.',
      '..oFFFoFFFoooo..',
      '...ooo.ooo......',
    ],
  },
  jabarkas: {
    palette: { o: OUTLINE, g: '#6a8a4a', G: '#4a6232', h: BONE, r: '#c03020', d: '#141018', y: GOLD, f: '#8a5a30' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....offffffo....',
      '...offffffffo...',
      '...oggggggggo...',
      '..ooggggggggoo..',
      '..ogggrggrgggo..',
      '..ogggggggggGo..',
      '...oggGggGggo...',
      '...oghggggho....',
      '....oggggggo....',
      '.....oooooo.....',
      '.offfTTTTTTfffo.',
      '.offTTTTTTTTffo.',
      '.offTTTyyTTTffo.',
      '.oooooooooooooo.',
    ],
  },
  shiva: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', n: '#3a2414', d: '#141018', r: '#c03020', w: '#f0ead8', f: '#8a5a30', y: GOLD },
    pixels: [
      '.......oo.......',
      '......owwo......',
      '.....owffwo.....',
      '....onnnnnno....',
      '...onnnnnnnno...',
      '...onsssssssno..',
      '...onsdsssdsno..',
      '...onsssssssno..',
      '...onssSSSssno..',
      '...onssrrrssno..',
      '....onsssssno...',
      '.....ooooooo....',
      '.onnnTTTTTTnnno.',
      '.onnTTTTTTTTnno.',
      '.onnTTTyyTTTnno.',
      '.oooooooooooooo.',
    ],
  },
  terek: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', n: '#3a2414', d: '#141018', h: STEEL, H: DARK_STEEL, c: '#40c0f0', y: GOLD },
    pixels: [
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhhcchhho...',
      '..oHhhhhhhhhHo..',
      '..oHHHHHHHHHHo..',
      '...osssssssso...',
      '...osdssssdso...',
      '...ossssssss....',
      '...ossSSSSsso...',
      '...onnnnnnnno...',
      '....onnnnnno....',
      '.....oonnoo.....',
      '.occcTTTTTTccco.',
      '.occTTTTTTTTcco.',
      '.occTTTyyTTTcco.',
      '.oooooooooooooo.',
    ],
  },
  boulder: {
    palette: { o: OUTLINE, l: '#e0c890', s: '#c8a868', S: '#a08048', d: '#6a5030' },
    pixels: [
      '................',
      '................',
      '................',
      '.......ooooo....',
      '.....oollllso...',
      '....ollsssssSo..',
      '...olsssssSsSo..',
      '..olssSssssSSo..',
      '..olsssssSSSSSo.',
      '.oolssssSSSSdSo.',
      '.olsssSSSSSSdSo.',
      '.osssSSSSdSddSo.',
      '.oSssSSSSdddddo.',
      '.oSSSSSSddddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  totem: {
    palette: { o: OUTLINE, w: '#a06a32', W: '#6a4220', r: '#c03020', y: GOLD, k: '#141018', g: '#4a8a3a' },
    pixels: [
      '..oo...oo...oo..',
      '..oyo.ogo..oyo..',
      '...oyoooooooyo..',
      '....oooyyyoooo..',
      '.....owwwwwo....',
      '.....okwwwko....',
      '.....owwrwwo....',
      '.....oWkkkWo....',
      '.....owwwwwo....',
      '.....oyrwryo....',
      '.....owwwwwo....',
      '.....oWkkkWo....',
      '.....owwwwwo....',
      '.....owWwWwo....',
      '....owwwwwwwo...',
      '...ooooooooooo..',
    ],
  },
  stronghold: {
    palette: { o: OUTLINE, h: BONE, y: '#d0a858', Y: '#8a6a2a', w: WOOD, W: '#5a3a1e', d: '#2a1a10' },
    pixels: [
      '.o............o.',
      '.oh..........ho.',
      '..oh...oo...ho..',
      '...oho.oo.ohoo..',
      '....ohoyyohoo...',
      '....oyyYyyyo....',
      '...oyyYyyYyyo...',
      '..oyYyyyyyyYyo..',
      '.oyyyyYyyYyyyyo.',
      '.oooooooooooooo.',
      '.owWwWoddoWwWwo.',
      '.owWwWoddoWwWwo.',
      '.owWwWoddoWwWwo.',
      'oowWwWoddoWwWwoo',
      'o.o.o.oddo.o.o.o',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const STRONGHOLD_TINTS = {
  hobgoblin: '#c06030',
  wolfRaider: '#606870',
  orcChieftain: '#c03030',
  ogreMage: '#6040c0',
  thunderbird: '#40a0ff',
  cyclopsKing: '#c0a040',
  ancientBehemoth: '#d8c8a0',
} satisfies Partial<Record<UpgradedCreature, string>>
