import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, STEEL, DARK_STEEL, WOOD, BOOTS, BONE, GOLD, type Sprite } from './shared'

/** Stronghold: its creatures, heroes, town emblem and homeland obstacles. */
export const STRONGHOLD_SPRITES = {
  goblin: {
    palette: { o: OUTLINE, g: '#8a9a40', G: '#5e6a2a', y: '#ffe040', k: '#2a2024', w: '#efe7cf', l: '#6a5238', b: BOOTS, W: '#6a4a28' },
    pixels: [
      '................',
      '................',
      '......o.........',
      '.....ogo........',
      '......ogooo..oo.',
      '.......ogggooWWo',
      '.......ogggyoWWo',
      '......oogggggWWo',
      '.....oTTTggkwWo.',
      '....oTTTTToooWo.',
      '....oTTTTTgggo..',
      '....oGtttoooo...',
      '.....ollllo.....',
      '.....ogoogo.....',
      '....ogo..ogo....',
      '...obbo..obbo...',
    ],
  },
  wolfRider: {
    palette: { o: OUTLINE, G: '#8a7a68', g: '#5a4e42', L: '#b0a28e', e: '#f0c040', m: '#7a1a14', f: '#f4f0e0', k: '#2a2018', S: '#7aa040', s: '#4e7028', B: '#6a4a30', M: '#b8c0c8', w: '#8a5a2b', r: '#e03020' },
    pixels: [
      '.......o.oooMMMo........',
      '......oSoBBooMo..o......',
      '.o.....oSSSoowo.oGo.....',
      'oGo.....oSSrowooGoGo....',
      'oGGo.....oSSowoGGGGooo..',
      '.oGGoooooBTTSwoGGGeGGGo.',
      '.oGGoGGGGBBBGwGGGGGGGGko',
      '..ooGGGGGGsGGwGGGGGmfmfo',
      '...oGGGGGGsGGwGGGoooooo.',
      '....oGGGLLLLLwLGGo......',
      '...oGGGgooooogGGGo......',
      '....oGogo...ogoGo.......',
      '....oGogo...ogoGo.......',
      '....oGogo...ogoGo.......',
      '....oGogo...ogoGo.......',
      '....okkko...okokko......',
    ],
  },
  orc: {
    palette: { o: OUTLINE, g: '#7a8a4a', G: '#4e5a2e', l: '#6a4a2a', L: '#5a3a1e', w: '#efe7cf', r: '#e02020', W: WOOD, m: '#c8d0d8', b: BOOTS },
    pixels: [
      '..omo...........',
      '.ommo...........',
      '.omoWo..oooo....',
      '..o.oWoogGGGo...',
      '....ogogggro....',
      '....ogoggggo....',
      '.....ogggGGwo...',
      '....olggggoo....',
      '....oglggggoo...',
      '....ogglggogGo..',
      '....oggglgooo...',
      '....oTTTTTTo....',
      '.....otttto.....',
      '.....oLooLo.....',
      '.....oLooLo.....',
      '....obboobbo....',
    ],
  },
  ogre: {
    palette: { o: OUTLINE, s: '#d8a088', S: '#a8705a', k: '#2a2024', w: '#efe7cf', W: '#7a5230', K: '#4e3420', b: BOOTS },
    pixels: [
      '..oWWo..........',
      '.oWKWo..oooo....',
      '.oWWWo.ossSSo...',
      '..oooWooSsko....',
      '.....oWossso....',
      '.....ooWosowo...',
      '....osssssoo....',
      '...ossssssso....',
      '...ossssssso....',
      '...osssssssso...',
      '...osSsssssoso..',
      '....osSSSSooso..',
      '...oTTTTTTToSo..',
      '....ottttSo.o...',
      '....oSoooSoo....',
      '...obbboobbbo...',
    ],
  },
  roc: {
    palette: { o: OUTLINE, f: '#7a3a20', F: '#4e2414', h: '#e0c8a0', y: GOLD, k: '#1e1410' },
    pixels: [
      '........................',
      '....oFFoFFFoFoo.........',
      '...oFFffffffffFo........',
      '..oFFFfffffffffo........',
      '..oFFffffffffffo........',
      '...oFffffffffffooooo....',
      '...oFFfffffffffffhhkoo..',
      '....ooFFFFFFFFFFohhhyy..',
      '.oooffffffffffffoThooy..',
      'oFFffffffffffffffoo..o..',
      'oFFffffffffffffffo......',
      '.oooooffffffffoo........',
      '......oooyoyooo.........',
      '........oyoyo...........',
      '.......oyoyoyo..........',
      '........o.o.o...........',
    ],
  },
  cyclops: {
    palette: { o: OUTLINE, s: '#c08a68', S: '#8a6048', w: '#f0f0f0', r: '#e02020', k: '#2a1c12', l: '#7a7a80', L: '#a8a8b0', K: '#55555c', b: BOOTS },
    pixels: [
      '....oollllo.....',
      '...ollLLlllo....',
      '...ollllllllo...',
      '....olllllKo....',
      '...osoollooso...',
      '...osossSSoso...',
      '..osoosswrooso..',
      '..osoossssooso..',
      '..osssssskosso..',
      '...osssssssoo...',
      '...osssssso.....',
      '...osssssso.....',
      '...oTTTTTTo.....',
      '....ottttSo.....',
      '....oSoooSo.....',
      '...obbo.obbo....',
    ],
  },
  behemoth: {
    palette: { o: OUTLINE, F: '#a87848', f: '#6e4a28', L: '#c8986a', S: '#7a5030', c: '#f0e8d0', e: '#ff3018', m: '#4a1008' },
    pixels: [
      '............ooo.oco.....',
      '..........ooFFFococo....',
      '.........oFfLLFFSSSoo...',
      '.......ooFfLLLLFSSSeSo..',
      '......oFfFFFFfFFFSSSSSo.',
      '.....oFfFFFFfFFFFSSSSco.',
      '....oFfFFFFFFFFFLFcmco..',
      '...oFfFFFFFFFFFFFFSSo...',
      '...oFFFFFFFFFffoFFFo....',
      '...oFFFFFFFooffoFLFo....',
      '....oFFFFFo.offooFFo....',
      '.....oFFFffooffooFFFo...',
      '....oFFFoffooffooFFFo...',
      '...oFFFooffooffo.oFFoo..',
      '...oFFFooffococoocococo.',
      '...oFFFFcocco.o..ocococo',
    ],
  },
  jabarkas: {
    palette: { o: OUTLINE, g: '#6a8a4a', G: '#4a6232', h: BONE, r: '#c03020', d: '#141018', y: GOLD, f: '#8a5a30' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....offffffo....',
      '...offffffffo...',
      '...oggggggggo...',
      '..ooggggggggoo..',
      '..ogggrggrgggo..',
      '..ogggggggggGo..',
      '...oggGggGggo...',
      '...oghggggho....',
      '....oggggggo....',
      '.....oooooo.....',
      '.offfTTTTTTfffo.',
      '.offTTTTTTTTffo.',
      '.offTTTyyTTTffo.',
      '.oooooooooooooo.',
    ],
  },
  shiva: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', n: '#3a2414', d: '#141018', r: '#c03020', w: '#f0ead8', f: '#8a5a30', y: GOLD },
    pixels: [
      '.......oo.......',
      '......owwo......',
      '.....owffwo.....',
      '....onnnnnno....',
      '...onnnnnnnno...',
      '...onsssssssno..',
      '...onsdsssdsno..',
      '...onsssssssno..',
      '...onssSSSssno..',
      '...onssrrrssno..',
      '....onsssssno...',
      '.....ooooooo....',
      '.onnnTTTTTTnnno.',
      '.onnTTTTTTTTnno.',
      '.onnTTTyyTTTnno.',
      '.oooooooooooooo.',
    ],
  },
  terek: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', n: '#3a2414', d: '#141018', h: STEEL, H: DARK_STEEL, c: '#40c0f0', y: GOLD },
    pixels: [
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhhcchhho...',
      '..oHhhhhhhhhHo..',
      '..oHHHHHHHHHHo..',
      '...osssssssso...',
      '...osdssssdso...',
      '...ossssssss....',
      '...ossSSSSsso...',
      '...onnnnnnnno...',
      '....onnnnnno....',
      '.....oonnoo.....',
      '.occcTTTTTTccco.',
      '.occTTTTTTTTcco.',
      '.occTTTyyTTTcco.',
      '.oooooooooooooo.',
    ],
  },
  boulder: {
    palette: { o: OUTLINE, l: '#e0c890', s: '#c8a868', S: '#a08048', d: '#6a5030' },
    pixels: [
      '................',
      '................',
      '................',
      '.......ooooo....',
      '.....oollllso...',
      '....ollsssssSo..',
      '...olsssssSsSo..',
      '..olssSssssSSo..',
      '..olsssssSSSSSo.',
      '.oolssssSSSSdSo.',
      '.olsssSSSSSSdSo.',
      '.osssSSSSdSddSo.',
      '.oSssSSSSdddddo.',
      '.oSSSSSSddddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
  totem: {
    palette: { o: OUTLINE, w: '#a06a32', W: '#6a4220', r: '#c03020', y: GOLD, k: '#141018', g: '#4a8a3a' },
    pixels: [
      '..oo...oo...oo..',
      '..oyo.ogo..oyo..',
      '...oyoooooooyo..',
      '....oooyyyoooo..',
      '.....owwwwwo....',
      '.....okwwwko....',
      '.....owwrwwo....',
      '.....oWkkkWo....',
      '.....owwwwwo....',
      '.....oyrwryo....',
      '.....owwwwwo....',
      '.....oWkkkWo....',
      '.....owwwwwo....',
      '.....owWwWwo....',
      '....owwwwwwwo...',
      '...ooooooooooo..',
    ],
  },
  stronghold: {
    palette: { o: OUTLINE, h: BONE, y: '#d0a858', Y: '#8a6a2a', w: WOOD, W: '#5a3a1e', d: '#2a1a10' },
    pixels: [
      '.o............o.',
      '.oh..........ho.',
      '..oh...oo...ho..',
      '...oho.oo.ohoo..',
      '....ohoyyohoo...',
      '....oyyYyyyo....',
      '...oyyYyyYyyo...',
      '..oyYyyyyyyYyo..',
      '.oyyyyYyyYyyyyo.',
      '.oooooooooooooo.',
      '.owWwWoddoWwWwo.',
      '.owWwWoddoWwWwo.',
      '.owWwWoddoWwWwo.',
      'oowWwWoddoWwWwoo',
      'o.o.o.oddo.o.o.o',
      'oooooooooooooooo',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const STRONGHOLD_TINTS = {
  hobgoblin: '#c06030',
  wolfRaider: '#606870',
  orcChieftain: '#c03030',
  ogreMage: '#6040c0',
  thunderbird: '#40a0ff',
  cyclopsKing: '#c0a040',
  ancientBehemoth: '#d8c8a0',
} satisfies Partial<Record<UpgradedCreature, string>>

/** Upgrades that look different enough to need their own drawing rather than a tint of the base creature. */
export const STRONGHOLD_UPGRADE_SPRITES = {
  // The Ancient Behemoth: grey-blue hide and a ridge of bone spikes down its back.
  ancientBehemoth: {
    palette: { o: OUTLINE, F: '#6a7480', f: '#3e4650', L: '#8a96a2', S: '#4a525c', c: '#f4ecd8', e: '#ff4020', m: '#3a0808' },
    pixels: [
      '..........oocoo.oco.....',
      '.........ocoFFFococo....',
      '........ooFfLLFFSSSoo...',
      '......oocFfLLLLFSSSeSo..',
      '.....ocFfFFFFfFFFSSSSSo.',
      '....ooFfFFFFfFFFFSSSSco.',
      '...ocFfFFFFFFFFFLFcmco..',
      '...oFfFFFFFFFFFFFFSSo...',
      '...oFFFFFFFFFffoFFFo....',
      '...oFFFFFFFooffoFLFo....',
      '....oFFFFFo.offooFFo....',
      '.....oFFFffooffooFFFo...',
      '....oFFFoffooffooFFFo...',
      '...oFFFooffooffo.oFFoo..',
      '...oFFFooffococoocococo.',
      '...oFFFFcocco.o..ocococo',
    ],
  },
  // The Wolf Raider rides a darker, collared wolf, wears a steel cap and swings an axe instead of a club.
  wolfRaider: {
    palette: { o: OUTLINE, G: '#4a4a52', g: '#2e2e34', L: '#6e6e78', e: '#ffd040', m: '#8a1a14', f: '#f4f0e0', k: '#16141a', S: '#7aa040', s: '#4e7028', B: '#5a3a24', M: '#c0c8d0', w: '#6e4a28', r: '#ff3020' },
    pixels: [
      '.......ooooooMMMo.......',
      '......oSMMMMowMMoo......',
      '.o.....oMSSoowMooGo.....',
      'oGo.....oSSrowooGoGo....',
      'oGGo.....oSSowoGGGGooo..',
      '.oGGoooooBTTSwoMGGeGGGo.',
      '.oGGoGGGGBBBGwGMMGGGGGko',
      '..ooGGGGGGsGGwGGMGGmfmfo',
      '...oGGGGGGsGGwGGGoooooo.',
      '....oGGGLLLLLwLGGo......',
      '...oGGGgooooogGGGo......',
      '....oGogo...ogoGo.......',
      '....oGogo...ogoGo.......',
      '....oGogo...ogoGo.......',
      '....oGogo...ogoGo.......',
      '....okkko...okokko......',
    ],
  },
  // The Orc Chieftain wears a horned helm and a pauldron, and wields a double-bladed axe.
  orcChieftain: {
    palette: { o: OUTLINE, g: '#7a8a4a', G: '#4e5a2e', l: '#6a4a2a', L: '#5a3a1e', w: '#efe7cf', h: BONE, r: '#e02020', W: WOOD, m: '#c8d0d8', M: DARK_STEEL, y: GOLD, b: BOOTS },
    pixels: [
      'oo..oo..o...o...',
      'omoomo.ohoooho..',
      'ommmmo.ohmmmho..',
      'omoomWoommmmmo..',
      'oo..oWoggrggo...',
      '....ogoggggo....',
      '...ommoggGGwo...',
      '...oMmghghgoo...',
      '....oglggggoo...',
      '....ogglggogGo..',
      '....oggglgooo...',
      '....oTTyTTTo....',
      '.....otttto.....',
      '.....oLooLo.....',
      '.....oLooLo.....',
      '....obboobbo....',
    ],
  },
  // The Ogre Mage trades the club for a staff with a glowing orb and wears a purple robe and cap.
  ogreMage: {
    palette: { o: OUTLINE, s: '#d8a088', S: '#a8705a', k: '#2a2024', w: '#efe7cf', r: '#5a3a9a', R: '#3a2470', y: GOLD, W: WOOD, c: '#80e8ff', C: '#2080c0', b: BOOTS },
    pixels: [
      '........oooo.oo.',
      '.......orrrrocco',
      '.......oyyyyocCo',
      '......ooSskoowo.',
      '.....oossso.oWo.',
      '.......osowoosso',
      '....orrrrrrossso',
      '...orrrrrrrrsso.',
      '...oRrrrrrrrowo.',
      '...oRrryrrro.oWo',
      '...oRrrryrrroWo.',
      '....oRrryrrroWo.',
      '...oTTTTTTTooWo.',
      '...oRrrryrrroWo.',
      '...oRRRyRRRRoWo.',
      '...obbooobbo.oo.',
    ],
  },
  // The Thunderbird is a fiery red roc with a golden head, wreathed in crackling lightning.
  thunderbird: {
    palette: { o: OUTLINE, f: '#d0562a', F: '#8a2c14', h: '#f0c040', y: GOLD, k: '#1e1410', c: '#80e8ff', C: '#ffffff' },
    pixels: [
      '........................',
      '....oFFoFFFoFoo..c......',
      '...oFFffffffffFo.cc.....',
      '..oFFFfffffffffo..c.....',
      '..oFFffffffffffo.cC.....',
      '...oFffffffffffooooo....',
      '...oFFfffffffffffhhkoo..',
      '....ooFFFFFFFFFFohhhyy..',
      '.oooffffffffffffoThooy..',
      'oFFffffffffffffffoo..o..',
      'oFFffffffffffffffo......',
      '.oooooffffffffoo........',
      '.c....oooyoyooo.........',
      'cC......oyoyo...........',
      '.cc....oyoyoyo..........',
      '..c.....o.o.o...........',
    ],
  },
  // The Cyclops King wears a jewelled gold crown under the boulder he hurls.
  cyclopsKing: {
    palette: { o: OUTLINE, s: '#c08a68', S: '#8a6048', w: '#f0f0f0', r: '#e02020', k: '#2a1c12', l: '#7a7a80', L: '#a8a8b0', K: '#55555c', y: GOLD, b: BOOTS },
    pixels: [
      '....oollllo.....',
      '...ollLLlllo....',
      '...olllllllKo...',
      '....oooooooo....',
      '...osyoyyoyso...',
      '...osyyryyyso...',
      '..osoosswrooso..',
      '..osoossssooso..',
      '..osssssskosso..',
      '...osssssssoo...',
      '...osssssso.....',
      '...osssssso.....',
      '...oTTTyTTo.....',
      '....ottttSo.....',
      '....oSoooSo.....',
      '...obbo.obbo....',
    ],
  },
} satisfies Partial<Record<UpgradedCreature, Sprite>>
