import type { UpgradedCreature } from '../../../game'
import { OUTLINE, SKIN, WOOD, BOOTS, GOLD, type Sprite } from './shared'

/** Tower: its creatures, heroes, town emblem and homeland obstacles. */
export const TOWER_SPRITES = {
  gremlin: {
    palette: { o: OUTLINE, b: '#8a9ab0', B: '#5a6a80', y: '#f0d040', w: '#f0f0f0', k: '#3a3a40', K: '#6a6a72' },
    pixels: [
      '................',
      '................',
      '................',
      '....o...........',
      '...obo..........',
      '....obo.o.......',
      '.....obobo...oo.',
      '.....obbbyo.okko',
      '.....oobbbo.oKko',
      '....obbbbowookko',
      '...obbbbbbbo.oo.',
      '...obbbbboo.....',
      '....oTTTo.......',
      '....oBooBo......',
      '....oBooBo......',
      '...oBBooBBo.....',
    ],
  },
  stoneGargoyle: {
    palette: { o: OUTLINE, s: '#8a8a88', S: '#5e5e5c', r: '#ff4020', w: '#d8d8d0' },
    pixels: [
      '................',
      '...oooo.........',
      '..osSSSo........',
      '.oSSsSSSoo.o....',
      '.oSSSSSSSSoSo...',
      '.oSSSsSSosso....',
      '.oSSSSSSsssro...',
      '..ooSosssssso...',
      '....ossssToo....',
      '...ossssssosoo..',
      '...ossssssooswo.',
      '.ooSosssso..oo..',
      'oSSooSssoSo.....',
      '.oooSooooSoo....',
      '...oSSSo.oSSo...',
      '....ooo...oo....',
    ],
  },
  stoneGolem: {
    palette: { o: OUTLINE, s: '#9a9080', S: '#6e6656', k: '#4a4438', y: '#80e0ff' },
    pixels: [
      '................',
      '.........ooo....',
      '........ossso...',
      '........ossyo...',
      '...oooooossso...',
      '..ossksssksso...',
      '.oSsssssssssso..',
      '.oSsskkkkkksso..',
      '.oSSssskssssso..',
      '.oSSssTkTsssso..',
      '.oSSssskssssso..',
      'oSSSoSSSSSoSSSo.',
      'oSSSSSooSSoSSSo.',
      '.oooSSooSSoooo..',
      '...oSSooSSo.....',
      '....oo..oo......',
    ],
  },
  mage: {
    palette: { o: OUTLINE, s: SKIN, k: '#141018', r: '#a8322a', R: '#6e1e1a', w: WOOD, c: '#80e0ff' },
    pixels: [
      '.......o....oo..',
      '......oro..occo.',
      '.....orRo..occo.',
      '....orrRRo..ow..',
      '...oooooooo..w..',
      '....ossskso..w..',
      '.....osssso..w..',
      '...orrTTTrrosw..',
      '...orrrTrrro.w..',
      '...orrrTrrRo.w..',
      '..orrrrTrrRRow..',
      '..orrrrTrrRRow..',
      '.orrrrrtrrRRow..',
      '.orrrrrrrrRRRo..',
      '.oRrrrrrrRRRRo..',
      '..ooooooooooo...',
    ],
  },
  genie: {
    palette: { o: OUTLINE, c: '#9ac0f0', C: '#6a90d0', b: '#4a7ad0', B: '#2e56a0', y: '#e8c040', w: '#f4f0e8', k: '#141830' },
    pixels: [
      '.......ooo......',
      '......owwwo.....',
      '.....owwwTo.....',
      '......obbyo.....',
      '......obbbo.....',
      '.....obbbokooo..',
      '....obBBbboobBo.',
      '....oBbbbbbyoo..',
      '...oybbbbboo....',
      '...oBobbbo......',
      '....ooyyyo......',
      '.....occo.......',
      '....occo........',
      '...oCcCo........',
      '...occo.........',
      '..ocoo..........',
    ],
  },
  naga: {
    palette: { o: OUTLINE, g: '#5a7a3a', G: '#3a5226', s: '#c8a070', S: '#9a7448', k: '#1e1610', y: '#e8c040', m: '#d8dee6' },
    pixels: [
      '........oo......',
      '.......oyyo.....',
      '...o..oksoyo.o..',
      '..omo.oksko.omo.',
      '...omookssoomo..',
      '....oSkooooso...',
      '..oo.okoTooo.oo.',
      '.ommooSssosoommo',
      '..oomSSsssssmoo.',
      '..o.ooSssssoo.o.',
      'oomooSossoosoomo',
      'goommggggooommo.',
      'oggggggggggooo..',
      '.oggGggggGgo....',
      '..oggggGggo.....',
      '...ooooooo......',
    ],
  },
  giant: {
    palette: { o: OUTLINE, s: '#d8a888', S: '#a07058', h: '#6a4a2a', l: '#7a5530', k: '#141018', b: BOOTS },
    pixels: [
      '......ohhhoo....',
      '.....ohhssSSo...',
      '.....ohsssko....',
      '.....ohsssso....',
      '.....ooshhho....',
      '...oolssshho....',
      '..oSsslssssso...',
      '.oSossslsssoso..',
      '.oSollllllloso..',
      '.oSollllllloso..',
      '.oSollllllloso..',
      '..ooTTTTTTToSSo.',
      '....oSoooSo.oo..',
      '....oSo.oSo.....',
      '....oSo.oSoo....',
      '...obbboobbbo...',
    ],
  },
  piquedram: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', w: '#e8e8e8', g: '#60c0a0', y: GOLD, b: '#8a5a30' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....osssssso....',
      '...ossssssssso..',
      '..owyyyyyyyyywo.',
      '..owoggoooggowo.',
      '..owssssssssswo.',
      '..owsssssSssswo.',
      '..oowwwwwwwwwoo.',
      '...owwwssswwwo..',
      '....owwwwwwwo...',
      '..ooooowwwooooo.',
      '.obbbTTTTTTbbbo.',
      '.obbTTTTyTTTTbbo',
      '.obTTTTyyyTTTTbo',
      '.ooooooooooooooo',
    ],
  },
  thane: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', h: '#4a2e1a', H: '#2e1c10', k: '#141018', b: '#7a5a9a', f: '#60e0a0' },
    pixels: [
      '................',
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhhhhhhHo...',
      '...ohhsssssHo...',
      '...ohssssssHo...',
      '...ohskssksHo...',
      '...ohssssssHo...',
      '...oHssssSsHo...',
      '...oHsskkssHo...',
      '....oHsHHsHo....',
      '..oooooHHooooo..',
      '.obbTTTTTTTTbbo.',
      '.obTTTTTTTTTTbo.',
      '.obTTTTffTTTTbo.',
      '.oooooooooooooo.',
    ],
  },
  solmyr: {
    palette: { o: OUTLINE, s: SKIN, S: '#b08060', k: '#141018', b: '#3a6ad0', B: '#24408a', w: '#e8e8f0', W: '#a8a8b8', y: GOLD },
    pixels: [
      '.......oo.......',
      '......obbo......',
      '.....obbyBo.....',
      '....obbbbBBo....',
      '..oooooooooooo..',
      '...osssssssso...',
      '...osksssskso...',
      '...ossssSssso...',
      '...owwsssswwo...',
      '...owwwwwwwWo...',
      '....owwwwwWo....',
      '..oobowwwWobboo.',
      '.obbTTowWoTTbbo.',
      '.obTTTTooTTTTbo.',
      '.oBbbTTTTTTbbBo.',
      '.oooooooooooooo.',
    ],
  },
  tower: {
    palette: { o: OUTLINE, w: '#eef2f8', W: '#b8c4d8', b: '#4a7ad0', B: '#2a4a90', d: '#2a2440' },
    pixels: [
      '.......oTT......',
      '.......oTTT.....',
      '.......o........',
      '......obo.......',
      '......obBo......',
      '.....obbBBo.....',
      '.o...owwwWo...o.',
      'obo..owdwWo..obo',
      'obBo.owdwWo.obBo',
      'owWo.owwwWo.owWo',
      'owdWoowwwWoowdWo',
      'owwWoowwwWoowwWo',
      'owwWowwddWWowwWo',
      'owwWowwddWWowwWo',
      'oWWWowwddWWoWWWo',
      'oooooooooooooooo',
    ],
  },
  snowPine: {
    palette: { o: OUTLINE, w: '#f4f8ff', W: '#c0d0e8', g: '#2e6a4a', G: '#1c4630', b: '#7a4e2a', B: '#4a2e18' },
    pixels: [
      '.......oo.......',
      '......owwo......',
      '.....owwGo......',
      '.....ogggGo.....',
      '....owwwgGGo....',
      '....ogggGGGo....',
      '...owwwwwgGGo...',
      '...oggggGGGGo...',
      '..owwwwwwwgGGo..',
      '..ogggggGGGGGo..',
      '.owwwwwwwwwgGGo.',
      '.oggggggGGGGGGo.',
      '.oooooobBoooooo.',
      '......obBo......',
      '....wwobBowww...',
      '...owwwwwwwwWWo.',
    ],
  },
  iceRock: {
    palette: { o: OUTLINE, w: '#e8f4ff', i: '#a8d0f0', I: '#6aa0d0', g: '#7a8a98', G: '#4e5a68', d: '#34404c' },
    pixels: [
      '................',
      '................',
      '................',
      '................',
      '......oooo......',
      '....oowwwwioo...',
      '...owwwwiiiio...',
      '..owwiwwiiiiIo..',
      '..owiiiiiiiiIo..',
      '.oowiiiigiiIIo..',
      '.owiiiiggggIIIo.',
      '.oiiiigggGGIdIo.',
      '.oIiigGGGGGdddo.',
      '.oIIGGGGGGddddo.',
      '..oddddddddddo..',
      '...oooooooooo...',
    ],
  },
} satisfies Record<string, Sprite>

/** Each upgrade wears its creature's look, tinted toward a color of its own. */
export const TOWER_TINTS = {
  masterGremlin: '#4a7ad8',
  obsidianGargoyle: '#202030',
  ironGolem: '#8a8e98',
  archMage: '#8040d0',
  masterGenie: '#40d0ff',
  nagaQueen: '#f0c040',
  titan: '#e0e8ff',
} satisfies Partial<Record<UpgradedCreature, string>>
